import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const financialTerms=["financeiro","caixa","conta a pagar","conta a receber","a pagar","a receber","saldo","faturamento","receita","despesa","fluxo de caixa","previsao de caixa","pagamento","recebimento"];
const actions=(p:string)=>{const n=norm(p);const a:{label:string;route:string}[]=[];if(n.includes("qualidade")||n.includes("nao conformidade")||n.includes("fmea"))a.push({label:"Abrir Qualidade",route:"/qualidade"});if(n.includes("pcp")||n.includes("mrp")||n.includes("producao"))a.push({label:"Abrir PCP / MRP",route:"/pcp"});if(n.includes("fiscal")||financialTerms.some(x=>n.includes(x)))a.push({label:"Abrir Fiscal",route:"/fiscal"});return a.slice(0,3)};
function key(){const j=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");if(j)try{const k=JSON.parse(j);if(k.default)return String(k.default)}catch{}return Deno.env.get("SUPABASE_ANON_KEY")||null}
function image(v:string|null){if(!v||!/^data:image\/(png|jpe?g|webp|gif);base64,/i.test(v)||v.length>8_500_000)return null;return v}
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Método não permitido'},405);const auth=req.headers.get('Authorization');if(!auth)return out({error:'Não autenticado'},401);
 const url=Deno.env.get('SUPABASE_URL'),anon=key(),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!service)return out({error:'Configuração segura ausente'},500);
 const client=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await client.auth.getUser();if(error||!user)return out({error:'Sessão inválida'},401);
 const admin=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});let body:any;try{body=await req.json()}catch{return out({error:'JSON inválido'},400)}const pergunta=String(body.pergunta||'').trim(),img=image(body.imagem||null);if(!pergunta&&!img)return out({error:'Informe uma pergunta ou envie uma imagem'},400);if(body.imagem&&!img)return out({error:'Imagem inválida ou acima do limite permitido'},400);
 const {data:profile}=await admin.from('erp_usuarios').select('id,nome,email,empresa_id,nivel_admin,cargo,ativo,auth_user_id').eq('auth_user_id',user.id).maybeSingle();if(!profile?.ativo)return out({error:'Usuário industrial não autorizado'},403);
 const role=String(profile.cargo||'').toLowerCase(),level=Number(profile.nivel_admin||0),financialAllowed=level>=9||role.includes('fiscal')||role.includes('adm');if(financialTerms.some(x=>norm(pergunta).includes(x))&&!financialAllowed)return out({answer:'Você não possui permissão (Nível Fiscal/ADM) para visualizar dados financeiros.',blocked:true,actions:[]});
 const {data:docs}=await client.from('erp_ajuda_documentos').select('id,slug,titulo,resumo,conteudo,palavras_chave,rota').eq('publico',true).order('ordem').limit(100);const terms=norm(pergunta).split(/\s+/).filter((x:string)=>x.length>2);const ranked=(docs||[]).map((d:any)=>({...d,score:terms.reduce((s:number,t:string)=>s+(norm(`${d.titulo} ${d.resumo} ${d.conteudo} ${d.palavras_chave||''}`).includes(t)?1:0),0)})).sort((a:any,b:any)=>b.score-a.score).slice(0,6);const context=ranked.map((d:any)=>`[${d.titulo}] ${d.conteudo}`).join('\n\n');const apiKey=Deno.env.get('OPENAI_API_KEY');if(!apiKey)return out({answer:'A base de ajuda está disponível, mas o provedor de IA visual ainda não foi habilitado neste ambiente.',source:'base_local',actions:actions(pergunta)});
 const system=`Você é o assistente IA do SGQ ERP Industrial. Responda em português, com passos objetivos e sem inventar dados. Usuário autenticado: ${profile.email||user.email||''}. Cargo: ${profile.cargo||'não informado'}. Nível: ${level}. Empresa/tenant: ${profile.empresa_id}. Nunca revele IDs, tokens, segredos ou dados de outros tenants. Não responda valores financeiros para perfis sem autorização. Use o contexto da base e a imagem quando fornecida. Se houver uma ação direta possível, indique a rota sugerida.`;
 const content:any[]=[{type:'input_text',text:`CONTEXTO:\n${context||'Nenhum tópico relevante.'}\n\nPERGUNTA:\n${pergunta||'Analise a imagem e explique o problema e o próximo passo.'}`}];if(img)content.push({type:'input_image',image_url:img});const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:'gpt-5.6-luna',temperature:.2,input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content}]} )});if(!r.ok)return out({error:'Serviço de IA indisponível no momento'},502);const j=await r.json();const answer=String(j?.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text||'Não consegui gerar uma resposta agora.');return out({answer,source:'openai_vision',actions:actions(pergunta)});
});
