import { useEffect, useState } from 'react'
import { UsersRound, RefreshCw } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
type Role={id:string;codigo:string|null;nome:string|null;nivel:number|null;ativo:boolean|null}
export default function ConfiguracaoPerfis(){
 const [rows,setRows]=useState<Role[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const {data,error:e}=await supabase.from('erp_roles').select('id,codigo,nome,nivel,ativo').order('nivel',{ascending:false});if(e)throw e;setRows((data??[]) as Role[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os perfis.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 return <section className="space-y-4"><div className="flex items-center justify-between gap-4 border-b border-slate-200 pb-4"><div><span className="text-[9px] font-black uppercase tracking-[.16em] text-[#176487]">ADMINISTRAÇÃO • PERFIS</span><h2 className="mt-1 text-xl font-black text-[#123B50]">Perfis de Usuários</h2><p className="mt-1 text-[11px] font-semibold text-slate-500">Perfis reais cadastrados no RBAC do ERP.</p></div><button type="button" onClick={()=>void load()} className="inline-flex min-h-[38px] items-center gap-2 rounded-lg border border-[#B8D5DE] bg-white px-3 text-[10px] font-black text-[#123B50]"><RefreshCw size={14}/>ATUALIZAR</button></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[11px] font-bold text-red-700">{error}</div>}<div className="overflow-auto rounded-xl border border-[#C5DEE6]"><table className="w-full min-w-[620px] text-[11px]"><thead className="bg-[#123B50] text-white"><tr><th className="p-3 text-left">Código</th><th className="p-3 text-left">Perfil</th><th className="p-3 text-center">Nível</th><th className="p-3 text-center">Status</th></tr></thead><tbody>{loading?<tr><td colSpan={4} className="p-8 text-center font-bold text-slate-400">Consultando perfis no Supabase…</td></tr>:rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="p-3 font-mono font-black text-[#123B50]">{r.codigo||'—'}</td><td className="p-3 font-bold text-slate-700">{r.nome||'—'}</td><td className="p-3 text-center font-black text-[#123B50]">{r.nivel??'—'}</td><td className="p-3 text-center"><span className={`inline-flex rounded-md border px-2 py-1 text-[9px] font-black ${r.ativo===false?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{r.ativo===false?'INATIVO':'ATIVO'}</span></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="p-8 text-center text-[11px] font-semibold text-slate-500"><UsersRound className="mx-auto mb-2 text-[#2D8DB8]" size={24}/>Nenhum perfil real foi retornado pelo banco.</div>}</div></section>
}