import { useEffect, useState } from 'react'
import { Check, Save, ShieldCheck } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import ConfiguracoesEngenhariaLayout from './ConfiguracoesEngenhariaLayout'

type Role={id:string;name:string;description:string|null}
type Perm={view:boolean;edit:boolean;approve:boolean}
const modules=[['ENGENHARIA','Engenharia / BOM'],['COMERCIAL','Comercial / Vendas'],['MRP','Planejamento de Materiais / MRP'],['PCP','PCP / Ordens de Produção'],['FABRICA','Chão de Fábrica / Apontamentos'],['QUALIDADE','Qualidade / SGQ'],['ESTOQUE','Estoque / Almoxarifado'],['COMPRAS','Compras / Suprimentos'],['EXPEDICAO','Expedição'],['FINANCEIRO','Financeiro'],['FISCAL','Fiscal'],['RH','RH']]

export default function ConfiguracaoPermissoes(){
 const [roles,setRoles]=useState<Role[]>([]),[selected,setSelected]=useState<Role|null>(null),[matrix,setMatrix]=useState<Record<string,Perm>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Sessão não encontrada.');const {data:p,error:pe}=await supabase.from('erp_usuarios').select('empresa_id,is_master').eq('auth_user_id',user.user.id).eq('ativo',true).is('deleted_at',null).maybeSingle();if(pe)throw pe;if(!p?.empresa_id&&!p?.is_master)throw new Error('Usuário sem empresa vinculada.');let q=supabase.from('erp_roles').select('id,name,description').order('name');if(p.is_master===true)q=q.is('company_id',null);else q=q.eq('company_id',p.empresa_id);const {data,error}=await q;if(error)throw error;setRoles((data||[]) as Role[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar perfis.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const selectRole=async(r:Role)=>{setSelected(r);setError('');const {data,error}=await supabase.from('erp_role_module_permissions').select('module_code,can_view,can_edit,can_approve').eq('role_id',r.id);if(error){setError(error.message);return}const next:Record<string,Perm>={};for(const x of data||[])next[x.module_code]={view:Boolean(x.can_view),edit:Boolean(x.can_edit),approve:Boolean(x.can_approve)};setMatrix(next)}
 const toggle=(code:string,key:keyof Perm)=>setMatrix(m=>({...m,[code]:{...(m[code]||{view:false,edit:false,approve:false}),[key]:!(m[code]?.[key]??false)}}))
 const save=async()=>{if(!selected)return;setBusy(true);setError('');setMessage('');try{for(const [code,p] of Object.entries(matrix)){const {error}=await supabase.from('erp_role_module_permissions').upsert({role_id:selected.id,module_code:code,can_view:p.view,can_edit:p.edit,can_approve:p.approve,updated_at:new Date().toISOString()},{onConflict:'role_id,module_code'});if(error)throw error}setMessage('Permissões do perfil salvas no Supabase.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar as permissões.')}finally{setBusy(false)}}
 const status=(p:Perm)=>p.view&&p.edit&&p.approve?'Acesso Total':p.view&&p.edit?'Modificação':p.view?'Apenas Leitura':'Bloqueado'
 return <ConfiguracoesEngenhariaLayout title='Controle de Permissões por Perfil' subtitle='Defina o que cada perfil industrial pode visualizar, alterar e aprovar.'>
  {(message||error)&&<div className={'mb-5 rounded-xl border px-4 py-3 text-sm font-semibold '+(error?'border-red-200 bg-red-50 text-red-700':'border-cyan-200 bg-cyan-50 text-[#123B50]')}>{error||message}</div>}
  <section className='rounded-2xl bg-white border border-slate-200 shadow-sm p-5'><h2 className='font-black text-[#123B50] flex items-center gap-2'><ShieldCheck size={18}/> 1. Seleção de Perfil Industrial</h2><select disabled={busy} value={selected?.id||''} onChange={e=>{const r=roles.find(x=>x.id===e.target.value);if(r)void selectRole(r)}} className='mt-4 w-full max-w-2xl rounded-xl border border-slate-200 px-4 py-3 font-bold'><option value=''>Selecione o perfil para configurar</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{selected&&<p className='mt-3 text-sm text-slate-500'>{selected.description||'Perfil industrial sem descrição cadastrada.'}</p>}</section>
  <section className='mt-5 rounded-2xl bg-white border border-slate-200 shadow-sm overflow-hidden'><div className='p-5 border-b border-slate-100'><h2 className='font-black text-[#123B50] flex items-center gap-2'><ShieldCheck size={18}/> 2. Matriz de Permissões por Módulo</h2></div><div className='overflow-auto'><table className='w-full text-sm'><thead className='bg-[#F4FBFD] text-[11px] uppercase text-slate-500'><tr><th className='p-3 text-left min-w-[280px]'>Módulo Industrial</th><th className='p-3 text-center'>Visualizar</th><th className='p-3 text-center'>Criar / Editar</th><th className='p-3 text-center'>Aprovar / Liberar</th><th className='p-3 text-center'>Status</th></tr></thead><tbody>{modules.map(([code,label])=>{const p=matrix[code]||{view:false,edit:false,approve:false};return <tr key={code} className='border-t border-slate-100'><td className='p-3 font-bold text-slate-700'>{label}</td>{(['view','edit','approve'] as const).map(k=><td key={k} className='p-3 text-center'><button type='button' onClick={()=>toggle(code,k)} className={'inline-flex h-8 w-8 items-center justify-center rounded-lg border '+(p[k]?'bg-[#2D8DB8] border-[#2D8DB8] text-white':'bg-white border-slate-300 text-transparent')}><Check size={16}/></button></td>)}<td className='p-3 text-center'><span className='inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-700'>{status(p)}</span></td></tr>})}</tbody></table></div><div className='p-5 flex justify-end'><button type='button' onClick={()=>void save()} disabled={!selected||busy} className='rounded-xl bg-[#123B50] px-5 py-3 text-white font-black flex items-center gap-2'><Save size={17}/> Salvar Permissões do Perfil</button></div></section>
  <div className='mt-5 grid grid-cols-1 lg:grid-cols-2 gap-5'><section className='rounded-2xl border border-cyan-100 bg-[#F4FBFD] p-5'><h3 className='font-black text-[#123B50]'>Ajuda de Governança</h3><p className='mt-2 text-sm text-slate-600'>Visualizar controla acesso ao módulo. Criar/Editar permite alterar dados. Aprovar/Liberar controla ações de autoridade operacional.</p></section><section className='rounded-2xl border border-amber-200 bg-amber-50 p-5'><h3 className='font-black text-amber-900'>Regra de segurança</h3><p className='mt-2 text-sm text-amber-800'>A matriz é gravada por perfil no Supabase e fica disponível para o controle de acesso da aplicação.</p></section></div>
 </ConfiguracoesEngenhariaLayout>
}