import { useEffect, useState } from 'react'
import { FileText, RefreshCw } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
type Log={id:string;modulo:string|null;acao:string|null;entidade:string|null;created_at:string;dados:unknown}
export default function ConfiguracaoLogs(){
 const [rows,setRows]=useState<Log[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const {data,error:e}=await supabase.from('erp_logs_sistema').select('id,modulo,acao,entidade,created_at,dados').order('created_at',{ascending:false}).limit(100);if(e)throw e;setRows((data??[]) as Log[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os logs.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 return <section className="space-y-4"><div className="flex items-center justify-between gap-4 border-b border-slate-200 pb-4"><div><span className="text-[9px] font-black uppercase tracking-[.16em] text-[#176487]">ADMINISTRAÇÃO • AUDITORIA</span><h2 className="mt-1 text-xl font-black text-[#123B50]">Logs do Sistema</h2><p className="mt-1 text-[11px] font-semibold text-slate-500">Auditoria real registrada em erp_logs_sistema.</p></div><button type="button" onClick={()=>void load()} className="inline-flex min-h-[38px] items-center gap-2 rounded-lg border border-[#B8D5DE] bg-white px-3 text-[10px] font-black text-[#123B50]"><RefreshCw size={14}/>ATUALIZAR</button></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[11px] font-bold text-red-700">{error}</div>}<div className="overflow-auto rounded-xl border border-[#C5DEE6]"><table className="w-full min-w-[900px] text-[10px]"><thead className="bg-[#123B50] text-white"><tr><th className="p-3 text-left">Data</th><th className="p-3 text-left">Módulo</th><th className="p-3 text-left">Ação</th><th className="p-3 text-left">Entidade</th><th className="p-3 text-left">Dados</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-8 text-center font-bold text-slate-400">Consultando auditoria…</td></tr>:rows.map(r=><tr key={r.id} className="border-t border-slate-100 align-top"><td className="p-3 whitespace-nowrap text-slate-500">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="p-3 font-bold text-[#123B50]">{r.modulo||'—'}</td><td className="p-3 font-black text-[#123B50]">{r.acao||'—'}</td><td className="p-3 text-slate-600">{r.entidade||'—'}</td><td className="max-w-[420px] truncate p-3 font-mono text-slate-500">{typeof r.dados==='string'?r.dados:JSON.stringify(r.dados??{})}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="p-8 text-center text-[11px] font-semibold text-slate-500"><FileText className="mx-auto mb-2 text-[#2D8DB8]" size={24}/>Nenhum log real retornado.</div>}</div></section>
}