import { useEffect, useState } from 'react'
import { Check, Save, ShieldCheck, HelpCircle } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import ConfiguracoesEngenhariaLayout from './ConfiguracoesEngenhariaLayout'
type Role={id:string;name:string;description:string|null};type Perm={view:boolean;edit:boolean;approve:boolean}
const modules=[['ENGENHARIA','1. Engenharia de Produto (BOM)'],['COMERCIAL','2. Comercial e Pedidos de Venda'],['MRP','3. Planejamento de Materiais (MRP)'],['PCP','4. Programação PCP e Ordens (OP)'],['FABRICA','5. Chão de Fábrica e Apontamentos'],['QUALIDADE','6. Gestão de Qualidade (SGQ)']]
export default function ConfiguracaoPermissoes(){
 const [roles,setRoles]=useState<Role[]>([]),[selected,setSelected]=useState<Role|null>(null),[matrix,setMatrix]=useState<Record<string,Perm>>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 const load=async()=>{setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw Error('Sessão não encontrada.');const {data:p,error:pe}=await supabase.from('erp_usuarios').select('empresa_id,is_master').eq('auth_user_id',u.user.id).eq('ativo',true).is('deleted_at',null).maybeSingle();if(pe)throw pe;let q=supabase.from('erp_roles').select('id,name,description').order('name');q=p?.is_master===true?q.is('company_id',null):q.eq('company_id',p?.empresa_id??'');const {data,error}=await q;if(error)throw error;setRoles((data||[]) as Role[])}catch(e){setErr(e instanceof Error?e.message:'Erro ao carregar perfis.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const selectRole=async(r:Role)=>{setSelected(r);setErr('');const {data,error}=await supabase.from('erp_role_module_permissions').select('module_code,can_view,can_edit,can_approve').eq('role_id',r.id);if(error){setErr(error.message);return}const n:Record<string,Perm>={};for(const x of data||[])n[x.module_code]={view:Boolean(x.can_view),edit:Boolean(x.can_edit),approve:Boolean(x.can_approve)};setMatrix(n)}
 const toggle=(code:string,k:keyof Perm)=>setMatrix(m=>({...m,[code]:{...(m[code]||{view:false,edit:false,approve:false}),[k]:!(m[code]?.[k]??false)}}))
 const save=async()=>{if(!selected)return;setBusy(true);setErr('');try{for(const [code,p] of Object.entries(matrix)){const {error}=await supabase.from('erp_role_module_permissions').upsert({role_id:selected.id,module_code:code,can_view:p.view,can_edit:p.edit,can_approve:p.approve,updated_at:new Date().toISOString()},{onConflict:'role_id,module_code'});if(error)throw error}setMsg('Atualizado no Supabase.')}catch(e){setErr(e instanceof Error?e.message:'Erro ao salvar.')}finally{setBusy(false)}}
 const status=(p:Perm)=>p.view&&p.edit&&p.approve?'Acesso Total':p.view&&p.edit?'Modificação':p.view?'Leitura':'Bloqueado'
 return <ConfiguracoesEngenhariaLayout title="Controle de Permissões" subtitle="Matriz de autorização por perfil industrial.">
  {(msg||err)&&<div className={'mb-5 rounded-xl border px-4 py-3 text-sm font-bold '+(err?'border-red-200 bg-red-50 text-red-700':'border-cyan-200 bg-cyan-50 text-[#123B50]')}>{err||msg}</div>}
  <section className="rounded-3xl border border-slate-100 bg-white p-6 shadow-xl shadow-slate-200/30"><h2 className="flex items-center gap-2 border-b border-slate-100 pb-3 text-xs font-bold uppercase tracking-wider text-slate-400"><ShieldCheck className="h-4 w-4 text-blue-900"/>1. Seleção do Cargo Industrial</h2><div className="mt-5 grid grid-cols-1 items-center gap-6 md:grid-cols-3"><label className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Cargo Ativo<select disabled={busy} value={selected?.id||''} onChange={e=>{const r=roles.find(x=>x.id===e.target.value);if(r)void selectRole(r)}} className="mt-1.5 w-full rounded-xl border-2 border-slate-100 bg-slate-50 px-4 py-2.5 text-sm font-bold text-slate-800"><option value="">Selecione o cargo</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className="md:col-span-2 rounded-2xl border border-slate-100 bg-slate-50 p-4 text-xs font-semibold text-slate-500"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-blue-900">Escopo Técnico</span>{selected?.description||'Selecione um perfil para carregar o escopo cadastrado no banco.'}</div></div></section>
  <section className="mt-6 overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-xl shadow-slate-200/30"><div className="flex items-center justify-between border-b border-slate-100 p-6"><h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">2. Matriz de Segurança</h2><ShieldCheck className="h-5 w-5 text-[#2D8DB8]"/></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-[#123B50] text-white"><tr><th className="p-4 text-left">Módulo do Sistema</th><th className="p-4 text-center">Visualizar</th><th className="p-4 text-center">Criar / Editar</th><th className="p-4 text-center">Aprovar / Liberar</th><th className="p-4 text-center">Status</th></tr></thead><tbody>{modules.map(([code,label])=>{const p=matrix[code]||{view:false,edit:false,approve:false};return <tr key={code} className="border-t border-slate-100"><td className="p-4 font-bold text-slate-700">{label}</td>{(['view','edit','approve'] as const).map(k=><td key={k} className="p-4 text-center"><button type="button" aria-label={`${label} ${k}`} onClick={()=>toggle(code,k)} className={'inline-flex h-9 w-9 items-center justify-center rounded-xl border-2 transition '+(p[k]?'border-blue-600 bg-blue-600 text-white hover:bg-cyan-500':'border-slate-300 bg-white text-transparent hover:border-blue-400')}><Check size={17}/></button></td>)}<td className="p-4 text-center"><span className={'inline-flex rounded-full border px-3 py-1 text-xs font-black '+(p.view&&p.edit&&p.approve?'border-cyan-200 bg-cyan-50 text-cyan-700':p.view&&p.edit?'border-blue-200 bg-blue-50 text-blue-700':p.view?'border-slate-200 bg-slate-100 text-slate-600':'border-red-200 bg-red-50 text-red-700')}>{status(p)}</span></td></tr>})}</tbody></table></div><div className="flex justify-end p-6"><button type="button" disabled={!selected||busy} onClick={()=>void save()} className="flex items-center gap-2 rounded-xl bg-[#123B50] px-5 py-3 text-sm font-black text-white hover:bg-[#2D8DB8] disabled:opacity-50"><Save size={17}/>Atualizar Acessos no Supabase</button></div></section>
  <section className="mt-6 rounded-3xl border border-cyan-100 bg-[#F4FBFD] p-6"><div className="flex items-center gap-2 font-black text-[#123B50]"><HelpCircle size={18}/>3. Manual do Usuário: Governança de Matriz de Segurança</div><p className="mt-3 text-sm text-slate-600">Visualizar controla o acesso ao módulo; Criar/Editar permite alterações; Aprovar/Liberar representa autoridade operacional. A matriz é gravada por perfil no Supabase.</p></section>
 </ConfiguracoesEngenhariaLayout>
}
