import { useEffect, useMemo, useState } from 'react'
import { Calculator, FileSpreadsheet } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import LinkFieldCombobox, { type LinkOption } from '../../components/ui/LinkFieldCombobox'

type Seller={id:string;nome:string;email:string}
type Line={id:string;pedido_id:string;item_id:string;produto_id:string;quantidade:number;valor_total:number;percentual:number;comissao_liquida:number;pedido?:{numero:number;cliente_id:string|null};produto?:{codigo:string;nome:string};usuario_id:string|null}
type Client={id:string;nome:string}
const input='h-7 rounded-md border border-gray-200 bg-white px-2 py-0.5 text-[11px] text-gray-800 outline-none focus:border-blue-500'
const label='mb-0.5 block text-[10px] font-bold uppercase text-gray-500'
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const crc32=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
const u16=(n:number)=>new Uint8Array([n&255,(n>>>8)&255]),u32=(n:number)=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])
function zipStored(files:Array<{name:string;data:Uint8Array}>){const enc=new TextEncoder(),parts:Uint8Array[]=[];const central:Uint8Array[]=[];let offset=0;const dosTime=0,filesCount=files.length;for(const f of files){const name=enc.encode(f.name),crc=crc32(f.data);const local=new Uint8Array(30+name.length+f.data.length);local.set([80,75,3,4,20,0,0,0,0,0,0,0,0,0,...u32(crc),...u32(f.data.length),...u32(f.data.length),...u16(name.length),0, ...name]);local.set(f.data,30+name.length);parts.push(local);const cen=new Uint8Array(46+name.length);cen.set([80,75,1,2,20,0,20,0,0,0,0,0,0,0,...u32(crc),...u32(f.data.length),...u32(f.data.length),...u16(name.length),0,0,0,0,0,0,0,0,...u32(offset)]);cen.set(name,46);central.push(cen);offset+=local.length}const centralSize=central.reduce((n,x)=>n+x.length,0);const end=new Uint8Array(22);end.set([80,75,5,6,0,0,0,0,...u16(filesCount),...u16(filesCount),...u32(centralSize),...u32(offset),0,0]);const chunks=[...parts,...central,end];const payload=new ArrayBuffer(chunks.reduce((total,chunk)=>total+chunk.byteLength,0));const output=new Uint8Array(payload);let cursor=0;for(const chunk of chunks){output.set(chunk,cursor);cursor+=chunk.byteLength}return new Blob([payload],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function sheetXml(lines:Line[],clients:Client[]){const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const clientMap=new Map(clients.map(c=>[c.id,c.nome]));const rows=[['Pedido','Cliente','SKU','Qtd Faturada','Valor Total Nota','% Comissão da Regra','Comissão Líquida R$'],...lines.map(l=>[String(l.pedido?.numero??''),clientMap.get(l.pedido?.cliente_id??'')??'',l.produto?.codigo??'',String(l.quantidade),String(l.valor_total),String(l.percentual),String(l.comissao_liquida)])];return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map(r=>'<row>'+r.map(v=>'<c t="inlineStr"><is><t>'+esc(v)+'</t></is></c>').join('')+'</row>').join('')+'</sheetData></worksheet>'}
async function exportXlsx(lines:Line[],clients:Client[]){const enc=new TextEncoder();const contentTypes='<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>';const rels='<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';const wb='<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Comissoes" sheetId="1" r:id="rId1"/></sheets></workbook>';const wbr='<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>';const blob=zipStored([{name:'[Content_Types].xml',data:enc.encode(contentTypes)},{name:'_rels/.rels',data:enc.encode(rels)},{name:'xl/workbook.xml',data:enc.encode(wb)},{name:'xl/_rels/workbook.xml.rels',data:enc.encode(wbr)},{name:'xl/worksheets/sheet1.xml',data:enc.encode(sheetXml(lines,clients))}]);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='comissoes-'+new Date().toISOString().slice(0,7)+'.xlsx';a.click();URL.revokeObjectURL(a.href)}
export default function CalculoComissao(){
 const [competencia,setCompetencia]=useState(new Date().toISOString().slice(0,7)),[sellerId,setSellerId]=useState(''),[meta,setMeta]=useState(''),[calcId,setCalcId]=useState(''),[lines,setLines]=useState<Line[]>([]),[clients,setClients]=useState<Client[]>([]),[sellers,setSellers]=useState<Seller[]>([]),[error,setError]=useState('')
 const load=async()=>{const [s,c]=await Promise.all([supabase.from('erp_usuarios').select('id,nome,email').eq('ativo',true).is('deleted_at',null).order('nome'),supabase.from('erp_clientes').select('id,nome').eq('ativo',true).order('nome').limit(5000)]);if(s.error)throw s.error;if(c.error)throw c.error;setSellers((s.data??[]) as Seller[]);setClients((c.data??[]) as Client[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar vendedores.'))},[])
 const run=async()=>{setError('');const r=await supabase.rpc('erp_comissao_calcular',{p_competencia:competencia+'-01',p_usuario_id:sellerId||null,p_meta_faturamento:Number(meta)||0});if(r.error){setError(r.error.message);return}setCalcId(String((r.data as {calculo_id:string}).calculo_id));const q=await supabase.from('erp_comissao_linhas').select('id,pedido_id,item_id,produto_id,usuario_id,quantidade,valor_total,percentual,comissao_liquida,pedido:erp_pedidos_venda(numero,cliente_id),produto:erp_produtos(codigo,nome)').eq('calculo_id',String((r.data as {calculo_id:string}).calculo_id)).order('created_at');if(q.error)setError(q.error.message);else setLines((q.data??[]) as unknown as Line[])}
 const options:LinkOption[]=useMemo(()=>sellers.map(s=>({value:s.id,label:s.nome,description:s.email})),[sellers])
 const total=lines.reduce((s,l)=>s+Number(l.valor_total),0),commission=lines.reduce((s,l)=>s+Number(l.comissao_liquida),0),goal=Number(meta)||0
 return <main className="min-h-screen bg-slate-50 p-3"><section className="border border-gray-200 bg-white p-2 shadow-sm"><div className="mb-2 flex items-end gap-2"><div><label className={label}>Competência</label><input className={input+' w-[110px]'} type="month" value={competencia} onChange={e=>setCompetencia(e.target.value)}/></div><div className="w-[180px]"><label className={label}>Vendedor / Agente</label><LinkFieldCombobox value={sellerId} options={options} onChange={setSellerId}/></div><div><label className={label}>Meta Faturamento</label><input className={input+' w-[110px] text-right'} inputMode="decimal" value={meta} onChange={e=>setMeta(e.target.value)}/></div><button type="button" className="flex h-7 w-[120px] items-center justify-center gap-1 rounded-md bg-blue-600 text-[11px] font-bold text-white" onClick={()=>void run()}><Calculator size={12}/>Calcular</button></div>{error&&<div className="mb-2 text-[11px] text-red-600">{error}</div>}
 <div className="scroll-fade-x max-h-[250px] overflow-auto border border-gray-200"><table className="w-full border-collapse text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="px-2 text-left font-normal">Pedido</th><th className="min-w-[220px] px-2 text-left font-normal">Cliente</th><th className="px-2 text-left font-normal">SKU</th><th className="px-2 text-right font-normal">Qtd Faturada</th><th className="px-2 text-right font-normal">Valor Total Nota</th><th className="px-2 text-right font-normal">% Comissão da Regra</th><th className="px-2 text-right font-normal">Comissão Líquida R$</th></tr></thead><tbody>{lines.map((l,i)=><tr key={l.id} className={i%2?'bg-slate-50':'bg-white'} style={{height:26}}><td className="px-2">{l.pedido?.numero??'—'}</td><td className="px-2">{clients.find(c=>c.id===l.pedido?.cliente_id)?.nome??'—'}</td><td className="px-2">{l.produto?.codigo??'—'}</td><td className="px-2 text-right">{Number(l.quantidade).toLocaleString('pt-BR')}</td><td className="px-2 text-right">{money(Number(l.valor_total))}</td><td className="px-2 text-right">{Number(l.percentual).toFixed(2)}%</td><td className="px-2 text-right font-semibold">{money(Number(l.comissao_liquida))}</td></tr>)}</tbody></table></div>
 <div className="mt-2 flex items-center justify-between border-t border-gray-200 pt-2 text-[11px]"><div className="flex items-center gap-3"><span>Total Vendas: <b>{money(total)}</b></span><span>Meta Batida: {goal>0&&total>=goal?<span className="rounded bg-emerald-100 px-1.5 py-0.5 text-[9px] font-bold text-emerald-800">🟢 META ATINGIDA</span>:<span className="text-gray-500">NÃO</span>}</span><span>Total Comissão: <b>{money(commission)}</b></span></div><button type="button" disabled={!calcId||!lines.length} className="flex h-7 w-[140px] items-center justify-center gap-1 rounded-md bg-emerald-600 text-[11px] font-bold text-white disabled:opacity-40" onClick={()=>void exportXlsx(lines,clients)}><FileSpreadsheet size={12}/>Exportar XLSX</button></div>
 </section></main>
}
