import { ArrowLeft, Plus } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
type Product={id:string;codigo:string;nome:string}
type Row={id:string;sku_insumo:string;qtd:number;unidade:string;custo_unitario:number}
const input='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]'
const label='mb-0.5 text-[10px] font-bold uppercase text-gray-500'
const button='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'
export default function EngenhariaBOM(){
 const nav=useNavigate(),[pai,setPai]=useState(''),[sku,setSku]=useState(''),[qtd,setQtd]=useState('1'),[un,setUn]=useState('UN'),[custo,setCusto]=useState('0'),[products,setProducts]=useState<Product[]>([]),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState('')
 const load=async()=>{const p=await supabase.from('erp_produtos').select('id,codigo,nome').eq('ativo',true).order('codigo').limit(3000);if(p.error)throw p.error;setProducts((p.data??[]) as Product[]);if(pai){const r=await supabase.from('erp_pcp_bom_itens').select('id,sku_insumo,qtd,unidade,custo_unitario').eq('produto_pai_id',pai).order('created_at');if(r.error)throw r.error;setRows((r.data??[]) as Row[])}}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar BOM.'))},[pai])
 const add=async()=>{const p=products.find(x=>x.codigo===sku);if(!p||!pai){setError('Selecione o produto pai e um insumo cadastrado.');return}const r=await supabase.rpc('erp_pcp_bom_adicionar',{p_produto_pai_id:pai,p_produto_id:p.id,p_sku_insumo:p.codigo,p_qtd:Number(qtd),p_unidade:un,p_custo_unitario:Number(custo)});if(r.error)setError(r.error.message);else{setSku('');await load()}}
 return <main className="min-h-screen bg-slate-50 p-3"><div className="space-y-2"><div className="flex items-center gap-2"><button onClick={()=>nav('/engenharia')} className={button+' border border-gray-200 bg-white text-gray-600'}><ArrowLeft size={12}/>Voltar</button><b className="text-[13px]">ENGENHARIA DE PRODUTO (BOM)</b></div>{error&&<div className="border border-red-200 bg-red-50 p-1 text-[10px] text-red-700">{error}</div>}<section className="rounded-md border border-gray-200 bg-white p-2"><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><label className={label}>Produto a Fabricar</label><select className={input+' w-full'} value={pai} onChange={e=>setPai(e.target.value)}><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.codigo} - {p.nome}</option>)}</select></div></div></section><section className="rounded-md border border-gray-200 bg-gray-50 p-2"><div className="flex items-end gap-2"><div className="w-[140px]"><label className={label}>Matéria-Prima</label><input className={input+' w-[140px]'} value={sku} onChange={e=>setSku(e.target.value)}/></div><div className="w-[70px]"><label className={label}>Qtd Insumo</label><input className={input+' w-[70px]'} value={qtd} onChange={e=>setQtd(e.target.value)}/></div><div className="w-[60px]"><label className={label}>Unidade</label><input className={input+' w-[60px]'} value={un} onChange={e=>setUn(e.target.value)}/></div><div className="w-[90px]"><label className={label}>Custo Est. UN</label><input className={input+' w-[90px]'} value={custo} onChange={e=>setCusto(e.target.value)}/></div><button onClick={()=>void add()} className={button+' w-[80px] bg-blue-600 text-white'}><Plus size={12}/>Adicionar</button></div></section><section className="h-[200px] overflow-auto rounded-md border border-gray-200 bg-white"><table className="w-full text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th>SKU</th><th>Qtd</th><th>Un</th><th>Custo UN</th><th>Custo Total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="h-[26px] even:bg-slate-50"><td>{r.sku_insumo}</td><td>{r.qtd}</td><td>{r.unidade}</td><td>{Number(r.custo_unitario).toFixed(2)}</td><td>{(Number(r.qtd)*Number(r.custo_unitario)).toFixed(2)}</td></tr>)}</tbody></table></section></div></main>
}