import { ArrowLeft, Plus } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
type Product={id:string;codigo:string;nome:string};type Post={id:string;codigo_posto:string;nome_posto:string};type Row={id:string;sequencia:number;operacao:string;posto_id:string;tempo_min:number}
const i='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]';const l='mb-0.5 block text-[10px] font-bold uppercase text-gray-500';const b='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'
export default function FichaProcesso(){
 const n=useNavigate();const [produto,setProduto]=useState('');const [seq,setSeq]=useState('10');const [operacao,setOperacao]=useState('');const [posto,setPosto]=useState('');const [tempo,setTempo]=useState('0');const [products,setProducts]=useState<Product[]>([]);const [postos,setPostos]=useState<Post[]>([]);const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState('')
 const load=async()=>{const [p,w]=await Promise.all([supabase.from('erp_produtos').select('id,codigo,nome').eq('ativo',true).order('codigo').limit(3000),supabase.from('erp_postos_trabalho').select('id,codigo_posto,nome_posto').eq('ativo',true).order('codigo_posto')]);if(p.error||w.error)throw new Error(p.error?.message??w.error?.message??'Falha ao carregar processo.');setProducts((p.data??[]) as Product[]);setPostos((w.data??[]) as Post[]);if(produto){const r=await supabase.from('erp_pcp_roteiro_operacoes').select('id,sequencia,operacao,posto_id,tempo_min').eq('produto_id',produto).order('sequencia');if(r.error)throw r.error;setRows((r.data??[]) as Row[])}}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar ficha.'))},[produto])
 const add=async()=>{setError('');if(!produto||!posto||!operacao.trim()){setError('Produto, operação e posto são obrigatórios.');return}const empresa=await supabase.rpc('erp_current_empresa_id');if(empresa.error||!empresa.data){setError('Empresa não identificada.');return}const r=await supabase.from('erp_pcp_roteiro_operacoes').insert({empresa_id:empresa.data,produto_id:produto,sequencia:Number(seq),operacao:operacao.trim(),posto_id:posto,tempo_min:Number(tempo)});if(r.error){setError(r.error.message);return}setOperacao('');await load()}
 const total=rows.reduce((s,r)=>s+Number(r.tempo_min),0)
 return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mx-auto max-w-[1500px] space-y-2"><div className="flex items-center gap-2"><button type="button" onClick={()=>n(-1)} className={b+' border border-gray-200 bg-white text-gray-600'}><ArrowLeft size={12}/>Voltar</button><h1 className="text-[13px] font-bold">ROTEIRO DE PRODUÇÃO E FICHA DE PROCESSO</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><label className={l}>Produto</label><select className={i+' w-full'} value={produto} onChange={e=>setProduto(e.target.value)}><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.nome}</option>)}</select></div><div className="w-[50px]"><label className={l}>Seq.</label><input className={i+' w-[50px]'} value={seq} onChange={e=>setSeq(e.target.value)}/></div><div className="w-[160px]"><label className={l}>Operação</label><input className={i+' w-[160px]'} value={operacao} onChange={e=>setOperacao(e.target.value)}/></div><div className="w-[180px]"><label className={l}>Posto de Trabalho</label><select className={i+' w-[180px]'} value={posto} onChange={e=>setPosto(e.target.value)}><option value="">Selecione</option>{postos.map(p=><option key={p.id} value={p.id}>{p.codigo_posto} · {p.nome_posto}</option>)}</select></div><div className="w-[80px]"><label className={l}>Tempo Min.</label><input type="number" min="0" step="0.001" className={i+' w-[80px]'} value={tempo} onChange={e=>setTempo(e.target.value)}/></div><button type="button" onClick={()=>void add()} className={b+' w-[80px] bg-blue-600 text-white'}><Plus size={12}/>Adicionar</button></div></section>{error&&<div className="rounded border border-red-200 bg-red-50 px-2 py-1 text-[10px] text-red-700">{error}</div>}<section className="h-[200px] overflow-auto rounded-md border border-gray-200 bg-white shadow-sm"><table className="w-full min-w-[650px] text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="w-[60px] font-normal">Seq.</th><th className="px-2 text-left font-normal">Operação</th><th className="w-[220px] px-2 text-left font-normal">Posto</th><th className="w-[100px] px-2 text-right font-normal">Tempo Min.</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="h-[26px] border-b border-gray-100 even:bg-slate-50"><td className="text-center">{r.sequencia}</td><td className="px-2">{r.operacao}</td><td className="px-2">{postos.find(p=>p.id===r.posto_id)?.nome_posto??'—'}</td><td className="px-2 text-right">{Number(r.tempo_min).toFixed(3)}</td></tr>)}</tbody></table></section><div className="text-right text-[11px] font-bold">Tempo Total Fábrica: {total.toFixed(3)} min</div></div></main>
}