import { ArrowLeft, Factory, Play, CheckCircle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'

type Row={id:string;numero_op:string;produto_id:string;quantidade:number;status:string;criado_em:string;pedido_venda_id:string|null;data_prevista:string|null}
type Product={id:string;codigo:string;nome:string}
type Order={id:string;numero:string;cliente_id:string|null}
type Tab='TODOS'|'EM_FILA'|'EM_PROCESSO'|'CONCLUIDO'
const input='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]'
const button='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'

const normalizeStatus=(value:string):string=>{const v=value.trim().toUpperCase().replaceAll(' ','_');if(v.includes('CONCLU'))return 'CONCLUIDO';if(v.includes('PROCESS'))return 'EM_PROCESSO';if(v.includes('FILA')||v.includes('PRODUZ'))return 'EM_FILA';return v||'EM_FILA'}

export default function PainelOrdensProducao(){
 const n=useNavigate();const [tab,setTab]=useState<Tab>('TODOS');const [query,setQuery]=useState('');const [rows,setRows]=useState<Row[]>([]);const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [error,setError]=useState('')
 const load=async()=>{setError('');const empresa=await supabase.rpc('erp_current_empresa_id');if(empresa.error||!empresa.data){setError(empresa.error?.message??'Empresa da sessão não identificada.');return}const empresaId=String(empresa.data);const r=await supabase.from('erp_ordens_producao').select('id,numero_op,produto_id,quantidade,status,criado_em,pedido_venda_id,data_prevista').eq('empresa_id',empresaId).order('prioridade').order('criado_em',{ascending:false}).limit(500);if(r.error){setError(r.error.message);return}const data=(r.data??[]) as Row[];setRows(data);const pids=[...new Set(data.map(x=>x.produto_id))];const oids=[...new Set(data.map(x=>x.pedido_venda_id).filter((x):x is string=>Boolean(x)))];const [p,o]=await Promise.all([pids.length?supabase.from('erp_produtos').select('id,codigo,nome').eq('empresa_id',empresaId).in('id',pids):Promise.resolve({data:[],error:null}),oids.length?supabase.from('erp_pedidos_venda').select('id,numero,cliente_id').eq('empresa_id',empresaId).in('id',oids):Promise.resolve({data:[],error:null})]);if(p.error||o.error){setError(p.error?.message??o.error?.message??'Falha ao carregar referências das OPs.');return}setProducts((p.data??[]) as Product[]);setOrders((o.data??[]) as Order[])}
 useEffect(()=>{void load()},[])
 const productMap=useMemo(()=>new Map(products.map(p=>[p.id,p.codigo+' · '+p.nome])),[products]);const orderMap=useMemo(()=>new Map(orders.map(o=>[o.id,String(o.numero)])),[orders])
 const filtered=rows.filter(r=>{const status=normalizeStatus(r.status);const matchTab=tab==='TODOS'||status===tab;const text=(r.numero_op+' '+(productMap.get(r.produto_id)??'')+' '+(r.pedido_venda_id?orderMap.get(r.pedido_venda_id)??'':'' )).toLowerCase();return matchTab&&(!query||text.includes(query.toLowerCase()))})
 const changeStatus=async(row:Row,status:string)=>{const r=await supabase.from('erp_ordens_producao').update({status}).eq('id',row.id);if(r.error){setError(r.error.message);return}await load()}
 return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mx-auto max-w-[1600px] space-y-2"><div className="flex items-center gap-2"><button type="button" onClick={()=>n(-1)} className={button+' border border-gray-200 bg-white text-gray-600'}><ArrowLeft size={12}/>Voltar</button><Factory size={14} className="text-blue-700"/><h1 className="text-[13px] font-bold">FILA DE FABRICAÇÃO INDUSTRIAL — OPs</h1><div className="ml-auto"><input className={input+' w-[140px]'} placeholder="Buscar OP" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
  <section className="flex items-center gap-2 rounded-md border border-gray-200 bg-white p-2"><button type="button" onClick={()=>setTab('TODOS')} className={button+' '+(tab==='TODOS'?'bg-slate-700 text-white':'border border-gray-200 bg-white')}>📊 TODOS</button><button type="button" onClick={()=>setTab('EM_FILA')} className={button+' '+(tab==='EM_FILA'?'bg-amber-500 text-white':'border border-gray-200 bg-white')}>🟡 EM FILA</button><button type="button" onClick={()=>setTab('EM_PROCESSO')} className={button+' '+(tab==='EM_PROCESSO'?'bg-blue-600 text-white':'border border-gray-200 bg-white')}>🔵 EM PROCESSO</button><button type="button" onClick={()=>setTab('CONCLUIDO')} className={button+' '+(tab==='CONCLUIDO'?'bg-emerald-600 text-white':'border border-gray-200 bg-white')}>🟢 CONCLUÍDO</button></section>
  {error&&<div className="rounded border border-red-200 bg-red-50 px-2 py-1 text-[10px] text-red-700">{error}</div>}
  <section className="scroll-fade-x h-[280px] overflow-auto rounded-md border border-gray-200 bg-white shadow-sm">
   <table className="w-full min-w-[950px] border-collapse text-[10px]">
    <thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="w-[100px] px-2 text-left font-normal">Nº OP</th><th className="w-[120px] px-2 text-left font-normal">Pedido Origem</th><th className="px-2 text-left font-normal">Produto</th><th className="w-[120px] px-2 text-right font-normal">Qtd. Fabricar</th><th className="w-[110px] px-2 text-left font-normal">Data</th><th className="w-[130px] px-2 text-left font-normal">Status</th><th className="w-[150px] px-2 text-center font-normal">Workflow</th></tr></thead>
    <tbody>{filtered.map(row => {
     const status = normalizeStatus(row.status)
     return <tr key={row.id} className="h-[26px] border-b border-gray-100 even:bg-slate-50"><td className="px-2 font-bold">{row.numero_op}</td><td className="px-2">{row.pedido_venda_id ? (orderMap.get(row.pedido_venda_id) ?? '—') : '—'}</td><td className="px-2">{productMap.get(row.produto_id) ?? row.produto_id}</td><td className="px-2 text-right">{Number(row.quantidade).toLocaleString('pt-BR')}</td><td className="px-2">{row.data_prevista ?? new Date(row.criado_em).toLocaleDateString('pt-BR')}</td><td className="px-2">{status === 'CONCLUIDO' ? <span className="rounded bg-green-100 px-1.5 py-0.5 text-[10px] font-bold text-green-800">🟢 CONCLUÍDO</span> : status === 'EM_PROCESSO' ? <span className="rounded bg-blue-100 px-1.5 py-0.5 text-[10px] font-bold text-blue-800">🔵 EM PROCESSO</span> : <span className="rounded bg-amber-100 px-1.5 py-0.5 text-[10px] font-bold text-amber-800">🟡 EM FILA</span>}</td><td className="px-2"><div className="flex justify-center gap-1">{status !== 'EM_PROCESSO' && status !== 'CONCLUIDO' && <button type="button" onClick={() => void changeStatus(row, 'EM_PROCESSO')} className="inline-flex h-7 w-7 items-center justify-center rounded-md border border-blue-200 text-blue-700" title="Iniciar OP"><Play size={11}/></button>}{status === 'EM_PROCESSO' && <button type="button" onClick={() => void changeStatus(row, 'CONCLUIDO')} className="inline-flex h-7 w-7 items-center justify-center rounded-md border border-emerald-200 text-emerald-700" title="Concluir OP"><CheckCircle size={11}/></button>}</div></td></tr>
    })}{!filtered.length && <tr><td colSpan={7} className="h-16 text-center text-gray-400">Nenhuma OP encontrada.</td></tr>}</tbody>
   </table>
  </section>
 </div></main>
}