import { useEffect,useState } from 'react'
import { CheckCircle2,Lock,Search,ShieldCheck } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import { EntityCodeLookup,type LookupRecord } from '../../components/industrial/EntityCodeLookup'
export default function QualidadeAssinaturaIT(){
 const[records,setRecords]=useState<LookupRecord[]>([]),[codigo,setCodigo]=useState(''),[rev,setRev]=useState(''),[hash,setHash]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[ok,setOk]=useState('')
 useEffect(()=>{void (async()=>{const r=await supabase.from('erp_qualidade_documentos_revisoes').select('id,codigo_documento,titulo_documento,revisao,status').eq('status','VIGENTE').order('codigo_documento');if(!r.error)setRecords((r.data??[]).map(x=>({id:x.id,codigo:x.codigo_documento,nome:x.titulo_documento})))})()},[])
 const sign=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setErr('');setOk('');try{const s=await supabase.auth.getSession();if(!s.data.session)throw new Error('Gestor não autenticado.');const row=records.find(x=>x.codigo===codigo);if(!row)throw new Error('Documento vigente não encontrado.');const id=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(row.id+'|'+codigo+'|'+rev+'|'+s.data.session.user.id+'|'+new Date().toISOString()));const h=Array.from(new Uint8Array(id)).map(b=>b.toString(16).padStart(2,'0')).join('');const u=await supabase.from('erp_qualidade_documentos_revisoes').update({assinatura_digital_hash:h}).eq('id',row.id).is('assinatura_digital_hash',null);if(u.error)throw u.error;if(u.data===null){}setHash(h);setOk('Revisão assinada e protegida contra alterações críticas pelo banco.')}catch(x){setErr(x instanceof Error?x.message:'Falha ao assinar.')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-100 p-4 text-slate-900"><form onSubmit={sign} className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-6 shadow-md"><div className="flex items-center justify-between gap-4 border-b pb-5"><div><div className="flex items-center gap-2 text-sky-700"><ShieldCheck/><span className="text-xs font-black uppercase tracking-widest">SGQ · Homologação</span></div><h1 className="text-2xl font-black">Assinatura Eletrônica de IT</h1></div><button disabled={busy||!!hash} className="h-11 rounded-lg bg-sky-700 px-5 text-sm font-black text-white"><Lock size={16} className="mr-2 inline"/>{busy?'ASSINANDO':'ASSINAR E LIBERAR'}</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><EntityCodeLookup label="DOCUMENTO VIGENTE" value={records.find(r=>r.codigo===codigo)?.id??''} records={records} required onChange={id=>{const x=records.find(r=>r.id===id);if(x)setCodigo(x.codigo??'')}} onSelect={x=>setCodigo(x.codigo??'')}/><label className="grid gap-2 text-xs font-black uppercase">REVISÃO<input className="h-[54px] rounded-md border border-slate-300 px-3 text-base font-black" value={rev} onChange={e=>setRev(e.target.value)}/></label></div>{(err||ok)&&<div className="mt-5 rounded-xl border p-4 font-bold">{err||ok}</div>}{hash&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><CheckCircle2 className="text-emerald-700"/><p className="mt-2 break-all font-mono text-xs">{hash}</p></div>}</form></main>
}