import { ArrowLeft, Calculator, FileSpreadsheet } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import { makeXlsx } from '../../utils/makeXlsx'

type Seller={id:string;nome:string}
type Line={id:string;pedido_id:string;produto_id:string;quantidade:number;valor_total:number;percentual:number;comissao_liquida:number;produto:string;cliente:string}
const i='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]';const l='mb-0.5 block text-[10px] font-bold uppercase text-gray-500';const b='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'
function exportXlsx(rows:string[][],name:string){const blob=makeXlsx(rows,'Comissões');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export default function AuditoriaComissoes(){
 const n=useNavigate();const [sellers,setSellers]=useState<Seller[]>([]);const [seller,setSeller]=useState('');const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const [target,setTarget]=useState('0');const [lines,setLines]=useState<Line[]>([]);const [meta,setMeta]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{void (async()=>{const r=await supabase.from('erp_usuarios').select('id,nome').eq('ativo',true).is('deleted_at',null).order('nome');if(r.error)setError(r.error.message);else setSellers((r.data??[]) as Seller[])})()},[])
 const calculate=async()=>{setError('');const r=await supabase.rpc('erp_comissao_calcular',{p_competencia:month+'-01',p_usuario_id:seller||null,p_meta_faturamento:Number(target)||0});if(r.error){setError(r.error.message);return}const result=r.data as {calculo_id:string;meta_atingida:boolean};setMeta(Boolean(result.meta_atingida));const q=await supabase.from('erp_comissao_linhas').select('id,pedido_id,produto_id,quantidade,valor_total,percentual,comissao_liquida').eq('calculo_id',result.calculo_id).order('created_at');if(q.error){setError(q.error.message);return}const items=q.data??[];const pids=[...new Set(items.map(x=>x.produto_id))];const oids=[...new Set(items.map(x=>x.pedido_id))];const [p,o]=await Promise.all([pids.length?supabase.from('erp_produtos').select('id,codigo,nome').in('id',pids):Promise.resolve({data:[],error:null}),oids.length?supabase.from('erp_pedidos_venda').select('id,cliente_id').in('id',oids):Promise.resolve({data:[],error:null})]);if(p.error||o.error){setError(p.error?.message??o.error?.message??'Falha ao carregar comissão.');return}const cids=[...new Set((o.data??[]).map(x=>x.cliente_id).filter((x):x is string=>Boolean(x)))];const c= cids.length?await supabase.from('erp_clientes').select('id,nome').in('id',cids):{data:[],error:null};if(c.error){setError(c.error.message);return}const pm=new Map((p.data??[]).map(x=>[x.id,x.codigo]));const om=new Map((o.data??[]).map(x=>[x.id,x.cliente_id]));const cm=new Map((c.data??[]).map(x=>[x.id,x.nome]));setLines(items.map(x=>({id:x.id,pedido_id:x.pedido_id,produto_id:x.produto_id,quantidade:Number(x.quantidade),valor_total:Number(x.valor_total),percentual:Number(x.percentual),comissao_liquida:Number(x.comissao_liquida),produto:pm.get(x.produto_id)??x.produto_id,cliente:cm.get(om.get(x.pedido_id)??'')??'—'})))}
 const downloadComissao=()=>exportXlsx([['Pedido','Cliente','SKU','Qtd','Valor Total Nota','%','Comissão Líquida'],...lines.map(x=>[x.pedido_id,x.cliente,x.produto,String(x.quantidade),x.valor_total.toFixed(2),x.percentual.toFixed(2),x.comissao_liquida.toFixed(2)])],`comissoes-${month}.xlsx`)
 return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mx-auto max-w-[1600px] space-y-2"><div className="flex items-center gap-2"><button type="button" onClick={()=>n(-1)} className={b+' border border-gray-200 bg-white text-gray-600'}><ArrowLeft size={12}/>Voltar</button><h1 className="text-[13px] font-bold">AUDITORIA DE COMISSÕES E METAS</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div className="w-[160px]"><label className={l}>Vendedor</label><select className={i+' w-[160px]'} value={seller} onChange={e=>setSeller(e.target.value)}><option value="">Todos</option>{sellers.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></div><div className="w-[120px]"><label className={l}>Competência</label><input type="month" className={i+' w-[120px]'} value={month} onChange={e=>setMonth(e.target.value)}/></div><div className="w-[110px]"><label className={l}>Meta R$</label><input type="number" className={i+' w-[110px]'} value={target} onChange={e=>setTarget(e.target.value)}/></div><button type="button" onClick={()=>void calculate()} className={b+' w-[110px] bg-blue-600 text-white'}><Calculator size={12}/>Calcular</button></div></section>{error&&<div className="rounded border border-red-200 bg-red-50 px-2 py-1 text-[10px] text-red-700">{error}</div>}<section className="scroll-fade-x h-[250px] overflow-auto rounded-md border border-gray-200 bg-white shadow-sm"><table className="w-full min-w-[900px] border-collapse text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="px-2 text-left font-normal">Pedido</th><th className="px-2 text-left font-normal">Cliente</th><th className="px-2 text-left font-normal">SKU</th><th className="px-2 text-right font-normal">Qtd</th><th className="px-2 text-right font-normal">Valor Total Nota</th><th className="px-2 text-right font-normal">%</th><th className="px-2 text-right font-normal">Comissão Líquida</th></tr></thead><tbody>{lines.map(x=><tr key={x.id} className="h-[26px] border-b border-gray-100 even:bg-slate-50"><td className="px-2">{x.pedido_id}</td><td className="px-2">{x.cliente}</td><td className="px-2">{x.produto}</td><td className="px-2 text-right">{x.quantidade}</td><td className="px-2 text-right">{x.valor_total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td className="px-2 text-right">{x.percentual.toFixed(2)}</td><td className="px-2 text-right">{x.comissao_liquida.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td></tr>)}{meta&&<tr><td colSpan={7} className="p-2"><span className="rounded bg-green-100 px-2 py-0.5 text-[10px] font-bold text-green-800">🟢 META ATINGIDA</span></td></tr>}</tbody></table></section><div className="flex justify-end"><button type="button" onClick={downloadComissao} className={b+' w-[140px] bg-emerald-600 text-white'}><FileSpreadsheet size={12}/>Exportar Comissão</button></div></div></main>
}