import { ArrowLeft, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'

type Rule={id:string;codigo:string;descricao:string;casas:number;ativo:boolean}
const i='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]';const l='mb-0.5 block text-[10px] font-bold uppercase text-gray-500';const b='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'
export default function CadastroDecimais(){
 const n=useNavigate();const [rules,setRules]=useState<Rule[]>([]);const [codigo,setCodigo]=useState('VOLUME');const [descricao,setDescricao]=useState('Cubagem de faturamento e carga');const [casas,setCasas]=useState('4');const [error,setError]=useState('');const [message,setMessage]=useState('')
 const load=async()=>{const r=await supabase.from('erp_regras_decimais').select('id,codigo,descricao,casas,ativo').eq('ativo',true).order('codigo');if(r.error)setError(r.error.message);else setRules((r.data??[]) as Rule[])}
 useEffect(()=>{void load()},[])
 const save=async()=>{setError('');setMessage('');const r=await supabase.rpc('erp_decimal_salvar_regra',{p_codigo:codigo.trim().toUpperCase(),p_descricao:descricao.trim(),p_casas:Number(casas)});if(r.error){setError(r.error.message);return}setMessage('Regra salva.');await load()}
 return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mx-auto max-w-[1400px] space-y-2"><div className="flex items-center gap-2"><button type="button" onClick={()=>n(-1)} className={b+' border border-gray-200 bg-white text-gray-600'}><ArrowLeft size={12}/>Voltar</button><h1 className="text-[13px] font-bold">CADASTRO DE PRECISÃO DECIMAL — CUBAGEM</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div className="w-[110px]"><label className={l}>Código</label><input className={i+' w-[110px]'} value={codigo} onChange={e=>setCodigo(e.target.value)}/></div><div className="min-w-0 flex-1"><label className={l}>Descrição</label><input className={i+' w-full'} value={descricao} onChange={e=>setDescricao(e.target.value)}/></div><div className="w-[70px]"><label className={l}>Casas</label><input className={i+' w-[70px]'} type="number" min="0" max="8" value={casas} onChange={e=>setCasas(e.target.value)}/></div><button type="button" onClick={()=>void save()} className={b+' w-[95px] bg-blue-600 text-white'}><Save size={12}/>Gravar</button></div></section><section className="rounded-md border border-gray-200 bg-white shadow-sm"><table className="w-full text-[10px]"><thead className="bg-slate-700 text-white"><tr className="h-7"><th className="px-2 text-left font-normal">Código</th><th className="px-2 text-left font-normal">Descrição</th><th className="w-[80px] px-2 text-right font-normal">Casas</th><th className="w-[160px] px-2 text-right font-normal">Exemplo</th></tr></thead><tbody>{rules.map(r=><tr key={r.id} className="h-[26px] border-b border-gray-100 even:bg-slate-50"><td className="px-2 font-bold">{r.codigo}</td><td className="px-2">{r.descricao}</td><td className="px-2 text-right">{r.casas}</td><td className="px-2 text-right">{(123.456789).toFixed(r.casas)}</td></tr>)}</tbody></table></section>{message&&<div className="text-[10px] font-bold text-emerald-700">{message}</div>}{error&&<div className="text-[10px] text-red-700">{error}</div>}</div></main>
}