import { ArrowLeft, RefreshCw } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'

type Account={id:string;codigo:string;nome:string;banco:string|null;saldo_inicial:number;ativo:boolean}
type Row={id:string;documento:string|null;descricao:string;debito:number;credito:number;criado_em:string}
const input='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px] outline-none focus:border-blue-400'
const label='mb-0.5 block text-[10px] font-bold uppercase text-gray-500'
const button='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'
export default function PainelRazaoGeral(){
 const navigate=useNavigate();const [accounts,setAccounts]=useState<Account[]>([]);const [accountId,setAccountId]=useState('');const [rows,setRows]=useState<Row[]>([]);const [balance,setBalance]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 const loadAccounts=async()=>{const r=await supabase.from('erp_contas_bancarias').select('id,codigo,nome,banco,saldo_inicial,ativo').eq('ativo',true).order('nome');if(r.error){setError(r.error.message);return}setAccounts((r.data??[]) as Account[])}
 const loadLedger=async()=>{if(!accountId){setRows([]);setBalance(0);return}setLoading(true);const r=await supabase.from('erp_fiscal_razao_lancamentos').select('id,documento,descricao,debito,credito,criado_em').eq('conta_bancaria_id',accountId).order('criado_em',{ascending:false}).limit(1000);if(r.error){setError(r.error.message);setLoading(false);return}const data=(r.data??[]) as Row[];setRows(data);const opening=Number(accounts.find(a=>a.id===accountId)?.saldo_inicial??0);setBalance(opening+data.reduce((sum,line)=>sum+Number(line.credito)-Number(line.debito),0));setLoading(false)}
 useEffect(()=>{void loadAccounts()},[]);useEffect(()=>{void loadLedger()},[accountId])
 const totalDebit=useMemo(()=>rows.reduce((s,r)=>s+Number(r.debito),0),[rows]);const totalCredit=useMemo(()=>rows.reduce((s,r)=>s+Number(r.credito),0),[rows])
 return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mx-auto max-w-[1600px] space-y-2"><div className="flex items-center gap-2"><button type="button" className={button+' border border-gray-200 bg-white text-gray-600'} onClick={()=>navigate(-1)}><ArrowLeft size={12}/>Voltar</button><h1 className="text-[13px] font-bold">MONITOR DO RAZÃO GERAL — GL</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div className="w-[160px] shrink-0"><label className={label}>Empresa</label><input className={input+' w-[160px] bg-gray-100'} value="Empresa atual" readOnly/></div><div className="w-[160px] shrink-0"><label className={label}>Banco / Diário</label><select className={input+' w-[160px]'} value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.codigo} · {a.nome}</option>)}</select></div><button type="button" className={button+' w-[110px] bg-blue-600 text-white'} onClick={()=>void loadLedger()} disabled={loading}><RefreshCw size={12}/>Filtrar</button></div>{error&&<div className="mt-2 rounded border border-red-200 bg-red-50 px-2 py-1 text-[10px] text-red-700">{error}</div>}<div className="scroll-fade-x mt-2 h-[250px] overflow-auto rounded border border-gray-200"><table className="w-full min-w-[720px] border-collapse text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="px-2 text-left font-normal">Data</th><th className="px-2 text-left font-normal">Documento</th><th className="px-2 text-left font-normal">Descrição</th><th className="px-2 text-right font-normal">Débito</th><th className="px-2 text-right font-normal">Crédito</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="h-[26px] border-b border-gray-100 even:bg-slate-50"><td className="px-2">{new Date(r.criado_em).toLocaleDateString('pt-BR')}</td><td className="px-2">{r.documento??'—'}</td><td className="px-2">{r.descricao}</td><td className="px-2 text-right">{Number(r.debito).toLocaleString('pt-BR',{minimumFractionDigits:2})}</td><td className="px-2 text-right">{Number(r.credito).toLocaleString('pt-BR',{minimumFractionDigits:2})}</td></tr>)}{!rows.length&&<tr><td colSpan={5} className="h-16 text-center text-gray-400">{loading?'Consultando razão…':'Selecione uma conta bancária.'}</td></tr>}</tbody></table></div><div className="mt-2 flex h-7 items-center justify-between rounded-sm bg-slate-700 px-3 text-[11px] font-bold text-white"><span>Débitos {totalDebit.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} · Créditos {totalCredit.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</span><span className={balance>=0?'rounded bg-green-200 px-2 py-0.5 text-green-800':'rounded bg-red-200 px-2 py-0.5 text-red-800'}>SALDO OFICIAL DO RAZÃO: {balance.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</span></div></section></div></main>
}