import { useEffect, useState } from 'react'
import { Filter, RefreshCw, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
type Log={id:string;created_at:string|null;usuario_id:string|null;acao:string|null;tabela:string|null;registro_id:string|null;dados:unknown}
export default function AdminLogs(){const[rows,setRows]=useState<Log[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const r=await supabase.from('logs_sistema').select('id,created_at,usuario_id,acao,tabela,registro_id,dados').order('created_at',{ascending:false}).limit(500);if(r.error)throw r.error;setRows((r.data??[]) as Log[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a trilha de auditoria.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const filtered=rows.filter(r=>{const q=query.trim().toLowerCase();return !q||[r.usuario_id,r.acao,r.tabela,r.registro_id].filter(Boolean).join(' ').toLowerCase().includes(q)})
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-900 print:bg-white"><div className="mx-auto max-w-[1700px] space-y-5"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-4 print:hidden"><div><p className="text-sm font-black uppercase tracking-widest text-sky-700">ADMINISTRATIVO › TRILHA DE AUDITORIA</p><h1 className="text-3xl font-black">Logs de Segurança e Conformidade</h1><p className="mt-1 text-base font-semibold text-slate-600">Histórico real de ações persistidas no banco.</p></div><div className="flex gap-2"><button type="button" onClick={()=>void load()} className="flex h-[54px] items-center gap-2 rounded-md border border-slate-300 bg-white px-5 font-black"><RefreshCw size={18}/> ATUALIZAR</button><button type="button" onClick={()=>window.print()} className="flex h-[54px] items-center gap-2 rounded-md bg-slate-900 px-5 font-black text-white"><ShieldCheck size={18}/> IMPRIMIR</button></div></header><section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-center gap-3 print:hidden"><Filter size={20} className="text-sky-700"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar usuário, tabela, ação ou registro" className="h-[54px] min-w-[320px] flex-1 rounded-md border border-slate-300 bg-white px-3 text-base font-semibold text-slate-900"/><span className="font-black text-slate-600">{filtered.length} evento(s)</span></div>{error&&<div className="mb-4 rounded-md border border-rose-300 bg-rose-50 p-4 font-bold text-rose-800">{error}</div>}<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-base"><thead className="bg-slate-100"><tr className="h-[54px] text-left font-black"><th className="px-4">Data / Hora</th><th className="px-4">Usuário ID</th><th className="px-4">Ação</th><th className="px-4">Tabela</th><th className="px-4">Registro</th><th className="px-4">Dados</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="h-[54px] border-t border-slate-200"><td className="whitespace-nowrap px-4">{r.created_at?new Date(r.created_at).toLocaleString('pt-BR'):'—'}</td><td className="px-4 font-semibold">{r.usuario_id??'—'}</td><td className="px-4 font-black">{r.acao??'—'}</td><td className="px-4">{r.tabela??'—'}</td><td className="px-4">{r.registro_id??'—'}</td><td className="max-w-[420px] truncate px-4 text-sm text-slate-600">{r.dados?JSON.stringify(r.dados):'—'}</td></tr>)}{!busy&&!filtered.length&&<tr><td colSpan={6} className="p-10 text-center font-bold text-slate-600">Nenhum evento encontrado.</td></tr>}</tbody></table></div></section></div></main>
}
