import { useEffect, useMemo, useState } from 'react'
import { Filter, History, RefreshCw, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Log={id:string;created_at:string|null;usuario_id:string|null;acao:string|null;tabela:string|null;registro_id:string|null;dados:unknown}
type User={id:string;nome:string|null;email:string|null}

export default function AdminLogs(){
 const [rows,setRows]=useState<Log[]>([]),[users,setUsers]=useState<User[]>([]),[usuarioFiltro,setUsuarioFiltro]=useState('Todos'),[moduloFiltro,setModuloFiltro]=useState('Todos'),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const [logs,userRows]=await Promise.all([supabase.from('logs_sistema').select('id,created_at,usuario_id,acao,tabela,registro_id,dados').order('created_at',{ascending:false}).limit(500),supabase.from('erp_usuarios').select('id,nome,email').order('nome')]);if(logs.error)throw logs.error;if(userRows.error)throw userRows.error;setRows((logs.data||[]) as Log[]);setUsers((userRows.data||[]) as User[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a trilha de auditoria.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const modules=useMemo(()=>Array.from(new Set(rows.map(r=>r.tabela).filter((v):v is string=>Boolean(v)))).sort(),[rows])
 const filtered=useMemo(()=>rows.filter(r=>(usuarioFiltro==='Todos'||r.usuario_id===usuarioFiltro)&&(moduloFiltro==='Todos'||r.tabela===moduloFiltro)),[rows,usuarioFiltro,moduloFiltro])
 const userMap=useMemo(()=>new Map(users.map(u=>[u.id,u])),[users])
 return <div className="space-y-6 bg-[#F4F7FE]"><header className="border-b border-slate-200 pb-4"><span className="block text-xs font-bold uppercase tracking-wider text-blue-600">Configurações / Auditoria</span><h2 className="text-3xl font-black tracking-tight text-slate-900">Logs do Sistema</h2><p className="mt-1 text-sm text-slate-500">Rastreamento real de modificações, acessos e operações persistidas no Supabase.</p></header>
 {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
 <section className="rounded-3xl border border-slate-100 bg-white p-6 shadow-xl shadow-slate-200/40"><div className="mb-4 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-400"><Filter size={17} className="text-[#2D8DB8]"/>Filtros de Rastreabilidade</div><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><label className="text-[11px] font-black uppercase text-slate-500">Filtrar por Usuário<select value={usuarioFiltro} onChange={e=>setUsuarioFiltro(e.target.value)} className="mt-1 w-full rounded-2xl border-2 border-slate-100 bg-slate-50 px-4 py-2 text-sm font-bold text-slate-800"><option value="Todos">Todos os Usuários</option>{users.map(u=><option key={u.id} value={u.id}>{u.nome||u.email||u.id}</option>)}</select></label><label className="text-[11px] font-black uppercase text-slate-500">Módulo / Tabela<select value={moduloFiltro} onChange={e=>setModuloFiltro(e.target.value)} className="mt-1 w-full rounded-2xl border-2 border-slate-100 bg-slate-50 px-4 py-2 text-sm font-bold text-slate-800"><option value="Todos">Todos os Módulos</option>{modules.map(m=><option key={m} value={m}>{m}</option>)}</select></label></div></section>
 <section className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-xl shadow-slate-200/40"><div className="flex items-center justify-between border-b border-slate-100 p-6"><h3 className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-400"><History size={17} className="text-[#2D8DB8]"/>Histórico Cronológico de Ocorrências</h3><button type="button" onClick={()=>void load()} disabled={busy} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-[#123B50]"><RefreshCw size={15}/>Atualizar</button></div><div className="overflow-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[#123B50] text-white"><tr><th className="p-4 text-left">Data / Hora</th><th className="p-4 text-left">Usuário</th><th className="p-4 text-left">Módulo</th><th className="p-4 text-left">Ação Registrada</th><th className="p-4 text-left">Registro</th></tr></thead><tbody>{busy?<tr><td colSpan={5} className="p-8 text-center text-slate-400">Consultando trilha de auditoria...</td></tr>:filtered.length?filtered.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="whitespace-nowrap p-4 font-mono text-xs">{r.created_at?new Date(r.created_at).toLocaleString('pt-BR'):'—'}</td><td className="p-4 font-bold">{userMap.get(r.usuario_id||'')?.nome||r.usuario_id||'—'}</td><td className="p-4 font-semibold text-[#123B50]">{r.tabela||'—'}</td><td className="p-4">{r.acao||'—'}</td><td className="p-4 text-xs text-slate-500">{r.registro_id||'—'}</td></tr>):<tr><td colSpan={5} className="p-10 text-center font-bold text-slate-400">Nenhum evento registrado no sistema</td></tr>}</tbody></table></div></section>
 <section className="rounded-3xl border border-cyan-100 bg-white p-6 shadow-xl shadow-slate-200/30"><div className="flex items-center gap-2 font-black text-[#123B50]"><ShieldCheck size={18} className="text-[#2D8DB8]"/>Manual do Usuário: Rastreabilidade Inviolável</div><p className="mt-2 text-sm text-slate-600">A tela consulta somente eventos efetivamente persistidos no banco e aplica os filtros em tempo real.</p></section></div>
}