import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
type Product={id:string;codigo:string;nome:string;grupo:string|null;subgrupo:string|null;unidade:string;peso_liquido:number;peso_bruto:number;estoque_atual:number;foto_url:string|null;observacoes:string|null;preco:number}
type Payload={cliente:{nome:string;email:string|null;tabela:string;codigo_tabela:string};produtos:Product[];gerado_em:string}
export default function CatalogoDigitalPublico(){
 const [data,setData]=useState<Payload|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true)
 useEffect(()=>{void(async()=>{try{const token=new URLSearchParams(window.location.search).get('token');if(!token)throw new Error('Link de catálogo inválido.');const r=await supabase.rpc('erp_catalogo_publico',{p_token:token});if(r.error)throw r.error;setData(r.data as Payload)}catch(e){setError(e instanceof Error?e.message:'Catálogo indisponível.')}finally{setLoading(false)}})()},[])
 if(loading)return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#F4FBFD',fontFamily:'Inter,Roboto,Arial'}}>Carregando catálogo…</main>
 if(error||!data)return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#F4FBFD',fontFamily:'Inter,Roboto,Arial'}}><section style={{background:'#fff',padding:28,border:'1px solid #D6E5EA',borderRadius:8,color:'#A32D25'}}>{error||'Catálogo indisponível.'}</section></main>
 const products=data.produtos.filter(p=>!query||`${p.codigo} ${p.nome} ${p.grupo??''} ${p.subgrupo??''}`.toLowerCase().includes(query.toLowerCase()))
 return <main style={{minHeight:'100vh',background:'#F4FBFD',color:'#123B50',fontFamily:'Inter,Roboto,Arial',padding:'18px 4vw'}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:20,borderBottom:'1px solid #D6E5EA',paddingBottom:14,marginBottom:14}}><div><div style={{fontSize:11,fontWeight:900,color:'#2D8DB8',letterSpacing:'.08em'}}>CATÁLOGO DIGITAL INDUSTRIAL</div><h1 style={{margin:'3px 0',fontSize:25}}>Mostruário para {data.cliente.nome}</h1><div style={{fontSize:12,color:'#607983'}}>Tabela comercial: <b>{data.cliente.codigo_tabela} • {data.cliente.tabela}</b></div></div><div style={{minWidth:240}}><label style={{display:'grid',gap:4,fontSize:11,fontWeight:800}}>Pesquisar produto<input style={{height:36,border:'1px solid #BFD0D7',borderRadius:5,padding:'0 10px'}} value={query} onChange={e=>setQuery(e.target.value)} placeholder='Código, descrição ou categoria'/></label></div></header>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))',gap:11}}>
   {products.map(p=><article key={p.id} style={{background:'#fff',border:'1px solid #D6E5EA',borderRadius:7,overflow:'hidden'}}><div style={{height:165,background:'#EDF5F7',display:'grid',placeItems:'center'}}>{p.foto_url?<img src={p.foto_url} alt={p.nome} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<span style={{fontSize:11,fontWeight:800,color:'#78919B'}}>IMAGEM NÃO CADASTRADA</span>}</div><div style={{padding:12}}><div style={{fontSize:11,fontWeight:900,color:'#2D8DB8'}}>{p.codigo}</div><h2 style={{fontSize:15,margin:'4px 0 8px'}}>{p.nome}</h2><div style={{fontSize:11,color:'#607983',display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}><span>Grupo<br/><b>{p.grupo||'—'}</b></span><span>Categoria<br/><b>{p.subgrupo||'—'}</b></span><span>Peso<br/><b>{Number(p.peso_liquido||0).toLocaleString('pt-BR')} kg</b></span><span>Estoque<br/><b>{Number(p.estoque_atual||0).toLocaleString('pt-BR')} {p.unidade}</b></span></div><p style={{fontSize:11,color:'#607983',minHeight:30}}>{p.observacoes||'Aplicação industrial não cadastrada.'}</p><div style={{borderTop:'1px solid #E5EEF1',paddingTop:8,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:10,color:'#607983'}}>Preço comercial</span><strong style={{fontSize:17,color:'#2D8DB8'}}>R$ {Number(p.preco||0).toLocaleString('pt-BR',{minimumFractionDigits:2})}</strong></div></div></article>)}
  </section>
  {!products.length&&<div style={{padding:30,textAlign:'center',background:'#fff',border:'1px solid #D6E5EA'}}>Nenhum produto disponível neste catálogo.</div>}
  <footer style={{padding:'18px 0',fontSize:10,color:'#6A818B'}}>Catálogo gerado pelo SGQ ERP Industrial • Consulta pública controlada por token.</footer>
 </main>
}
