import { BookOpen, CheckCircle2, FileText, HelpCircle, ShieldCheck, Truck } from 'lucide-react'
import VendasLayout from './VendasLayout'

const sections=[
 {title:'Fluxo completo de compras',icon:FileText,items:['Necessidade PCP/MRP ou solicitação manual','Requisição e seleção dos materiais','Cotação RFQ com fornecedores','Comparação das propostas e escolha comercial','Pedido de compra e aprovação','Validação fiscal','Liberação para compra','Recebimento da NF-e e conferência','Lote, rastreabilidade e entrada no estoque','Reflexo financeiro em contas a pagar']},
 {title:'Campos que devem ser conferidos',icon:CheckCircle2,items:['Fornecedor, comprador, centro de custo e local de entrega','Referência da cotação e especificação técnica','Condição e prazo de pagamento','Prazo de entrega e itens com quantidade, unidade e preço','Frete, desconto, transportadora e modalidade de frete','Contrato, observações de recebimento e parecer fiscal','NF-e, chave de acesso, fornecedor, itens, valores e lotes']},
 {title:'Permissões e responsabilidades',icon:ShieldCheck,items:['Compras cria e edita solicitações e pedidos conforme permissão','Gestor/Compras aprova comercialmente o pedido','Fiscal valida a parte fiscal e tributária','Estoque recebe, confere, rastreia lotes e movimenta saldo','Financeiro recebe os reflexos de títulos a pagar após as etapas válidas']},
 {title:'Fornecedores',icon:Truck,items:['Código, razão social, nome fantasia e CNPJ','E-mail, telefone, contato, endereço, cidade e UF','Qualificação ISO 9001, número, validade e certificado','Observações e situação ativa/inativa']},
]
export default function ComprasAjuda(){
 return <VendasLayout title="Ajuda de Compras" subtitle="Manual operacional • campos • responsabilidades • fluxo"><main className="buy-help"><style>{`.buy-help{min-height:100vh;background:#f8fafc;padding:20px}.buy-help-wrap{max-width:1200px;margin:0 auto}.buy-help-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.buy-help-card{background:#fff;border:1px solid #dbe3ea;border-radius:9px;padding:18px}.buy-help-card h2{font-size:16px;margin:0 0 10px;display:flex;gap:8px;align-items:center}.buy-help-card ul{margin:0;padding-left:20px;color:#475569;line-height:1.8;font-size:12px}.buy-help-head{margin-bottom:14px}.buy-help-head h1{margin:4px 0;font-size:28px}.buy-help-head p{margin:0;color:#64748b}@media(max-width:800px){.buy-help-grid{grid-template-columns:1fr}}@media print{.buy-help{background:#fff;padding:0}}`}</style><div className="buy-help-wrap"><header className="buy-help-head"><span style={{fontSize:9,fontWeight:900,color:'#2563eb',letterSpacing:'.12em'}}>COMPRAS • AJUDA</span><h1>Manual operacional de Compras</h1><p>Guia rápido para conferir o processo ponta a ponta sem perder informação.</p></header><div className="buy-help-grid">{sections.map(section=>{const Icon=section.icon;return <section className="buy-help-card" key={section.title}><h2><Icon size={18}/>{section.title}</h2><ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul></section>})}</div><section className="buy-help-card" style={{marginTop:12}}><h2><HelpCircle size={18}/> Regra principal</h2><p style={{color:'#475569',fontSize:12,lineHeight:1.7}}>Não avance uma compra ignorando uma etapa obrigatória: a aprovação comercial e a validação fiscal são responsabilidades diferentes. O recebimento somente deve gerar estoque quando a NF-e e os lotes estiverem conferidos.</p></section></div></main></VendasLayout>
}
