import { useEffect, useState } from 'react'
import { ShoppingCart, Printer } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import EntityCodeLookup, { type LookupRecord } from '../components/industrial/EntityCodeLookup'
type Req={id:string;ordem_producao_id:string|null;status:string};type Item={id:string;requisicao_id:string;produto_id:string;quantidade:number;fornecedor_id:string|null;status:string}
export default function ComprasRequisicoes(){const[req,setReq]=useState<Req[]>([]),[items,setItems]=useState<Item[]>([]),[products,setProducts]=useState<LookupRecord[]>([]),[suppliers,setSuppliers]=useState<LookupRecord[]>([]),[ops,setOps]=useState<LookupRecord[]>([]),[op,setOp]=useState(''),[msg,setMsg]=useState('')
useEffect(()=>{void(async()=>{const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)return;const[r,i,p,f,o]=await Promise.all([supabase.from('erp_requisicoes_compra').select('id,ordem_producao_id,status').eq('empresa_id',c.data).order('created_at',{ascending:false}),supabase.from('erp_requisicoes_compra_itens').select('id,requisicao_id,produto_id,quantidade,fornecedor_id,status').eq('empresa_id',c.data).order('created_at'),supabase.from('erp_produtos').select('id,codigo,nome,descricao,estoque_atual').eq('empresa_id',c.data).eq('ativo',true).order('codigo'),supabase.from('erp_fornecedores').select('id,codigo,razao_social,nome_fantasia').eq('empresa_id',c.data).eq('ativo',true).order('codigo'),supabase.from('erp_ordens_producao').select('id,numero_op,numero').eq('empresa_id',c.data).order('created_at',{ascending:false})]);setReq((r.data??[]) as Req[]);setItems((i.data??[]) as Item[]);setProducts((p.data??[]) as LookupRecord[]);setSuppliers((f.data??[]) as LookupRecord[]);setOps((o.data??[]).map(x=>({id:x.id,codigo:x.numero_op||x.numero,nome:'OP'})) as LookupRecord[])})()},[])
const visible=op?items.filter(i=>req.find(r=>r.id===i.requisicao_id)?.ordem_producao_id===op):items
async function efetivar(){const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)return;const r=await supabase.from('erp_requisicoes_compra').update({status:'PEDIDO_ENVIADO',updated_at:new Date().toISOString()}).eq('empresa_id',c.data).eq('status','AGUARDANDO_COTACAO');setMsg(r.error?r.error.message:'Requisições efetivadas para compra.')}
return <main className="min-h-screen bg-slate-100 p-5 text-slate-900"><header className="mx-auto flex max-w-[1800px] items-center justify-between border-b border-slate-200 pb-4"><div><p className="text-sm font-bold text-sky-700">COMPRAS &gt; REQUISIÇÕES MRP</p><h1 className="text-xl font-bold text-slate-950">Gestão de Compras e Suprimentos Industriais</h1></div><div className="flex gap-2"><button onClick={()=>void efetivar()} className="rounded-md bg-slate-900 px-5 py-3 font-bold text-white"><ShoppingCart className="mr-2 inline"/>EFETIVAR PEDIDO</button><button onClick={()=>window.print()} className="rounded-md bg-slate-700 px-5 py-3 font-bold text-white"><Printer className="mr-2 inline"/>RELATÓRIO</button></div></header><section className="mx-auto mt-5 max-w-[1800px] rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="max-w-xl"><EntityCodeLookup label="FILTRAR PENDÊNCIAS POR OP" value={op} records={ops} onChange={setOp} onSelect={r=>setOp(r.id)}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1000px] text-base"><thead className="bg-slate-900 text-white"><tr><th className="h-14 px-4 text-left">INSUMO</th><th className="px-4 text-left">QTD FALTANTE</th><th className="px-4 text-left">FORNECEDOR HOMOLOGADO</th><th className="px-4 text-left">STATUS</th></tr></thead><tbody>{visible.map(i=>{const p=products.find(x=>x.id===i.produto_id);const f=suppliers.find(x=>x.id===i.fornecedor_id);return <tr key={i.id} className="h-14 border-b border-slate-200 even:bg-slate-50"><td className="px-4 font-bold">{p?.codigo} - {p?.nome}</td><td className="px-4">{i.quantidade}</td><td className="px-4">{f?.nome||f?.codigo||'Não definido'}</td><td className="px-4"><span className={'rounded-full px-3 py-1 text-sm font-bold '+(i.status==='PEDIDO_ENVIADO'?'bg-blue-100 text-blue-900':'bg-orange-100 text-orange-900')}>{i.status}</span></td></tr>})}</tbody></table></div>{!visible.length&&<p className="p-8 text-center font-bold text-slate-600">Nenhuma requisição de compra pendente.</p>}{msg&&<p className="mt-4 rounded-md bg-emerald-50 p-4 font-bold text-emerald-800">{msg}</p>}</section></main>}
