import { useEffect, useMemo, useState } from 'react'
import { Building2, Check, KeyRound, Mail, Plus, RefreshCw, Save, Search, ShieldCheck, UserPlus, Users, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Profile={empresa_id:string|null;is_master:boolean;nivel_admin?:number;perfil?:string;nome?:string}
type User={id:string;nome:string;email:string|null;ativo:boolean;setor_id:string|null;matricula:string|null;role:string|null;nivel_admin:number}
type Sector={id:string;codigo:string;nome:string;ativo:boolean}
type Form={nome:string;email:string;setor_id:string;matricula:string;perfil:string;password:string}
type Permission=Record<string,boolean>

const modules=['Dashboard','Clientes','Fornecedores','Produtos','Engenharia','Máquinas','Moldes e Ferramentas','Processos','PCP','MRP','Ordens de Produção','Apontamentos','Setup','Refugo','OEE','Matéria-prima','Estoque','Almoxarifado','Compras','Qualidade','RPNC','Rastreabilidade','Manutenção','Custos','Expedição','Vendas','Financeiro','Fiscal','RH','Relatórios','Documentos','Auditorias','Configurações']
const standardSectors=[['DIRETORIA','Diretoria / Administração'],['PRODUCAO','Produção'],['PCP','PCP - Planejamento e Controle da Produção'],['QUALIDADE','Qualidade'],['ENGENHARIA','Engenharia'],['MANUTENCAO','Manutenção'],['ALMOX','Almoxarifado'],['ESTOQUE','Estoque / Logística'],['COMPRAS','Compras / Suprimentos'],['VENDAS','Comercial / Vendas'],['FINANCEIRO','Financeiro'],['FISCAL','Fiscal / Contábil'],['RH','Recursos Humanos'],['TI','Tecnologia da Informação'],['EXPEDICAO','Expedição / Logística'],['SEGURANCA','Segurança / SST'],['P&D','Pesquisa e Desenvolvimento'],['ADMIN','Administrativo'],['METROLOGIA','Metrologia'],['FERRAMENTARIA','Ferramentaria']]
const emptyForm:Form={nome:'',email:'',setor_id:'',matricula:'',perfil:'OPERATOR',password:''}
const isAdmin=(p:Profile)=>p.is_master===true || Number(p.nivel_admin||0)>=8 || ['ADMIN','ADMINISTRADOR','SUPER_ADMIN'].includes(String(p.perfil||'').toUpperCase())

export default function ConfiguracoesADM({profile}:{profile:Profile}){
 const [users,setUsers]=useState<User[]>([]),[sectors,setSectors]=useState<Sector[]>([]),[permissions,setPermissions]=useState<Permission>({}),[form,setForm]=useState<Form>(emptyForm)
 const [sectorName,setSectorName]=useState(''),[sectorCode,setSectorCode]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<User|null>(null)
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[showNew,setShowNew]=useState(false),[security,setSecurity]=useState({current:'',next:'',confirm:''}),[securityBusy,setSecurityBusy]=useState(false)

 const load=async()=>{if(!profile.empresa_id){setUsers([]);setSectors([]);return}setBusy(true);setError('');try{const[u,s]=await Promise.all([supabase.from('erp_usuarios').select('id,nome,email,ativo,setor_id,matricula,role,nivel_admin').eq('empresa_id',profile.empresa_id).is('deleted_at',null).order('nome'),supabase.from('erp_setores').select('id,codigo,nome,ativo').eq('empresa_id',profile.empresa_id).eq('ativo',true).order('nome')]);if(u.error)throw u.error;if(s.error)throw s.error;setUsers((u.data||[]) as User[]);setSectors((s.data||[]) as Sector[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar usuários e setores.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[profile.empresa_id])
 const visibleUsers=useMemo(()=>users.filter(u=>JSON.stringify(u).toLowerCase().includes(query.toLowerCase())),[users,query])
 const toggle=(uid:string,module:string)=>{const k=uid+'|'+module;setPermissions(p=>({...p,[k]:!(p[k]??false)}))}
 const savePermissions=async(uid:string)=>{if(!profile.empresa_id)return;setBusy(true);setError('');try{for(const modulo of modules){const permitido=permissions[uid+'|'+modulo]??false;const{error}=await supabase.from('erp_tablet_acl').upsert({empresa_id:profile.empresa_id,usuario_id:uid,modulo,permitido,updated_at:new Date().toISOString()},{onConflict:'empresa_id,usuario_id,modulo'});if(error)throw error}setMessage('Permissões salvas para o funcionário.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar as permissões.')}finally{setBusy(false)}}
 const loadUserPermissions=async(u:User)=>{setSelected(u);setError('');const{data,error}=await supabase.from('erp_tablet_acl').select('modulo,permitido').eq('empresa_id',profile.empresa_id).eq('usuario_id',u.id);if(error){setError(error.message);return}const next:Permission={};for(const row of data||[])next[u.id+'|'+row.modulo]=Boolean(row.permitido);setPermissions(next)}
 const createSector=async()=>{if(!profile.empresa_id||!sectorName.trim())return;setBusy(true);setError('');try{const codigo=(sectorCode.trim()||sectorName.trim().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^A-Za-z0-9]+/g,'_').toUpperCase()).slice(0,30);const{error}=await supabase.from('erp_setores').insert({empresa_id:profile.empresa_id,codigo,nome:sectorName.trim(),ativo:true});if(error)throw error;setSectorName('');setSectorCode('');setMessage('Setor cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível cadastrar o setor.')}finally{setBusy(false)}}
 const seedSectors=async()=>{if(!profile.empresa_id)return;setBusy(true);setError('');try{const{data:existing,error:e}=await supabase.from('erp_setores').select('codigo').eq('empresa_id',profile.empresa_id);if(e)throw e;const have=new Set((existing||[]).map(x=>String(x.codigo).toUpperCase()));const rows=standardSectors.filter(x=>!have.has(x[0])).map(x=>({empresa_id:profile.empresa_id,codigo:x[0],nome:x[1],ativo:true}));if(rows.length){const{error}=await supabase.from('erp_setores').insert(rows);if(error)throw error}setMessage(rows.length?String(rows.length)+' setores padrão cadastrados.':'Os setores padrão já estão cadastrados.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar os setores padrão.')}finally{setBusy(false)}}
 const changeMyPassword=async()=>{if(security.next!==security.confirm){setError('A confirmação da nova senha não confere.');return}if(security.next.length<6){setError('A nova senha deve ter pelo menos 6 caracteres.');return}setSecurityBusy(true);setError('');setMessage('');try{const{data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'change_my_password',currentPassword:security.current,newPassword:security.next}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Não foi possível alterar a senha.');setSecurity({current:'',next:'',confirm:''});setMessage('Sua senha foi alterada com sucesso.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar a senha.')}finally{setSecurityBusy(false)}}
 const resetPassword=async(u:User)=>{if(!u.email)return setError('Este usuário não possui e-mail cadastrado.');if(!window.confirm('Enviar um link seguro de redefinição para '+u.email+'? A senha atual nunca será exibida.'))return;setBusy(true);setError('');setMessage('');try{const{data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'reset_password',user_id:u.id}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Não foi possível solicitar a redefinição.');setMessage(data.message||'Link de redefinição enviado.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível redefinir a senha.')}finally{setBusy(false)}}
 const createUser=async()=>{if(!form.nome.trim()||!form.email.trim()||!form.setor_id){setError('Preencha nome, e-mail e setor.');return}if(form.password&&form.password.length<6){setError('A senha deve ter pelo menos 6 caracteres.');return}setBusy(true);setError('');setMessage('');try{const{data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'create_user',nome:form.nome.trim(),email:form.email.trim().toLowerCase(),setor_id:form.setor_id,matricula:form.matricula.trim()||undefined,nivel_admin:1,password:form.password||undefined}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Não foi possível criar o usuário.');setMessage(data.temporary_password?'Funcionário criado. Senha inicial: '+data.temporary_password:'Funcionário criado com a senha informada.');setShowNew(false);setForm(emptyForm);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o funcionário.')}finally{setBusy(false)}}

 if(!profile.empresa_id&&!profile.is_master)return <main className="erp-page-v3"><section className="erp-card-v3"><h1>Acesso administrativo da empresa</h1><p>Esta tela é para o administrador da empresa. O Master Universal não cadastra funcionários de uma empresa por aqui.</p></section></main>
 if(!isAdmin(profile))return <main className="erp-page-v3"><section className="erp-card-v3"><ShieldCheck size={30}/><h1>Acesso restrito</h1><p>Somente o Administrador da empresa ou o Master Universal pode administrar usuários e permissões.</p></section></main>

 return <main className="erp-page-v3" style={{paddingBottom:60}}>
  <header className="erp-page-header-v3"><div><span className="erp-eyebrow">ADMINISTRAÇÃO DA EMPRESA</span><h1>Usuários, Departamentos e Permissões</h1><p>O administrador cadastra o funcionário, define o setor, cria a senha e escolhe exatamente quais módulos ele poderá usar.</p></div><ShieldCheck size={38}/></header>
  {(message||error)&&<div className={error?'erp-alert-error':'erp-alert-ok'}>{error||message}</div>}
  <section className="erp-card-v3" style={{marginBottom:16}}>
   <div><span className="erp-eyebrow">MINHA CONTA • SEGURANÇA</span><h2><KeyRound size={23}/> Alterar minha senha</h2><p>Você pode trocar sua própria senha sem pedir acesso à senha de ninguém.</p></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12,marginTop:14}}>
    <label>Senha atual<input type="password" value={security.current} onChange={e=>setSecurity({...security,current:e.target.value})} autoComplete="current-password"/></label>
    <label>Nova senha<input type="password" value={security.next} onChange={e=>setSecurity({...security,next:e.target.value})} autoComplete="new-password"/></label>
    <label>Confirmar nova senha<input type="password" value={security.confirm} onChange={e=>setSecurity({...security,confirm:e.target.value})} autoComplete="new-password"/></label>
   </div>
   <div style={{display:'flex',justifyContent:'flex-end',marginTop:12}}><button className="erp-btn-primary" onClick={()=>void changeMyPassword()} disabled={securityBusy}><KeyRound size={16}/>{securityBusy?'Alterando…':'Alterar minha senha'}</button></div>
  </section>
  <section className="erp-card-v3" style={{marginBottom:16}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2><Users size={23}/> Funcionários / usuários</h2><p>Conta individual por funcionário. Nunca compartilhe uma senha.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="erp-btn-secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Atualizar</button><button className="erp-btn-primary" onClick={()=>setShowNew(true)} disabled={busy}><UserPlus size={16}/> Novo funcionário</button></div></div>
   <div style={{marginTop:14,display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><div style={{position:'relative',flex:'1 1 300px'}}><Search size={16} style={{position:'absolute',left:11,top:12}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar funcionário, e-mail ou matrícula" style={{paddingLeft:36}}/></div><strong>{visibleUsers.length} funcionário(s)</strong></div>
   <div className="erp-table-scroll" style={{marginTop:12}}><table className="erp-table-v3"><thead><tr><th>Funcionário</th><th>E-mail</th><th>Setor</th><th>Perfil</th><th>Status</th><th>Permissões</th></tr></thead><tbody>{visibleUsers.map(u=><tr key={u.id}><td><b>{u.nome}</b><small>{u.matricula||'Sem matrícula'}</small></td><td>{u.email||'—'}</td><td>{sectors.find(s=>s.id===u.setor_id)?.nome||'Sem setor'}</td><td>{u.role||'OPERADOR'}</td><td>{u.ativo?'Ativo':'Inativo'}</td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="erp-btn-secondary" onClick={()=>void loadUserPermissions(u)}><ShieldCheck size={15}/> Acessos</button>{u.id!==profile.empresa_id&&<button className="erp-btn-secondary" onClick={()=>void resetPassword(u)} disabled={busy}><KeyRound size={15}/> Redefinir senha</button></div></td></tr>)}</tbody></table></div>
  </section>
  <section className="erp-card-v3" style={{marginBottom:16}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2><Building2 size={23}/> Departamentos / setores da empresa</h2><p>Base industrial comum, totalmente ajustável pelo cliente.</p></div><button className="erp-btn-secondary" onClick={()=>void seedSectors()} disabled={busy}><Plus size={16}/> Criar setores padrão</button></div>
   <div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:10,marginTop:14}}><input value={sectorCode} onChange={e=>setSectorCode(e.target.value)} placeholder="Código do setor (opcional)"/><input value={sectorName} onChange={e=>setSectorName(e.target.value)} placeholder="Nome do setor"/><button className="erp-btn-primary" onClick={()=>void createSector()} disabled={busy}><Save size={16}/> Salvar setor</button></div>
   <div style={{display:'flex',flexWrap:'wrap',gap:8,marginTop:14}}>{sectors.map(s=><span key={s.id} style={{padding:'8px 11px',border:'1px solid #cfe0e5',borderRadius:999,background:'#f6fafb'}}><b>{s.codigo}</b> · {s.nome}</span>)}</div>
  </section>
  {selected&&<section className="erp-card-v3" style={{marginBottom:16}}>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h2><ShieldCheck size={23}/> Acessos de {selected.nome}</h2><p>Clique nos módulos que este funcionário poderá abrir. O padrão é bloqueado até liberar.</p></div><button onClick={()=>setSelected(null)}><X/></button></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(190px,1fr))',gap:9,marginTop:15}}>{modules.map(m=>{const k=selected.id+'|'+m;return <button key={m} type="button" onClick={()=>toggle(selected.id,m)} style={{textAlign:'left',padding:'12px',borderRadius:10,border:'1px solid #cbdde3',background:(permissions[k]??false)?'#e9f7f1':'#fff',color:'#17333f',cursor:'pointer'}}><span style={{display:'flex',gap:8,alignItems:'center'}}><span style={{width:22,height:22,borderRadius:6,border:'1px solid #9db7bf',display:'grid',placeItems:'center'}}>{(permissions[k]??false)&&<Check size={15}/>}</span><b>{m}</b></span></button>})}</div>
   <div style={{display:'flex',justifyContent:'flex-end',marginTop:15}}><button className="erp-btn-primary" onClick={()=>void savePermissions(selected.id)} disabled={busy}><Save size={17}/> Salvar permissões</button></div>
  </section>}
  {showNew&&<div style={{position:'fixed',inset:0,zIndex:10000,background:'rgba(8,32,40,.58)',display:'grid',placeItems:'center',padding:20}}><section className="erp-card-v3" style={{width:'min(760px,100%)',maxHeight:'92vh',overflow:'auto'}}>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><span className="erp-eyebrow">NOVO ACESSO</span><h2>Cadastro do funcionário</h2><p>O cadastro pertence à empresa logada, não ao Master Universal.</p></div><button onClick={()=>setShowNew(false)}><X/></button></div>
   <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginTop:15}}><label>Nome completo<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} placeholder="Ex.: João da Silva"/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="joao@empresa.com"/></label><label>Matrícula<input value={form.matricula} onChange={e=>setForm({...form,matricula:e.target.value})} placeholder="Matrícula"/></label><label>Setor / departamento<select value={form.setor_id} onChange={e=>setForm({...form,setor_id:e.target.value})}><option value="">Selecione o setor</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><label>Perfil operacional<select value={form.perfil} onChange={e=>setForm({...form,perfil:e.target.value})}><option value="OPERATOR">Operador</option><option value="SUPERVISOR">Supervisor</option><option value="ANALYST">Analista</option></select></label><label>Senha inicial<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo 6 caracteres"/></label></div>
   <div style={{marginTop:14,padding:13,border:'1px solid #d7e7ea',borderRadius:10,background:'#f6fafb',fontSize:13}}><Mail size={16} style={{verticalAlign:'middle',marginRight:5}}/> O administrador pode criar uma senha e entregar ao funcionário. Se deixar em branco, o sistema gera uma senha temporária.</div>
   <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button className="erp-btn-secondary" onClick={()=>setShowNew(false)}>Cancelar</button><button className="erp-btn-primary" onClick={()=>void createUser()} disabled={busy}><KeyRound size={16}/>{busy?'Criando…':'Criar acesso'}</button></div>
  </section></div>}
 </main>
}
