import {useEffect,useState} from 'react'
import {ShieldCheck,Save,Settings2,Languages} from 'lucide-react'
import {supabase} from '../lib/supabaseClient'
const modules=['PCP','Qualidade','Almoxarifado','Fiscal','Vendas','Compras','Moldes & Ferramentaria','Relatórios','Configurações']
export default function ConfiguracoesADM({profile}:{profile:{empresa_id:string|null;is_master:boolean;nivel_admin?:number;perfil?:string}}){const[users,setUsers]=useState<any[]>([]),[acl,setAcl]=useState<Record<string,boolean>>({}),[prefix,setPrefix]=useState<Record<string,string>>({OP:'OP-',LOTE:'LOTE-',RPNC:'RPNC-',PV:'PV-',NF:'NF-'}),[lang,setLang]=useState(localStorage.getItem('erp-lang')||'pt-BR'),[msg,setMsg]=useState('')
useEffect(()=>{void (async()=>{if(!profile.empresa_id&&!profile.is_master)return;let q=supabase.from('erp_usuarios').select('id,nome,email,empresa_id,ativo').eq('ativo',true);if(profile.empresa_id)q=q.eq('empresa_id',profile.empresa_id);const r=await q;setUsers(r.data||[])})()},[profile])
async function saveAcl(userId:string){if(!profile.empresa_id)return;for(const m of modules)await supabase.from('erp_tablet_acl').upsert({empresa_id:profile.empresa_id,usuario_id:userId,modulo:m,permitido:Boolean(acl[userId+'|'+m]??true),updated_at:new Date().toISOString()},{onConflict:'empresa_id,usuario_id,modulo'});setMsg('Permissões salvas.')}
async function savePrefixes(){if(!profile.empresa_id)return;for(const [tipo,prefixo] of Object.entries(prefix))await supabase.from('erp_prefixos_documentos').upsert({empresa_id:profile.empresa_id,tipo,prefixo,updated_at:new Date().toISOString()},{onConflict:'empresa_id,tipo'});setMsg('Prefixos salvos.')}
if(profile.is_master!==true || profile.empresa_id!==null) return <main className="erp-page-v3"><section className="erp-card-v3"><h1>Acesso administrativo restrito</h1><p>Esta área exige nível administrativo 8 ou superior.</p></section></main>;
return <main className="erp-page-v3"><header className="erp-page-header-v3"><div><span className="erp-eyebrow">ADMINISTRAÇÃO</span><h1>Configurações Administrativas</h1><p>ACL do Tablet, prefixos e idioma do ERP.</p></div><Settings2 size={36}/></header>{msg&&<div className="erp-alert-ok">{msg}</div>}<section className="erp-card-v3"><h2><ShieldCheck size={24}/> Controle de Permissões (ACL)</h2><p>Defina quais ambientes cada colaborador pode acessar.</p><div className="erp-table-scroll"><table className="erp-table-v3"><thead><tr><th>Colaborador</th>{modules.map(m=><th key={m}>{m}</th>)}<th>Salvar</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.nome}</b><small>{u.email}</small></td>{modules.map(m=><td key={m}><input type="checkbox" checked={acl[u.id+'|'+m]??true} onChange={e=>setAcl({...acl,[u.id+'|'+m]:e.target.checked})}/></td>)}<td><button className="erp-btn-primary" onClick={()=>void saveAcl(u.id)}><Save size={16}/></button></td></tr>)}</tbody></table></div></section><section className="erp-card-v3"><h2>Higiene de homologação Plastibor</h2><p>Operação destrutiva restrita ao Master Universal. Remove somente os pedidos marcados como teste 1001–1050 e inventários de homologação, preservando dados produtivos.</p><button className="erp-btn-secondary" onClick={async()=>{if(!window.confirm('Zerar Banco Plastibor? Somente os dados marcados de homologação serão removidos.'))return;const{data,error}=await supabase.rpc('erp_master_purge_plastibor_test_data');if(error){setMsg(error.message);return}setMsg('Purge executado: '+JSON.stringify(data))}}>Zerar Banco Plastibor</button></section><section className="erp-card-v3"><h2>Prefixos automáticos</h2><div className="grid md:grid-cols-5 gap-4">{Object.entries(prefix).map(([k,v])=><label key={k}>{k}<input value={v} onChange={e=>setPrefix({...prefix,[k]:e.target.value})}/></label>)}</div><button className="erp-btn-primary mt-5" onClick={()=>void savePrefixes()}><Save size={18}/> Salvar padrões</button></section><section className="erp-card-v3"><h2><Languages size={24}/> Idioma</h2><div className="flex gap-3"><button className={lang==='pt-BR'?'erp-btn-primary':'erp-btn-secondary'} onClick={()=>{setLang('pt-BR');localStorage.setItem('erp-lang','pt-BR');location.reload()}}>PT</button><button className={lang==='en-US'?'erp-btn-primary':'erp-btn-secondary'} onClick={()=>{setLang('en-US');localStorage.setItem('erp-lang','en-US');location.reload()}}>EN</button></div></section></main>}