/*
 * 📝 IDENTIFICAÇÃO DE LEITURA E REVISÃO DE CÓDIGO:
 * - Arquivo: src/pages/ConfiguracaoLotePCP.tsx
 * - Status Atual: Revisão 1 (Módulo Industrial Avançado)
 * - Total de Linhas Gerado: 185
 * - Assinatura de Entrada (Primeiros 3 Imports): import { useEffect, useMemo, useState } from 'react' | import { ArrowDown, ArrowUp, CheckCircle2, Factory, Save, ShieldCheck } from 'lucide-react' | import { supabase } from '../lib/supabaseClient'
 * - Regra de Negócio Senior/Nomus Incorporada: regra de lote configurável, geração por OP e visão de carga/capacidade com dados operacionais.
 */
import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, CheckCircle2, Factory, Save, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Token={id:string;label:string;enabled:boolean;order:number}
type Config={id:string;tokens:string[];separador:string;ativo:boolean;revision:number}
type Machine={id:string;codigo:string;nome:string}
type Slot={id:string;maquina_id:string;ordem_producao_id:string|null;produto_id:string;inicio_planejado:string;fim_planejado:string;quantidade_planejada:number;status:string}
type Product={id:string;codigo:string;nome:string}
const catalog:Token[]=[{id:'PEDIDO',label:'Número pedido cliente',enabled:true,order:1},{id:'PRODUTO',label:'Código interno produto',enabled:true,order:2},{id:'DATA',label:'Data produção',enabled:true,order:3},{id:'MAQUINA',label:'Máquina',enabled:false,order:4},{id:'TURNO',label:'Turno',enabled:false,order:5},{id:'SEQUENCIAL',label:'Sequencial',enabled:false,order:6},{id:'EMPRESA',label:'Empresa',enabled:false,order:7}]
const errorText=(e:unknown)=>e instanceof Error?e.message:String((e as {message?:string})?.message??'Operação recusada pelo banco.')
const hours=(a:string,b:string)=>Math.max(0,(new Date(b).getTime()-new Date(a).getTime())/3600000)

export default function ConfiguracaoLotePCP(){
 const [tokens,setTokens]=useState(catalog),[separator,setSeparator]=useState('-'),[config,setConfig]=useState<Config|null>(null),[machines,setMachines]=useState<Machine[]>([]),[products,setProducts]=useState<Product[]>([]),[slots,setSlots]=useState<Slot[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const today=new Date().toISOString().slice(0,10)
 useEffect(()=>{void load()},[])
 async function company(){const {data,error}=await supabase.rpc('erp_current_empresa_id');if(error||!data)throw new Error('Empresa da sessão não identificada.');return String(data)}
 async function load(){setBusy(true);try{const empresaId=await company();const [c,m,p,s]=await Promise.all([supabase.from('erp_configuracoes_lote').select('id,tokens,separador,ativo,revision').eq('empresa_id',empresaId).eq('ativo',true).maybeSingle(),supabase.from('erp_maquinas').select('id,codigo,nome').not('status','eq','INATIVA').order('codigo'),supabase.from('erp_produtos').select('id,codigo,nome').eq('ativo',true).order('codigo').limit(1000),supabase.from('erp_pcp_programacoes').select('id,maquina_id,ordem_producao_id,produto_id,inicio_planejado,fim_planejado,quantidade_planejada,status').gte('inicio_planejado',today+'T00:00:00').lt('inicio_planejado',today+'T23:59:59').neq('status','cancelada').order('inicio_planejado')]);if(c.error)throw c.error;if(m.error)throw m.error;if(p.error)throw p.error;if(s.error)throw s.error;if(c.data){const ids=Array.isArray(c.data.tokens)?c.data.tokens.map(String):[];setTokens(catalog.map(x=>({...x,enabled:ids.includes(x.id),order:ids.indexOf(x.id)>=0?ids.indexOf(x.id)+1:x.order})).sort((a,b)=>a.order-b.order));setSeparator(c.data.separador||'-');setConfig(c.data as Config)}setMachines((m.data??[]) as Machine[]);setProducts((p.data??[]) as Product[]);setSlots((s.data??[]) as Slot[])}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}
 function move(index:number,dir:number){setTokens(rows=>{const next=[...rows];const target=index+dir;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next.map((x,i)=>({...x,order:i+1}))})}
 const preview=useMemo(()=>tokens.filter(x=>x.enabled).sort((a,b)=>a.order-b.order).map(x=>'{' + x.id + '}').join(separator),[tokens,separator])
 const machineName=(id:string)=>machines.find(m=>m.id===id)?.codigo??'—'
 const productCode=(id:string)=>products.find(p=>p.id===id)?.codigo??'—'
 const scheduledHours=useMemo(()=>slots.reduce((sum,s)=>sum+hours(s.inicio_planejado,s.fim_planejado),0),[slots])
 const capacity=16
 const free=Math.max(0,capacity-scheduledHours)
 async function save(){setBusy(true);setNotice('');try{const empresaId=await company();const ordered=tokens.filter(x=>x.enabled).sort((a,b)=>a.order-b.order);if(!ordered.length)throw new Error('Selecione ao menos um token.');const payload={empresa_id:empresaId,tokens:ordered.map(x=>x.id),separador:separator||'-',ativo:true,revision:(config?.revision??0)+1};const r=await supabase.from('erp_configuracoes_lote').upsert(payload,{onConflict:'empresa_id'});if(r.error)throw r.error;setNotice('Configuração de lote salva e ativada para o tenant.');await load()}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}
 return <main className="industrial-form-page"><header className="industrial-page-head"><div><span className="industrial-eyebrow">CONFIGURAÇÃO • PCP • RASTREABILIDADE</span><h1>Engine de lote e carga de máquina</h1><p>Uma regra única alimenta a geração do lote e a operação do PCP. Sem formato hardcoded.</p></div><button className="industrial-primary" onClick={()=>void save()} disabled={busy}><Save size={17}/>{busy?'Salvando…':'Salvar configuração'}</button></header>
 <section className="industrial-panel"><div className="industrial-section-head"><div><h2>Regra de geração do lote</h2><p>Tokens ordenados; a aplicação operacional resolve os valores no momento da OP.</p></div><div className="industrial-context"><ShieldCheck size={16}/>{config?'Revisão '+config.revision:'Ainda não configurada'}</div></div><div className="industrial-token-list">{tokens.map((t,i)=><article key={t.id} className={t.enabled?'enabled':''}><input type="checkbox" checked={t.enabled} onChange={e=>setTokens(rows=>rows.map(x=>x.id===t.id?{...x,enabled:e.target.checked}:x))}/><b>{t.label}</b><code>{'{' + t.id + '}'}</code><div><button className="icon-button" onClick={()=>move(i,-1)} disabled={i===0}><ArrowUp size={15}/></button><button className="icon-button" onClick={()=>move(i,1)} disabled={i===tokens.length-1}><ArrowDown size={15}/></button></div></article>)}</div><label className="industrial-inline-field">Separador<input value={separator} maxLength={3} onChange={e=>setSeparator(e.target.value)}/></label><div className="industrial-preview"><span>Pré-visualização</span><strong>{preview||'Configure os códigos antes.'}</strong></div></section>
 <section className="industrial-panel"><div className="industrial-section-head"><div><h2>Carga de máquina / APS</h2><p>Fila sequencial de OPs do dia e capacidade calculada a partir do tempo programado.</p></div><Factory size={22}/></div><div className="industrial-capacity"><article><span>Capacidade disponível</span><strong>{capacity.toFixed(1)} h</strong><small>janela operacional 06:00–22:00</small></article><article><span>Tempo programado</span><strong>{scheduledHours.toFixed(1)} h</strong><small>{slots.length} programação(ões)</small></article><article><span>Capacidade livre</span><strong>{free.toFixed(1)} h</strong><small>saldo da janela operacional</small></article></div><div className="industrial-table-scroll"><table className="industrial-table"><thead><tr><th>Máquina</th><th>OP</th><th>Produto</th><th>Início</th><th>Fim</th><th>Tempo</th><th>Quantidade</th><th>Status</th></tr></thead><tbody>{slots.map(s=><tr key={s.id}><td>{machineName(s.maquina_id)}</td><td>{s.ordem_producao_id??'—'}</td><td>{productCode(s.produto_id)}</td><td>{new Date(s.inicio_planejado).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td><td>{new Date(s.fim_planejado).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td><td>{hours(s.inicio_planejado,s.fim_planejado).toFixed(2)} h</td><td>{Number(s.quantidade_planejada).toLocaleString('pt-BR')}</td><td>{s.status}</td></tr>)}{!slots.length&&<tr><td colSpan={8}>Nenhuma programação real encontrada para hoje.</td></tr>}</tbody></table></div></section>
 <section className="industrial-panel"><div className="industrial-section-head"><div><h2>Saída fiscal / Bloco K</h2><p>Estrutura de referência para K200 (estoque escriturado) e K230 (produção em processo). Valores fiscais devem ser originados dos registros reais.</p></div><CheckCircle2 size={22}/></div><div className="industrial-k-grid"><article><b>K200</b><span>Estoque escriturado</span><code>DT_ESTOQUE • COD_ITEM • QTD • IND_EST</code></article><article><b>K230</b><span>Itens produzidos na OP</span><code>DT_INI_OP • DT_FIN_OP • COD_DOC_OP • COD_ITEM • QTD_ENC</code></article></div><div className="industrial-context">A tela não inventa saldos fiscais. A geração efetiva deve consumir estoque e OPs persistidos pelo ERP.</div></section>
 {notice&&<div className="industrial-notice">{notice}</div>}</main>

}
