import { useState } from 'react'
import { CalendarDays, Factory, Filter, Search, Settings2 } from 'lucide-react'
import { Button, Field, FilterBar, Input, KPI, KpiStrip, PageHeader, SearchInput, Select, StatusBadge, Surface } from '../components/ui/erp-design-system'

type Direction='default'|'alt-blue'|'alt-teal'

export default function DesignSystemShowcase(){
  const [direction,setDirection]=useState<Direction>('default')
  const [search,setSearch]=useState('')
  return <div className="ds-page" data-erp-theme={direction}>
    <main style={{maxWidth:1440,margin:'0 auto',padding:'24px'}}>
      <PageHeader eyebrow="ERP Industrial • Design System 2026" title="Biblioteca visual operacional" description="Direção A é o padrão de produção. As direções B e C existem somente para homologação visual." actions={<div className="ds-page-header__actions"><Button variant={direction==='default'?'primary':'default'} onClick={()=>setDirection('default')}>A · Industrial</Button><Button variant={direction==='alt-blue'?'primary':'default'} onClick={()=>setDirection('alt-blue')}>B · Enterprise Blue</Button><Button variant={direction==='alt-teal'?'primary':'default'} onClick={()=>setDirection('alt-teal')}>C · Teal</Button></div>}/>
      <div className="ds-toolbar"><StatusBadge status="production" label="Produção"/><StatusBadge status="setup" label="Setup / troca de molde"/><StatusBadge status="idle" label="Sem programação"/><StatusBadge status="stop" label="Parada"/><StatusBadge status="maintenance" label="Manutenção"/><StatusBadge status="risk" label="Risco / atraso"/></div>
      <KpiStrip><KPI label="Ocupação fábrica" value="83,4%" meta="período selecionado" tone="success"/><KPI label="Horas planejadas" value="1.284 h" meta="vs. 1.540 h disponíveis"/><KPI label="Em produção" value="16" meta="máquinas"/><KPI label="Setup" value="4" meta="trocas hoje" tone="warning"/><KPI label="OPs em risco" value="3" meta="ação necessária" tone="danger"/></KpiStrip>
      <FilterBar onClear={()=>setSearch('')}><SearchInput value={search} onChange={setSearch}/><Field label="Período"><Select defaultValue="mes"><option value="mes">Setembro 2026</option><option value="semana">Semana atual</option><option value="dia">Hoje</option></Select></Field><Field label="Máquina"><Select defaultValue="todas"><option value="todas">Todas</option><option>Injetora 01</option><option>Injetora 02</option></Select></Field><Field label="Status"><Select defaultValue="todos"><option value="todos">Todos</option><option>Produção</option><option>Setup</option><option>Parada</option></Select></Field></FilterBar>
      <div style={{display:'grid',gridTemplateColumns:'1.4fr .8fr',gap:16,marginTop:16}}>
        <Surface><div className="ds-surface__head"><div><strong>Componentes de planejamento</strong><div className="ds-muted" style={{fontSize:12}}>Padrão para a grade mensal e visão diária</div></div><Button size="sm"><Settings2 size={14}/>Configurar</Button></div><div className="ds-surface__body"><div className="ds-planning-grid"><table><thead><tr><th>Máquina</th><th>15</th><th>16</th><th>17</th><th>18</th><th>19</th></tr></thead><tbody><tr><td><strong>INJ-01</strong><br/><span className="ds-muted">250 t</span></td><td><div className="ds-plan-cell"><div className="ds-plan-segment ds-plan-segment--production"><strong>OP-1025</strong></div></div></td><td><div className="ds-plan-cell"><div className="ds-plan-segment ds-plan-segment--setup"><strong>SETUP</strong></div></div></td><td><div className="ds-plan-cell"><div className="ds-plan-segment ds-plan-segment--production"><strong>OP-1031</strong></div></div></td><td><div className="ds-plan-cell"><div className="ds-plan-segment ds-plan-segment--risk"><strong>OP-1031</strong></div></div></td><td><div className="ds-plan-cell"><span className="ds-plan-more">Livre</span></div></td></tr></tbody></table></div></div></Surface>
        <Surface><div className="ds-surface__head"><strong>Princípios aplicados</strong></div><div className="ds-surface__body"><ul style={{margin:0,paddingLeft:18,lineHeight:1.9,fontSize:12}}><li>Fundo claro e navegação azul petróleo.</li><li>Dados densos, porém legíveis.</li><li>Cards somente onde agregam hierarquia.</li><li>Status sem cores saturadas.</li><li>Números alinhados com fonte monoespaçada.</li><li>Touch targets de 48 px no tablet.</li></ul></div></Surface>
      </div>
      <Surface style={{marginTop:16}}><div className="ds-surface__head"><strong>Estados e ações</strong></div><div className="ds-surface__body"><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Button variant="primary"><Factory size={15}/>Programar produção</Button><Button><CalendarDays size={15}/>Abrir dia</Button><Button><Filter size={15}/>Filtrar</Button><Button variant="success">Aprovar</Button><Button variant="danger">Bloquear</Button><Button variant="ghost"><Search size={15}/>Pesquisar</Button><Input placeholder="Campo padrão" style={{maxWidth:260}}/></div></div></Surface>
    </main>
  </div>
}
