import { FormEvent, useEffect, useState } from 'react'
import { CheckCircle2, FileCheck2, FilePlus2, History, LockKeyhole, RefreshCw, Send, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import './DocumentosQualidadeControle.css'

type Doc={id:string;codigo:string;titulo:string;departamento:string;tipo:string;revisao:number;status:string;proxima_revisao:string|null;motivo_alteracao:string|null}
type Revision={id:string;documento_id:string;revisao:number;status:string;titulo:string;conteudo:string|null;motivo_alteracao:string|null;criado_em:string;aprovado_em:string|null;liberado_em:string|null}
type User={id:string;empresa_id:string;setor_id:string|null;nivel_admin:number}
const statusLabel:Record<string,string>={rascunho:'Rascunho',solicitada_alteracao:'Alteração solicitada',em_revisao:'Em revisão',aprovada:'Aprovada',liberada:'Liberada',vigente:'Vigente',substituida:'Substituída',obsoleta:'Obsoleta'}

export default function DocumentosQualidadeControle(){
 const[docs,setDocs]=useState<Doc[]>([]),[revisions,setRevisions]=useState<Revision[]>([]),[user,setUser]=useState<User|null>(null),[selected,setSelected]=useState<Doc|null>(null)
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
 const[form,setForm]=useState({codigo:'',titulo:'',departamento:'',tipo:'Procedimento',conteudo:'',motivo:'Criação do documento'})
 async function load(){setLoading(true);setError('');const auth=(await supabase.auth.getUser()).data.user;if(!auth){setError('Sessão não encontrada.');setLoading(false);return}const{data:u,error:ue}=await supabase.from('erp_usuarios').select('id,empresa_id,setor_id,nivel_admin').eq('auth_user_id',auth.id).maybeSingle();if(ue||!u){setError(ue?.message||'Usuário ERP não encontrado.');setLoading(false);return}setUser(u);const{data:d,error:de}=await supabase.from('erp_documentos_qualidade').select('id,codigo,titulo,departamento,tipo,revisao,status,proxima_revisao,motivo_alteracao').order('codigo');if(de)setError(de.message);setDocs((d||[]) as Doc[]);setLoading(false)}
 async function loadRevisions(id:string){const{data,error}=await supabase.from('erp_documentos_qualidade_revisoes').select('id,documento_id,revisao,status,titulo,conteudo,motivo_alteracao,criado_em,aprovado_em,liberado_em').eq('documento_id',id).order('revisao',{ascending:false});if(error)setError(error.message);setRevisions((data||[]) as Revision[])}
 useEffect(()=>{void load()},[])
 function selectDoc(d:Doc){setSelected(d);setNotice('');void loadRevisions(d.id)}
 async function createDoc(e:FormEvent){e.preventDefault();if(!user)return;setSaving(true);setError('');setNotice('');const{data:d,error:de}=await supabase.from('erp_documentos_qualidade').insert({empresa_id:user.empresa_id,codigo:form.codigo.trim(),titulo:form.titulo.trim(),departamento:form.departamento.trim(),tipo:form.tipo,conteudo:form.conteudo.trim(),revisao:0,status:'rascunho',proprietario_id:user.id,preparado_por:user.id,motivo_alteracao:form.motivo.trim()}).select('id,codigo,titulo,departamento,tipo,revisao,status,proxima_revisao,motivo_alteracao').single();if(de){setError(de.message);setSaving(false);return}const{error:re}=await supabase.from('erp_documentos_qualidade_revisoes').insert({documento_id:d.id,empresa_id:user.empresa_id,revisao:0,status:'rascunho',titulo:d.titulo,conteudo:form.conteudo.trim(),motivo_alteracao:form.motivo.trim(),criado_por:user.id});if(re)setError(re.message);else{setNotice('Documento criado como Rascunho.');setForm({codigo:'',titulo:'',departamento:'',tipo:'Procedimento',conteudo:'',motivo:'Criação do documento'});await load();selectDoc(d as Doc)}setSaving(false)}
 async function transition(status:string){if(!selected||!user)return;setSaving(true);setError('');const rev=revisions[0];if(!rev){setError('A revisão atual não foi encontrada.');setSaving(false);return}const patch:any={status};if(status==='em_revisao')patch.revisado_por=user.id;if(status==='aprovada')patch.aprovado_por=user.id,patch.aprovado_em=new Date().toISOString();if(status==='liberada')patch.liberado_por=user.id,patch.liberado_em=new Date().toISOString(),patch.data_efetiva=new Date().toISOString();const{error}=await supabase.from('erp_documentos_qualidade_revisoes').update(patch).eq('id',rev.id);if(error){setError(error.message);setSaving(false);return}const docPatch:any={status};if(status==='aprovada')docPatch.aprovado_por=user.id,docPatch.aprovado_em=new Date().toISOString();if(status==='liberada')docPatch.data_efetiva=new Date().toISOString(),docPatch.revisao_atual_id=rev.id;await supabase.from('erp_documentos_qualidade').update(docPatch).eq('id',selected.id);await load();const fresh=docs.find(x=>x.id===selected.id)||selected;setSelected({...fresh,status});await loadRevisions(selected.id);setNotice(`Documento ${statusLabel[status]||status}.`);setSaving(false)}
 async function requestChange(){if(!selected||!user)return;const motivo=window.prompt('Descreva o motivo da alteração solicitada:');if(!motivo?.trim())return;setSaving(true);const{error}=await supabase.from('erp_documentos_qualidade_solicitacoes').insert({documento_id:selected.id,empresa_id:user.empresa_id,solicitante_id:user.id,setor_solicitante_id:user.setor_id,motivo:motivo.trim()});if(error)setError(error.message);else setNotice('Solicitação enviada para a Qualidade.');setSaving(false)}
 return <main className="qms-control-page"><header className="qms-control-head"><div><span className="qms-kicker">SGQ ERP • CONTROLE DE DOCUMENTOS</span><h1>Procedimentos e documentos controlados</h1><p>Criação, revisão, aprovação, liberação, distribuição e ciência com histórico imutável por revisão.</p></div><button className="qms-refresh" onClick={()=>void load()}><RefreshCw size={17}/> Atualizar</button></header>
 <section className="qms-grid"><aside className="qms-panel qms-list"><div className="qms-panel-title"><b>Documentos</b><span>{docs.length}</span></div>{loading?<p>Carregando…</p>:docs.length===0?<p>Nenhum documento cadastrado.</p>:docs.map(d=><button className={selected?.id===d.id?'qms-doc active':'qms-doc'} key={d.id} onClick={()=>selectDoc(d)}><span>{d.codigo}</span><strong>{d.titulo}</strong><small>{d.departamento} • Rev. {d.revisao} • {statusLabel[d.status]||d.status}</small></button>)}</aside>
 <section className="qms-panel qms-detail">{selected?<><div className="qms-detail-head"><div><span className="qms-code">{selected.codigo}</span><h2>{selected.titulo}</h2><p>{selected.departamento} • {selected.tipo}</p></div><div className="qms-actions"><button onClick={()=>void requestChange()} disabled={saving}><Send size={16}/> Solicitar alteração</button>{revisions[0]?.status==='rascunho'&&<button onClick={()=>void transition('em_revisao')} disabled={saving}><History size={16}/> Enviar para revisão</button>}{revisions[0]?.status==='em_revisao'&&<button onClick={()=>void transition('aprovada')} disabled={saving}><CheckCircle2 size={16}/> Aprovar</button>}{revisions[0]?.status==='aprovada'&&<button onClick={()=>void transition('liberada')} disabled={saving}><ShieldCheck size={16}/> Liberar</button>}</div></div><div className="qms-status-row"><span className={`qms-status status-${selected.status}`}>{statusLabel[selected.status]||selected.status}</span><span>Revisão {selected.revisao}</span><span>Documento controlado</span>{selected.proxima_revisao&&<span>Próxima revisão: {new Date(selected.proxima_revisao).toLocaleDateString('pt-BR')}</span>}</div><div className="qms-document-paper"><div className="qms-paper-header"><b>SGQ ERP</b><span>DOCUMENTO CONTROLADO</span><span>Código: {selected.codigo} • Rev. {selected.revisao}</span></div><h3>{selected.titulo}</h3><div className="qms-paper-body">{(revisions[0]?.conteudo||'Sem conteúdo cadastrado.').split('\n').map((x,i)=><p key={i}>{x||' '}</p>)}</div></div><div className="qms-history"><h3><History size={18}/> Histórico de revisões</h3>{revisions.map(r=><article key={r.id}><div><b>Rev. {r.revisao}</b><span>{statusLabel[r.status]||r.status}</span></div><p>{r.motivo_alteracao||'Sem motivo informado.'}</p><small>{new Date(r.criado_em).toLocaleString('pt-BR')}</small></article>)}</div></>:<div className="qms-empty"><FileCheck2 size={44}/><h2>Selecione um documento</h2><p>Use o fluxo controlado para revisar e liberar cada nova versão.</p></div>}</section>
 <aside className="qms-panel qms-create"><div className="qms-panel-title"><b><FilePlus2 size={18}/> Novo documento</b><LockKeyhole size={17}/></div><form onSubmit={createDoc}><label>Código<input value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})} placeholder="POP-QUAL-001" required/></label><label>Título<input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Procedimento de controle" required/></label><label>Departamento<input value={form.departamento} onChange={e=>setForm({...form,departamento:e.target.value})} placeholder="Qualidade" required/></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>Procedimento</option><option>Instrução de Trabalho</option><option>Formulário</option><option>Política</option><option>Manual</option></select></label><label>Conteúdo<textarea rows={10} value={form.conteudo} onChange={e=>setForm({...form,conteudo:e.target.value})} placeholder="Objetivo, escopo, responsabilidades, procedimento, controles e registros…" required/></label><label>Motivo da criação<textarea rows={3} value={form.motivo} onChange={e=>setForm({...form,motivo:e.target.value})} required/></label>{error&&<div className="qms-error">{error}</div>}{notice&&<div className="qms-notice">{notice}</div>}<button className="qms-primary" disabled={saving}><FilePlus2 size={16}/>{saving?'Salvando…':'Criar documento controlado'}</button></form></aside></section></main>
}
