import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft, ArrowRightLeft, Boxes, ClipboardCheck, PackagePlus, PackageMinus, RefreshCw, Search, Warehouse } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
type Tab='saldo'|'entrada'|'saida'|'transferencia'|'almox'|'producao'
type Product={id:string;codigo:string;nome:string;estoque_atual:number;categoria:string|null}
type Location={id:string;codigo:string;nome:string;almoxarifado_id:string;tipo:string;ativo:boolean}
type Warehouse={id:string;codigo:string;nome:string;tipo:string;ativo:boolean}
type Movement={id:string;produto_id:string|null;tipo:string;quantidade:number;origem:string|null;documento:string|null;ordem_producao_id:string|null;observacao:string|null;created_at:string}
type OP={id:string;numero_op:string;produto_id:string|null;quantidade:number;status:string}
export default function EstoqueAlmoxarifado(){
 const[tab,setTab]=useState<Tab>('saldo'),[products,setProducts]=useState<Product[]>([]),[locations,setLocations]=useState<Location[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[movements,setMovements]=useState<Movement[]>([]),[ops,setOps]=useState<OP[]>([]),[query,setQuery]=useState(''),[productId,setProductId]=useState(''),[locationId,setLocationId]=useState(''),[quantity,setQuantity]=useState(''),[targetLocation,setTargetLocation]=useState(''),[found,setFound]=useState(''),[bad,setBad]=useState(''),[defectText,setDefectText]=useState(''),[selectedOp,setSelectedOp]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){setBusy(true);setError('');try{const[p,l,w,m,o]=await Promise.all([supabase.from('erp_produtos').select('id,codigo,nome,estoque_atual,categoria').eq('ativo',true).order('codigo').limit(2000),supabase.from('erp_estoque_localizacoes').select('id,codigo,nome,almoxarifado_id,tipo,ativo').eq('ativo',true).order('codigo'),supabase.from('erp_almoxarifados').select('id,codigo,nome,tipo,ativo').eq('ativo',true).order('codigo'),supabase.from('erp_estoque_movimentos').select('id,produto_id,tipo,quantidade,origem,documento,ordem_producao_id,observacao,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('erp_ordens_producao').select('id,numero_op,produto_id,quantidade,status').order('criado_em',{ascending:false}).limit(500)]);for(const x of[p,l,w,m,o])if(x.error)throw x.error;setProducts((p.data||[]) as Product[]);setLocations((l.data||[]) as Location[]);setWarehouses((w.data||[]) as Warehouse[]);setMovements((m.data||[]) as Movement[]);setOps((o.data||[]) as OP[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar estoque.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>products.filter(p=>!query||p.codigo.toLowerCase().includes(query.toLowerCase())||p.nome.toLowerCase().includes(query.toLowerCase())),[products,query])
 async function movement(tipo:'entrada'|'saida'){if(!productId||Number(quantity)<=0){setError('Selecione o produto e informe a quantidade.');return}setBusy(true);setError('');try{const p=products.find(x=>x.id===productId);const{error}=await supabase.from('erp_estoque_movimentos').insert({empresa_id:(await supabase.rpc('erp_current_empresa_id')).data,produto_id:productId,tipo,quantidade:Number(quantity),origem:'estoque',localizacao_destino_id:tipo==='entrada'?locationId||null:null,localizacao_origem_id:tipo==='saida'?locationId||null:null,observacao:tipo==='entrada'?'Entrada manual':'Saída manual'});if(error)throw error;const next=Math.max(0,Number(p?.estoque_atual||0)+(tipo==='entrada'?Number(quantity):-Number(quantity)));const{error:pe}=await supabase.from('erp_produtos').update({estoque_atual:next}).eq('id',productId);if(pe)throw pe;setMessage((tipo==='entrada'?'Entrada':'Saída')+' registrada.');setQuantity('');await load()}catch(e){setError(e instanceof Error?e.message:'Falha no movimento.')}finally{setBusy(false)}}
 async function transfer(){if(!productId||!locationId||!targetLocation||Number(quantity)<=0){setError('Informe produto, origem, destino e quantidade.');return}setBusy(true);setError('');try{const empresa=(await supabase.rpc('erp_current_empresa_id')).data as string;const{error}=await supabase.from('erp_estoque_movimentos').insert({empresa_id:empresa,produto_id:productId,tipo:'transferencia',quantidade:Number(quantity),origem:'almoxarifado',localizacao_origem_id:locationId,localizacao_destino_id:targetLocation,observacao:'Transferência de localização'});if(error)throw error;setMessage('Transferência registrada entre localizações.');setQuantity('');await load()}catch(e){setError(e instanceof Error?e.message:'Falha na transferência.')}finally{setBusy(false)}}
 async function confirmProduction(){if(!selectedOp){setError('Selecione a OP.');return}const f=Number(found),b=Number(bad);if(f<0||b<0||b>f){setError('Quantidade encontrada/defeituosa inválida.');return}const defs=defectText.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const a=x.split(':');return{defeito:a[0].trim(),quantidade:Number(a[1]||0),observacao:a.slice(2).join(':').trim()||null}}).filter(x=>x.defeito&&x.quantidade>0);setBusy(true);setError('');try{const{data,error}=await supabase.rpc('erp_registrar_conferencia_producao',{p_ordem_producao_id:selectedOp,p_quantidade_encontrada:f,p_quantidade_defeituosa:b,p_defeitos:defs,p_localizacao_destino_id:locationId||null,p_acabamento:true,p_observacao:'Conferência do Almoxarifado após acabamento'});if(error)throw error;const r=data as {quantidade_boa?:number;saldo_producao?:number};setMessage('Conferido: '+Number(r.quantidade_boa||0)+' boas no estoque, '+b+' no refugo. Saldo OP: '+Number(r.saldo_producao||0)+'.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha na conferência.')}finally{setBusy(false)}}
 const tabs:[Tab,string,LucideIcon][]=[['saldo','Saldo / Endereços',Boxes],['entrada','Entrada',PackagePlus],['saida','Saída',PackageMinus],['transferencia','Transferência',ArrowRightLeft],['almox','Almoxarifado',Warehouse],['producao','Conferir produção',ClipboardCheck]]
 return <main className="pcp-page" style={{padding:24,maxWidth:1750,margin:'0 auto'}}><header className="pcp-toolbar"><div><button className="secondary-v2" onClick={()=>location.href='/erp-industrial'}><ArrowLeft size={17}/> Voltar</button><span className="v2-eyebrow">ESTOQUE • ALMOXARIFADO</span><h1 style={{margin:'6px 0'}}>Estoque e Almoxarifado</h1><p style={{margin:0,color:'#64777d'}}>Entradas, saídas, endereços, transferência, acabamento e conferência real da produção.</p></div><button className="menu-green" onClick={()=>void load()} disabled={busy}><RefreshCw size={17}/> {busy?'Atualizando…':'Atualizar'}</button></header>{(message||error)&&<div className={error?'error':'notice'} style={{margin:'12px 0'}}>{error||message}</div>}<nav className="quality-tabs">{tabs.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={16}/>{label}</button>)}</nav>
 {tab==='saldo'&&<section className="crud-list"><div className="crud-list-head"><div><strong>Saldo de produtos</strong><small>O endereço físico é controlado separadamente do saldo total do produto.</small></div><div className="module-search"><Search size={16}/><input placeholder="Código ou produto" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="crud-table-wrap"><table><thead><tr><th>Código</th><th>Produto</th><th>Categoria</th><th>Saldo ERP</th><th>Endereços ativos</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td>{p.codigo}</td><td>{p.nome}</td><td>{p.categoria||'—'}</td><td>{p.estoque_atual}</td><td>{locations.length}</td></tr>)}</tbody></table></div></section>}
 {tab==='entrada'&&<MovementForm title="Dar entrada no estoque" productId={productId} setProductId={setProductId} locationId={locationId} setLocationId={setLocationId} quantity={quantity} setQuantity={setQuantity} products={products} locations={locations} action={()=>void movement('entrada')} busy={busy}/>}
 {tab==='saida'&&<MovementForm title="Dar saída no estoque" productId={productId} setProductId={setProductId} locationId={locationId} setLocationId={setLocationId} quantity={quantity} setQuantity={setQuantity} products={products} locations={locations} action={()=>void movement('saida')} busy={busy}/>}
 {tab==='transferencia'&&<section className="erp-card" style={{padding:18,maxWidth:800}}><span className="v2-eyebrow">MOVIMENTAÇÃO INTERNA</span><h2>Transferir entre endereços</h2><Select label="Produto" value={productId} onChange={setProductId} options={products.map(p=>[p.id,p.codigo+' • '+p.nome])}/><Select label="Origem" value={locationId} onChange={setLocationId} options={locations.map(l=>[l.id,l.codigo+' • '+l.nome])}/><Select label="Destino" value={targetLocation} onChange={setTargetLocation} options={locations.map(l=>[l.id,l.codigo+' • '+l.nome])}/><label>Quantidade<input type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button className="menu-green" disabled={busy} onClick={transfer}><ArrowRightLeft size={16}/> Transferir</button></section>}
 {tab==='almox'&&<section><div className="quality-kpis">{warehouses.map(w=><article key={w.id}><Warehouse/><span>{w.codigo}</span><strong>{w.nome}</strong><small>{locations.filter(l=>l.almoxarifado_id===w.id).length} endereços</small></article>)}</div><Table title="Endereços físicos" cols={['Código','Nome','Tipo','Almoxarifado']} rows={locations.map(l=>[l.codigo,l.nome,l.tipo,warehouses.find(w=>w.id===l.almoxarifado_id)?.codigo||'—'])}/></section>}
 {tab==='producao'&&<section className="quality-split"><section className="erp-card" style={{padding:18}}><span className="v2-eyebrow">GRID DE CONFERÊNCIA</span><h2>Lançar produção no estoque</h2><Select label="Ordem de produção" value={selectedOp} onChange={setSelectedOp} options={ops.map(o=>[o.id,o.numero_op+' • planejado '+o.quantidade+' • '+o.status])}/><label>Quantidade encontrada<input type="number" min="0" step="any" value={found} onChange={e=>setFound(e.target.value)}/></label><label>Quantidade defeituosa<input type="number" min="0" step="any" value={bad} onChange={e=>setBad(e.target.value)}/></label><Select label="Endereço das peças boas" value={locationId} onChange={setLocationId} options={locations.map(l=>[l.id,l.codigo+' • '+l.nome])}/><label>Defeitos para Qualidade<textarea rows={6} value={defectText} onChange={e=>setDefectText(e.target.value)} placeholder={'Rebarba:200\nMancha:150\nDimensão fora:150:observação'}/></label><button className="menu-green" disabled={busy} onClick={confirmProduction}><ClipboardCheck size={16}/> Conferir e lançar</button></section><section className="erp-card" style={{padding:18}}><h2>Regra física</h2><p>Exemplo: OP 5.000 → encontrados 4.500 → defeitos 500 → boas 4.000.</p><div className="quality-kpis"><article><span>Planejada</span><strong>{ops.find(o=>o.id===selectedOp)?.quantidade||'—'}</strong></article><article><span>Encontrada</span><strong>{found||'—'}</strong></article><article><span>Defeito</span><strong>{bad||'—'}</strong></article><article><span>Boa</span><strong>{found?Math.max(0,Number(found)-Number(bad||0)):'—'}</strong></article></div><p>As boas geram entrada no estoque e o refugo gera movimento separado; os defeitos são enviados para análise da Qualidade.</p></section></section>}
 </main>
}
function MovementForm({title,productId,setProductId,locationId,setLocationId,quantity,setQuantity,products,locations,action,busy}:{title:string;productId:string;setProductId:(v:string)=>void;locationId:string;setLocationId:(v:string)=>void;quantity:string;setQuantity:(v:string)=>void;products:Product[];locations:Location[];action:()=>void;busy:boolean}){return <section className="erp-card" style={{padding:18,maxWidth:800}}><h2>{title}</h2><Select label="Produto" value={productId} onChange={setProductId} options={products.map(p=>[p.id,p.codigo+' • '+p.nome])}/><Select label="Endereço" value={locationId} onChange={setLocationId} options={locations.map(l=>[l.id,l.codigo+' • '+l.nome])}/><label>Quantidade<input type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button className="menu-green" disabled={busy} onClick={action}>{title}</button></section>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Selecione</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Table({title,cols,rows}:{title:string;cols:string[];rows:(string|number)[][]}){return <section className="crud-list" style={{marginTop:14}}><div className="crud-list-head"><strong>{title}</strong><small>{rows.length} registros</small></div><div className="crud-table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{String(v??'—')}</td>)}</tr>)}</tbody></table></div></section>}
