import { useEffect, useState } from 'react'
import { CheckCircle2, RefreshCw, Truck, XCircle } from 'lucide-react'
import VendasLayout, { type SalesNavSection } from './VendasLayout'
import { supabase } from '../lib/supabaseClient'

type Manifest={id:string;numero:number;status:string;peso_total_kg:number;capacidade_kg:number|null;data_expedicao:string|null;transportadora:string|null;veiculo_id:string|null;motorista_id:string|null}
const nav:SalesNavSection[]=[{label:'Expedição',items:[{label:'Roteirização',href:'/expedicao/roteirizacao',icon:Truck},{label:'Portaria',href:'/expedicao/portaria',icon:CheckCircle2}]},{label:'Integrações',items:[{label:'Fiscal',href:'/fiscal',icon:CheckCircle2},{label:'Vendas',href:'/vendas',icon:Truck},{label:'Estoque',href:'/estoque',icon:Truck}]}]

export default function ExpedicaoPortaria(){
 const [empresa,setEmpresa]=useState(''),[rows,setRows]=useState<Manifest[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const current=await supabase.rpc('erp_current_empresa_id');if(current.error||!current.data)throw current.error??new Error('Empresa ERP não identificada.');const id=String(current.data);setEmpresa(id);const result=await supabase.from('erp_expedicoes').select('id,numero,status,peso_total_kg,capacidade_kg,data_expedicao,transportadora,veiculo_id,motorista_id').eq('empresa_id',id).in('status',['PREPARACAO','LIBERADA']).order('numero',{ascending:false}).limit(100);if(result.error)throw result.error;setRows((result.data??[]) as Manifest[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar a portaria.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const current=rows.find(x=>x.id===selected)??null
 const release=async()=>{if(!current||!empresa){setError('Selecione um romaneio em preparação.');return}if(current.status!=='PREPARACAO'){setError('Somente romaneios em preparação podem ser liberados.');return}setBusy(true);setError('');setMessage('');try{const result=await supabase.from('erp_expedicoes').update({status:'LIBERADA',updated_at:new Date().toISOString()}).eq('id',current.id).eq('empresa_id',empresa).eq('status','PREPARACAO').select('id').maybeSingle();if(result.error)throw result.error;if(!result.data)throw new Error('O romaneio não foi liberado. Verifique permissão e status.');setMessage('Saída liberada no banco real.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao liberar a saída.')}finally{setBusy(false)}}
 return <VendasLayout title="Expedição / Portaria" subtitle="Romaneio • conferência • liberação real de saída" onRefresh={()=>void load()} navSections={nav}><main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-6">
  {(message||error)&&<div role={error?'alert':'status'} className={error?'mb-4 border border-rose-300 bg-rose-50 p-3 text-rose-900':'mb-4 border border-emerald-300 bg-emerald-50 p-3 text-emerald-900'}>{error||message}</div>}
  <section className="grid gap-4 lg:grid-cols-[1fr_1.4fr]"><article className="border border-slate-300 bg-white p-4"><div className="mb-3 flex items-center gap-2"><Truck size={18}/><h2 className="text-sm text-[#123B50]">Romaneios em portaria</h2></div><select className="h-10 w-full border border-slate-300 bg-white px-2" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione o romaneio</option>{rows.map(row=><option key={row.id} value={row.id}>#{row.numero} • {row.status} • {Number(row.peso_total_kg).toLocaleString('pt-BR')} kg</option>)}</select><button type="button" disabled={!current||current.status!=='PREPARACAO'||busy} onClick={()=>void release()} className="mt-3 flex h-10 w-full items-center justify-center gap-2 border border-emerald-700 bg-emerald-700 px-3 text-white disabled:opacity-50"><CheckCircle2 size={15}/>LIBERAR SAÍDA</button></article>
  <article className="border border-slate-300 bg-white p-4">{current?<><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><div><span className="text-[10px] text-slate-500">ROMANEIO</span><strong className="block text-lg">#{current.numero}</strong></div><div><span className="text-[10px] text-slate-500">STATUS</span><strong className="block">{current.status}</strong></div><div><span className="text-[10px] text-slate-500">PESO DOCUMENTAL</span><strong className="block">{Number(current.peso_total_kg).toLocaleString('pt-BR')} kg</strong></div><div><span className="text-[10px] text-slate-500">CAPACIDADE</span><strong className="block">{current.capacidade_kg?Number(current.capacidade_kg).toLocaleString('pt-BR')+' kg':'—'}</strong></div><div><span className="text-[10px] text-slate-500">DATA</span><strong className="block">{current.data_expedicao??'—'}</strong></div><div><span className="text-[10px] text-slate-500">TRANSPORTADORA</span><strong className="block">{current.transportadora??'—'}</strong></div></div><div className="mt-4 border-t border-slate-200 pt-3 text-xs text-slate-600">A portaria não inventa pesagem. O peso exibido é o peso persistido nas NF-e vinculadas ao romaneio. Integração com balança só deve ser adicionada quando houver contrato real.</div></>:<div className="flex min-h-48 items-center justify-center text-sm text-slate-500"><XCircle size={16} className="mr-2"/>Selecione um romaneio.</div>}</article></section>
 </main></VendasLayout>
}
