/*
 * 📝 IDENTIFICAÇÃO DE LEITURA E REVISÃO DE CÓDIGO:
 * - Arquivo: src/pages/FichaEngenharia.tsx
 * - Status Atual: Revisão 1 (Módulo Industrial Avançado)
 * - Total de Linhas Gerado: 250
 * - Assinatura de Entrada (Primeiros 3 Imports): import { useEffect, useMemo, useState } from 'react' | import { CheckCircle2, ClipboardList, Factory, Plus, Save, Trash2 } from 'lucide-react' | import { supabase } from '../lib/supabaseClient'
 * - Regra de Negócio Senior/Nomus Incorporada: ficha técnica separada em modelo/BOM e roteiro, com consumo, perda, lote, sequência, recurso, setup e ciclo.
 */
import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardList, Factory, Plus, Save, Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Product={id:string;codigo:string;nome:string;unidade:string|null}
type Machine={id:string;codigo:string;nome:string}
type Ficha={id:string;produto_id:string;versao:number;rendimento:number;unidade_rendimento:string;observacoes:string|null;ativa:boolean}
type BomRow={id?:string;componente_id:string;quantidade:string;perda_percentual:string;lote_obrigatorio:boolean;tipo_item:'COMPRADO'|'FABRICADO';sequencia:number}
type OpRow={id?:string;sequencia:number;operacao:string;maquina_id:string;molde_id:string;setup_min:string;ciclo_seg:string;instrucoes:string}
const emptyBom=():BomRow=>({componente_id:'',quantidade:'1',perda_percentual:'0',lote_obrigatorio:false,tipo_item:'COMPRADO',sequencia:10})
const emptyOp=():OpRow=>({sequencia:10,operacao:'',maquina_id:'',molde_id:'',setup_min:'0',ciclo_seg:'0',instrucoes:''})
const errorText=(e:unknown)=>e instanceof Error?e.message:String((e as {message?:string})?.message??'Operação recusada pelo banco.')

export default function FichaEngenharia(){
 const [products,setProducts]=useState<Product[]>([]),[machines,setMachines]=useState<Machine[]>([]),[ficha,setFicha]=useState<Ficha|null>(null)
 const [productId,setProductId]=useState(''),[version,setVersion]=useState('1'),[rendimento,setRendimento]=useState('1'),[unit,setUnit]=useState('UN'),[notes,setNotes]=useState('')
 const [bom,setBom]=useState<BomRow[]>([emptyBom()]),[ops,setOps]=useState<OpRow[]>([emptyOp()])
 const [tab,setTab]=useState<'geral'|'bom'|'processo'>('geral'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState('')
 const selected=useMemo(()=>products.find(p=>p.id===productId),[products,productId])
 useEffect(()=>{void loadBase()},[])
 async function company(){const {data,error}=await supabase.rpc('erp_current_empresa_id');if(error||!data)throw new Error('Empresa da sessão não identificada.');return String(data)}
 async function loadBase(){setLoading(true);try{const [p,m]=await Promise.all([supabase.from('erp_produtos').select('id,codigo,nome,unidade').eq('ativo',true).order('codigo').limit(2000),supabase.from('erp_maquinas').select('id,codigo,nome').eq('ativo',true).order('codigo').limit(500)]);if(p.error)throw p.error;if(m.error)throw m.error;setProducts((p.data??[]) as Product[]);setMachines((m.data??[]) as Machine[])}catch(e){setNotice(errorText(e))}finally{setLoading(false)}}
 async function loadFicha(id:string){if(!id){setFicha(null);setBom([emptyBom()]);setOps([emptyOp()]);return}setBusy(true);try{const empresaId=await company();const f=await supabase.from('erp_fichas_tecnicas').select('id,produto_id,versao,rendimento,unidade_rendimento,observacoes,ativa').eq('empresa_id',empresaId).eq('produto_id',id).eq('ativa',true).order('versao',{ascending:false}).limit(1).maybeSingle();if(f.error)throw f.error;if(!f.data){setFicha(null);setBom([emptyBom()]);setOps([emptyOp()]);setVersion('1');setRendimento('1');setUnit('UN');setNotes('');return}const current=f.data as Ficha;setFicha(current);setVersion(String(current.versao));setRendimento(String(current.rendimento));setUnit(current.unidade_rendimento);setNotes(current.observacoes??'');const [bi,ro]=await Promise.all([supabase.from('erp_ficha_itens').select('id,componente_id,quantidade,perda_percentual,lote_obrigatorio,tipo_item,sequencia').eq('empresa_id',empresaId).eq('ficha_id',current.id).order('sequencia'),supabase.from('erp_ficha_operacoes').select('id,sequencia,operacao,maquina_id,molde_id,setup_min,ciclo_seg,instrucoes').eq('empresa_id',empresaId).eq('ficha_id',current.id).order('sequencia')]);if(bi.error)throw bi.error;if(ro.error)throw ro.error;setBom((bi.data??[]).map(x=>({id:x.id,componente_id:x.componente_id,quantidade:String(x.quantidade),perda_percentual:String(x.perda_percentual),lote_obrigatorio:Boolean(x.lote_obrigatorio),tipo_item:x.tipo_item,sequencia:x.sequencia})));setOps((ro.data??[]).map(x=>({id:x.id,sequencia:x.sequencia,operacao:x.operacao,maquina_id:x.maquina_id??'',molde_id:x.molde_id??'',setup_min:String(x.setup_min),ciclo_seg:String(x.ciclo_seg),instrucoes:x.instrucoes??''})))}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}
 useEffect(()=>{void loadFicha(productId)},[productId])
 function setBomField(index:number,key:keyof BomRow,value:string|boolean){setBom(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row))}
 function setOpField(index:number,key:keyof OpRow,value:string|number){setOps(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row))}
 async function save(){setBusy(true);setNotice('');try{if(!productId)throw new Error('Selecione o produto produzido.');if(bom.some(r=>!r.componente_id||Number(r.quantidade)<=0))throw new Error('Preencha todos os componentes da BOM.');if(ops.some(r=>!r.operacao.trim()||Number(r.ciclo_seg)<0||Number(r.setup_min)<0))throw new Error('Preencha todas as operações e tempos.');const empresaId=await company();const saved=await supabase.from('erp_fichas_tecnicas').upsert({empresa_id:empresaId,produto_id:productId,versao:Number(version),rendimento:Number(rendimento),unidade_rendimento:unit.trim()||'UN',observacoes:notes.trim()||null,ativa:true},{onConflict:'empresa_id,produto_id,versao'}).select('id,produto_id,versao,rendimento,unidade_rendimento,observacoes,ativa').single();if(saved.error)throw saved.error;const fichaId=String(saved.data.id);const bi=await supabase.from('erp_ficha_itens').upsert(bom.map(x=>({...(x.id?{id:x.id}:{}),empresa_id:empresaId,ficha_id:fichaId,componente_id:x.componente_id,quantidade:Number(x.quantidade),perda_percentual:Number(x.perda_percentual),lote_obrigatorio:x.lote_obrigatorio,tipo_item:x.tipo_item,sequencia:x.sequencia})),{onConflict:'id'});if(bi.error)throw bi.error;const ro=await supabase.from('erp_ficha_operacoes').upsert(ops.map(x=>({...(x.id?{id:x.id}:{}),empresa_id:empresaId,ficha_id:fichaId,sequencia:x.sequencia,operacao:x.operacao.trim(),maquina_id:x.maquina_id||null,molde_id:x.molde_id||null,setup_min:Number(x.setup_min),ciclo_seg:Number(x.ciclo_seg),instrucoes:x.instrucoes.trim()||null})),{onConflict:'id'});if(ro.error)throw ro.error;setFicha(saved.data as Ficha);setNotice('Ficha técnica salva: BOM e roteiro persistidos no tenant atual.')}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}
 if(loading)return <main className="industrial-form-page"><div className="industrial-panel">Carregando engenharia…</div></main>
 return <main className="industrial-form-page"><header className="industrial-page-head"><div><span className="industrial-eyebrow">ENGENHARIA INDUSTRIAL</span><h1>Ficha técnica do produto</h1><p>Modelo/BOM e roteiro são a base do MRP, PCP, chão de fábrica e custos.</p></div><button className="industrial-primary" onClick={()=>void save()} disabled={busy}><Save size={17}/>{busy?'Salvando…':'Salvar ficha'}</button></header>
  <section className="industrial-panel industrial-toolbar"><label>Produto produzido<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecione o produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.codigo} — {p.nome}</option>)}</select></label><label>Versão<input type="number" min="1" value={version} onChange={e=>setVersion(e.target.value)}/></label><label>Rendimento<input type="number" min="0.000001" step="0.001" value={rendimento} onChange={e=>setRendimento(e.target.value)}/></label><label>Unidade<input value={unit} onChange={e=>setUnit(e.target.value.toUpperCase())}/></label></section>
  {selected&&<div className="industrial-context"><CheckCircle2 size={17}/> Produto selecionado: <strong>{selected.codigo} — {selected.nome}</strong>{ficha&&<span>Ficha ativa v{ficha.versao}</span>}</div>}
  <nav className="industrial-tabs">{(['geral','bom','processo'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='geral'?'Geral':t==='bom'?'BOM / Materiais':'Processo / Roteiro'}</button>)}</nav>
  {tab==='geral'&&<section className="industrial-panel"><h2>Identificação e controle</h2><label>Observações<textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Critérios técnicos, revisão, aplicação e instruções gerais…"/></label><div className="industrial-info-grid"><article><ClipboardList/><b>Estrutura multinível</b><span>Componentes comprados ou fabricados, consumo e perda.</span></article><article><Factory/><b>Roteiro produtivo</b><span>Operações, recursos, setup e ciclo padrão.</span></article></div></section>}
  {tab==='bom'&&<section className="industrial-panel"><div className="industrial-section-head"><div><h2>Estrutura de materiais</h2><p>Consumo líquido, perda operacional, lote e origem do componente.</p></div><button className="industrial-secondary" onClick={()=>setBom(rows=>[...rows,{...emptyBom(),sequencia:(rows.at(-1)?.sequencia??0)+10}])}><Plus size={16}/>Adicionar componente</button></div><div className="industrial-table-scroll"><table className="industrial-table"><thead><tr><th>Seq.</th><th>Componente</th><th>Qtd. líquida</th><th>Perda %</th><th>Lote</th><th>Origem</th><th/></tr></thead><tbody>{bom.map((row,i)=><tr key={row.id??'new-'+i}><td>{row.sequencia}</td><td><select value={row.componente_id} onChange={e=>setBomField(i,'componente_id',e.target.value)}><option value="">Selecionar</option>{products.filter(p=>p.id!==productId).map(p=><option key={p.id} value={p.id}>{p.codigo} — {p.nome}</option>)}</select></td><td><input type="number" min="0.000001" step="0.001" value={row.quantidade} onChange={e=>setBomField(i,'quantidade',e.target.value)}/></td><td><input type="number" min="0" step="0.01" value={row.perda_percentual} onChange={e=>setBomField(i,'perda_percentual',e.target.value)}/></td><td><input type="checkbox" checked={row.lote_obrigatorio} onChange={e=>setBomField(i,'lote_obrigatorio',e.target.checked)}/></td><td><select value={row.tipo_item} onChange={e=>setBomField(i,'tipo_item',e.target.value as BomRow['tipo_item'])}><option value="COMPRADO">Comprado</option><option value="FABRICADO">Fabricado</option></select></td><td><button className="icon-button danger" onClick={()=>setBom(rows=>rows.length===1?[emptyBom()]:rows.filter((_,n)=>n!==i))} aria-label="Remover componente"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></section>}
  {tab==='processo'&&<section className="industrial-panel"><div className="industrial-section-head"><div><h2>Roteiro de fabricação</h2><p>Sequência operacional, recurso preferencial, ferramental, setup e ciclo teórico.</p></div><button className="industrial-secondary" onClick={()=>setOps(rows=>[...rows,{...emptyOp(),sequencia:(rows.at(-1)?.sequencia??0)+10}])}><Plus size={16}/>Adicionar operação</button></div><div className="industrial-table-scroll"><table className="industrial-table"><thead><tr><th>Seq.</th><th>Operação</th><th>Máquina</th><th>Molde/Ferramental ID</th><th>Setup min</th><th>Ciclo seg.</th><th>Instrução</th><th/></tr></thead><tbody>{ops.map((row,i)=><tr key={row.id??'op-'+i}><td>{row.sequencia}</td><td><input value={row.operacao} onChange={e=>setOpField(i,'operacao',e.target.value)} placeholder="Injeção / Rebarbação / Estampagem"/></td><td><select value={row.maquina_id} onChange={e=>setOpField(i,'maquina_id',e.target.value)}><option value="">Sem máquina</option>{machines.map(m=><option key={m.id} value={m.id}>{m.codigo} — {m.nome}</option>)}</select></td><td><input value={row.molde_id} onChange={e=>setOpField(i,'molde_id',e.target.value)} placeholder="UUID do ferramental"/></td><td><input type="number" min="0" step="0.1" value={row.setup_min} onChange={e=>setOpField(i,'setup_min',e.target.value)}/></td><td><input type="number" min="0" step="0.001" value={row.ciclo_seg} onChange={e=>setOpField(i,'ciclo_seg',e.target.value)}/></td><td><textarea rows={2} value={row.instrucoes} onChange={e=>setOpField(i,'instrucoes',e.target.value)} placeholder="Instrução de trabalho controlada"/></td><td><button className="icon-button danger" onClick={()=>setOps(rows=>rows.length===1?[emptyOp()]:rows.filter((_,n)=>n!==i))} aria-label="Remover operação"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></section>}
  {notice&&<div className="industrial-notice" role="status">{notice}</div>}
 </main>
}