import { useEffect,useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import { fetchAllPages } from '../lib/supabasePagination'
import IndustrialPageShell,{SectionCard,Table,Field,ToolbarButton} from '../components/industrial/IndustrialPageShell'
type Row={id:string;tipo:string;entidade:string;vencimento:string;valor:number;status:string}
const PAGE_SIZE=25
export default function FinanceiroFluxoCaixa(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[page,setPage]=useState(0)
async function load(){setLoading(true);try{const data=await fetchAllPages<{id:string;tipo:string|null;descricao:string|null;data_vencimento:string|null;valor:number|null;status:string|null}>((from,to)=>supabase.from('erp_financeiro_lancamentos').select('id,tipo,descricao,data_vencimento,valor,status',{count:'exact'}).order('data_vencimento').range(from,to));setRows(data.map(v=>({id:String(v.id),tipo:String(v.tipo??''),entidade:String(v.descricao??''),vencimento:String(v.data_vencimento??''),valor:Number(v.valor??0),status:String(v.status??'')})));setMsg('');setPage(0)}catch(cause){setRows([]);setMsg(`${cause instanceof Error?cause.message:'Contrato financeiro indisponível nesta instalação.'} Nenhum dado fictício foi criado.`)}finally{setLoading(false)}}
useEffect(()=>{void load()},[])
const pageCount=Math.max(1,Math.ceil(rows.length/PAGE_SIZE)),visibleRows=rows.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE)
useEffect(()=>{setPage(current=>Math.min(current,pageCount-1))},[pageCount])
const tone=(s:string)=>{const x=s.toUpperCase();if(['PAGO','LIQUIDADO','LIBERADO','CONFORME'].some(v=>x.includes(v)))return'ips-status-green';if(['VENCIDO','BLOQUEADO','RECUSADO'].some(v=>x.includes(v)))return'ips-status-rose';return'ips-status-amber'}
return <IndustrialPageShell module="Financeiro / Fluxo de Caixa" title="Gestão de Duplicatas e Fluxo de Caixa" actions={[{label:'ATUALIZAR',type:'neutral',icon:<RefreshCw size={18}/>,onClick:()=>void load()}]}><SectionCard title="1. Painel de controle financeiro"><Table><thead><tr><th>Tipo</th><th>Entidade / Parceiro</th><th>Vencimento</th><th>Valor (R$)</th><th>Status</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Consultando lançamentos...</td></tr>:rows.length===0?<tr><td colSpan={5}>Nenhum lançamento financeiro disponível.</td></tr>:visibleRows.map(r=><tr key={r.id}><td>{r.tipo}</td><td>{r.entidade}</td><td>{r.vencimento}</td><td>{r.valor.toLocaleString('pt-BR',{minimumFractionDigits:2})}</td><td className={tone(r.status)}>{r.status}</td></tr>)}</tbody></Table><nav aria-label="Paginação do fluxo de caixa" className="flex items-center justify-end gap-3 border-t border-slate-200 p-3"><button type="button" disabled={page===0} onClick={()=>setPage(current=>Math.max(0,current-1))} className="h-9 border border-slate-300 bg-white px-3 text-sm disabled:opacity-50">Anterior</button><span aria-live="polite" className="text-xs text-slate-600">Página {page+1} de {pageCount}</span><button type="button" disabled={page+1>=pageCount} onClick={()=>setPage(current=>Math.min(pageCount-1,current+1))} className="h-9 border border-slate-300 bg-white px-3 text-sm disabled:opacity-50">Próxima</button></nav></SectionCard><SectionCard title="2. Resumo de fluxo de caixa"><div className="ips-grid-2"><Field label="Saldo disponível atual"><input readOnly value="Calculado pelos lançamentos reais"/></Field><Field label="Saldo previsto do mês"><input readOnly value="Calculado pelos vencimentos reais"/></Field></div>{msg&&<p className="mt-4 font-semibold text-slate-900" role="status">{msg}</p>}<div className="ips-bottom-actions"><ToolbarButton tone="neutral" onClick={()=>void load()}>ATUALIZAR</ToolbarButton></div></SectionCard></IndustrialPageShell>}