import { useEffect,useState } from 'react'
import { Plus, Save, Zap } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import IndustrialPageShell,{SectionCard,Table,Field,ToolbarButton} from '../components/industrial/IndustrialPageShell'
type Row={id:string;tipo:string;entidade:string;vencimento:string;valor:number;status:string}
export default function FinanceiroFluxoCaixa(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState('')
async function load(){setLoading(true);const{data,error}=await supabase.from('erp_financeiro_lancamentos').select('id,tipo,descricao,data_vencimento,valor,status').order('data_vencimento').limit(500);if(error){setRows([]);setMsg('Contrato financeiro indisponível nesta instalação. Nenhum dado fictício foi criado.')}else setRows((data??[]).map((x:unknown)=>{const v=x as Record<string,unknown>;return{id:String(v.id??''),tipo:String(v.tipo??''),entidade:String(v.descricao??''),vencimento:String(v.data_vencimento??''),valor:Number(v.valor??0),status:String(v.status??'')}}));setLoading(false)}
useEffect(()=>{void load()},[])
const tone=(s:string)=>{const x=s.toUpperCase();if(['PAGO','LIQUIDADO','LIBERADO','CONFORME'].some(v=>x.includes(v)))return'ips-status-green';if(['VENCIDO','BLOQUEADO','RECUSADO'].some(v=>x.includes(v)))return'ips-status-rose';return'ips-status-amber'}
return <IndustrialPageShell module="Financeiro / Fluxo de Caixa" title="Gestão de Duplicatas e Fluxo de Caixa" actions={[{label:'LANÇAR MANUAL',type:'primary',icon:<Plus size={18}/>,onClick:()=>setMsg('Lançamento manual disponível após contrato financeiro persistido.')},{label:'GRAVAR PARCELA',type:'success',icon:<Save size={18}/>,onClick:()=>setMsg('Parcela deve nascer do documento fiscal de origem.')},{label:'LIQUIDAR / BAIXA',type:'neutral',icon:<Zap size={18}/>,onClick:()=>setMsg('Baixa exige lançamento financeiro real.')}]}><SectionCard title="1. Painel de controle financeiro"><Table><thead><tr><th>Tipo</th><th>Entidade / Parceiro</th><th>Vencimento</th><th>Valor (R$)</th><th>Status</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Consultando lançamentos...</td></tr>:rows.length===0?<tr><td colSpan={5}>Nenhum lançamento financeiro disponível.</td></tr>:rows.map(r=><tr key={r.id}><td>{r.tipo}</td><td>{r.entidade}</td><td>{r.vencimento}</td><td>{r.valor.toLocaleString('pt-BR',{minimumFractionDigits:2})}</td><td className={tone(r.status)}>{r.status}</td></tr>)}</tbody></Table></SectionCard><SectionCard title="2. Resumo de fluxo de caixa"><div className="ips-grid-2"><Field label="Saldo disponível atual"><input readOnly value="Calculado pelos lançamentos reais"/></Field><Field label="Saldo previsto do mês"><input readOnly value="Calculado pelos vencimentos reais"/></Field></div>{msg&&<p className="mt-4 font-semibold text-slate-900">{msg}</p>}<div className="ips-bottom-actions"><ToolbarButton tone="neutral" onClick={()=>void load()}>ATUALIZAR</ToolbarButton></div></SectionCard></IndustrialPageShell>}