import { useEffect, useState } from 'react'
import { CheckCircle2, RefreshCw, Search, XCircle } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import VendasLayout from './VendasLayout'

type Row={id:string;numero:number;status:string;fiscal_status:string;fiscal_parecer:string|null;total:number;data_pedido:string;fornecedor_id:string}
type Supplier={id:string;razao_social:string;nome_fantasia:string|null}

export default function FiscalCompras(){
 const [rows,setRows]=useState<Row[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.');const id=String(e.data);const [p,s]=await Promise.all([supabase.from('erp_pedidos_compra').select('id,numero,status,fiscal_status,fiscal_parecer,total,data_pedido,fornecedor_id').eq('empresa_id',id).order('data_pedido',{ascending:false}),supabase.from('erp_fornecedores').select('id,razao_social,nome_fantasia').eq('empresa_id',id).eq('ativo',true)]);if(p.error)throw p.error;if(s.error)throw s.error;setRows((p.data??[]) as Row[]);setSuppliers((s.data??[]) as Supplier[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar compras.')}finally{setBusy(false)}} 
 useEffect(()=>{void load()},[])
 const supplier=new Map(suppliers.map(s=>[s.id,s.nome_fantasia||s.razao_social]))
 const visible=rows.filter(r=>(String(r.numero)+' '+(supplier.get(r.fornecedor_id)||'')+' '+r.status+' '+r.fiscal_status).toLowerCase().includes(q.toLowerCase()))
 const decide=async(id:string,status:'VALIDADO'|'BLOQUEADO')=>{setBusy(true);setError('');setMessage('');try{const r=await supabase.rpc('erp_compras_validar_fiscal',{p_pedido_id:id,p_status:status,p_parecer:status==='VALIDADO'?'Validação fiscal concluída.':'Compra bloqueada pelo Fiscal. Quadro fiscal deve ser revisado.'});if(r.error)throw r.error;setMessage(status==='VALIDADO'?'Compra validada pelo Fiscal.':'Compra bloqueada pelo Fiscal.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar a decisão fiscal.')}finally{setBusy(false)}}
 return <VendasLayout title="Validação fiscal de compras" subtitle="Conferência fiscal antes da liberação da aquisição" onRefresh={()=>void load()}><main className="sales-workspace"><section className="sales-page-heading"><div><span className="sales-eyebrow">FISCAL / COMPRAS</span><h1>Validação fiscal de compras</h1><p>O Fiscal valida a parte tributária e cadastral; a aprovação comercial continua sendo responsabilidade de Compras/gestor.</p></div><div className="sales-heading-actions"><button className="sales-button sales-button--secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={14}/> Atualizar</button></div></section>{(message||error)&&<div className={error?'sales-alert':'sales-message'}>{error||message}</div>}<section className="sales-orders-card"><div className="sales-list-toolbar"><label className="sales-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pedido, fornecedor ou status..."/></label></div><div className="sales-table-scroll"><table className="sales-orders-table"><thead><tr><th>Pedido</th><th>Fornecedor</th><th>Status compra</th><th>Fiscal</th><th>Total</th><th>Ações</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className={r.fiscal_status==='BLOQUEADO'?'is-status-pendente':r.fiscal_status==='VALIDADO'?'is-status-finalizado':''}><td>PC-{String(r.numero).padStart(4,'0')}</td><td>{supplier.get(r.fornecedor_id)||'Fornecedor não localizado'}</td><td><span className="sales-status is-neutral">{r.status}</span></td><td><span className={`sales-status ${r.fiscal_status==='VALIDADO'?'is-success':r.fiscal_status==='BLOQUEADO'?'is-danger':'is-warning'}`}>{r.fiscal_status}</span></td><td>{Number(r.total||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><div className="sales-row-actions">{r.fiscal_status!=='VALIDADO'&&<button className="sales-icon-action" title="Validar fiscal" onClick={()=>void decide(r.id,'VALIDADO')} disabled={busy}><CheckCircle2 size={15}/></button>}{r.fiscal_status!=='BLOQUEADO'&&<button className="sales-icon-action" title="Bloquear fiscal" onClick={()=>void decide(r.id,'BLOQUEADO')} disabled={busy}><XCircle size={15}/></button>}</div></td></tr>)}{!visible.length&&<tr><td colSpan={6} className="sales-empty-state">Nenhum pedido encontrado.</td></tr>}</tbody></table></div></section></main></VendasLayout>
}
