import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react'
import { FileCheck2, FileDown, FileUp, KeyRound, Plus, Search, Settings2, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type FiscalDoc={id:string;tipo:string;modelo:string;serie:number;numero:number|null;status:string;ambiente:string;natureza_operacao:string|null;data_emissao:string|null;chave_acesso:string|null;destinatario_nome:string|null;destinatario_documento:string|null;valor_total:number;mensagem_retorno:string|null}
type FiscalConfig={id?:string;ambiente:'homologacao'|'producao';regime_tributario:string;serie_nfe:number;proximo_numero_nfe:number;certificado_configurado:boolean;integrador_configurado:boolean}
const emptyConfig:FiscalConfig={ambiente:'homologacao',regime_tributario:'',serie_nfe:1,proximo_numero_nfe:1,certificado_configurado:false,integrador_configurado:false}
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));const date=(v:string|null)=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(v)):'—'

export default function Fiscal(){
 const[docs,setDocs]=useState<FiscalDoc[]>([]),[config,setConfig]=useState<FiscalConfig>(emptyConfig),[query,setQuery]=useState(''),[status,setStatus]=useState('todos'),[tab,setTab]=useState<'notas'|'emitir'|'config'>('notas'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[xmlName,setXmlName]=useState(''),[notConfigured,setNotConfigured]=useState(false)
 async function empresaId(){const{data,error}=await supabase.rpc('erp_current_empresa_id');if(error)throw error;if(!data)throw new Error('Empresa do usuário não encontrada.');return data as string}
 async function load(){const{data,error:de}=await supabase.from('erp_documentos_fiscais').select('id,tipo,modelo,serie,numero,status,ambiente,natureza_operacao,data_emissao,chave_acesso,destinatario_nome,destinatario_documento,valor_total,mensagem_retorno').order('created_at',{ascending:false}).limit(200);if(de)throw de;setDocs((data||[]) as FiscalDoc[]);const companyId=await empresaId();const{data:cfg,error:ce}=await supabase.from('erp_config_fiscal').select('*').eq('empresa_id',companyId).maybeSingle();if(ce)throw ce;if(cfg)setConfig(cfg as FiscalConfig)}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar Fiscal.'))},[])
 const filtered=useMemo(()=>docs.filter(d=>{const hay=`${d.numero||''} ${d.chave_acesso||''} ${d.destinatario_nome||''} ${d.destinatario_documento||''}`.toLowerCase();return hay.includes(query.toLowerCase())&&(status==='todos'||d.status===status)}),[docs,query,status])
 async function saveConfig(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const companyId=await empresaId();const payload={ambiente:config.ambiente,regime_tributario:config.regime_tributario,serie_nfe:config.serie_nfe,proximo_numero_nfe:config.proximo_numero_nfe,empresa_id:companyId};const{error:se}=config.id?await supabase.from('erp_config_fiscal').update(payload).eq('id',config.id):await supabase.from('erp_config_fiscal').insert(payload);if(se)throw se;await load();setMessage('Parâmetros fiscais salvos. Credenciais do provedor permanecem exclusivamente no backend.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a configuração.')}finally{setBusy(false)}}
 async function createDraft(){setBusy(true);setError('');setMessage('');try{const companyId=await empresaId();const number=config.proximo_numero_nfe||1;const{error:ie}=await supabase.from('erp_documentos_fiscais').insert({empresa_id:companyId,tipo:'NFe',modelo:'55',serie:config.serie_nfe||1,numero:number,status:'rascunho',ambiente:config.ambiente,natureza_operacao:'Venda de mercadoria',data_emissao:new Date().toISOString(),mensagem_retorno:'Rascunho criado. Autorização real depende do integrador fiscal configurado no backend.'});if(ie)throw ie;const next={...config,proximo_numero_nfe:number+1};setConfig(next);const{data:row}=await supabase.from('erp_config_fiscal').select('id').eq('empresa_id',companyId).maybeSingle();if(row?.id)await supabase.from('erp_config_fiscal').update({proximo_numero_nfe:number+1}).eq('id',row.id);await load();setTab('notas');setMessage(`NF-e ${number} criada como rascunho.`)}catch(e){setError(e instanceof Error?e.message:'Falha ao criar NF-e.')}finally{setBusy(false)}}
 async function emit(doc:FiscalDoc){setBusy(true);setError('');setMessage('');setNotConfigured(false);try{const{data, error:fnError}=await supabase.functions.invoke('emitir-nfe',{body:{documento_id:doc.id}});if(fnError){const raw=fnError.message||'Falha na função fiscal.';if(/not_configured|não configurado|nao_configurado/i.test(raw)){setNotConfigured(true);throw new Error('Ambiente de Teste / Não Configurado: o integrador fiscal e o certificado ainda não foram cadastrados no backend. Nenhuma autorização fictícia foi gerada.')}throw fnError}if(data?.status==='nao_configurado'){setNotConfigured(true);throw new Error(data.message)}setMessage(`Retorno do integrador fiscal: ${data?.status||'pendente'}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Falha na emissão NF-e.')}finally{setBusy(false)}}
 function extractXml(xml:string){const parser=new DOMParser();const doc=parser.parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML inválido.');const all=xml.replace(/\s+/g,'');const keyMatch=all.match(/(?:NFe|nfe)?(?:[A-Za-z0-9:_-]*chNFe)?([0-9]{44})/);const accessKey=keyMatch?.[1]||doc.querySelector('chNFe')?.textContent?.trim()||null;const node=(n:string)=>doc.getElementsByTagNameNS('*',n)[0]?.textContent?.trim()||doc.getElementsByTagName(n)[0]?.textContent?.trim()||'';return{accessKey,numero:node('nNF'),serie:Number(node('serie')||1),recipient:node('xNome'),recipientDoc:node('CNPJ')||node('CPF'),total:Number(node('vNF')||0),issuedAt:node('dhEmi')||node('dEmi')}}
 async function importXml(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setMessage('');setXmlName(file.name);try{const xml=await file.text();const p=extractXml(xml);const companyId=await empresaId();const{error:ie}=await supabase.from('erp_documentos_fiscais').insert({empresa_id:companyId,tipo:'NFe',modelo:'55',serie:p.serie,numero:p.numero?Number(p.numero):null,status:'autorizada',ambiente:config.ambiente,data_emissao:p.issuedAt?new Date(p.issuedAt).toISOString():null,chave_acesso:p.accessKey,destinatario_nome:p.recipient,destinatario_documento:p.recipientDoc,valor_total:p.total,xml_original:xml,mensagem_retorno:'XML importado da contabilidade. O ERP não declara autorização própria; o XML recebido é a evidência externa.'});if(ie)throw ie;await load();setMessage(p.accessKey?`XML importado. Chave: ${p.accessKey}`:'XML importado, mas a chave não foi encontrada.')}catch(err){setError(err instanceof Error?err.message:'Falha ao importar XML.')}finally{setBusy(false);e.target.value=''}}
 async function lookupKey(key:string){setBusy(true);setError('');setMessage('');try{const clean=key.replace(/\D/g,'');if(clean.length!==44)throw new Error('A chave de acesso deve conter 44 dígitos.');const{data,error:fe}=await supabase.from('erp_documentos_fiscais').select('*').eq('chave_acesso',clean).maybeSingle();if(fe)throw fe;setMessage(data?`Nota localizada no ERP: ${data.numero||'sem número'} — ${data.status}.`:'Chave válida, mas esta NF-e ainda não foi importada para o ERP.')}catch(e){setError(e instanceof Error?e.message:'Falha na consulta.')}finally{setBusy(false)}}
 return <div className="panel fiscal-page"><div className="panel-head"><div><span className="eyebrow">FISCAL • NF-e</span><h2>Notas fiscais eletrônicas</h2><p>Preparação, integração fiscal real e importação de XML. Nenhuma autorização é inventada.</p></div><div className="fiscal-actions"><label className="secondary fiscal-upload"><FileUp size={17}/> Importar XML<input type="file" accept=".xml,text/xml,application/xml" onChange={importXml}/></label><button className="primary" onClick={()=>setTab('emitir')}><Plus size={17}/> Nova NF-e</button></div></div>{(message||error)&&<div className={error?'error':'notice'}>{error||message}</div>}{notConfigured&&<div className="notice" style={{border:'1px solid #f59e0b',background:'#fffbeb',color:'#92400e'}}><ShieldCheck size={17}/> Ambiente de Teste / Não Configurado — o botão de emissão está conectado ao backend, mas o provedor fiscal só será chamado depois que `NFE_GATEWAY_URL` e `NFE_GATEWAY_TOKEN` forem configurados com credenciais reais.</div>}
 <div className="tabs"><button className={tab==='notas'?'tab active':'tab'} onClick={()=>setTab('notas')}><FileCheck2 size={16}/> Notas</button><button className={tab==='emitir'?'tab active':'tab'} onClick={()=>setTab('emitir')}><Plus size={16}/> Emitir</button><button className={tab==='config'?'tab active':'tab'} onClick={()=>setTab('config')}><Settings2 size={16}/> Configuração</button></div>
 {tab==='notas'&&<><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Pesquisar número, destinatário ou chave" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos</option><option value="rascunho">Rascunho</option><option value="pendente">Pendente</option><option value="autorizada">Autorizada</option><option value="rejeitada">Rejeitada</option><option value="cancelada">Cancelada</option></select><span>{filtered.length} notas</span></div><div className="fiscal-key-box"><div><KeyRound size={18}/><div><strong>Consultar chave de acesso</strong><small>44 dígitos • busca apenas dentro da empresa atual.</small></div></div><input maxLength={44} placeholder="Chave de 44 dígitos" onKeyDown={e=>{if(e.key==='Enter')void lookupKey(e.currentTarget.value)}}/></div><div className="table-wrap"><table><thead><tr><th>Número</th><th>Emissão</th><th>Destinatário</th><th>Chave</th><th>Total</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id}><td>{d.serie}/{d.numero||'—'}</td><td>{date(d.data_emissao)}</td><td>{d.destinatario_nome||'—'}<small className="table-sub">{d.destinatario_documento||''}</small></td><td><code>{d.chave_acesso||'Não informada'}</code></td><td>{money(d.valor_total)}</td><td><span className={`fiscal-status ${d.status}`}>{d.status}</span></td><td>{d.status==='rascunho'||d.status==='pendente'?<button className="secondary" disabled={busy} onClick={()=>void emit(d)}>Emitir NF-e</button>:<span>—</span>}</td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="empty">Nenhuma nota encontrada.</td></tr>}</tbody></table></div></>}
 {tab==='emitir'&&<div className="fiscal-emit-grid"><div className="panel fiscal-card"><span className="eyebrow">NOVA NF-e</span><h3>Preparar documento</h3><p>Crie o rascunho e depois use “Emitir NF-e”. A Edge Function valida a sessão e somente chama o integrador real quando as credenciais de backend existem.</p><button className="primary" disabled={busy} onClick={()=>void createDraft()}><Plus size={17}/> {busy?'Criando…':'Criar NF-e como rascunho'}</button></div><div className="panel fiscal-card"><ShieldCheck size={34}/><h3>Integração segura</h3><ul><li>JWT obrigatório na Edge Function.</li><li>CORS limitado ao domínio de produção, previews válidas e localhost.</li><li>Token do gateway fica somente no backend.</li><li>Sem protocolo, chave, XML ou DANFE fictícios.</li></ul></div></div>}
 {tab==='config'&&<form className="fiscal-config panel" onSubmit={saveConfig}><span className="eyebrow">PARÂMETROS</span><h3>Configuração fiscal da empresa</h3><div className="form-grid"><label>Ambiente<select value={config.ambiente} onChange={e=>setConfig({...config,ambiente:e.target.value as FiscalConfig['ambiente']})}><option value="homologacao">Homologação</option><option value="producao">Produção</option></select></label><label>Regime tributário<input value={config.regime_tributario} onChange={e=>setConfig({...config,regime_tributario:e.target.value})}/></label><label>Série<input type="number" min="1" value={config.serie_nfe} onChange={e=>setConfig({...config,serie_nfe:Number(e.target.value)})}/></label><label>Próximo número<input type="number" min="1" value={config.proximo_numero_nfe} onChange={e=>setConfig({...config,proximo_numero_nfe:Number(e.target.value)})}/></label></div><div className="notice"><ShieldCheck size={16}/> Certificado digital e token do integrador não são armazenados no navegador. A Edge Function usa secrets server-side.</div><button className="primary" disabled={busy}>Salvar parâmetros</button><p className="fiscal-note"><FileDown size={15}/> XML recebido da contabilidade continua disponível para importação e rastreabilidade.</p></form>}
 {xmlName&&<div className="notice">Último arquivo processado: {xmlName}</div>}</div>
}
