import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

type Row={id:string;codigo:string;processo:string;etapa:string;falha:string;efeito:string;causa:string;controle:string;severidade:number;ocorrencia:number;deteccao:number;rpn:number;acao:string|null;responsavel:string|null;data_limite:string|null;status:string}

export default function FMEAIndustrial(){
 const [rows,setRows]=useState<Row[]>([]),[empresaId,setEmpresaId]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [form,setForm]=useState({codigo:'',processo:'',etapa:'',falha:'',efeito:'',causa:'',controle:'',severidade:1,ocorrencia:1,deteccao:1,acao:'',responsavel:'',data_limite:''})
 async function load(){setLoading(true);setError('');try{const {data,error:e}=await supabase.rpc('erp_current_empresa_id');if(e)throw e;if(!data)throw new Error('Empresa da sessão não identificada.');setEmpresaId(String(data));const r=await supabase.from('erp_fmea').select('*').eq('empresa_id',String(data)).order('rpn',{ascending:false}).order('codigo');if(r.error)throw r.error;setRows((r.data??[]) as Row[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar FMEA.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const stats=useMemo(()=>({total:rows.length,criticos:rows.filter(r=>r.rpn>=200).length,abertos:rows.filter(r=>r.status==='ABERTO').length}),[rows])
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{if(!empresaId)throw new Error('Empresa não identificada.');if(!form.codigo.trim()||!form.processo.trim()||!form.falha.trim())throw new Error('Código, processo e falha são obrigatórios.');const r=await supabase.from('erp_fmea').insert({...form,empresa_id:empresaId,acao:form.acao||null,responsavel:form.responsavel||null,data_limite:form.data_limite||null,status:'ABERTO'}).select('*').single();if(r.error)throw r.error;setRows(x=>[r.data as Row,...x].sort((a,b)=>b.rpn-a.rpn));setForm({codigo:'',processo:'',etapa:'',falha:'',efeito:'',causa:'',controle:'',severidade:1,ocorrencia:1,deteccao:1,acao:'',responsavel:'',data_limite:''});setMessage('FMEA gravado no banco.')}catch(e){setError(e instanceof Error?e.message:'Falha ao gravar FMEA.')}finally{setSaving(false)}}
 return <main className="pcp-page"><header className="pcp-toolbar"><div><span>QUALIDADE • FMEA</span><h1>FMEA de Processo</h1><p>Risco calculado: Severidade × Ocorrência × Detecção.</p></div><button type="button" onClick={()=>void load()} disabled={loading}>Atualizar</button></header><section className="quality-kpis"><article><b>{stats.total}</b><span>FMEAs</span></article><article><b>{stats.criticos}</b><span>RPN ≥ 200</span></article><article><b>{stats.abertos}</b><span>Em aberto</span></article></section>{(error||message)&&<div className={error?'alert error':'alert ok'} role="alert">{error||message}</div>}<section className="industrial-modal" style={{position:'relative',marginBottom:14}}><div className="industrial-modal-head"><strong>Novo risco de processo</strong></div><form onSubmit={save} className="process-form-grid">{([['Código','codigo'],['Processo','processo'],['Etapa','etapa'],['Falha','falha'],['Efeito','efeito'],['Causa','causa'],['Controle atual','controle'],['Ação','acao'],['Responsável','responsavel']] as const).map(([label,key])=><label key={key}><span>{label}</span><input value={form[key]} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/></label>)}<label><span>Data limite</span><input type="date" value={form.data_limite} onChange={e=>setForm(x=>({...x,data_limite:e.target.value}))}/></label>{([['Severidade','severidade'],['Ocorrência','ocorrencia'],['Detecção','deteccao']] as const).map(([label,key])=><label key={key}><span>{label} (1–10)</span><input type="number" min="1" max="10" value={form[key]} onChange={e=>setForm(x=>({...x,[key]:Number(e.target.value)}))}/></label>)}<div><span>RPN calculado</span><strong style={{display:'block',fontSize:24}}>{form.severidade*form.ocorrencia*form.deteccao}</strong></div><button className="secondary-v2" type="submit" disabled={saving}>{saving?'Gravando…':'Gravar FMEA'}</button></form></section><section className="crud-list">{loading?<p>Carregando dados reais…</p>:rows.length===0?<p>Nenhum FMEA cadastrado nesta empresa.</p>:<div style={{overflowX:'auto'}}><table><thead><tr><th>Código</th><th>Processo</th><th>Falha</th><th>S</th><th>O</th><th>D</th><th>RPN</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.codigo}</td><td>{r.processo}</td><td>{r.falha}</td><td>{r.severidade}</td><td>{r.ocorrencia}</td><td>{r.deteccao}</td><td><strong>{r.rpn}</strong></td><td>{r.status}</td></tr>)}</tbody></table></div>}</section></main>
}