import { useEffect, useMemo, useState } from 'react'
import { Plus, RefreshCw, Save, ShieldCheck, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Row={id:string;codigo:string;processo:string;etapa:string;falha:string;efeito:string;causa:string;controle:string;severidade:number;ocorrencia:number;deteccao:number;rpn:number;acao:string|null;responsavel:string|null;data_limite:string|null;status:string}
const blank={codigo:'',processo:'',etapa:'',falha:'',efeito:'',causa:'',controle:'',severidade:'5',ocorrencia:'5',deteccao:'5',acao:'',responsavel:'',data_limite:'',status:'ABERTO'}

export default function FMEAIndustrial(){
 const [rows,setRows]=useState<Row[]>([]),[form,setForm]=useState({...blank}),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState('')
 async function company(){const {data,error}=await supabase.rpc('erp_current_empresa_id');if(error||!data)throw error??new Error('Empresa da sessão não identificada.');return String(data)}
 async function load(){setBusy(true);setError('');try{const id=await company();const r=await supabase.from('erp_fmea').select('*').eq('empresa_id',id).order('rpn',{ascending:false}).limit(1000);if(r.error)throw r.error;setRows((r.data??[]) as Row[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar FMEA.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>rows.filter(x=>!query||[x.codigo,x.processo,x.etapa,x.falha,x.status].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query])
 const stats=useMemo(()=>({total:rows.length,alto:rows.filter(x=>x.rpn>=200).length,aberto:rows.filter(x=>x.status==='ABERTO').length}),[rows])
 async function save(){setBusy(true);setError('');setMessage('');try{const empresa_id=await company();if(!form.codigo.trim()||!form.processo.trim()||!form.falha.trim())throw new Error('Código, processo e modo de falha são obrigatórios.');const r=await supabase.from('erp_fmea').insert({empresa_id,codigo:form.codigo.trim(),processo:form.processo.trim(),etapa:form.etapa.trim(),falha:form.falha.trim(),efeito:form.efeito.trim(),causa:form.causa.trim(),controle:form.controle.trim(),severidade:Number(form.severidade),ocorrencia:Number(form.ocorrencia),deteccao:Number(form.deteccao),acao:form.acao.trim()||null,responsavel:form.responsavel.trim()||null,data_limite:form.data_limite||null,status:form.status}).select('*').single();if(r.error)throw r.error;setMessage('FMEA gravado no banco real.');setShow(false);setForm({...blank});await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível gravar o FMEA.')}finally{setBusy(false)}}
 return <main className="pcp-page" style={{padding:24,maxWidth:1650,margin:'0 auto'}}><header className="pcp-toolbar"><div><span className="v2-eyebrow">QUALIDADE • FMEA</span><h1 style={{margin:'6px 0'}}>FMEA de Processo</h1><p style={{margin:0,color:'#64777d'}}>Falha, efeito, causa, controles, RPN e ações preventivas.</p></div><div style={{display:'flex',gap:8}}><button className="secondary-v2" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Atualizar</button><button className="menu-green" onClick={()=>setShow(true)}><Plus size={16}/> Novo FMEA</button></div></header>
 {(message||error)&&<div className={error?'error':'notice'} style={{margin:'12px 0'}}>{error||message}</div>}
 <section className="quality-kpis"><article><ShieldCheck/><span>Itens FMEA</span><strong>{stats.total}</strong></article><article><span>RPN ≥ 200</span><strong>{stats.alto}</strong></article><article><span>Abertos</span><strong>{stats.aberto}</strong></article></section>
 <section className="crud-list" style={{marginTop:14}}><div className="crud-list-head"><div><strong>Registros FMEA</strong><small>Ordenados pelo RPN para facilitar a análise de risco.</small></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar..." /></div><div className="crud-table-wrap"><table><thead><tr><th>Código</th><th>Processo</th><th>Etapa</th><th>Falha</th><th>S</th><th>O</th><th>D</th><th>RPN</th><th>Status</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.codigo}</td><td>{x.processo}</td><td>{x.etapa||'—'}</td><td>{x.falha}</td><td>{x.severidade}</td><td>{x.ocorrencia}</td><td>{x.deteccao}</td><td><strong>{x.rpn}</strong></td><td>{x.status}</td></tr>)}{!filtered.length&&<tr><td colSpan={9}>Nenhum FMEA cadastrado.</td></tr>}</tbody></table></div></section>
 {show&&<div className="industrial-modal-backdrop"><section className="industrial-modal"><header className="industrial-modal-head"><div><span>QUALIDADE • ANÁLISE DE RISCO</span><h2>Novo FMEA</h2></div><button className="icon-button" onClick={()=>setShow(false)}><X size={18}/></button></header><div className="process-form-grid"><label>Código<input value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/></label><label>Processo<input value={form.processo} onChange={e=>setForm({...form,processo:e.target.value})}/></label><label>Etapa<input value={form.etapa} onChange={e=>setForm({...form,etapa:e.target.value})}/></label><label>Falha<input value={form.falha} onChange={e=>setForm({...form,falha:e.target.value})}/></label><label>Efeito<textarea value={form.efeito} onChange={e=>setForm({...form,efeito:e.target.value})}/></label><label>Causa<textarea value={form.causa} onChange={e=>setForm({...form,causa:e.target.value})}/></label><label>Controle<textarea value={form.controle} onChange={e=>setForm({...form,controle:e.target.value})}/></label><label>Ação<textarea value={form.acao} onChange={e=>setForm({...form,acao:e.target.value})}/></label><label>Responsável<input value={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.value})}/></label><label>Data limite<input type="date" value={form.data_limite} onChange={e=>setForm({...form,data_limite:e.target.value})}/></label><label>Severidade (1–10)<input type="number" min="1" max="10" value={form.severidade} onChange={e=>setForm({...form,severidade:e.target.value})}/></label><label>Ocorrência (1–10)<input type="number" min="1" max="10" value={form.ocorrencia} onChange={e=>setForm({...form,ocorrencia:e.target.value})}/></label><label>Detecção (1–10)<input type="number" min="1" max="10" value={form.deteccao} onChange={e=>setForm({...form,deteccao:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ABERTO</option><option>EM_TRATAMENTO</option><option>CONCLUIDO</option></select></label></div><footer style={{display:'flex',justifyContent:'flex-end',gap:8}}><button className="secondary-v2" onClick={()=>setShow(false)}>Cancelar</button><button className="menu-green" disabled={busy} onClick={()=>void save()}><Save size={16}/> Salvar</button></footer></section></div>}</main>
}