/*
📝 IDENTIFICAÇÃO DE LEITURA E REVISÃO DE CÓDIGO:
- Arquivo: src/pages/FornecedoresIndustrial.tsx
- Status Atual: Revisão 3 (Compras e Qualificação de Fornecedores)
- Total de Linhas Gerado: 32
- Assinatura de Entrada (Primeiros 3 Imports): import { ChangeEvent, FormEvent, useEffect, useState } from 'react' | import { Check, Download, FileCheck2, Pencil, Plus, Printer, RefreshCw, Search, ShieldCheck, Star, Trash2, Upload, X } from 'lucide-react' | import { supabase } from '../lib/supabaseClient'
- Regra de Negócio Incorporada: Cadastro real de fornecedor, certificado ISO 9001 em Storage privado, validade e qualificação visual por estrela.
*/
import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import { Check, Download, FileCheck2, Pencil, Plus, Search, ShieldCheck, Star, Upload, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Supplier={id:string;codigo:string|null;razao_social:string;nome_fantasia:string|null;documento:string|null;email:string|null;telefone:string|null;cidade:string|null;estado:string|null;contato:string|null;ativo:boolean;iso_9001_certificado:boolean;iso_certificado_nome:string|null;iso_certificado_path:string|null;iso_certificado_validade:string|null;iso_certificado_numero:string|null;observacoes:string|null}
type Form={codigo:string;razao_social:string;nome_fantasia:string;documento:string;email:string;telefone:string;cidade:string;estado:string;contato:string;iso_9001_certificado:boolean;iso_certificado_validade:string;iso_certificado_numero:string;observacoes:string}
const empty:Form={codigo:'',razao_social:'',nome_fantasia:'',documento:'',email:'',telefone:'',cidade:'',estado:'',contato:'',iso_9001_certificado:false,iso_certificado_validade:'',iso_certificado_numero:'',observacoes:''}
const input:React.CSSProperties={width:'100%',minHeight:42,border:'1px solid #cbd5e1',borderRadius:10,padding:'0 11px',boxSizing:'border-box',background:'#fff',color:'#111827'}
const label:React.CSSProperties={display:'grid',gap:6,fontSize:12,fontWeight:800,color:'#334155'}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:20,boxShadow:'0 8px 28px rgba(15,23,42,.05)'}
const today=()=>new Date().toISOString().slice(0,10)
const digits=(value:string)=>value.replace(/\D/g,'')
const formatCnpj=(value:string)=>{const d=digits(value).slice(0,14);if(d.length<=2)return d;if(d.length<=5)return `${d.slice(0,2)}.${d.slice(2)}`;if(d.length<=8)return `${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5)}`;if(d.length<=12)return `${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8)}`;return `${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`}
function isoValido(s:Supplier){return s.iso_9001_certificado&&(!s.iso_certificado_validade||s.iso_certificado_validade>=today())}
export default function FornecedoresIndustrial(){
 const [empresaId,setEmpresaId]=useState(''),[rows,setRows]=useState<Supplier[]>([]),[query,setQuery]=useState(''),[editing,setEditing]=useState<string|null>(null),[show,setShow]=useState(false),[form,setForm]=useState<Form>(empty),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const {data:empresa,error:ee}=await supabase.rpc('erp_current_empresa_id');if(ee||!empresa)throw ee??new Error('Empresa da sessão não identificada.');const id=String(empresa);setEmpresaId(id);const {data,error:e}=await supabase.from('erp_fornecedores').select('*').eq('empresa_id',id).order('razao_social').limit(1000);if(e)throw e;setRows((data??[]) as Supplier[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar fornecedores.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const filtered=rows.filter(r=>{const q=query.trim().toLowerCase();return !q||`${r.razao_social} ${r.nome_fantasia??''} ${r.documento??''} ${r.codigo??''}`.toLowerCase().includes(q)})
 const openNew=()=>{setEditing(null);setForm(empty);setFile(null);setShow(true);setMessage('');setError('')}
 const edit=(r:Supplier)=>{setEditing(r.id);setForm({codigo:r.codigo??'',razao_social:r.razao_social,nome_fantasia:r.nome_fantasia??'',documento:r.documento??'',email:r.email??'',telefone:r.telefone??'',cidade:r.cidade??'',estado:r.estado??'',contato:r.contato??'',iso_9001_certificado:r.iso_9001_certificado,iso_certificado_validade:r.iso_certificado_validade??'',iso_certificado_numero:r.iso_certificado_numero??'',observacoes:r.observacoes??''});setFile(null);setShow(true);setMessage('');setError('')}
 const save=async(e:FormEvent)=>{e.preventDefault();if(!empresaId)return;setBusy(true);setError('');setMessage('');try{if(!form.razao_social.trim())throw new Error('Informe a razão social.');const cnpj=digits(form.documento);if(cnpj&&cnpj.length!==14)throw new Error('CNPJ deve conter 14 dígitos.');if(form.iso_9001_certificado&&!file&&!editing)throw new Error('Anexe o certificado ISO 9001.');let id=editing;const payload={empresa_id:empresaId,codigo:form.codigo.trim()||null,razao_social:form.razao_social.trim(),nome_fantasia:form.nome_fantasia.trim()||null,documento:cnpj||null,email:form.email.trim()||null,telefone:form.telefone.trim()||null,cidade:form.cidade.trim()||null,estado:form.estado.trim().toUpperCase()||null,contato:form.contato.trim()||null,iso_9001_certificado:form.iso_9001_certificado,iso_certificado_validade:form.iso_certificado_validade||null,iso_certificado_numero:form.iso_certificado_numero.trim()||null,observacoes:form.observacoes.trim()||null,updated_at:new Date().toISOString()};if(id){const {error:e}=await supabase.from('erp_fornecedores').update(payload).eq('id',id).eq('empresa_id',empresaId);if(e)throw e}else{const {data,error:e}=await supabase.from('erp_fornecedores').insert(payload).select('id').single();if(e||!data)throw e??new Error('Fornecedor não retornado pelo banco.');id=data.id}
 if(file){const safe=file.name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${empresaId}/${id}/iso-9001-${Date.now()}-${safe}`;const upload=await supabase.storage.from('erp-fornecedor-certificados').upload(path,file,{upsert:true,contentType:file.type||'application/octet-stream'});if(upload.error)throw upload.error;const {error:e}=await supabase.from('erp_fornecedores').update({iso_certificado_nome:file.name,iso_certificado_path:path,iso_9001_certificado:true,updated_at:new Date().toISOString()}).eq('id',id).eq('empresa_id',empresaId);if(e)throw e}
 setShow(false);setMessage(editing?'Fornecedor atualizado.':'Fornecedor cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o fornecedor.')}finally{setBusy(false)}}
 const download=async(path:string|null)=>{if(!path)return;const {data,error:e}=await supabase.storage.from('erp-fornecedor-certificados').createSignedUrl(path,300);if(e)throw e;window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 const remove=async(r:Supplier)=>{if(!window.confirm(`Excluir o fornecedor ${r.razao_social}?`))return;setBusy(true);try{const {error:e}=await supabase.from('erp_fornecedores').delete().eq('id',r.id).eq('empresa_id',empresaId);if(e)throw e;setMessage('Fornecedor excluído.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir o fornecedor.')}finally{setBusy(false)}}
 const print=()=>window.print()
 return (
  <main style={{minHeight:'100vh',background:'#FAFAFA',color:'#111827',padding:24,boxSizing:'border-box'}}>
    <div style={{maxWidth:1500,margin:'0 auto'}}>
      <header className="supplier-page-head"><div><span className="industrial-eyebrow">COMPRAS • CADASTRO MESTRE</span><h1>Fornecedores</h1><p>Cadastro, CNPJ, contatos, qualificação ISO 9001 e documentos.</p></div><div className="supplier-actions"><button className="industrial-secondary" type="button" onClick={()=>void load()}><RefreshCw size={18}/> Atualizar</button><button className="industrial-secondary" type="button" onClick={print}><Printer size={18}/> Imprimir lista</button><button className="industrial-primary" type="button" onClick={openNew}><Plus size={18}/> Novo fornecedor</button></div></header>
      {(message||error)&&<div style={{marginBottom:16,color:error?'#b91c1c':'#047857'}}>{error||message}</div>}
      <section style={card}><div className="supplier-toolbar"><div className="supplier-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar por fornecedor, CNPJ ou código" style={{...input,border:0,boxShadow:'none'}}/></div><span className="supplier-count">{filtered.length} fornecedor(es)</span></div><div style={{overflowX:'auto',marginTop:16}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Qualificação','Código','Fornecedor','CNPJ','Certificado','Validade','Ações'].map(h=><th key={h} style={{textAlign:'left',padding:12}}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td style={{padding:12}}>{isoValido(r)?<span style={{color:'#eab308'}}><Star size={18} fill="currentColor"/> ISO 9001</span>:'Sem certificação'}</td><td style={{padding:12}}>{r.codigo||'—'}</td><td style={{padding:12}}>{r.razao_social}</td><td style={{padding:12}}>{r.documento||'—'}</td><td style={{padding:12}}>{r.iso_certificado_path?<button onClick={()=>void download(r.iso_certificado_path).catch(e=>setError(e instanceof Error?e.message:'Falha ao abrir certificado.'))}><Download size={15}/> Abrir</button>:'Não anexado'}</td><td style={{padding:12}}>{r.iso_certificado_validade||'—'}</td><td style={{padding:12}}><div className="supplier-row-actions"><button className="industrial-secondary" type="button" onClick={()=>edit(r)} title="Editar"><Pencil size={16}/> Editar</button><button className="supplier-danger" type="button" onClick={()=>void remove(r)} title="Excluir"><Trash2 size={16}/> Excluir</button></div></td></tr>)}</tbody></table></div></section>
    </div>
    {show&&<div style={{position:'fixed',inset:0,zIndex:30,background:'rgba(15,23,42,.55)',display:'grid',placeItems:'center',padding:20}}><form onSubmit={save} style={{...card,width:'min(900px,100%)',maxHeight:'92vh',overflow:'auto'}}><header style={{display:'flex',justifyContent:'space-between'}}><h2>{editing?'Editar':'Novo'} fornecedor</h2><button type="button" onClick={()=>setShow(false)}><X/></button></header><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12}}><label style={label}>Código<input style={input} value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/></label><label style={label}>Razão social *<input style={input} value={form.razao_social} onChange={e=>setForm({...form,razao_social:e.target.value})}/></label><label style={label}>CNPJ *<input style={input} inputMode="numeric" maxLength={18} value={formatCnpj(form.documento)} onChange={e=>setForm({...form,documento:digits(e.target.value).slice(0,14)})} placeholder="00.000.000/0000-00"/></label><label style={label}>Cidade<input style={input} value={form.cidade} onChange={e=>setForm({...form,cidade:e.target.value})}/></label><label style={label}>UF<input style={input} value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}/></label><label style={label}>ISO 9001<input type="checkbox" checked={form.iso_9001_certificado} onChange={e=>setForm({...form,iso_9001_certificado:e.target.checked})}/></label><label style={label}>Validade<input type="date" style={input} value={form.iso_certificado_validade} onChange={e=>setForm({...form,iso_certificado_validade:e.target.value})}/></label><label style={label}>Certificado<input type="file" accept=".pdf,image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]??null)}/></label></div><footer className="supplier-modal-foot"><button className="industrial-secondary" type="button" onClick={()=>setShow(false)}>Cancelar</button><button className="industrial-primary" disabled={busy} type="submit"><Check size={17}/> {editing?'Salvar alterações':'Gravar fornecedor'}</button></footer></form></div>}
  </main>
)
}
<style>{`
.supplier-page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:20px}.supplier-page-head h1{margin:5px 0;font-size:36px;letter-spacing:-.03em;color:#17333F}.supplier-page-head p{margin:0;color:#536B76;font-size:17px}.supplier-actions{display:flex;gap:8px;flex-wrap:wrap}.supplier-toolbar{display:flex;align-items:center;gap:14px}.supplier-search{display:flex;align-items:center;gap:8px;flex:1;border:1px solid #b9d2da;border-radius:10px;background:#fff;padding-left:12px}.supplier-count{font-weight:800;color:#536B76;white-space:nowrap}.supplier-row-actions{display:flex;gap:6px;flex-wrap:wrap}.supplier-danger{display:inline-flex;align-items:center;gap:6px;min-height:44px;border:1px solid #e1b5b8;border-radius:10px;background:#fff5f5;color:#a12d35;padding:0 11px;font-weight:800}.supplier-modal-foot{display:flex;justify-content:flex-end;gap:8px;margin-top:18px;padding-top:16px;border-top:1px solid #dceaf0}@media(max-width:900px){.supplier-page-head{flex-direction:column}.supplier-actions{width:100%}.supplier-actions>*{flex:1}.supplier-toolbar{flex-direction:column;align-items:stretch}.supplier-count{align-self:flex-start}}
`}</style>
/* Revisão 4 — cadastro mestre industrial. */