import React from 'react'
import { useMemo } from 'react'
import { BookOpen, Boxes, CheckCircle2, FileText, Factory, HelpCircle, KeyRound, Package, ShieldCheck, ShoppingCart, Wrench } from 'lucide-react'

const sections = [
  { id:'login', title:'Login e acesso', icon:KeyRound, intro:'Acesso seguro por empresa, usuário/e-mail e senha.', items:['Instalar no Computador: instala o ERP como aplicativo quando o navegador oferecer o recurso PWA.','Acessar sistema: valida empresa, usuário, senha, sessão Supabase e vínculo ativo antes de liberar o ERP.','Esqueci minha senha: envia o fluxo oficial de recuperação do Supabase para o e-mail informado.','Cadastrar nova empresa: abre o cadastro da empresa para iniciar o processo comercial.'] },
  { id:'pcp', title:'PCP Industrial', icon:Factory, intro:'Cockpit de produção com programação, prensa, lados, operadores, moldes, setup e apontamento.', items:['Lado A e Lado B: representam posições operacionais independentes da prensa e permitem operadores distintos.','Operadores simultâneos: cada lado pode receber seu operador responsável sem misturar os apontamentos.','Troca de molde / Setup: registre a mudança como etapa de preparação antes da nova programação.','Planejado x Real: compare horários e quantidades programadas com os apontamentos reais.','Paradas OEE: registre motivo e duração para separar disponibilidade, produção e perdas.','Finalizar produção: grava o apontamento pela operação transacional do banco; conflitos e regras são devolvidos ao usuário.'] },
  { id:'vendas', title:'Produtos, vendas e estoque', icon:ShoppingCart, intro:'Cadastro mestre, estoque e fechamento transacional.', items:['Novo produto: cadastra código, descrição, unidade, custos, preço e estoque inicial.','Pesquisar: filtra código, nome e tipo sem alterar os dados do banco.','Editar: atualiza o cadastro existente.','Excluir: deve ser entendido como inativação lógica quando houver histórico; o produto permanece preservado para rastreabilidade.','Frente de Venda: selecione somente produtos ativos com saldo disponível.','Estoque insuficiente: a interface bloqueia a inclusão acima do saldo e a RPC segura do banco permanece como segunda barreira.','Finalizar venda: chama a operação transacional que registra a venda e atualiza o estoque.'] },
  { id:'qualidade', title:'Qualidade / SGQ', icon:ShieldCheck, intro:'Controle de não conformidade, documentos e rastreabilidade.', items:['RPNC: abra o relatório registrando produto, lote, evidência, causa, contenção e ação.','Assinatura eletrônica: a assinatura do inspetor identifica a aprovação da etapa no fluxo controlado.','Documentos: utilize revisão, aprovação e anexos para manter a versão válida do procedimento.','Relatório técnico: gere a saída a partir dos dados reais registrados, sem números fictícios.'] },
  { id:'fiscal', title:'Fiscal / NF-e', icon:FileText, intro:'Acompanhamento da emissão fiscal e documentos armazenados.', items:['Emitir NF-e: envia somente a venda finalizada e os dados fiscais necessários para a Edge Function configurada.','Aguardando: transmissão/processamento ainda não concluído.','Autorizada: a SEFAZ confirmou a nota e o protocolo/chave podem ser apresentados quando disponíveis.','Rejeitada: a nota precisa ser corrigida conforme a mensagem retornada pela SEFAZ.','XML e DANFE: os botões devem abrir os arquivos efetivamente existentes no Storage; nunca apresentar arquivo fictício.'] },
]

function Mockup({ title, children }: { title:string; children:React.ReactNode }) { return <div className="manual-mockup"><div className="manual-window"><span/><span/><span/><b>{title}</b></div><div className="manual-screen">{children}</div></div> }

export default function ManualUsuario(){
 const cards = useMemo(()=>sections,[ ])
 return <main className="manual-page">
  <header className="manual-hero"><div><span className="manual-eyebrow">SGQ ERP • MANUAL OPERACIONAL</span><h1>Manual do Usuário</h1><p>Guia visual dos principais módulos, botões e fluxos do ERP Industrial.</p></div><div className="manual-badge"><BookOpen size={22}/> Operação segura</div></header>
  <div className="manual-grid">{cards.map(({id,title,icon:Icon,intro,items})=><section id={id} className="manual-section" key={id}><div className="manual-section-head"><div className="manual-icon"><Icon size={22}/></div><div><h2>{title}</h2><p>{intro}</p></div></div><Mockup title={title}><div className="manual-toolbar"><span className="manual-skeleton"/><span className="manual-skeleton short"/><span className="manual-button">Ação principal</span></div><div className="manual-panels"><div className="manual-panel"><strong>Área de trabalho</strong><span/><span/><span/></div><div className="manual-panel"><strong>Indicadores</strong><span/><span className="short"/></div></div></Mockup><div className="manual-actions">{items.map((text,i)=><article key={text}><div className="manual-number">{i+1}</div><div><strong>{text.split(':')[0]}</strong>{text.includes(':')?<p>{text.slice(text.indexOf(':')+1).trim()}</p>:null}</div></article>)}</div></section>)}</div>
  <footer className="manual-footer"><HelpCircle size={18}/> Em caso de erro, preserve a mensagem exibida na tela para a equipe de suporte. O manual descreve o comportamento esperado; os dados exibidos sempre devem vir do banco real.</footer>
 </main>
}
