import {useMemo,useState} from 'react'
import {BookOpen,CheckCircle2,Factory,FileText,HelpCircle,KeyRound,Package,Search,ShieldCheck,ShoppingCart,ArrowRight} from 'lucide-react'

type Section={id:string;title:string;icon:typeof BookOpen;intro:string;route:string;steps:string[]}
const sections:Section[]=[
 {id:'login',title:'Login e acesso',icon:KeyRound,intro:'Acesso seguro por Supabase Auth, empresa, usuário e perfil.',route:'/login',steps:['Entre com o usuário real da empresa.','Aguarde a validação da sessão e do vínculo com a empresa.','Se houver erro, preserve a mensagem exibida; não use senha de demonstração.']},
 {id:'pedidos',title:'Pedidos Pendentes',icon:ShoppingCart,intro:'Entrada do pedido no topo e lista operacional abaixo, com ligação ao estoque e à produção.',route:'/pedidos-vendas',steps:['Preencha cliente, Pedido Cliente, entrada, entrega e itens.','Pesquise produto por código/descrição em vez de abrir milhares de opções.','Grave o pedido e confirme o retorno do banco. Depois use Gerar OP ou Enviar PCP conforme o status.']},
 {id:'pcp',title:'PCP Industrial',icon:Factory,intro:'Planejamento, programação, máquinas, operações, setup, produção e apontamento.',route:'/pcp',steps:['Comece pelo pedido/OP pendente.','Confira ficha, matéria-prima, máquina, operação, sequência, setup e ciclo.','Registre o apontamento real; a produção deve atualizar OP, qualidade e estoque conforme as regras transacionais.']},
 {id:'produtos',title:'Produtos e estoque',icon:Package,intro:'Cadastro mestre, saldo, lote, reserva e movimentação.',route:'/produtos-vendas',steps:['Pesquise por código ou descrição.','Confirme unidade, estoque e dados fiscais antes de movimentar.','Use a tela de estoque para entradas, saídas, transferências, reservas e inventário.']},
 {id:'qualidade',title:'Qualidade / SGQ',icon:ShieldCheck,intro:'Inspeção, RPNC, documentos, PPAP/RIA/PSW, calibração e rastreabilidade.',route:'/qualidade',steps:['Abra o registro pelo produto, OP, lote ou documento relacionado.','Preencha evidências, características e responsáveis; não invente medições.','Finalize somente depois que o retorno do banco confirmar a gravação.']},
 {id:'documentos',title:'Documentos da Qualidade',icon:FileText,intro:'Lista de documentos, visualizador, anexos, obsoletos e configuração/revisão.',route:'/qualidade/documentos',steps:['Pesquise e selecione o documento na lista.','Use o visualizador para consultar e Configurar Documento para revisar.','Anexos e histórico devem permanecer vinculados à versão real.']},
 {id:'fiscal',title:'Fiscal / NF-e',icon:FileText,intro:'Documentos fiscais, itens, impostos, liberação e DANFE.',route:'/fiscal',steps:['Confira pedido, destinatário e dados fiscais antes da emissão.','Use a emissão NF-e somente com os campos que o banco suporta.','XML/DANFE só podem ser apresentados quando o arquivo real existir.']},
]
export default function ManualUsuario(){
 const [query,setQuery]=useState('')
 const filtered=useMemo(()=>sections.filter(s=>(s.title+' '+s.intro+' '+s.steps.join(' ')).toLowerCase().includes(query.toLowerCase())),[query])
 return <main className="manual-page">
  <header className="manual-hero"><div><span className="manual-eyebrow">SGQ ERP • MANUAL OPERACIONAL</span><h1>Manual do Usuário</h1><p>Ajuda prática para operar as telas reais do ERP sem depender de menus escondidos.</p></div><div className="manual-badge"><BookOpen size={22}/> Ajuda operacional</div></header>
  <section className="manual-helpbar"><div><HelpCircle size={20}/><div><strong>Precisa de ajuda para preencher uma tela?</strong><span>Pesquise abaixo pelo módulo ou pela tarefa.</span></div></div><label className="manual-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: pedido, OP, estoque, RPNC, NF-e..."/></label></section>
  <div className="manual-grid">{filtered.map(s=>{const Icon=s.icon;return <section id={s.id} className="manual-section" key={s.id}><div className="manual-section-head"><div className="manual-icon"><Icon size={22}/></div><div><h2>{s.title}</h2><p>{s.intro}</p></div><a href={s.route} className="manual-open">Abrir tela <ArrowRight size={15}/></a></div><div className="manual-actions">{s.steps.map((step,i)=><article key={step}><div className="manual-number">{i+1}</div><div><strong>Passo {i+1}</strong><p>{step}</p></div></article>)}</div><div className="manual-real"><CheckCircle2 size={16}/> Regra: só considerar concluído depois de confirmar persistência e resultado na tela.</div></section>})}</div>
  {filtered.length===0&&<section className="manual-empty"><Search size={22}/><strong>Nenhum tópico encontrado.</strong><span>Tente “pedido”, “PCP”, “estoque”, “qualidade” ou “NF-e”.</span></section>}
  <footer className="manual-footer"><HelpCircle size={18}/> O botão AJUDA do cabeçalho abre este manual. Para suporte, preserve a mensagem técnica e a rota em que ocorreu o problema.</footer>
 </main>
}
