import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft, Plus, RefreshCw, Save, Wrench, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import { fetchAllPages } from '../lib/supabasePagination'
type Asset={id:string;codigo:string;nome:string;status:string;tipo:string|null}
type WO={id:string;ativo_id:string;tipo:string;descricao:string;prioridade:string;status:string;data_prevista:string|null}
const blank={ativo_id:'',tipo:'PREVENTIVA',descricao:'',prioridade:'MEDIA',status:'ABERTA',data_prevista:''}
const PAGE_SIZE=25
export default function ManutencaoIndustrial(){
 const[a,setA]=useState<Asset[]>([]),[w,setW]=useState<WO[]>([]),[form,setForm]=useState({...blank}),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[page,setPage]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const company=await supabase.rpc('erp_current_empresa_id');if(company.error||!company.data)throw company.error??new Error('Empresa da sessão não identificada.');const empresa_id=String(company.data);const[x,y]=await Promise.all([fetchAllPages<Asset>((from,to)=>supabase.from('erp_maquinas').select('id,codigo,nome,status,tipo',{count:'exact'}).eq('empresa_id',empresa_id).order('codigo').range(from,to)),fetchAllPages<WO>((from,to)=>supabase.from('erp_manutencao_ordens').select('id,ativo_id,tipo,descricao,prioridade,status,data_prevista',{count:'exact'}).eq('empresa_id',empresa_id).order('data_prevista',{ascending:true}).range(from,to))]);setA(x);setW(y)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar manutenção.')}finally{setBusy(false)}}
useEffect(()=>{void load()},[])
 const pageCount=Math.max(1,Math.ceil(w.length/PAGE_SIZE))
 const visibleOrders=w.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE)
 useEffect(()=>{setPage(current=>Math.min(current,pageCount-1))},[pageCount])
const name=(id:string)=>a.find(x=>x.id===id)?.codigo||id
const stats=useMemo(()=>({open:w.filter(x=>!['CONCLUIDA','CANCELADA'].includes(x.status)).length,prev:w.filter(x=>x.tipo==='PREVENTIVA'&&x.status!=='CONCLUIDA').length,crit:w.filter(x=>x.prioridade==='ALTA'&&x.status!=='CONCLUIDA').length,assets:a.length}),[w,a])
const save=async()=>{if(!form.ativo_id||!form.descricao.trim()){setError('Ativo e descrição são obrigatórios.');return}setBusy(true);setError('');try{const company=await supabase.rpc('erp_current_empresa_id');if(company.error||!company.data)throw company.error??new Error('Empresa da sessão não identificada.');const r=await supabase.from('erp_manutencao_ordens').insert({...form,empresa_id:String(company.data)});if(r.error)throw r.error;setMessage('Ordem de manutenção criada no banco real.');setShow(false);setForm({...blank});await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a ordem.')}finally{setBusy(false)}}
return <main className="pcp-page" style={{padding:24,maxWidth:1650,margin:'0 auto'}}>
 <header className="pcp-toolbar"><div><button type="button" className="secondary-v2" onClick={()=>location.href='/erp-industrial'}><ArrowLeft size={17}/> Voltar</button><span className="v2-eyebrow">MANUTENÇÃO • ATIVOS</span><h1 style={{margin:'6px 0'}}>Manutenção Industrial</h1><p style={{margin:0,color:'#64777d'}}>Ativos, ordens preventivas e corretivas, prioridade e programação.</p></div><button type="button" className="menu-green" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Atualizar</button></header>
 {(message||error)&&<div role={error?'alert':'status'} className={error?'error':'notice'} style={{margin:'12px 0'}}>{error||message}</div>}
 <section className="quality-kpis"><article><Wrench/><span>Ativos</span><strong>{stats.assets}</strong></article><article><span>Ordens abertas</span><strong>{stats.open}</strong></article><article><span>Preventivas pendentes</span><strong>{stats.prev}</strong></article><article><span>Prioridade alta</span><strong>{stats.crit}</strong></article></section>
 <section className="crud-list" style={{marginTop:14}}><div className="crud-list-head"><div><strong>Ordens de manutenção</strong><small>Preventiva e corretiva vinculadas às máquinas cadastradas.</small></div><button type="button" className="menu-green" onClick={()=>{setForm({...blank,ativo_id:a[0]?.id||''});setShow(true)}}><Plus size={16}/> Nova ordem</button></div>
  <div className="crud-table-wrap"><table><thead><tr><th>Ativo</th><th>Tipo</th><th>Descrição</th><th>Prioridade</th><th>Prevista</th><th>Status</th></tr></thead><tbody>{visibleOrders.map(x=><tr key={x.id}><td>{name(x.ativo_id)}</td><td>{x.tipo}</td><td>{x.descricao}</td><td>{x.prioridade}</td><td>{x.data_prevista||'—'}</td><td>{x.status}</td></tr>)}{!w.length&&<tr><td colSpan={6}>Nenhuma ordem de manutenção.</td></tr>}</tbody></table></div>
  <nav aria-label="Paginação das ordens preventivas" className="flex items-center justify-between gap-3 border-t border-slate-200 p-3 text-sm"><span>{w.length} ordem(ns) · página {page+1} de {pageCount}</span><div className="flex gap-2"><button type="button" disabled={page===0} onClick={()=>setPage(current=>Math.max(0,current-1))} className="min-h-10 rounded border border-slate-300 px-3 font-bold disabled:opacity-50">Anterior</button><button type="button" disabled={page+1>=pageCount} onClick={()=>setPage(current=>Math.min(pageCount-1,current+1))} className="min-h-10 rounded border border-slate-300 px-3 font-bold disabled:opacity-50">Próxima</button></div></nav>
 </section>
 {show&&<div className="industrial-modal-backdrop" role="presentation"><section className="industrial-modal" role="dialog" aria-modal="true" aria-labelledby="maintenance-form-title"><header className="industrial-modal-head"><div><span>MANUTENÇÃO • ORDEM</span><h2 id="maintenance-form-title">Nova ordem</h2></div><button type="button" aria-label="Fechar formulário" className="icon-button" onClick={()=>setShow(false)}><X size={18}/></button></header><div className="process-form-grid"><label>Ativo<select value={form.ativo_id} onChange={e=>setForm({...form,ativo_id:e.target.value})}>{a.map(x=><option key={x.id} value={x.id}>{x.codigo} • {x.nome}</option>)}</select></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>PREVENTIVA</option><option>CORRETIVA</option><option>PREDITIVA</option></select></label><label>Prioridade<select value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}><option>BAIXA</option><option>MEDIA</option><option>ALTA</option><option>CRITICA</option></select></label><label>Data prevista<input type="date" value={form.data_prevista} onChange={e=>setForm({...form,data_prevista:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Descrição<textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label></div><footer style={{display:'flex',justifyContent:'flex-end',gap:8}}><button type="button" className="secondary-v2" onClick={()=>setShow(false)}>Cancelar</button><button type="button" className="menu-green" disabled={busy} onClick={()=>void save()}><Save size={16}/> Salvar</button></footer></section></div>}
</main>
}