import { ArrowLeft, ArrowRight, BarChart3, Boxes, ClipboardCheck, Factory, FileText, PackageCheck, Receipt, ShieldCheck, Truck, Users, Wrench } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

type ModuleInfo={title:string;eyebrow:string;description:string;functionality:string[];flow:string[];indicators:string[];integrations:string[];route:string;Icon:LucideIcon}
const modules:Record<string,ModuleInfo>={
 pcp:{title:'PCP e Produção',eyebrow:'PLANEJAMENTO E CHÃO DE FÁBRICA',description:'Planeje ordens, capacidade, sequenciamento e acompanhamento da produção em um fluxo único.',functionality:['Ordens de produção e programação','Máquinas, moldes, operadores e recursos','Apontamentos, paradas, setup e perdas','Finalização, lotes e rastreabilidade'],flow:['Planejamento','Programação','Produção','Apontamento','Qualidade','Fechamento'],indicators:['Produção realizada','Perdas e paradas','Eficiência operacional','OEE'],integrations:['Engenharia','MRP','Estoque','Qualidade'],route:'/pcp',Icon:Factory},
 estoque:{title:'Estoque e Materiais',eyebrow:'MATERIAIS E RASTREABILIDADE',description:'Controle saldos, movimentações, necessidades e rastreabilidade dos materiais usados pela operação.',functionality:['Cadastro e consulta de itens','Entradas, saídas e ajustes','Saldos por empresa e localização','Rastreabilidade e integração com produção'],flow:['Necessidade','Entrada','Armazenagem','Consumo','Saldo','Inventário'],indicators:['Saldo disponível','Itens críticos','Movimentações','Giro de estoque'],integrations:['PCP','Recebimento','Compras','Indicadores'],route:'/produtos-vendas',Icon:Boxes},
 recebimento:{title:'Recebimento de Materiais',eyebrow:'ENTRADA DE MATERIAIS',description:'Centralize o recebimento, conferência fiscal e distribuição dos itens por lote.',functionality:['Importação e conferência de NF-e XML','Conferência de itens e quantidades','Distribuição por múltiplos lotes','Registro do recebimento para estoque'],flow:['NF-e','Conferência','Lotes','Recebimento','Estoque','Rastreabilidade'],indicators:['Recebimentos pendentes','Divergências','Itens recebidos','Lotes gerados'],integrations:['Estoque','Fiscal','Fornecedores','Rastreabilidade'],route:'/recebimento-materiais',Icon:PackageCheck},
 qualidade:{title:'Qualidade',eyebrow:'SGQ E CONFORMIDADE',description:'Gerencie inspeções, não conformidades, auditorias, ações e documentos mantendo evidências.',functionality:['RPNC e não conformidades','Auditorias e evidências','Ações corretivas e CAPA','Documentos e procedimentos controlados'],flow:['Ocorrência','Análise','Risco','Ação','Evidência','Verificação'],indicators:['RPN aberto','Não conformidades','Ações vencidas','Auditorias'],integrations:['Produção','Documentos','Auditorias','Indicadores'],route:'/qualidade',Icon:ClipboardCheck},
 manutencao:{title:'Manutenção',eyebrow:'ATIVOS E CONFIABILIDADE',description:'Organize manutenção preventiva e corretiva, equipamentos, intervenções e histórico operacional.',functionality:['Cadastro e controle de ativos','Manutenção preventiva e corretiva','Ordens e histórico de intervenções','Integração com máquinas e operação'],flow:['Ativo','Plano','Ordem','Execução','Apontamento','Histórico'],indicators:['Ordens abertas','Preventivas pendentes','Paradas','Disponibilidade'],integrations:['Máquinas','PCP','Produção','Indicadores'],route:'/operacao-industrial',Icon:Wrench},
 fiscal:{title:'Financeiro e Fiscal',eyebrow:'CONTROLE FINANCEIRO E FISCAL',description:'Conecte os reflexos financeiros e fiscais das operações realizadas no ERP.',functionality:['Processos e documentos fiscais','Previsão e acompanhamento financeiro','Integração dos eventos da operação','Consultas e indicadores gerenciais'],flow:['Operação','Documento','Fiscal','Financeiro','Conciliação','Indicador'],indicators:['Valores processados','Pendências fiscais','Previsões','Movimentações'],integrations:['Recebimento','Vendas','Financeiro','Relatórios'],route:'/fiscal',Icon:Receipt},
 indicadores:{title:'Indicadores',eyebrow:'GESTÃO E PERFORMANCE',description:'Transforme os dados dos módulos em indicadores para acompanhamento da fábrica.',functionality:['Indicadores de produção e PCP','Qualidade e não conformidades','Estoque e materiais','Desempenho operacional e gestão'],flow:['Dados','Consolidação','Indicador','Análise','Ação','Resultado'],indicators:['Produção','Qualidade','Estoque','Performance'],integrations:['Todos os módulos','Dashboards','Relatórios','Gestão'],route:'/erp-industrial',Icon:BarChart3},
 engenharia:{title:'Engenharia e BOM',eyebrow:'PRODUTO E PROCESSO',description:'Estruture fichas técnicas, versões, componentes e roteiros para fabricar com padrão.',functionality:['Estruturas e listas de materiais','Versões e revisões','Fichas técnicas','Roteiros de fabricação'],flow:['Produto','BOM','Versão','Roteiro','Liberação','Produção'],indicators:['BOMs ativas','Revisões','Produtos liberados','Pendências'],integrations:['PCP','MRP','Produtos','Qualidade'],route:'/produtos-vendas',Icon:FileText},
 compras:{title:'Compras e Fornecedores',eyebrow:'SUPRIMENTOS',description:'Organize solicitações, fornecedores, pedidos, aprovações e recebimentos.',functionality:['Solicitações de compra','Pedidos e aprovações','Cadastro de fornecedores','Acompanhamento de entrega'],flow:['Necessidade','Cotação','Pedido','Aprovação','Recebimento','Conferência'],indicators:['Pedidos abertos','Atrasos','Compras do período','Fornecedores'],integrations:['MRP','Estoque','Recebimento','Financeiro'],route:'/compras-solicitacao',Icon:Truck},
 clientes:{title:'Clientes',eyebrow:'COMERCIAL',description:'Centralize clientes, contatos, documentos, histórico e relacionamento industrial.',functionality:['Cadastro de clientes','Contatos e documentos','Histórico comercial','Consultas por empresa'],flow:['Cadastro','Contato','Pedido','Produção','Expedição','Histórico'],indicators:['Clientes ativos','Novos clientes','Pedidos','Recorrência'],integrations:['Produtos','Vendas','Fiscal','Expedição'],route:'/produtos-vendas',Icon:Users},
 rastreabilidade:{title:'Rastreabilidade',eyebrow:'LOTE A LOTE',description:'Acompanhe a cadeia da matéria-prima até o produto acabado e a expedição.',functionality:['Lotes de matéria-prima','Vínculo com ordens de produção','Produto acabado e lotes','Histórico de expedição'],flow:['Matéria-prima','Lote','OP','Produto','Inspeção','Expedição'],indicators:['Lotes ativos','Rastreios','Bloqueios','Ocorrências'],integrations:['Estoque','Produção','Qualidade','Expedição'],route:'/qualidade',Icon:ShieldCheck},
 custos:{title:'Custos Industriais',eyebrow:'CUSTO E MARGEM',description:'Consolide materiais, mão de obra, máquinas, perdas e custos indiretos para entender a operação.',functionality:['Custo de materiais','Mão de obra e máquina','Perdas e refugo','Margem e análise por produto'],flow:['Materiais','Produção','Perdas','Custo','Margem','Resultado'],indicators:['Custo médio','Custo por OP','Margem','Perdas'],integrations:['Produção','Estoque','Financeiro','Indicadores'],route:'/custos',Icon:BarChart3},
 expedicao:{title:'Expedição',eyebrow:'ENTREGA E LOGÍSTICA',description:'Organize separação, conferência, embalagem, romaneio e entrega ao cliente.',functionality:['Separação de pedidos','Conferência de volumes','Romaneio','Acompanhamento de entrega'],flow:['Pedido','Separação','Conferência','Embalagem','Romaneio','Entrega'],indicators:['Pedidos pendentes','Volumes','Entregas','Divergências'],integrations:['Vendas','Estoque','Clientes','Fiscal'],route:'/produtos-vendas',Icon:Truck},
 fmea:{title:'FMEA e Risco',eyebrow:'PREVENÇÃO E RISCO',description:'Analise modos de falha, severidade, ocorrência, detecção e ações preventivas.',functionality:['FMEA de processo e produto','Cálculo e acompanhamento de RPN','Ações preventivas','Revisões e evidências'],flow:['Falha','Causa','Efeito','Risco','Ação','Revisão'],indicators:['RPN alto','Ações abertas','FMEAs ativos','Revisões'],integrations:['Qualidade','Engenharia','Produção','CAPA'],route:'/qualidade',Icon:ClipboardCheck},
 rh:{title:'RH e Competências',eyebrow:'PESSOAS E COMPETÊNCIAS',description:'Organize pessoas, funções, treinamentos, competências e permissões por empresa.',functionality:['Cadastro de colaboradores','Matriz de competências','Treinamentos','Perfis e permissões'],flow:['Pessoa','Função','Competência','Treinamento','Avaliação','Acesso'],indicators:['Colaboradores','Treinamentos pendentes','Competências','Acessos'],integrations:['Usuários','Produção','Qualidade','Gestão'],route:'/usuarios',Icon:Users},
 injecao:{title:'Injeção Plástica',eyebrow:'MANUFATURA • INJEÇÃO',description:'Controle específico de injetoras, moldes, cavidades, ciclos, secagem, parâmetros, setups, refugo e rastreabilidade.',functionality:['Injetoras e capacidade','Moldes, cavidades e vida útil','Receitas e parâmetros de processo','Setup e troca de molde','Consumo, refugo e reprocesso','Rastreabilidade de lote'],flow:['Pedido','MRP','Molde + máquina','Setup','Injeção','Inspeção','Estoque'],indicators:['OEE','Refugo','Ciclo real','Setup','Produção por cavidade'],integrations:['Engenharia','PCP','Estoque','Qualidade','Manutenção'],route:'/processos/injecao',Icon:Factory},
 prensados:{title:'Prensados',eyebrow:'MANUFATURA • PRENSAGEM',description:'Processos de prensagem com composto, pré-forma, ferramental, pressão, temperatura, cura e pós-cura.',functionality:['Prensas e capacidade','Ferramentais','Receitas de processo','Pressão e temperatura','Tempo de cura','Controle de perdas'],flow:['Produto','Ferramental','Preparação','Prensagem','Cura','Inspeção'],indicators:['Ciclo','Refugo','Eficiência','Produção por prensa'],integrations:['Engenharia','PCP','Qualidade','Manutenção'],route:'/processos/prensados',Icon:Factory},
 estamparia:{title:'Estamparia',eyebrow:'MANUFATURA • ESTAMPAGEM',description:'Gestão de prensas, estampos, chapas, força, avanço, lubrificação, setups e qualidade.',functionality:['Prensas e capacidade','Estampos e ferramentas','Espessura e material','Força e tonelagem','Avanço e lubrificação','Refugo e inspeção'],flow:['Pedido','Material','Estampo','Setup','Estampagem','Inspeção','Expedição'],indicators:['Peças/hora','Setup','Refugo','OEE','Tonelagem'],integrations:['PCP','Engenharia','Estoque','Qualidade'],route:'/processos/estamparia',Icon:Factory},
 ferramentaria:{title:'Ferramentaria',eyebrow:'ENGENHARIA • FERRAMENTAS',description:'Ciclo completo de moldes, estampos e dispositivos: projeto, revisão, fabricação, manutenção e vida útil.',functionality:['Cadastro de ferramentas','Revisões e desenhos','Componentes e materiais','Manutenção preventiva','Ciclos e vida útil','Histórico de intervenções'],flow:['Projeto','Orçamento','Fabricação','Try-out','Liberação','Manutenção','Vida útil'],indicators:['Ferramentas ativas','Ciclos','Manutenções','Custo por ferramenta'],integrations:['Engenharia','Produção','Compras','Manutenção','Qualidade'],route:'/processos/ferramentaria',Icon:Wrench},
 extrusao:{title:'Extrusão',eyebrow:'MANUFATURA • EXTRUSÃO',description:'Processos de extrusão com linhas, matrizes, parâmetros, bobinas e controle contínuo.',functionality:['Linhas de extrusão','Matrizes e ferramentas','Receitas e parâmetros','Velocidade e temperatura','Bobinas e lotes','Perdas e rendimento'],flow:['Material','Matriz','Setup','Extrusão','Controle','Bobina','Expedição'],indicators:['Rendimento','Velocidade','Refugo','OEE'],integrations:['PCP','Estoque','Qualidade','Manutenção'],route:'/processos/extrusao',Icon:Factory},
 usinagem:{title:'Usinagem',eyebrow:'MANUFATURA • USINAGEM',description:'Operações de torno, fresamento, furação e centros de usinagem com roteiro, ferramentas e tempos.',functionality:['Máquinas e centros','Ferramentas de corte','Roteiros de operação','Tempos padrão','Setup','Inspeção dimensional'],flow:['BOM','Roteiro','Ferramenta','Setup','Usinagem','Inspeção'],indicators:['Tempo ciclo','Utilização','Refugo','OEE'],integrations:['Engenharia','PCP','Estoque','Qualidade'],route:'/processos/usinagem',Icon:Factory},
 solda:{title:'Soldagem',eyebrow:'MANUFATURA • SOLDAGEM',description:'Controle de operações de solda, consumíveis, parâmetros, operadores qualificados e inspeções.',functionality:['Processos de soldagem','Consumíveis e lotes','Parâmetros','Qualificação de operador','Inspeções','Rastreabilidade'],flow:['Material','Preparação','Soldagem','Inspeção','Retrabalho','Liberação'],indicators:['Refugo','Retrabalho','Tempo','Não conformidades'],integrations:['RH','Qualidade','PCP','Estoque'],route:'/processos/soldagem',Icon:Factory},
 montagem:{title:'Montagem',eyebrow:'MANUFATURA • MONTAGEM',description:'Montagem de componentes e subconjuntos com sequência, kits, instruções, testes e rastreabilidade.',functionality:['BOM multinível','Kitting','Sequência de montagem','Instruções de trabalho','Testes funcionais','Rastreabilidade'],flow:['Kit','Montagem','Teste','Inspeção','Embalagem','Expedição'],indicators:['Produtividade','Tempo ciclo','Retrabalho','FTQ'],integrations:['Engenharia','Estoque','Qualidade','Expedição'],route:'/processos/montagem',Icon:Factory},
 corte:{title:'Corte e Preparação',eyebrow:'MANUFATURA • CORTE',description:'Controle de corte de chapas, tubos, perfis e materiais com aproveitamento e perdas.',functionality:['Planos de corte','Máquinas','Materiais','Aproveitamento','Retalhos','Rastreabilidade'],flow:['Material','Plano de corte','Corte','Conferência','Retalho','Próxima operação'],indicators:['Aproveitamento','Refugo','Tempo','Custo'],integrations:['PCP','Estoque','Compras','Custos'],route:'/processos/corte',Icon:Factory},
 pintura:{title:'Pintura e Acabamento',eyebrow:'MANUFATURA • ACABAMENTO',description:'Processos de pintura, tratamento e acabamento com receitas, lotes, parâmetros e inspeções.',functionality:['Linhas e cabines','Receitas','Materiais e lotes','Parâmetros','Secagem/cura','Inspeção visual e dimensional'],flow:['Preparação','Aplicação','Cura','Inspeção','Embalagem'],indicators:['Rendimento','Refugo','Consumo','FTQ'],integrations:['Estoque','Qualidade','PCP','Manutenção'],route:'/processos/pintura',Icon:Factory}
}
const aliases:Record<string,string>={injetados:'injecao',prensas:'prensados',estampo:'estamparia',ferramentas:'ferramentaria',producao:'pcp','pcp-producao':'pcp',materiais:'estoque','fiscal-financeiro':'fiscal','manutencao-industrial':'manutencao'}
const fallback:ModuleInfo={title:'Módulo Industrial',eyebrow:'SGQ ERP',description:'Área modular do SGQ ERP para centralizar processos, dados, indicadores e permissões da empresa.',functionality:['Dados organizados por empresa','Processos rastreáveis','Permissões por perfil','Indicadores gerenciais'],flow:['Cadastro','Processo','Controle','Indicador','Análise','Ação'],indicators:['Operação','Pendências','Performance','Histórico'],integrations:['Cadastros','Produção','Qualidade','Gestão'],route:'/erp-industrial',Icon:Factory}
export default function ModuleOverviewIndustrial({module}:{module:string}){const key=aliases[module] || module;const item=modules[key] || fallback;const Icon=item.Icon;return <main className="module-overview-page"><div className="module-overview-shell"><a className="module-back" href="/"><ArrowLeft size={17}/> Voltar ao site</a><section className="module-hero"><div className="module-hero-main"><span className="module-eyebrow">{item.eyebrow}</span><div className="module-title-row"><span className="module-icon"><Icon size={30}/></span><h1>{item.title}</h1></div><p className="module-description">{item.description}</p><div className="module-actions"><a className="module-primary" href={item.route}>Entrar no módulo <ArrowRight size={17}/></a><a className="module-secondary" href={`/planos?modulo=${key}`}>Ver planos para este módulo</a></div></div><aside className="module-flow-card"><span className="module-card-kicker">FLUXO OPERACIONAL</span><h2>Como o módulo trabalha</h2><ol>{item.flow.map((step,index)=><li key={step}><b>{String(index+1).padStart(2,'0')}</b><span>{step}</span></li>)}</ol></aside></section><section className="module-grid"><article className="module-card"><span>01</span><h2>O que você faz aqui</h2><ul>{item.functionality.map(value=><li key={value}>{value}</li>)}</ul></article><article className="module-card"><span>02</span><h2>Indicadores</h2><ul>{item.indicators.map(value=><li key={value}>{value}</li>)}</ul></article><article className="module-card"><span>03</span><h2>Integrações</h2><ul>{item.integrations.map(value=><li key={value}>{value}</li>)}</ul></article></section><section className="module-bottom-cta"><div><span className="module-eyebrow">DADOS REAIS • EMPRESA AUTENTICADA</span><h2>Pronto para conhecer este recurso?</h2><p>A apresentação é pública. A operação real permanece protegida pelo Supabase Auth, permissões e RLS da empresa autenticada.</p></div><a className="module-primary" href={`/planos?modulo=${key}`}>Ver planos e começar <ArrowRight size={17}/></a></section></div></main>}
