import { useEffect, useMemo, useState } from 'react'
import { Box, FileText, Plus, Save, Search, Trash2, Wrench, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import EntityCodeLookup from '../components/industrial/EntityCodeLookup'

type Mold={id:string;codigo:string;nome:string;tipo:string;numero_cavidades:number|null;vida_ciclos:number|null;ciclos_realizados:number;ultima_manutencao_em:string|null;proxima_manutencao_em:string|null;status:string;revisao:string|null;desenho_referencia:string|null;parametros:Record<string,unknown>}
type Form={id:string;codigo:string;nome:string;tipo:string;numero_cavidades:string;cavidades_ativas:string;vida_ciclos:string;ciclos_realizados:string;status:string;revisao:string;localizacao:string;material:string;peso_kg:string;desenho_referencia:string;ultima_manutencao_em:string;proxima_manutencao_em:string;observacoes:string}

const blank:Form={id:'',codigo:'',nome:'',tipo:'MOLDE',numero_cavidades:'1',cavidades_ativas:'1',vida_ciclos:'',ciclos_realizados:'0',status:'ATIVA',revisao:'',localizacao:'',material:'',peso_kg:'',desenho_referencia:'',ultima_manutencao_em:'',proxima_manutencao_em:'',observacoes:''}
const input='min-h-12 w-full rounded-md border border-slate-300 bg-white px-3 text-base font-medium text-slate-900 outline-none focus:border-sky-600 focus:ring-2 focus:ring-sky-100'
const label='grid gap-2 text-sm font-extrabold uppercase tracking-wide text-slate-800'

function normalize(x:Mold):Form{
 const p=x.parametros||{}
 return {id:x.id,codigo:x.codigo||'',nome:x.nome||'',tipo:x.tipo||'MOLDE',numero_cavidades:String(x.numero_cavidades??1),cavidades_ativas:String((p.cavidades_ativas??x.numero_cavidades??1)),vida_ciclos:String(x.vida_ciclos??''),ciclos_realizados:String(x.ciclos_realizados??0),status:x.status||'ATIVA',revisao:x.revisao||'',localizacao:String(p.localizacao??''),material:String(p.material??''),peso_kg:String(p.peso_kg??''),desenho_referencia:x.desenho_referencia||'',ultima_manutencao_em:x.ultima_manutencao_em?x.ultima_manutencao_em.slice(0,10):'',proxima_manutencao_em:x.proxima_manutencao_em?x.proxima_manutencao_em.slice(0,10):'',observacoes:String(p.observacoes??'')}
}

export default function MoldesInjecao(){
 const [rows,setRows]=useState<Mold[]>([]),[form,setForm]=useState<Form>(blank),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[lookupOpen,setLookupOpen]=useState(false)
 async function load(){
  setError('')
  const company=await supabase.rpc('erp_current_empresa_id')
  if(company.error||!company.data){setError('Empresa ERP não identificada.');return}
  const r=await supabase.from('erp_ferramentas_industriais').select('id,codigo,nome,tipo,numero_cavidades,vida_ciclos,ciclos_realizados,ultima_manutencao_em,proxima_manutencao_em,status,revisao,desenho_referencia,parametros').eq('empresa_id',company.data).eq('ativo',true).order('codigo').limit(2000)
  if(r.error){setError(r.error.message);return}
  setRows((r.data??[]) as Mold[])
 }
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>rows.filter(x=>!query||[x.codigo,x.nome,x.tipo,x.status].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query])
 const maintenanceLeft=Math.max(0,Number(form.vida_ciclos||0)-Number(form.ciclos_realizados||0))
 function update<K extends keyof Form>(k:K,v:Form[K]){setForm(x=>({...x,[k]:v}));setNotice('');setError('')}
 function novo(){setForm(blank);setNotice('Novo molde pronto para cadastro.');setError('')}
 function open(x:Mold){setForm(normalize(x));setNotice('');setError('')}
 async function save(){
  setBusy(true);setError('');setNotice('')
  try{
   if(!form.codigo.trim()||!form.nome.trim())throw new Error('Código e descrição do molde são obrigatórios.')
   const company=await supabase.rpc('erp_current_empresa_id');const user=await supabase.auth.getUser()
   if(company.error||!company.data)throw company.error||new Error('Empresa ERP não identificada.')
   const payload={empresa_id:company.data,codigo:form.codigo.trim(),nome:form.nome.trim(),tipo:form.tipo,numero_cavidades:Math.max(0,Number(form.numero_cavidades)||0),vida_ciclos:Number(form.vida_ciclos)||null,ciclos_realizados:Number(form.ciclos_realizados)||0,status:form.status,revisao:form.revisao.trim()||null,desenho_referencia:form.desenho_referencia.trim()||null,parametros:{cavidades_ativas:Number(form.cavidades_ativas)||0,localizacao:form.localizacao.trim(),material:form.material.trim(),peso_kg:Number(form.peso_kg)||null,observacoes:form.observacoes.trim()},ultima_manutencao_em:form.ultima_manutencao_em||null,proxima_manutencao_em:form.proxima_manutencao_em||null,atualizado_por:user.data.user?.id||null,atualizado_em:new Date().toISOString()}
   const r=form.id?await supabase.from('erp_ferramentas_industriais').update(payload).eq('id',form.id).select('*').single():await supabase.from('erp_ferramentas_industriais').insert({...payload,criado_por:user.data.user?.id||null}).select('*').single()
   if(r.error)throw r.error
   setForm(normalize(r.data as Mold));setNotice('Cadastro do molde gravado.');await load()
  }catch(e){setError(e instanceof Error?e.message:'Não foi possível gravar o molde.')}finally{setBusy(false)}
 }
 async function remove(){
  if(!form.id)return
  if(!window.confirm('Excluir este molde/ferramental do cadastro ativo?'))return
  setBusy(true)
  try{const r=await supabase.from('erp_ferramentas_industriais').update({ativo:false,atualizado_em:new Date().toISOString()}).eq('id',form.id);if(r.error)throw r.error;novo();setNotice('Molde arquivado do cadastro ativo.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível arquivar o molde.')}finally{setBusy(false)}
 }
 return <main className="min-h-screen bg-slate-100 text-slate-900">
  <header className="sticky top-0 z-30 border-b border-slate-700 bg-slate-900 px-4 py-3 text-white shadow-lg"><div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-sky-300">QUALIDADE & ENGENHARIA • FERRAMENTARIA</p><h1 className="text-2xl font-extrabold">Controle de Moldes e Estampos</h1></div><div className="flex flex-wrap gap-2"><button onClick={novo} className="rounded-md border border-slate-600 px-4 py-2 text-sm font-extrabold text-white hover:bg-slate-800"><Plus size={16} className="mr-2 inline"/>NOVO MOLDE</button><button onClick={()=>void save()} disabled={busy} className="rounded-md bg-sky-600 px-5 py-2 text-sm font-extrabold text-white hover:bg-sky-500"><Save size={16} className="mr-2 inline"/>GRAVAR</button><button onClick={()=>void remove()} disabled={!form.id||busy} className="rounded-md bg-red-700 px-4 py-2 text-sm font-extrabold text-white hover:bg-red-600 disabled:opacity-40"><Trash2 size={16} className="mr-2 inline"/>DELETAR</button><button onClick={()=>setLookupOpen(true)} className="rounded-md border border-slate-500 px-4 py-2 text-sm font-extrabold text-white hover:bg-slate-800"><Search size={16} className="mr-2 inline"/>LOCALIZAR VIA LUPA</button></div></div></header>
  <div className="mx-auto grid max-w-[1700px] grid-cols-1 gap-5 p-4 lg:grid-cols-[300px_minmax(0,1fr)]">
   <aside className="rounded-md border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><p className="text-xs font-extrabold uppercase tracking-wider text-slate-600">CONSULTA DE MOLDES</p><div className="mt-3 flex gap-2"><input className={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código / descrição"/><button onClick={()=>setLookupOpen(true)} className="rounded-md bg-slate-900 px-3 text-white"><Search size={18}/></button></div></div><div className="max-h-[70vh] overflow-auto p-2">{filtered.map(x=><button key={x.id} onClick={()=>open(x)} className={x.id===form.id?'mb-2 w-full rounded-md border border-sky-400 bg-sky-50 p-3 text-left':'mb-2 w-full rounded-md border border-slate-200 bg-white p-3 text-left hover:border-sky-300'}><b className="block text-base">{x.codigo}</b><span className="block text-sm text-slate-700">{x.nome}</span><span className="mt-1 text-xs font-bold text-slate-600">{x.status} • {x.ciclos_realizados.toLocaleString('pt-BR')} ciclos</span></button>)}{!filtered.length&&<p className="p-5 text-center text-sm font-semibold text-slate-600">Nenhum molde cadastrado.</p>}</div></aside>
   <section className="space-y-5">
    {(error||notice)&&<div className={error?'rounded-md border border-red-200 bg-red-50 p-4 text-base font-bold text-red-800':'rounded-md border border-emerald-200 bg-emerald-50 p-4 text-base font-bold text-emerald-800'}>{error||notice}</div>}
    <section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 border-b border-slate-200 pb-4"><p className="text-sm font-extrabold uppercase tracking-wider text-sky-700">1. FICHA TÉCNICA E IDENTIFICAÇÃO DO UTENSÍLIO</p><h2 className="mt-1 text-xl font-extrabold">Gerenciamento ativo de moldes e estampos</h2></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><label className={label}>Nº DO MOLDE<input className={input} value={form.codigo} onChange={e=>update('codigo',e.target.value)} placeholder="MLD-2026-044"/></label><label className={label}>DESCRIÇÃO<input className={input} value={form.nome} onChange={e=>update('nome',e.target.value)} placeholder="Molde Injeção Tampa"/></label><label className={label}>LOCALIZAÇÃO<input className={input} value={form.localizacao} onChange={e=>update('localizacao',e.target.value)} placeholder="Prateleira B3"/></label><label className={label}>Nº CAVIDADES<input className={input} type="number" min="0" value={form.numero_cavidades} onChange={e=>update('numero_cavidades',e.target.value)}/></label><label className={label}>CAVIDADES ATIVAS<input className={input} type="number" min="0" value={form.cavidades_ativas} onChange={e=>update('cavidades_ativas',e.target.value)}/></label><label className={label}>AÇO / MATERIAL<input className={input} value={form.material} onChange={e=>update('material',e.target.value)} placeholder="P20 Nitretado"/></label><label className={label}>PESO TOTAL (KG)<input className={input} type="number" step="0.001" value={form.peso_kg} onChange={e=>update('peso_kg',e.target.value)}/></label><label className={label}>REVISÃO<input className={input} value={form.revisao} onChange={e=>update('revisao',e.target.value)} placeholder="Rev. 03"/></label></div></section>
    <section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 border-b border-slate-200 pb-4"><p className="text-sm font-extrabold uppercase tracking-wider text-sky-700">2. HISTÓRICO DE VIDA ÚTIL E MANUTENÇÃO PREVENTIVA</p><h2 className="mt-1 text-xl font-extrabold">Contadores e disponibilidade operacional</h2></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><label className={label}>CONTADOR DE CICLOS<input className={input} type="number" min="0" value={form.ciclos_realizados} onChange={e=>update('ciclos_realizados',e.target.value)}/></label><label className={label}>LIMITE PARA MANUTENÇÃO<input className={input} type="number" min="0" value={form.vida_ciclos} onChange={e=>update('vida_ciclos',e.target.value)}/></label><label className={label}>ÚLTIMA MANUTENÇÃO<input className={input} type="date" value={form.ultima_manutencao_em} onChange={e=>update('ultima_manutencao_em',e.target.value)}/></label><label className={label}>PRÓXIMA MANUTENÇÃO<input className={input} type="date" value={form.proxima_manutencao_em} onChange={e=>update('proxima_manutencao_em',e.target.value)}/></label><label className={label}>STATUS<select className={input} value={form.status} onChange={e=>update('status',e.target.value)}><option>ATIVA</option><option>EM_PRODUCAO</option><option>EM_MANUTENCAO</option><option>INATIVA</option></select></label><label className={label}>TIPO<select className={input} value={form.tipo} onChange={e=>update('tipo',e.target.value)}><option>MOLDE</option><option>ESTAMPO</option><option>FERRAMENTA</option><option>DISPOSITIVO</option><option>MATRIZ</option><option>OUTRO</option></select></label></div><div className="mt-5 rounded-md border border-slate-200 bg-slate-50 p-5"><div className="flex flex-wrap items-center gap-3"><Wrench className="text-sky-700"/><div><b className="text-lg">Alerta de vida útil</b><p className="text-base text-slate-700">{form.vida_ciclos?'Faltam '+maintenanceLeft.toLocaleString('pt-BR')+' ciclos para o limite cadastrado.':'Cadastre o limite de ciclos para calcular a próxima revisão.'}</p></div></div></div></section>
    <section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 border-b border-slate-200 pb-4"><FileText className="text-sky-700"/><div><p className="text-sm font-extrabold uppercase tracking-wider text-sky-700">3. REFERÊNCIAS E OBSERVAÇÕES</p><h2 className="text-xl font-extrabold">Desenho, referência e manutenção</h2></div></div><label className={label}>DESENHO / REFERÊNCIA<input className={input} value={form.desenho_referencia} onChange={e=>update('desenho_referencia',e.target.value)} placeholder="Código do desenho técnico ou referência"/></label><label className={label+' mt-4'}>OBSERVAÇÕES<textarea className="min-h-32 w-full rounded-md border border-slate-300 bg-white p-3 text-base font-medium text-slate-900 outline-none focus:border-sky-600 focus:ring-2 focus:ring-sky-100" value={form.observacoes} onChange={e=>update('observacoes',e.target.value)} placeholder="Intervenções, cuidados, restrições e observações da Ferramentaria."/></label><div className="mt-5 flex justify-end border-t border-slate-200 pt-4"><button onClick={()=>void save()} disabled={busy} className="rounded-md bg-sky-700 px-6 py-3 text-base font-extrabold text-white hover:bg-sky-600"><Save size={18} className="mr-2 inline"/>GRAVAR CADASTRO</button></div></section>
   </section>
  </div>
  {lookupOpen&&<div className="fixed inset-0 z-[10000] grid place-items-center bg-slate-950/70 p-4"><section className="w-full max-w-6xl overflow-hidden rounded-md border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-200 bg-slate-900 p-5 text-white"><div><p className="text-sm font-extrabold uppercase tracking-wider text-sky-300">CONSULTA INDUSTRIAL</p><h2 className="text-2xl font-extrabold">Localizar molde / ferramental</h2></div><button onClick={()=>setLookupOpen(false)} className="rounded-md border border-slate-600 p-2 text-white hover:bg-slate-800"><X/></button></header><div className="p-5"><EntityCodeLookup label="CÓDIGO DO MOLDE / FERRAMENTAL" value="" records={rows.map(x=>({id:x.id,codigo:x.codigo,nome:x.nome,dimensoes:String(x.parametros?.localizacao??''),molde:x.nome}))} onChange={()=>{}} onSelect={r=>{const x=rows.find(m=>m.id===r.id);if(x)open(x);setLookupOpen(false)}} helper="Código direto ou filtros por descrição, dimensões, canal e molde."/></div></section></div>}
 </main>
