import { useEffect, useMemo, useState } from 'react'
import { Check, FileDown, Plus, RefreshCw, Save, Send, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import '../styles/synqra-workspace.css'

type FieldMap=Record<string,string>
type Item={id:string;produto_id:string;codigo:string;descricao:string;ncm:string;cfop:string;cst_csosn:string;unidade:string;quantidade:string;valor_unitario:string;valor_desconto:string;icms_aliquota:string;ipi_aliquota:string;pis_aliquota:string;cofins_aliquota:string;origem:string}
const emptyItem=():Item=>({id:crypto.randomUUID(),produto_id:'',codigo:'',descricao:'',ncm:'',cfop:'',cst_csosn:'',unidade:'',quantidade:'1',valor_unitario:'0',valor_desconto:'0',icms_aliquota:'0',ipi_aliquota:'0',pis_aliquota:'0',cofins_aliquota:'0',origem:'0'})
const n=(v:string)=>{const x=v.trim().replace(/\./g,'').replace(',','.');const z=Number(x);return Number.isFinite(z)?z:0}
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)
const digits=(v:string,max:number)=>v.replace(/\D/g,'').slice(0,max)
const Field=({label,value,onChange,required=false,readOnly=false,wide=false}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;readOnly?:boolean;wide?:boolean})=><label className={wide?'synqra-nfe-field wide':''}><span>{label}{required?' *':''}</span><input value={value} readOnly={readOnly} onChange={e=>onChange(e.target.value)} /></label>

export default function NFeEmissaoCompact(){
 const [companyId,setCompanyId]=useState('');const [company,setCompany]=useState<FieldMap>({});const [customer,setCustomer]=useState<FieldMap>({});const [products,setProducts]=useState<Array<FieldMap>>([]);const [transporters,setTransporters]=useState<Array<FieldMap>>([])
 const [form,setForm]=useState<FieldMap>({natureza:'',serie:'',numero:'',tipo_emissao:'1',finalidade:'1',tipo_operacao:'1',emissao:new Date().toISOString().slice(0,16),saida:'',cfop:'',modalidade_frete:'9',transportadora:'',transportadora_cnpj:'',placa:'',uf_placa:'',rntrc:'',volumes:'0',especie:'',marca:'',peso_liquido:'0',peso_bruto:'0',informacoes:''})
 const [items,setItems]=useState<Item[]>([emptyItem()]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [documentId,setDocumentId]=useState<string|null>(null)
 useEffect(()=>{void load()},[])
 async function load(){
  setBusy(true);setError('')
  try{
   const auth=await supabase.auth.getUser();if(auth.error||!auth.data.user)throw new Error('Sessão não localizada.')
   const empresa=await supabase.rpc('erp_current_empresa_id');if(empresa.error||!empresa.data)throw empresa.error??new Error('Empresa da sessão não localizada.')
   const id=String(empresa.data);setCompanyId(id)
   const [er,pr,tr,cf]=await Promise.all([
    supabase.from('erp_empresas').select('razao_social,nome_fantasia,cnpj,endereco,cidade,uf,cep,telefone,email,inscricao_estadual').eq('id',id).single(),
    supabase.from('erp_produtos').select('id,codigo,nome,unidade,ncm,cest,cfop_saida,cst_icms,csosn,origem_fiscal,preco_venda,aliquota_icms,aliquota_ipi,aliquota_pis,aliquota_cofins').eq('empresa_id',id).eq('ativo',true).order('nome').limit(1000),
    supabase.from('erp_transportadoras').select('id,codigo,razao_social,cnpj,ie,telefone,cidade,uf').eq('empresa_id',id).eq('ativo',true).order('razao_social').limit(500),
    supabase.from('erp_config_fiscal').select('serie_nfe,proximo_numero_nfe,ambiente,regime_tributario,cnpj_emitente,razao_social_emitente,inscricao_estadual,habilitado_nfe').eq('empresa_id',id).maybeSingle()
   ])
   if(er.error)throw er.error;if(pr.error)throw pr.error;if(tr.error)throw tr.error;if(cf.error)throw cf.error
   setCompany((er.data??{}) as FieldMap);setProducts((pr.data??[]) as Array<FieldMap>);setTransporters((tr.data??[]) as Array<FieldMap>)
   const cfg=cf.data as FieldMap|null;if(cfg)setForm(v=>({...v,serie:String(cfg.serie_nfe??''),numero:String(cfg.proximo_numero_nfe??''),ambiente:String(cfg.ambiente??'')}))
  }catch(e){setError(e instanceof Error?e.message:'Falha ao carregar dados fiscais.')}finally{setBusy(false)}
 }
 const totalProdutos=useMemo(()=>items.reduce((s,i)=>s+Math.max(0,n(i.quantidade)*n(i.valor_unitario)-n(i.valor_desconto)),0),[items])
 const totals=useMemo(()=>({produtos:totalProdutos,desconto:items.reduce((s,i)=>s+n(i.valor_desconto),0),frete:n(form.frete??'0'),ipi:items.reduce((s,i)=>s+(n(i.quantidade)*n(i.valor_unitario)-n(i.valor_desconto))*n(i.ipi_aliquota)/100,0),pis:items.reduce((s,i)=>s+(n(i.quantidade)*n(i.valor_unitario)-n(i.valor_desconto))*n(i.pis_aliquota)/100,0),cofins:items.reduce((s,i)=>s+(n(i.quantidade)*n(i.valor_unitario)-n(i.valor_desconto))*n(i.cofins_aliquota)/100,0)}),[items,totalProdutos,form.frete])
 const totalNota=totals.produtos+totals.frete+totals.ipi+totals.pis+totals.cofins-totals.desconto
 const set=(key:string,value:string)=>{setForm(v=>({...v,[key]:value}));setError('')}
 const setItem=(id:string,key:keyof Item,value:string)=>setItems(v=>v.map(i=>i.id===id?{...i,[key]:value}:i))
 const selectProduct=(id:string,itemId:string)=>{const p=products.find(x=>String(x.id)===id);if(!p)return;setItems(v=>v.map(i=>i.id===itemId?{...i,produto_id:String(p.id),codigo:String(p.codigo??''),descricao:String(p.nome??''),ncm:digits(String(p.ncm??''),8),cfop:digits(String(p.cfop_saida??form.cfop??''),4),unidade:String(p.unidade??''),valor_unitario:String(p.preco_venda??0),cst_csosn:String(p.cst_icms??p.csosn??''),origem:digits(String(p.origem_fiscal??'0'),1),icms_aliquota:String(p.aliquota_icms??0),ipi_aliquota:String(p.aliquota_ipi??0),pis_aliquota:String(p.aliquota_pis??0),cofins_aliquota:String(p.aliquota_cofins??0)}:i))}
 const validate=()=>{if(!form.natureza.trim())return'Informe a Natureza da Operação.';if(digits(form.serie,3)==='')return'Informe a Série.';if(!customer.documento?.trim())return'CNPJ/CPF do destinatário é obrigatório.';if(!customer.nome?.trim())return'Razão Social/Nome é obrigatório.';if(!form.cfop||digits(form.cfop,4).length!==4)return'CFOP da operação deve ter 4 dígitos.';if(items.some(i=>!i.codigo||!i.ncm||digits(i.cfop,4).length!==4||!i.unidade||n(i.quantidade)<=0))return'Complete Código, NCM, CFOP, Unidade e Quantidade dos itens.';return null}
 const save=async()=>{setBusy(true);setMessage('');setError('');try{const v=validate();if(v)throw new Error(v);const payload={empresa_id:companyId,tipo:form.tipo_operacao==='1'?'NF-e':'NF-e Entrada',modelo:'55',serie:digits(form.serie,3),numero:form.numero?Number(form.numero):null,status:'Rascunho',natureza_operacao:form.natureza,cfop:digits(form.cfop,4),ambiente:form.ambiente||'homologacao',data_emissao:new Date(form.emissao).toISOString(),data_saida:form.saida?new Date(form.saida).toISOString():null,destinatario_nome:customer.nome,destinatario_documento:customer.documento,destinatario_ie:customer.ie||null,destinatario_email:customer.email||null,destinatario_endereco:customer.endereco||null,destinatario_bairro:customer.bairro||null,destinatario_cep:customer.cep||null,destinatario_cidade:customer.cidade||null,destinatario_uf:customer.uf||null,modalidade_frete:form.modalidade_frete,transportadora:form.transportadora||null,placa:form.placa||null,uf_transportadora:form.uf_placa||null,peso_liquido:n(form.peso_liquido),peso_bruto:n(form.peso_bruto),volumes:n(form.volumes),valor_produtos:totals.produtos,valor_frete:totals.frete,valor_outras_despesas:n(form.outras),valor_desconto:totals.desconto,base_calculo_icms:n(form.base_icms),valor_icms:n(form.valor_icms),base_icms_st:n(form.base_icms_st),valor_icms_st:n(form.valor_icms_st),valor_ipi:totals.ipi,valor_pis:totals.pis,valor_cofins:totals.cofins,valor_total:totalNota,valor_liquido:totalNota}
 const rows=items.map((i,index)=>({produto_id:i.produto_id||null,item_numero:index+1,codigo_produto:i.codigo,descricao_produto:i.descricao,ncm:digits(i.ncm,8),cfop:digits(i.cfop,4),unidade:i.unidade,quantidade:n(i.quantidade),valor_unitario:n(i.valor_unitario),valor_total:Math.max(0,n(i.quantidade)*n(i.valor_unitario)-n(i.valor_desconto)),valor_desconto:n(i.valor_desconto),origem:digits(i.origem,1),cst_csosn:i.cst_csosn||null,icms_aliquota:n(i.icms_aliquota),ipi_aliquota:n(i.ipi_aliquota),pis_aliquota:n(i.pis_aliquota),cofins_aliquota:n(i.cofins_aliquota)}))
 const rpc=await supabase.rpc('erp_salvar_rascunho_nfe',{p_documento_id:documentId,p_documento:payload,p_itens:rows});if(rpc.error||!rpc.data)throw new Error(rpc.error?.message||'Não foi possível salvar o rascunho fiscal.');setDocumentId(String(rpc.data));setMessage('NF-e gravada como rascunho. Nenhuma transmissão à SEFAZ foi executada.')}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar NF-e.')}finally{setBusy(false)}}
 const invalid=(key:string)=>Boolean(error&&(!form[key]||form[key].trim()===''))
 return <main className="synqra-workspace synqra-nfe"><header className="synqra-workspace-header"><button className="synqra-workspace-brand" type="button" onClick={()=>window.location.assign('/tablet/dashboard')}><img src="/logo/sgq-erp.png" alt="SGQERP Industrial"/><span><strong>SGQERP INDUSTRIAL</strong><small>EMISSÃO FISCAL • NF-e 55</small></span></button><button className="synqra-master-menu" type="button" onClick={()=>window.location.assign('/vendas')}>MENU FISCAL</button><div className="synqra-session"><div><strong>{company.razao_social??'Emitente'}</strong><span>{form.ambiente||'AMBIENTE NÃO CONFIGURADO'}</span></div></div></header>
 <section className="synqra-workspace-body">
  <div className="synqra-workspace-title"><div><h1>Emissor NF-e • Workspace Fiscal</h1><p>Identificação → destinatário → itens → tributação → transporte → informações adicionais</p></div><button className="synqra-tool-button" type="button" onClick={()=>void load()} disabled={busy}><RefreshCw size={13}/>ATUALIZAR</button></div>
  {(error||message)&&<div className={error?'synqra-nfe-alert error':'synqra-nfe-alert ok'}>{error||message}</div>}
  <div className="synqra-nfe-actions"><button onClick={()=>{setDocumentId(null);setItems([emptyItem()]);setMessage('');setError('')}}><Plus size={13}/>NOVA NOTA</button><button onClick={()=>void save()} disabled={busy}><Save size={13}/>SALVAR / VALIDAR</button><button className="primary" disabled={busy||!documentId} title={!documentId?'Salve a NF-e antes de emitir.':''}><Send size={13}/>EMITIR</button><button disabled={!documentId}><FileDown size={13}/>GERAR DANFE PDF</button><button disabled={!documentId}><X size={13}/>CANCELAR NF</button></div>

  <section className="synqra-nfe-block"><h2>01 • DADOS DA NF-e</h2><div className="synqra-nfe-grid">
   <Field label="Natureza da Operação" value={form.natureza} onChange={v=>set('natureza',v)} required/><Field label="Série" value={form.serie} onChange={v=>set('serie',digits(v,3))} required/><Field label="Número NF" value={form.numero} onChange={v=>set('numero',v)} readOnly/><label><span>TIPO EMISSÃO</span><select value={form.tipo_emissao} onChange={e=>set('tipo_emissao',e.target.value)}><option value="1">1 • Normal</option><option value="2">2 • Contingência</option></select></label><label><span>FINALIDADE</span><select value={form.finalidade} onChange={e=>set('finalidade',e.target.value)}><option value="1">1 • Normal</option><option value="2">2 • Complementar</option><option value="4">4 • Devolução</option></select></label><label><span>OPERAÇÃO</span><select value={form.tipo_operacao} onChange={e=>set('tipo_operacao',e.target.value)}><option value="1">1 • Saída</option><option value="0">0 • Entrada</option></select></label><Field label="Data/Hora Emissão" value={form.emissao} onChange={v=>set('emissao',v)}/><Field label="Data/Hora Saída/Entrada" value={form.saida} onChange={v=>set('saida',v)}/><Field label="CFOP Principal" value={form.cfop} onChange={v=>set('cfop',digits(v,4))} required/><Field label="Ambiente" value={form.ambiente} onChange={v=>set('ambiente',v)} readOnly/></div></section>

  <section className="synqra-nfe-block"><h2>02 • EMITENTE & DESTINATÁRIO / REMETENTE</h2><div className="synqra-nfe-grid"><Field label="CNPJ Emitente" value={String(company.cnpj??'')} onChange={()=>{}} readOnly/><Field label="Razão Social Emitente" value={String(company.razao_social??company.nome_fantasia??'')} onChange={()=>{}} readOnly/><Field label="IE Emitente" value={String(company.inscricao_estadual??'')} onChange={()=>{}} readOnly/><Field label="CNPJ / CPF Destinatário" value={String(customer.documento??'')} onChange={v=>setCustomer(c=>({...c,documento:v}))} required/><Field label="IE Destinatário" value={String(customer.ie??'')} onChange={v=>setCustomer(c=>({...c,ie:v}))}/><Field label="Razão Social / Nome" value={String(customer.nome??'')} onChange={v=>setCustomer(c=>({...c,nome:v}))} required wide/><Field label="Inscrição Municipal" value={String(customer.im??'')} onChange={v=>setCustomer(c=>({...c,im:v}))}/><Field label="Endereço Completo" value={String(customer.endereco??'')} onChange={v=>setCustomer(c=>({...c,endereco:v}))} wide/><Field label="Bairro" value={String(customer.bairro??'')} onChange={v=>setCustomer(c=>({...c,bairro:v}))}/><Field label="Município" value={String(customer.cidade??'')} onChange={v=>setCustomer(c=>({...c,cidade:v}))}/><Field label="UF" value={String(customer.uf??'')} onChange={v=>setCustomer(c=>({...c,uf:v.toUpperCase().slice(0,2)}))}/><Field label="CEP" value={String(customer.cep??'')} onChange={v=>setCustomer(c=>({...c,cep:v}))}/><Field label="Telefone" value={String(customer.telefone??'')} onChange={v=>setCustomer(c=>({...c,telefone:v}))}/><Field label="E-mail NF-e" value={String(customer.email??'')} onChange={v=>setCustomer(c=>({...c,email:v}))}/><Field label="Contato" value={String(customer.contato??'')} onChange={v=>setCustomer(c=>({...c,contato:v}))}/><Field label="Tipo Pessoa" value={String(customer.tipo_pessoa??'')} onChange={v=>setCustomer(c=>({...c,tipo_pessoa:v}))}/><Field label="Regime Tributário" value={String(customer.regime_tributario??'')} onChange={v=>setCustomer(c=>({...c,regime_tributario:v}))}/></div></section>

  <section className="synqra-nfe-block synqra-nfe-items"><div className="synqra-nfe-block-head"><h2>03 • GRID MESTRE DE ITENS DA NOTA</h2><button onClick={()=>setItems(v=>[...v,emptyItem()])}><Plus size={13}/>ADICIONAR ITEM</button></div><div className="synqra-nfe-table-wrap"><table><thead><tr><th>ITEM</th><th>CÓD. PRODUTO</th><th>DESCRIÇÃO DO INSUMO</th><th>NCM</th><th>CST/CSOSN</th><th>CFOP</th><th>UN</th><th>QTD</th><th>PREÇO UNIT.</th><th>VLR. BRUTO</th><th>DESCONTO</th><th>BC ICMS</th><th>ICMS %</th><th>VLR ICMS</th><th>IPI %</th><th>VLR IPI</th><th>PIS %</th><th>COFINS %</th><th>AÇÃO</th></tr></thead><tbody>{items.map((i,index)=>{const bruto=n(i.quantidade)*n(i.valor_unitario);const liq=Math.max(0,bruto-n(i.valor_desconto));return <tr key={i.id}><td>{index+1}</td><td><select value={i.produto_id} onChange={e=>selectProduct(e.target.value,i.id)}><option value="">MANUAL</option>{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.codigo??'')} • {String(p.nome??'')}</option>)}</select><input value={i.codigo} onChange={e=>setItem(i.id,'codigo',e.target.value)} aria-label="Código do produto"/></td><td><input value={i.descricao} onChange={e=>setItem(i.id,'descricao',e.target.value)}/></td><td><input value={i.ncm} maxLength={8} onChange={e=>setItem(i.id,'ncm',digits(e.target.value,8))}/></td><td><input value={i.cst_csosn} maxLength={4} onChange={e=>setItem(i.id,'cst_csosn',e.target.value.toUpperCase())}/></td><td><input value={i.cfop} maxLength={4} onChange={e=>setItem(i.id,'cfop',digits(e.target.value,4))}/></td><td><input value={i.unidade} onChange={e=>setItem(i.id,'unidade',e.target.value.toUpperCase())}/></td><td><input className="right" value={i.quantidade} onChange={e=>setItem(i.id,'quantidade',e.target.value)}/></td><td><input className="right" value={i.valor_unitario} onChange={e=>setItem(i.id,'valor_unitario',e.target.value)}/></td><td className="right">{money(bruto)}</td><td><input className="right" value={i.valor_desconto} onChange={e=>setItem(i.id,'valor_desconto',e.target.value)}/></td><td className="right">{money(liq)}</td><td><input className="right" value={i.icms_aliquota} onChange={e=>setItem(i.id,'icms_aliquota',e.target.value)}/></td><td className="right">{money(liq*n(i.icms_aliquota)/100)}</td><td><input className="right" value={i.ipi_aliquota} onChange={e=>setItem(i.id,'ipi_aliquota',e.target.value)}/></td><td className="right">{money(liq*n(i.ipi_aliquota)/100)}</td><td><input className="right" value={i.pis_aliquota} onChange={e=>setItem(i.id,'pis_aliquota',e.target.value)}/></td><td><input className="right" value={i.cofins_aliquota} onChange={e=>setItem(i.id,'cofins_aliquota',e.target.value)}/></td><td><button className="danger-icon" onClick={()=>setItems(v=>v.filter(x=>x.id!==i.id))} aria-label="Remover item">×</button></td></tr>})}</tbody></table></div></section>

  <section className="synqra-nfe-block"><h2>04 • TOTAIS DE IMPOSTOS</h2><div className="synqra-nfe-grid totals"><Field label="Base de Cálculo ICMS" value={form.base_icms??'0'} onChange={v=>set('base_icms',v)}/><Field label="Valor Total ICMS" value={form.valor_icms??'0'} onChange={v=>set('valor_icms',v)}/><Field label="BC ICMS ST" value={form.base_icms_st??'0'} onChange={v=>set('base_icms_st',v)}/><Field label="Valor ICMS ST" value={form.valor_icms_st??'0'} onChange={v=>set('valor_icms_st',v)}/><Field label="Valor Total Produtos" value={money(totals.produtos)} onChange={()=>{}} readOnly/><Field label="Valor Frete" value={form.frete??'0'} onChange={v=>set('frete',v)}/><Field label="Valor Seguro" value={form.seguro??'0'} onChange={v=>set('seguro',v)}/><Field label="Valor Desconto" value={String(totals.desconto)} onChange={()=>{}} readOnly/><Field label="Outras Despesas" value={form.outras??'0'} onChange={v=>set('outras',v)}/><Field label="Valor Total IPI" value={money(totals.ipi)} onChange={()=>{}} readOnly/><Field label="Valor Total PIS" value={money(totals.pis)} onChange={()=>{}} readOnly/><Field label="Valor Total COFINS" value={money(totals.cofins)} onChange={()=>{}} readOnly/><Field label="VALOR TOTAL DA NOTA FISCAL" value={money(totalNota)} onChange={()=>{}} readOnly wide/></div></section>

  <section className="synqra-nfe-block"><h2>05 • TRANSPORTADORA & VOLUMES</h2><div className="synqra-nfe-grid"><label><span>MODALIDADE DO FRETE</span><select value={form.modalidade_frete} onChange={e=>set('modalidade_frete',e.target.value)}><option value="0">0 • CIF</option><option value="1">1 • FOB</option><option value="9">9 • SEM FRETE</option></select></label><Field label="CNPJ/CPF TRANSP." value={form.transportadora_cnpj} onChange={v=>set('transportadora_cnpj',v)}/><label className="wide"><span>RAZÃO SOCIAL TRANSPORTADORA</span><select value={form.transportadora} onChange={e=>{const t=transporters.find(x=>String(x.id)===e.target.value);set('transportadora',t?String(t.razao_social??''):e.target.value);set('transportadora_cnpj',t?String(t.cnpj??''):form.transportadora_cnpj);set('uf_placa',t?String(t.uf??''):form.uf_placa)}}><option value="">Selecionar transportadora</option>{transporters.map(t=><option key={String(t.id)} value={String(t.id)}>{String(t.razao_social??'')}</option>)}</select></label><Field label="PLACA DO VEÍCULO" value={form.placa} onChange={v=>set('placa',v.toUpperCase().slice(0,8))}/><Field label="UF PLACA" value={form.uf_placa} onChange={v=>set('uf_placa',v.toUpperCase().slice(0,2))}/><Field label="RNTRC" value={form.rntrc} onChange={v=>set('rntrc',v)}/><Field label="QUANTIDADE VOLUMES" value={form.volumes} onChange={v=>set('volumes',v)}/><Field label="ESPÉCIE" value={form.especie} onChange={v=>set('especie',v)}/><Field label="MARCA" value={form.marca} onChange={v=>set('marca',v)}/><Field label="PESO LÍQUIDO KG" value={form.peso_liquido} onChange={v=>set('peso_liquido',v)}/><Field label="PESO BRUTO KG" value={form.peso_bruto} onChange={v=>set('peso_bruto',v)}/></div></section>
  <section className="synqra-nfe-block"><h2>06 • INFORMAÇÕES ADICIONAIS</h2><textarea value={form.informacoes} onChange={e=>set('informacoes',e.target.value)} placeholder="Informações complementares de interesse do contribuinte"/></section>
 </section>
 <style>{`.synqra-nfe{background:#f4f7fe}.synqra-nfe-block{background:#fff;border:1px solid #cbd5e1;border-radius:2px;padding:7px;margin-bottom:7px}.synqra-nfe-block h2{margin:0 0 6px;padding-bottom:4px;border-bottom:1px solid #dbe5e9;color:#123b50;font-size:10px;font-weight:600;letter-spacing:.06em}.synqra-nfe-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:6px}.synqra-nfe-field,.synqra-nfe-grid>label{display:flex;flex-direction:column;gap:2px;min-width:0;grid-column:span 2}.synqra-nfe-field.wide,.synqra-nfe-grid>label.wide{grid-column:span 4}.synqra-nfe-field span,.synqra-nfe-grid>label span{font-size:9px;line-height:10px;text-transform:uppercase;color:#536b76;font-weight:500}.synqra-nfe input,.synqra-nfe select{height:30px!important;min-height:30px!important;border-radius:2px!important;font-size:11px!important}.synqra-nfe-actions{display:flex;gap:4px;align-items:center;margin-bottom:7px}.synqra-nfe-actions button,.synqra-nfe-block-head button{height:30px;min-height:30px;display:inline-flex;align-items:center;gap:5px;border:1px solid #2d8db8;background:#fff;color:#24566b;border-radius:2px;padding:0 9px;font-size:10px;font-weight:500}.synqra-nfe-actions .primary,.synqra-nfe-block-head button{background:#2d8db8;color:#fff}.synqra-nfe-actions button:disabled{opacity:.45}.synqra-nfe-alert{padding:6px 8px;margin-bottom:7px;border:1px solid;border-radius:2px;font-size:10px}.synqra-nfe-alert.error{background:#fff1f2;border-color:#ef4444;color:#991b1b}.synqra-nfe-alert.ok{background:#ecfdf5;border-color:#34d399;color:#065f46}.synqra-nfe-block-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:5px}.synqra-nfe-block-head h2{flex:1}.synqra-nfe-table-wrap{overflow:auto}.synqra-nfe table{min-width:1900px;table-layout:fixed}.synqra-nfe th{height:28px;font-size:8px}.synqra-nfe td{height:30px;padding:2px 4px;font-size:10px}.synqra-nfe td input,.synqra-nfe td select{width:100%;height:28px!important;min-height:28px!important;font-size:10px!important}.synqra-nfe td.right{text-align:right}.synqra-nfe .danger-icon{height:26px;width:26px;border:1px solid #fecaca;background:#fff1f2;color:#b91c1c;border-radius:2px}.synqra-nfe-block textarea{width:100%;height:80px;resize:vertical;border:1px solid #b9cbd3;border-radius:2px;padding:6px;font-size:11px}.synqra-nfe .totals .synqra-nfe-field:last-child{grid-column:span 4}.synqra-nfe input:read-only{background:#f1f5f9}.synqra-nfe input:focus,.synqra-nfe select:focus,.synqra-nfe textarea:focus{outline:1px solid #2d8db8}@media(max-width:1100px){.synqra-nfe-grid{grid-template-columns:repeat(6,minmax(0,1fr))}.synqra-nfe-field,.synqra-nfe-grid>label{grid-column:span 2}.synqra-nfe-field.wide,.synqra-nfe-grid>label.wide{grid-column:span 3}}@media(max-width:700px){.synqra-nfe-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.synqra-nfe-field,.synqra-nfe-grid>label,.synqra-nfe-field.wide,.synqra-nfe-grid>label.wide{grid-column:span 2}.synqra-nfe-actions{overflow:auto}}`}</style>
 </main>
}
