import { useEffect, useRef, useState, type ReactNode } from 'react'
import { Check, MailCheck, Paperclip, Plus, Save, Search, Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import VendasLayout from './VendasLayout'

type Cliente={id:string;codigo:string|null;nome:string;documento:string|null}
type Produto={id:string;codigo:string;nome:string;unidade:string;unidade_venda:string;estoque_atual:number;preco_venda:number|null;codigo_barras:string|null;referencia_interna:string|null}
type Transportadora={id:string;codigo:string;razao_social:string}
type Item={produto_id:string;codigo:string;descricao:string;quantidade:number;unidade:string;valor_unitario:number;desconto:number;estoque:number;preco_custo_industrial:number}

const inputStyle='h-7 w-full rounded-[2px] border border-gray-200 bg-white px-2 py-0.5 text-[10px] text-gray-800 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500'
const labelStyle='mb-0.5 block text-[9px] font-medium uppercase tracking-wide text-gray-500'
const buttonStyle='flex h-7 items-center justify-center gap-1 rounded-[2px] px-2.5 py-0.5 text-[10px] font-medium'
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(v)?v:0)
const n=(v:string|number)=>Number(v)||0
const digits=(v:string)=>v.replace(/\D/g,'')
const maskCnpj=(v:string)=>{const d=digits(v).slice(0,14);return d.length<=2?d:d.length<=5?`${d.slice(0,2)}.${d.slice(2)}`:d.length<=8?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5)}`:d.length<=12?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8)}`:`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`}
const unit=(v:string)=>{const u=v.toUpperCase();if(['MT','M'].includes(u))return 'MT';if(['PÇ','PC','PCS'].includes(u))return 'PÇ';if(['LT','L'].includes(u))return 'LT';if(u==='MM')return 'MM';return u||'UN'}

function Field({label,width,grow=false,children}:{label:string;width?:string;grow?:boolean;children:ReactNode}){return <div className={`${width?'shrink-0':'min-w-0'} ${grow?'flex-1':''}`} style={width?{width}:undefined}><label className={labelStyle}>{label}</label>{children}</div>}

export default function NovoPedido(){
 const [empresaId,setEmpresaId]=useState(''),[clientes,setClientes]=useState<Cliente[]>([]),[produtos,setProdutos]=useState<Produto[]>([]),[transportadoras,setTransportadoras]=useState<Transportadora[]>([])
 const [edPedido,setEdPedido]=useState(''),[edDataEntrada,setEdDataEntrada]=useState(new Date().toISOString().slice(0,10)),[edDataEntrega,setEdDataEntrega]=useState('')
 const [clienteModo,setClienteModo]=useState<'Código'|'CNPJ'>('Código'),[edCodigoCliente,setEdCodigoCliente]=useState(''),[edNomeCliente,setEdNomeCliente]=useState(''),[cliente,setCliente]=useState<Cliente|null>(null)
 const [edCondicaoPagamento,setEdCondicaoPagamento]=useState('001 - À Vista'),[edFormaPagto,setEdFormaPagto]=useState('001 - PIX'),[edCfop,setEdCfop]=useState('5101'),[edFreteTipo,setEdFreteTipo]=useState(''),[edOrigem,setEdOrigem]=useState('Telefone'),[transportadora,setTransportadora]=useState('')
 const [edCodigoInterno,setEdCodigoInterno]=useState(''),[edDescricaoProduto,setEdDescricaoProduto]=useState(''),[edQuantidade,setEdQuantidade]=useState('1'),[edUnidade,setEdUnidade]=useState('UN'),[edValorUnitario,setEdValorUnitario]=useState('0'),[edDescontoPercentual,setEdDescontoPercentual]=useState('0'),[edPrecoCustoIndustrial,setEdPrecoCustoIndustrial]=useState('0')
 const [gridItens,setGridItens]=useState<Item[]>([]),[pedidoId,setPedidoId]=useState<string|null>(null),[frete,setFrete]=useState('0'),[outras,setOutras]=useState('0')
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[consulta,setConsulta]=useState<'cliente'|'produto'|'transportadora'|null>(null),[busca,setBusca]=useState('')
 const clienteRef=useRef<HTMLInputElement>(null),produtoRef=useRef<HTMLInputElement>(null),fileRef=useRef<HTMLInputElement>(null)

 const load=async()=>{
  const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.')
  const id=String(e.data);setEmpresaId(id)
  const [c,p,t]=await Promise.all([
   supabase.from('erp_clientes').select('id,codigo,nome,documento').eq('empresa_id',id).eq('ativo',true).order('nome').limit(3000),
   supabase.from('erp_produtos').select('id,codigo,nome,unidade,unidade_venda,estoque_atual,preco_venda,codigo_barras,referencia_interna').eq('empresa_id',id).eq('ativo',true).order('codigo').limit(5000),
   supabase.from('erp_transportadoras').select('id,codigo,razao_social').eq('empresa_id',id).eq('ativo',true).order('codigo').limit(1000)
  ])
  if(c.error)throw c.error;if(p.error)throw p.error;if(t.error)throw t.error
  setClientes((c.data??[]) as Cliente[]);setProdutos((p.data??[]) as Produto[]);setTransportadoras((t.data??[]) as Transportadora[])
 }
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar Novo Pedido.'))},[])

 const clienteBusca=async(v:string)=>{const raw=v.trim(),q=clienteModo==='CNPJ'?digits(raw):raw.toLowerCase();const found=clientes.find(c=>clienteModo==='CNPJ'?digits(c.documento??'')===q:(c.codigo??'').toLowerCase()===q);if(found){setCliente(found);setEdNomeCliente(found.nome);setEdCodigoCliente(clienteModo==='CNPJ'?maskCnpj(found.documento??q):(found.codigo??q));setError('');return}if(clienteModo!=='CNPJ'||q.length!==14){setError('Cliente não localizado no cadastro.');return}setLoading(true);try{const r=await supabase.functions.invoke('consultar-cnpj',{body:{cnpj:q}});if(r.error)throw r.error;const data=r.data as {razao_social?:string};const ins=await supabase.from('erp_clientes').insert({empresa_id:empresaId,nome:data.razao_social??'',documento:q,ativo:true}).select('id,codigo,nome,documento').single();if(ins.error)throw ins.error;const novo=ins.data as Cliente;setClientes(v=>[novo,...v]);setCliente(novo);setEdNomeCliente(novo.nome);setEdCodigoCliente(maskCnpj(q));setMessage('Cliente consultado na internet e incluído no cadastro.')}catch(e){setError(e instanceof Error?e.message:'Falha na consulta pública do CNPJ.')}finally{setLoading(false)}}
 const produtoBusca=async(v:string)=>{const q=v.trim().toLowerCase();const p=produtos.find(x=>[x.codigo,x.codigo_barras,x.referencia_interna].filter(Boolean).some(y=>String(y).toLowerCase()===q));if(!p){setEdDescricaoProduto('');setError('Produto/SKU não localizado.');return}setEdDescricaoProduto(p.nome);setEdCodigoInterno(p.codigo);setEdUnidade(unit(p.unidade_venda||p.unidade));setEdValorUnitario(String(p.preco_venda??0));const custo=await supabase.rpc('erp_obter_custo_industrial_produto',{p_produto_id:p.id});if(!custo.error)setEdPrecoCustoIndustrial(String(Number(custo.data??0)));setError('');if(cliente){const r=await supabase.rpc('erp_calcular_preco_sugerido_venda',{p_cliente_id:cliente.id,p_produto_id:p.id});const row=Array.isArray(r.data)?r.data[0]:r.data;if(!r.error&&row?.preco_sugerido!=null)setEdValorUnitario(String(row.preco_sugerido))}}

 const add=async()=>{const p=produtos.find(x=>x.codigo===edCodigoInterno);if(!p||n(edQuantidade)<=0){setError('Informe um produto válido e quantidade maior que zero.');return}let custo=n(edPrecoCustoIndustrial);if(custo===0){const r=await supabase.rpc('erp_obter_custo_industrial_produto',{p_produto_id:p.id});if(!r.error)custo=Number(r.data??0)}setGridItens(v=>[...v,{produto_id:p.id,codigo:p.codigo,descricao:p.nome,quantidade:n(edQuantidade),unidade:edUnidade,valor_unitario:n(edValorUnitario),desconto:n(edDescontoPercentual),estoque:n(p.estoque_atual),preco_custo_industrial:custo}]);setEdCodigoInterno('');setEdDescricaoProduto('');setEdQuantidade('1');setEdUnidade('UN');setEdValorUnitario('0');setEdDescontoPercentual('0');setEdPrecoCustoIndustrial('0');produtoRef.current?.focus()}
 const subtotal=gridItens.reduce((s,i)=>s+Math.max(i.quantidade*i.valor_unitario*(1-i.desconto/100),0),0),total=Math.max(subtotal+n(frete)+n(outras),0)

 const save=async(finalize:boolean)=>{if(!cliente){setError('Informe o cliente.');return}if(!gridItens.length){setError('Inclua pelo menos um item.');return}setLoading(true);setError('');try{const r=await supabase.rpc(finalize?'erp_finalizar_pedido_venda':'erp_gravar_rascunho_pedido_venda',{p_pedido_id:pedidoId,p_cliente_id:cliente.id,p_itens:gridItens.map(i=>({produto_id:i.produto_id,quantidade:i.quantidade,valor_unitario:i.valor_unitario,desconto:i.desconto,codigo:i.codigo,preco_custo_industrial:i.preco_custo_industrial})),p_data_entrada:edDataEntrada,p_data_entrega:edDataEntrega||null,p_pedido_cliente:null,p_observacoes:null,p_condicao_pagamento:edCondicaoPagamento,p_vendedor_nome:null,p_modalidade_frete:edFreteTipo||null,p_transportadora_id:transportadora?(transportadoras.find(t=>t.codigo===transportadora)?.id??null):null,p_via_entrada:edOrigem,p_cfop:edCfop,p_forma_pagamento:edFormaPagto,p_desconto:0,p_valor_frete:n(frete),p_valor_outras_despesas:n(outras)});if(r.error)throw r.error;setPedidoId(String(r.data));setEdPedido(String(r.data));setMessage(finalize?'Pedido finalizado.':'Rascunho gravado no PostgreSQL.')}catch(e){setError(e instanceof Error?e.message:'Falha ao gravar pedido.')}finally{setLoading(false)}}
 const importar=async()=>{setLoading(true);setError('');try{const r=await supabase.functions.invoke('vendas-importar-email',{body:{action:'drafts'}});if(r.error)throw r.error;setEdOrigem('E-mail');setMessage('Importação executada. Consulte o pedido retornado no banco para conferência.')}catch(e){setError(e instanceof Error?e.message:'Falha na importação de e-mail.')}finally{setLoading(false)}}
 const anexar=async(f:File)=>{if(!pedidoId){setError('Grave o pedido antes de anexar a origem.');return}setLoading(true);try{const path=empresaId+'/'+pedidoId+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await supabase.storage.from('pedidos-origem').upload(path,f,{contentType:f.type||'application/octet-stream'});if(u.error)throw u.error;const a=await supabase.from('erp_pedidos_anexos').insert({empresa_id:empresaId,pedido_id:pedidoId,url_arquivo:path,nome_arquivo:f.name});if(a.error)throw a.error;setMessage('Origem anexada e auditada.')}catch(e){setError(e instanceof Error?e.message:'Falha ao anexar origem.')}finally{setLoading(false)}}
 const clientesFiltro=clientes.filter(c=>!busca||c.nome.toLowerCase().includes(busca.toLowerCase())||(c.codigo??'').toLowerCase().includes(busca.toLowerCase())).slice(0,40)
 const transportadorasFiltro=transportadoras.filter(t=>!busca||t.codigo.toLowerCase().includes(busca.toLowerCase())||t.razao_social.toLowerCase().includes(busca.toLowerCase())).slice(0,40)
 const produtosFiltro=produtos.filter(p=>{const q=busca.toLowerCase();return !q||p.codigo.toLowerCase().includes(q)||p.nome.toLowerCase().includes(q)||(p.referencia_interna??'').toLowerCase().includes(q)||(p.codigo_barras??'').toLowerCase().includes(q)}).slice(0,40)

 return <VendasLayout title="Novo Pedido de Venda" subtitle="Entrada comercial → estoque → PCP" onRefresh={()=>void load()}>
  <div id="frmNovoPedido" className="erp-compact w-full space-y-2 bg-slate-50 text-[11px]">
   {(error||message)&&<div className={`border px-2 py-1 text-[10px] ${error?'border-red-200 bg-red-50 text-red-800':'border-green-200 bg-green-50 text-green-800'}`}>{error||message}</div>}
   <section className="rounded-[2px] border border-gray-200 bg-white p-2">
    <div className="mb-2 text-[10px] font-medium text-gray-700">IDENTIFICAÇÃO DO PEDIDO</div>
    <div className="mb-2 grid grid-cols-[95px_125px_80px_120px_minmax(220px,1fr)] items-end gap-2"><Field label="Nº Pedido" width="95px"><input id="edPedido" value={edPedido} readOnly className={`${inputStyle} bg-gray-100 font-medium border-dashed text-gray-500 cursor-not-allowed`}/></Field><Field label="Data Entrada" width="125px"><input id="edDataEntrada" type="date" value={edDataEntrada} onChange={e=>setEdDataEntrada(e.target.value)} className={inputStyle}/></Field><Field label="Busca Cliente" width="80px"><select value={clienteModo} onChange={e=>{const m=e.target.value as 'Código'|'CNPJ';setClienteModo(m);setEdCodigoCliente('')}} className={inputStyle}><option>Código</option><option>CNPJ</option></select></Field><Field label="Código / CNPJ" width="120px"><div className="flex gap-1"><input id="edCodigoCliente" ref={clienteRef} value={clienteModo==='CNPJ'?maskCnpj(edCodigoCliente):edCodigoCliente} onChange={e=>setEdCodigoCliente(clienteModo==='CNPJ'?digits(e.target.value):e.target.value)} onBlur={e=>void clienteBusca(e.target.value)} className={inputStyle}/><button type="button" onClick={()=>{setBusca('');setConsulta('cliente')}} className="h-7 w-7 shrink-0 rounded border border-gray-200 bg-gray-100"><Search size={12}/></button></div></Field></div>
<Field label="Razão Social" grow><input id="edNomeCliente" title={edNomeCliente} value={edNomeCliente} readOnly className={`${inputStyle} min-w-0 text-ellipsis overflow-hidden`}/></Field></div></div>
    <div className="grid grid-cols-[125px_140px_140px_70px_80px_100px_minmax(180px,1fr)] items-end gap-2"><Field label="Data Entrega" width="125px"><input id="edDataEntrega" type="date" value={edDataEntrega} onChange={e=>setEdDataEntrega(e.target.value)} className={inputStyle}/></Field><Field label="Condição" width="140px"><input id="edCondicaoPagamento" value={edCondicaoPagamento} onChange={e=>setEdCondicaoPagamento(e.target.value)} className={inputStyle}/></Field><Field label="Forma Pgto" width="140px"><input id="edFormaPagto" value={edFormaPagto} onChange={e=>setEdFormaPagto(e.target.value)} className={inputStyle}/></Field><Field label="CFOP" width="70px"><input id="edCfop" maxLength={4} value={edCfop} onChange={e=>setEdCfop(e.target.value.replace(/\D/g,'').slice(0,4))} className={inputStyle}/></Field><Field label="Frete" width="80px"><select id="edFreteTipo" value={edFreteTipo} onChange={e=>setEdFreteTipo(e.target.value)} className={inputStyle}><option value="">—</option><option value="CIF">CIF</option><option value="FOB">FOB</option></select></Field><Field label="Origem" width="100px"><select id="edOrigem" value={edOrigem} onChange={e=>setEdOrigem(e.target.value)} className={inputStyle}><option>E-mail</option><option>WhatsApp</option><option>Telefone</option><option>Representante</option></select></Field><Field label="Transportadora" grow><div className="flex gap-1"><input id="edTransportadora" value={transportadora} onChange={e=>setTransportadora(e.target.value)} className={inputStyle}/><button type="button" onClick={()=>{setBusca(transportadora);setConsulta("transportadora")}} className="h-7 w-7 shrink-0 rounded border border-gray-200 bg-gray-100"><Search size={12}/></button></div></Field></div>
   </section>
   <section className="flex items-end gap-2 rounded-sm border border-gray-200 bg-white p-1.5"><Field label="Cód. Prod." width="124px"><div className="flex gap-1"><input id="edCodigoInterno" ref={produtoRef} autoFocus value={edCodigoInterno} onChange={e=>setEdCodigoInterno(e.target.value)} onBlur={e=>void produtoBusca(e.target.value)} className={inputStyle}/><button type="button" onClick={()=>{setBusca('');setConsulta('produto')}} className="h-7 w-7 shrink-0 rounded border border-gray-200 bg-gray-100"><Search size={12}/></button></div></Field><Field label="Descrição Produto" grow><input id="edDescricaoProduto" value={edDescricaoProduto} readOnly className={inputStyle}/></Field><Field label="Qtd" width="60px"><input id="edQuantidade" type="number" value={edQuantidade} onChange={e=>setEdQuantidade(e.target.value)} className={inputStyle}/></Field><Field label="Un" width="50px"><select id="edUnidade" value={edUnidade} onChange={e=>setEdUnidade(e.target.value)} className={inputStyle}><option>MT</option><option>PÇ</option><option>LT</option><option>MM</option><option>UN</option></select></Field><Field label="Preço" width="90px"><input id="edValorUnitario" type="number" value={edValorUnitario} onChange={e=>setEdValorUnitario(e.target.value)} className={inputStyle}/></Field><Field label="Desc. %" width="60px"><input id="edDescontoPercentual" type="number" value={edDescontoPercentual} onChange={e=>setEdDescontoPercentual(e.target.value)} className={inputStyle}/></Field><button id="btnAdicionarItem" type="button" onClick={add} className="flex h-7 w-8 items-center justify-center rounded bg-blue-600 text-white"><Plus size={12}/></button></section>
   <section id="gridItens" className="h-[180px] overflow-auto rounded-[2px] border border-gray-200 bg-white"><table className="w-full border-collapse text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="px-2 text-left font-normal">Item</th><th className="px-2 text-left font-normal">Código</th><th className="px-2 text-left font-normal">Descrição</th><th className="px-2 text-right font-normal">Qtd</th><th className="px-2 text-left font-normal">Un</th><th className="px-2 text-right font-normal">Preço</th><th className="px-2 text-right font-normal">Desc.%</th><th className="px-2 text-right font-normal">Total</th><th className="px-2 text-right font-normal">Margem</th><th className="px-2 text-center font-normal">Ações</th></tr></thead><tbody>{gridItens.map((i,k)=><tr key={i.produto_id+'-'+k} className="h-7 border-t border-gray-200 even:bg-slate-50"><td className="px-2">{k+1}</td><td className="px-2">{i.codigo}</td><td className="px-2">{i.descricao}</td><td className="px-2 text-right">{i.quantidade}</td><td className="px-2">{i.unidade}</td><td className="px-2 text-right">{brl(i.valor_unitario)}</td><td className="px-2 text-right">{i.desconto.toFixed(2)}</td><td className="px-2 text-right font-medium">{brl(i.quantidade*i.valor_unitario*(1-i.desconto/100))}</td><td className="px-2 text-right font-medium text-gray-500">{(() => { const venda=i.quantidade*i.valor_unitario*(1-i.desconto/100); const custo=i.quantidade*i.preco_custo_industrial; return venda>0?((venda-custo)/venda*100).toFixed(1)+"%":"0.0%" })()}</td><td className="px-2 text-center"><button type="button" onClick={()=>setGridItens(v=>v.filter((_,x)=>x!==k))} className="inline-flex h-7 w-7 items-center justify-center rounded-[2px] border border-gray-200"><Trash2 size={11}/></button></td></tr>)}{!gridItens.length&&<tr><td colSpan={10} className="h-16 text-center text-[10px] text-gray-400">Nenhum item lançado.</td></tr>}</tbody></table></section>
   <section className="flex items-end justify-between gap-4 rounded-sm border border-gray-200 bg-white p-2"><div className="flex items-end gap-2"><Field label="Frete R$" width="100px"><input value={frete} onChange={e=>setFrete(e.target.value)} className={inputStyle}/></Field><Field label="Outras R$" width="100px"><input value={outras} onChange={e=>setOutras(e.target.value)} className={inputStyle}/></Field></div><div className="flex gap-4 text-[11px]"><span>Subtotal: <b>{brl(subtotal)}</b></span><span className="font-medium text-blue-700">Total Líquido: {brl(total)}</span></div></section>
   <div className="flex w-full items-center justify-end gap-2 border-t border-gray-200 pt-3"><input ref={fileRef} type="file" className="hidden" accept=".eml,.msg,.pdf,.png,.jpg,.jpeg,.webp" onChange={e=>{const f=e.target.files?.[0];if(f)void anexar(f);e.currentTarget.value=''}}/><button id="btnAnexar" type="button" onClick={()=>fileRef.current?.click()} className={`${buttonStyle} border border-gray-300 bg-gray-100 text-gray-700`}><Paperclip size={12}/>Anexar Origem</button><button id="btnImportarEmail" type="button" disabled={loading} onClick={()=>void importar()} className={`${buttonStyle} bg-green-600 text-white`}><MailCheck size={12}/>Importar E-mail</button><button id="btnGravar" type="button" disabled={loading} onClick={()=>void save(false)} className={`${buttonStyle} bg-blue-600 text-white`}><Save size={12}/>Salvar rascunho</button><button id="btnFinalizar" type="button" disabled={loading} onClick={()=>void save(true)} className={`${buttonStyle} bg-emerald-700 text-white`}><Check size={12}/>Finalizar pedido</button><button id="btnLimpar" type="button" onClick={()=>{setGridItens([]);setPedidoId(null);setEdPedido('');setEdCodigoCliente('');setEdNomeCliente('');setCliente(null);setError('');setMessage('')}} className={`${buttonStyle} bg-gray-500 text-white`}><Trash2 size={12}/>Limpar</button></div>
   {consulta&&<div className="fixed inset-0 z-50 flex items-start justify-center bg-black/10 pt-24" onMouseDown={()=>setConsulta(null)}><div className="w-[min(760px,92vw)] rounded-sm border border-gray-300 bg-white shadow-xl" onMouseDown={e=>e.stopPropagation()}><div className="flex h-8 items-center justify-between border-b px-2 text-[11px] font-medium"><span>{consulta==='cliente'?'CONSULTA DE CLIENTES':consulta==='transportadora'?'CONSULTA DE TRANSPORTADORAS':'CONSULTA DE PRODUTOS'}</span><button type="button" onClick={()=>setConsulta(null)} className="h-7 w-7 rounded border border-gray-200">×</button></div><div className="p-2"><input autoFocus value={busca} onChange={e=>setBusca(e.target.value)} className={inputStyle}/><div className="mt-2 max-h-72 overflow-auto border">{consulta==='cliente'?clientesFiltro.map(c=><button type="button" key={c.id} onClick={()=>{setCliente(c);setEdCodigoCliente(c.codigo??c.documento??'');setEdNomeCliente(c.nome);setConsulta(null)}} className="grid w-full grid-cols-[110px_1fr_160px] border-b px-2 py-1 text-left text-[10px] hover:bg-slate-50"><span>{c.codigo??''}</span><span>{c.nome}</span><span>{c.documento??''}</span></button>):consulta==='transportadora'?transportadorasFiltro.map(t=><button type="button" key={t.id} onClick={()=>{setTransportadora(t.codigo);setConsulta(null)}} className="grid w-full grid-cols-[120px_1fr] border-b px-2 py-1 text-left text-[10px] hover:bg-slate-50"><span>{t.codigo}</span><span>{t.razao_social}</span></button>):produtosFiltro.map(p=><button type="button" key={p.id} onClick={()=>{void produtoBusca(p.codigo);setConsulta(null)}} className="grid w-full grid-cols-[110px_1fr_70px_90px] border-b px-2 py-1 text-left text-[10px] hover:bg-slate-50"><span>{p.codigo}</span><span>{p.nome}</span><span>{unit(p.unidade_venda||p.unidade)}</span><span>{n(p.estoque_atual)}</span></button>)}</div></div></div></div>}
  </div>
 </VendasLayout>
}
