import { useEffect, useRef, useState, type ReactNode } from 'react'
import { Check, Edit3, FilePlus2, MailCheck, Paperclip, Plus, Save, Search, Trash2, XCircle, Printer } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import { fetchAllPages } from '../lib/supabasePagination'
import VendasLayout from './VendasLayout'

type Cliente={id:string;codigo:string|null;nome:string;documento:string|null}
type Produto={id:string;codigo:string;nome:string;unidade:string;unidade_venda:string;estoque_atual:number;preco_venda:number|null;codigo_barras:string|null;referencia_interna:string|null}
type Transportadora={id:string;codigo:string;razao_social:string}
type Vendedor={id:string;nome:string}
type Item={produto_id:string;codigo:string;descricao:string;quantidade:number;unidade:string;valor_unitario:number;desconto:number;estoque:number;preco_custo_industrial:number}

const inputStyle='h-[30px] w-full rounded-[2px] border border-gray-300 bg-white px-1.5 py-0.5 text-[11px] leading-4 text-gray-800 outline-none focus:border-blue-600 focus:ring-0'
const labelStyle='mb-0.5 block text-[9px] font-medium uppercase tracking-wide text-gray-500'
const buttonStyle='flex h-[30px] items-center justify-center gap-1 rounded-[2px] px-2.5 py-0.5 text-[11px] font-medium'
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(v)?v:0)
const n=(v:string|number)=>Number(v)||0
const digits=(v:string)=>v.replace(/\D/g,'')
const maskCnpj=(v:string)=>{const d=digits(v).slice(0,14);return d.length<=2?d:d.length<=5?`${d.slice(0,2)}.${d.slice(2)}`:d.length<=8?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5)}`:d.length<=12?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8)}`:`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`}
const unit=(v:string)=>{const u=v.toUpperCase();if(['MT','M'].includes(u))return 'MT';if(['PÇ','PC','PCS'].includes(u))return 'PÇ';if(['LT','L'].includes(u))return 'LT';if(u==='MM')return 'MM';return u||'UN'}

function Field({label,width,grow=false,required=false,children}:{label:string;width?:string;grow?:boolean;required?:boolean;children:ReactNode}){return <div className={`${width?'shrink-0':'min-w-0'} ${grow?'flex-1':''}`} style={width?{width}:undefined}><label className={labelStyle}>{label}{required&&<span className="ml-0.5 text-red-600" aria-hidden="true">*</span>}</label>{children}</div>}

export default function NovoPedido(){
 const [empresaId,setEmpresaId]=useState(''),[clientes,setClientes]=useState<Cliente[]>([]),[produtos,setProdutos]=useState<Produto[]>([]),[transportadoras,setTransportadoras]=useState<Transportadora[]>([]),[vendedores,setVendedores]=useState<Vendedor[]>([])
 const [edPedido,setEdPedido]=useState(''),[edDataEntrada,setEdDataEntrada]=useState(new Date().toISOString().slice(0,10)),[edDataEntrega,setEdDataEntrega]=useState('')
 const [clienteModo,setClienteModo]=useState<'Código'|'CNPJ'>('Código'),[edCodigoCliente,setEdCodigoCliente]=useState(''),[edNomeCliente,setEdNomeCliente]=useState(''),[cliente,setCliente]=useState<Cliente|null>(null)
 const [edCondicaoPagamento,setEdCondicaoPagamento]=useState('001 - À Vista'),[edFormaPagto,setEdFormaPagto]=useState('001 - PIX'),[edCfop,setEdCfop]=useState('5101'),[edFreteTipo,setEdFreteTipo]=useState(''),[edOrigem,setEdOrigem]=useState('Telefone'),[transportadora,setTransportadora]=useState(''),[vendedorNome,setVendedorNome]=useState('')
 const [edCodigoInterno,setEdCodigoInterno]=useState(''),[edDescricaoProduto,setEdDescricaoProduto]=useState(''),[edQuantidade,setEdQuantidade]=useState('1'),[edUnidade,setEdUnidade]=useState('UN'),[edValorUnitario,setEdValorUnitario]=useState('0'),[edDescontoPercentual,setEdDescontoPercentual]=useState('0'),[edPrecoCustoIndustrial,setEdPrecoCustoIndustrial]=useState('0')
 const [gridItens,setGridItens]=useState<Item[]>([]),[pedidoId,setPedidoId]=useState<string|null>(null),[frete,setFrete]=useState('0'),[outras,setOutras]=useState('0')
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[selectedItem,setSelectedItem]=useState<number|null>(null),[editingItem,setEditingItem]=useState<number|null>(null),[validationField,setValidationField]=useState<'cliente'|'produto'|'quantidade'|'dataEntrega'|'condicao'|'formaPagto'|'cfop'|'frete'|'origem'|'vendedor'|null>(null),[consulta,setConsulta]=useState<'cliente'|'produto'|'transportadora'|null>(null),[busca,setBusca]=useState('')
 const clienteRef=useRef<HTMLInputElement>(null),produtoRef=useRef<HTMLInputElement>(null),fileRef=useRef<HTMLInputElement>(null)

 const load=async()=>{
  const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.')
  const id=String(e.data);setEmpresaId(id)
  const [c,p,t,v]=await Promise.all([
   fetchAllPages<Cliente>((from,to)=>supabase.from('erp_clientes').select('id,codigo,nome,documento',{count:'exact'}).eq('empresa_id',id).eq('ativo',true).order('nome').range(from,to)),
   fetchAllPages<Produto>((from,to)=>supabase.from('erp_produtos').select('id,codigo,nome,unidade,unidade_venda,estoque_atual,preco_venda,codigo_barras,referencia_interna',{count:'exact'}).eq('empresa_id',id).eq('ativo',true).order('codigo').range(from,to)),
   fetchAllPages<Transportadora>((from,to)=>supabase.from('erp_transportadoras').select('id,codigo,razao_social',{count:'exact'}).eq('empresa_id',id).eq('ativo',true).order('codigo').range(from,to)),
   fetchAllPages<Vendedor>((from,to)=>supabase.from('erp_usuarios').select('id,nome',{count:'exact'}).eq('empresa_id',id).eq('ativo',true).is('deleted_at',null).order('nome').range(from,to))
  ])
  setClientes(c);setProdutos(p);setTransportadoras(t);setVendedores(v)
  const auth=await supabase.auth.getUser()
  const authUserId=auth.data.user?.id
  if(authUserId){
   const current=await supabase.from('erp_usuarios').select('id,nome').eq('empresa_id',id).eq('auth_user_id',authUserId).eq('ativo',true).is('deleted_at',null).maybeSingle()
   if(!current.error&&current.data?.nome)setVendedorNome(current.data.nome)
  }
 }
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar Novo Pedido.'))},[])

 const clienteBusca=async(v:string)=>{const raw=v.trim(),q=clienteModo==='CNPJ'?digits(raw):raw.toLowerCase();const found=clientes.find(c=>clienteModo==='CNPJ'?digits(c.documento??'')===q:(c.codigo??'').toLowerCase()===q);if(found){setCliente(found);setEdNomeCliente(found.nome);setEdCodigoCliente(clienteModo==='CNPJ'?maskCnpj(found.documento??q):(found.codigo??q));setError('');return}if(clienteModo!=='CNPJ'||q.length!==14){setError('Cliente não localizado no cadastro.');return}setLoading(true);try{const r=await supabase.functions.invoke('consultar-cnpj',{body:{cnpj:q}});if(r.error)throw r.error;const data=r.data as {razao_social?:string};const ins=await supabase.from('erp_clientes').insert({empresa_id:empresaId,nome:data.razao_social??'',documento:q,ativo:true}).select('id,codigo,nome,documento').single();if(ins.error)throw ins.error;const novo=ins.data as Cliente;setClientes(v=>[novo,...v]);setCliente(novo);setEdNomeCliente(novo.nome);setEdCodigoCliente(maskCnpj(q));setMessage('Cliente consultado na internet e incluído no cadastro.')}catch(e){setError(e instanceof Error?e.message:'Falha na consulta pública do CNPJ.')}finally{setLoading(false)}}
 const produtoBusca=async(v:string)=>{const q=v.trim().toLowerCase();const p=produtos.find(x=>[x.codigo,x.codigo_barras,x.referencia_interna].filter(Boolean).some(y=>String(y).toLowerCase()===q));if(!p){setEdDescricaoProduto('');setError('Produto/SKU não localizado.');return}setEdDescricaoProduto(p.nome);setEdCodigoInterno(p.codigo);setEdUnidade(unit(p.unidade_venda||p.unidade));setEdValorUnitario(String(p.preco_venda??0));const custo=await supabase.rpc('erp_obter_custo_industrial_produto',{p_produto_id:p.id});if(!custo.error)setEdPrecoCustoIndustrial(String(Number(custo.data??0)));setError('');if(cliente){const r=await supabase.rpc('erp_calcular_preco_sugerido_venda',{p_cliente_id:cliente.id,p_produto_id:p.id});const row=Array.isArray(r.data)?r.data[0]:r.data;if(!r.error&&row?.preco_sugerido!=null)setEdValorUnitario(String(row.preco_sugerido))}}

 const add=async()=>{const p=produtos.find(x=>x.codigo===edCodigoInterno);if(!p){setValidationField('produto');setError('');produtoRef.current?.focus();return}if(n(edQuantidade)<=0){setValidationField('quantidade');setError('');return}setValidationField(null);let custo=n(edPrecoCustoIndustrial);if(custo===0){const r=await supabase.rpc('erp_obter_custo_industrial_produto',{p_produto_id:p.id});if(!r.error)custo=Number(r.data??0)}setGridItens(v=>{const next={produto_id:p.id,codigo:p.codigo,descricao:p.nome,quantidade:n(edQuantidade),unidade:edUnidade,valor_unitario:n(edValorUnitario),desconto:n(edDescontoPercentual),estoque:n(p.estoque_atual),preco_custo_industrial:custo};if(editingItem===null)return [...v,next];return v.map((item,index)=>index===editingItem?next:item)});setEdCodigoInterno('');setEdDescricaoProduto('');setEdQuantidade('1');setEdUnidade('UN');setEdValorUnitario('0');setEdDescontoPercentual('0');setEdPrecoCustoIndustrial('0');setSelectedItem(null);setEditingItem(null);produtoRef.current?.focus()}
 const novoPedido=()=>{setGridItens([]);setPedidoId(null);setEditingItem(null);setEdPedido('');setEdCodigoCliente('');setEdNomeCliente('');setCliente(null);setFrete('0');setOutras('0');setValidationField(null);setError('');setMessage('');setSelectedItem(null);clienteRef.current?.focus()}
 const editarItemSelecionado=()=>{if(selectedItem===null)return;const item=gridItens[selectedItem];if(!item)return;setEditingItem(selectedItem);setEdCodigoInterno(item.codigo);setEdDescricaoProduto(item.descricao);setEdQuantidade(String(item.quantidade));setEdUnidade(item.unidade);setEdValorUnitario(String(item.valor_unitario));setEdDescontoPercentual(String(item.desconto));setEdPrecoCustoIndustrial(String(item.preco_custo_industrial));produtoRef.current?.focus()}
 const excluirItemSelecionado=()=>{if(selectedItem===null)return;setGridItens(v=>v.filter((_,index)=>index!==selectedItem));setSelectedItem(null);setEditingItem(null)}
 const subtotal=gridItens.reduce((s,i)=>s+Math.max(i.quantidade*i.valor_unitario*(1-i.desconto/100),0),0),total=Math.max(subtotal+n(frete)+n(outras),0)

 const save=async(finalize:boolean)=>{if(!cliente){setValidationField('cliente');setError('');clienteRef.current?.focus();return}if(!edDataEntrega){setValidationField('dataEntrega');setError('');return}if(!edCondicaoPagamento.trim()){setValidationField('condicao');setError('');return}if(!edFormaPagto.trim()){setValidationField('formaPagto');setError('');return}if(!edCfop.trim()){setValidationField('cfop');setError('');return}if(!edFreteTipo.trim()){setValidationField('frete');setError('');return}if(!edOrigem.trim()){setValidationField('origem');setError('');return}if(!vendedorNome.trim()){setValidationField('vendedor');setError('');return}if(!gridItens.length){setValidationField('produto');setError('');produtoRef.current?.focus();return}setValidationField(null);setLoading(true);setError('');try{const payload={p_cliente_id:cliente.id,p_itens:gridItens.map(i=>({produto_id:i.produto_id,quantidade:i.quantidade,valor_unitario:i.valor_unitario,desconto:Number((i.quantidade*i.valor_unitario*i.desconto/100).toFixed(2)),codigo:i.codigo,preco_custo_industrial:i.preco_custo_industrial})),p_data_entrada:edDataEntrada,p_data_entrega:edDataEntrega||null,p_pedido_cliente:null,p_observacoes:null,p_condicao_pagamento:edCondicaoPagamento,p_vendedor_nome:vendedorNome.trim(),p_modalidade_frete:edFreteTipo||null,p_transportadora_id:transportadora?(transportadoras.find(t=>t.codigo===transportadora)?.id??null):null,p_via_entrada:edOrigem,p_cfop:edCfop,p_forma_pagamento:edFormaPagto,p_desconto:0,p_valor_frete:n(frete),p_valor_outras_despesas:n(outras)};const r=finalize?await supabase.rpc('erp_finalizar_pedido_venda',payload):await supabase.rpc('erp_gravar_rascunho_pedido_venda',{p_pedido_id:pedidoId,...payload});if(r.error)throw r.error;setPedidoId(String(r.data));const pedido=await supabase.from('erp_pedidos_venda').select('numero').eq('id',String(r.data)).eq('empresa_id',empresaId).single();if(pedido.error)throw pedido.error;setEdPedido(String(pedido.data.numero));setMessage(finalize?'Pedido finalizado.':'Rascunho gravado no PostgreSQL.')}catch(e){setError(e instanceof Error?e.message:'Falha ao gravar pedido.')}finally{setLoading(false)}}
 const importar=async()=>{setLoading(true);setError('');try{const r=await supabase.functions.invoke('vendas-importar-email',{body:{action:'drafts'}});if(r.error)throw r.error;setEdOrigem('E-mail');setMessage('Importação executada. Consulte o pedido retornado no banco para conferência.')}catch(e){setError(e instanceof Error?e.message:'Falha na importação de e-mail.')}finally{setLoading(false)}}
 const anexar=async(f:File)=>{if(!pedidoId){setError('Grave o pedido antes de anexar a origem.');return}setLoading(true);try{const path=empresaId+'/'+pedidoId+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await supabase.storage.from('pedidos-origem').upload(path,f,{contentType:f.type||'application/octet-stream'});if(u.error)throw u.error;const a=await supabase.from('erp_pedidos_anexos').insert({empresa_id:empresaId,pedido_id:pedidoId,url_arquivo:path,nome_arquivo:f.name});if(a.error)throw a.error;setMessage('Origem anexada e auditada.')}catch(e){setError(e instanceof Error?e.message:'Falha ao anexar origem.')}finally{setLoading(false)}}
 const clientesFiltro=clientes.filter(c=>!busca||c.nome.toLowerCase().includes(busca.toLowerCase())||(c.codigo??'').toLowerCase().includes(busca.toLowerCase())).slice(0,40)
 const transportadorasFiltro=transportadoras.filter(t=>!busca||t.codigo.toLowerCase().includes(busca.toLowerCase())||t.razao_social.toLowerCase().includes(busca.toLowerCase())).slice(0,40)
 const produtosFiltro=produtos.filter(p=>{const q=busca.toLowerCase();return !q||p.codigo.toLowerCase().includes(q)||p.nome.toLowerCase().includes(q)||(p.referencia_interna??'').toLowerCase().includes(q)||(p.codigo_barras??'').toLowerCase().includes(q)}).slice(0,40)

 return <VendasLayout title="Novo Pedido de Venda" subtitle="Entrada comercial • estoque • PCP" showStatusCards={false}>
  <div id="frmNovoPedido" className="erp-compact w-full space-y-2 bg-white text-[11px] text-slate-700">
   {message&&<div role="status" className="border border-emerald-200 bg-emerald-50 px-2 py-1.5 text-[10px] text-emerald-800">{message}</div>}
   {error&&<div role="alert" className="border border-red-200 bg-red-50 px-2 py-1.5 text-[10px] text-red-700">{error}</div>}

   <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 pb-2">
    <div><div className="text-[9px] uppercase tracking-wide text-slate-500">Vendas / Pedidos / Novo</div><h2 className="mt-0.5 text-[18px] font-semibold text-slate-800">Entrada de Pedido</h2></div>
    <div className="flex flex-wrap items-center gap-1">
     <span className="mr-1 text-[10px] text-slate-500">{edPedido ? `Pedido nº ${edPedido}` : 'Novo pedido'}</span>
     <button type="button" disabled={loading} onClick={()=>void save(false)} className="flex h-[30px] items-center gap-1 rounded-[2px] border border-blue-700 bg-blue-600 px-3 text-[11px] font-medium text-white hover:bg-blue-700 disabled:opacity-50"><Save size={12}/>Salvar rascunho</button>
     <button type="button" onClick={novoPedido} className="flex h-[30px] items-center gap-1 rounded-[2px] border border-slate-300 bg-white px-2.5 text-[11px] text-slate-700 hover:bg-slate-50"><FilePlus2 size={12}/>Novo pedido</button>
     <input ref={fileRef} type="file" className="hidden" accept=".eml,.msg,.pdf,.png,.jpg,.jpeg,.webp" onChange={e=>{const f=e.target.files?.[0];if(f)void anexar(f);e.currentTarget.value=''}}/>
     <button id="btnAnexar" type="button" onClick={()=>fileRef.current?.click()} className={buttonStyle+' border border-slate-300 bg-white text-slate-700 hover:bg-slate-50'}><Paperclip size={12}/>Anexar origem</button>
     <button id="btnImportarEmail" type="button" disabled={loading} onClick={()=>void importar()} className={buttonStyle+' border border-emerald-700 bg-emerald-600 text-white hover:bg-emerald-700 disabled:opacity-50'}><MailCheck size={12}/>Importar e-mail</button>
     <button id="btnFinalizar" type="button" disabled={loading} onClick={()=>void save(true)} className={buttonStyle+' border border-blue-700 bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50'}><Check size={12}/>Confirmar e finalizar</button>
     <button type="button" onClick={()=>window.print()} className="flex h-[30px] items-center gap-1 rounded-[2px] border border-slate-300 bg-white px-2.5 text-[11px] text-slate-700 hover:bg-slate-50"><Printer size={12}/>Imprimir</button>
     <button type="button" onClick={novoPedido} className="flex h-[30px] items-center gap-1 rounded-[2px] border border-slate-300 bg-white px-2.5 text-[11px] text-slate-700 hover:bg-slate-50"><XCircle size={12}/>Cancelar</button>
    </div>
   </div>

   <div className="grid grid-cols-1 gap-2 xl:grid-cols-3">
    <section className="min-w-0 overflow-hidden rounded-[2px] border border-slate-200 bg-white">
     <h3 className="border-b border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px] font-semibold text-slate-700">Dados do Cliente</h3>
     <div className="grid grid-cols-1 gap-x-2 gap-y-2 p-2 sm:grid-cols-[100px_minmax(0,1fr)]">
      <Field label="Localizar por" width="100%"><select value={clienteModo} onChange={e=>{const m=e.target.value as 'Código'|'CNPJ';setClienteModo(m);setEdCodigoCliente('');setValidationField(null)}} className={inputStyle}><option>Código</option><option>CNPJ</option></select></Field>
      <Field label="Código / CNPJ" required><div className="flex gap-1"><input id="edCodigoCliente" ref={clienteRef} value={clienteModo==='CNPJ'?maskCnpj(edCodigoCliente):edCodigoCliente} onChange={e=>{setEdCodigoCliente(clienteModo==='CNPJ'?digits(e.target.value):e.target.value);setValidationField(null);setError('')}} onBlur={e=>{if(!e.target.value.trim()){setValidationField('cliente');return}void clienteBusca(e.target.value)}} placeholder={validationField==='cliente'?'Preencher...':undefined} className={validationField==='cliente'?inputStyle+' border-red-500 bg-red-50 placeholder:text-red-400':inputStyle}/><button type="button" aria-label="Consultar clientes" onClick={()=>{setBusca('');setConsulta('cliente')}} className="flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-[2px] border border-slate-300 bg-slate-50 text-slate-600 hover:bg-slate-100"><Search size={12}/></button></div></Field>
      <div className="sm:col-span-2"><Field label="Cliente / Razão Social" required><input id="edNomeCliente" title={edNomeCliente} value={edNomeCliente} readOnly onBlur={e=>{if(!e.target.value.trim())setValidationField('cliente')}} placeholder={validationField==='cliente'?'Selecione um cliente cadastrado': 'Selecione um cliente cadastrado'} className={validationField==='cliente'?inputStyle+' border-red-500 bg-red-50 placeholder:text-red-400':inputStyle}/></Field></div>
      <div className="sm:col-span-2"><Field label="CNPJ / CPF"><input value={cliente?.documento??''} readOnly className={inputStyle}/></Field></div>
     </div>
    </section>

    <section className="min-w-0 overflow-hidden rounded-[2px] border border-slate-200 bg-white">
     <h3 className="border-b border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px] font-semibold text-slate-700">Dados do Pedido</h3>
     <div className="grid grid-cols-2 gap-x-2 gap-y-2 p-2">
      <Field label="Nº do Pedido"><input id="edPedido" value={edPedido} readOnly className={inputStyle+' bg-slate-100 font-semibold text-slate-600'}/></Field>
      <Field label="Data do Pedido" required><input id="edDataEntrada" type="date" value={edDataEntrada} onChange={e=>setEdDataEntrada(e.target.value)} className={inputStyle}/></Field>
      <Field label="Condição de Pagamento" required><input id="edCondicaoPagamento" value={edCondicaoPagamento} onChange={e=>{setEdCondicaoPagamento(e.target.value);setValidationField(null)}} onBlur={e=>{if(!e.target.value.trim())setValidationField('condicao')}} className={validationField==='condicao'?inputStyle+' border-red-500 bg-red-50':inputStyle}/></Field>
      <Field label="Forma de Pagamento" required><input id="edFormaPagto" value={edFormaPagto} onChange={e=>{setEdFormaPagto(e.target.value);setValidationField(null)}} onBlur={e=>{if(!e.target.value.trim())setValidationField('formaPagto')}} className={validationField==='formaPagto'?inputStyle+' border-red-500 bg-red-50':inputStyle}/></Field>
      <Field label="CFOP" required><input id="edCfop" maxLength={4} value={edCfop} onChange={e=>{setEdCfop(e.target.value.replace(/\D/g,'').slice(0,4));setValidationField(null)}} onBlur={e=>{if(!e.target.value.trim())setValidationField('cfop')}} className={validationField==='cfop'?inputStyle+' border-red-500 bg-red-50':inputStyle}/></Field>
      <Field label="Origem do Pedido" required><select id="edOrigem" value={edOrigem} onChange={e=>{setEdOrigem(e.target.value);setValidationField(null)}} onBlur={e=>{if(!e.target.value)setValidationField('origem')}} className={validationField==='origem'?inputStyle+' border-red-500 bg-red-50':inputStyle}><option value="">Selecione...</option><option>E-mail</option><option>WhatsApp</option><option>Telefone</option><option>Representante</option></select></Field>
      <div className="col-span-2"><Field label="Vendedor responsável" required><select id="edVendedor" value={vendedorNome} onChange={e=>{setVendedorNome(e.target.value);setValidationField(null)}} onBlur={e=>{if(!e.target.value.trim())setValidationField('vendedor')}} className={validationField==='vendedor'?inputStyle+' border-red-500 bg-red-50':inputStyle}><option value="">Selecione o vendedor responsável</option>{vendedores.map(v=><option key={v.id} value={v.nome}>{v.nome}</option>)}</select></Field></div>
     </div>
    </section>

    <section className="min-w-0 overflow-hidden rounded-[2px] border border-slate-200 bg-white">
     <h3 className="border-b border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px] font-semibold text-slate-700">Entrega e Logística</h3>
     <div className="grid grid-cols-2 gap-x-2 gap-y-2 p-2">
      <Field label="Previsão de Entrega" required><input id="edDataEntrega" type="date" value={edDataEntrega} onChange={e=>{setEdDataEntrega(e.target.value);setValidationField(null)}} onBlur={e=>{if(!e.target.value)setValidationField('dataEntrega')}} className={validationField==='dataEntrega'?inputStyle+' border-red-500 bg-red-50':inputStyle}/></Field>
      <Field label="Tipo de Frete" required><select id="edFreteTipo" value={edFreteTipo} onChange={e=>{setEdFreteTipo(e.target.value);setValidationField(null)}} onBlur={e=>{if(!e.target.value)setValidationField('frete')}} className={validationField==='frete'?inputStyle+' border-red-500 bg-red-50':inputStyle}><option value="">Selecione...</option><option value="CIF">CIF</option><option value="FOB">FOB</option></select></Field>
      <div className="col-span-2"><Field label="Transportadora"><div className="flex gap-1"><select id="edTransportadora" value={transportadora} onChange={e=>setTransportadora(e.target.value)} className={inputStyle}><option value="">Selecione uma transportadora</option>{transportadoras.map(t=><option key={t.id} value={t.codigo}>{t.codigo} — {t.razao_social}</option>)}</select><button type="button" aria-label="Consultar transportadoras" onClick={()=>{setBusca(transportadora);setConsulta('transportadora')}} className="flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-[2px] border border-slate-300 bg-slate-50 text-slate-600 hover:bg-slate-100"><Search size={12}/></button></div></Field></div>
     </div>
    </section>
   </div>

   <section className="overflow-hidden rounded-[2px] border border-slate-200 bg-white">
    <h3 className="border-b border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px] font-semibold text-slate-700">Itens do Pedido</h3>
    <div className="grid grid-cols-2 gap-2 p-2 sm:grid-cols-[100px_minmax(160px,1fr)_70px_60px_100px_75px_auto] sm:items-end">
     <Field label="Código do Produto" width="100%" required><div className="flex gap-1"><input id="edCodigoInterno" ref={produtoRef} value={edCodigoInterno} onChange={e=>{setEdCodigoInterno(e.target.value);setValidationField(null);setError('')}} onBlur={e=>{if(!e.target.value.trim()){setValidationField('produto');return}void produtoBusca(e.target.value)}} placeholder={validationField==='produto'?'Preencher...':'Código / SKU'} className={validationField==='produto'?inputStyle+' border-red-500 bg-red-50 placeholder:text-red-400':inputStyle}/><button type="button" aria-label="Consultar produtos" onClick={()=>{setBusca('');setConsulta('produto')}} className="flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-[2px] border border-slate-300 bg-slate-50 text-slate-600 hover:bg-slate-100"><Search size={12}/></button></div></Field>
     <Field label="Descrição do Produto" width="100%"><input id="edDescricaoProduto" value={edDescricaoProduto} readOnly className={inputStyle+' bg-slate-50'}/></Field>
     <Field label="Quantidade" width="100%" required><input id="edQuantidade" type="number" min="0.0001" step="any" value={edQuantidade} onChange={e=>{setEdQuantidade(e.target.value);setValidationField(null);setError('')}} onBlur={e=>{if(n(e.target.value)<=0)setValidationField('quantidade')}} className={validationField==='quantidade'?inputStyle+' border-red-500 bg-red-50':inputStyle}/></Field>
     <Field label="Un." width="100%"><select id="edUnidade" value={edUnidade} onChange={e=>setEdUnidade(e.target.value)} className={inputStyle}><option>MT</option><option>PÇ</option><option>LT</option><option>MM</option><option>UN</option></select></Field>
     <Field label="Preço Unitário" width="100%"><input id="edValorUnitario" type="number" min="0" step="0.0001" value={edValorUnitario} onChange={e=>setEdValorUnitario(e.target.value)} className={inputStyle}/></Field>
     <Field label="Desconto %" width="100%"><input id="edDescontoPercentual" type="number" min="0" max="100" step="0.01" value={edDescontoPercentual} onChange={e=>setEdDescontoPercentual(e.target.value)} className={inputStyle}/></Field>
     <button id="btnAdicionarItem" title={editingItem===null?"Adicionar item":"Atualizar item selecionado"} type="button" onClick={()=>void add()} className="flex h-[30px] items-center justify-center gap-1 rounded-[2px] border border-blue-700 bg-blue-600 px-3 text-[10px] font-medium text-white hover:bg-blue-700"><Plus size={12}/>{editingItem===null?"Adicionar item":"Atualizar item"}</button>
    </div>
    <div id="gridItens" className="max-h-[420px] min-h-[180px] overflow-auto border-t border-slate-200">
     <table className="w-full border-collapse text-[10px] text-slate-700">
      <thead className="sticky top-0 z-10 bg-slate-100 text-slate-600"><tr className="h-8 border-b border-slate-200"><th className="px-2 text-left font-semibold">#</th><th className="px-2 text-left font-semibold">Código</th><th className="px-2 text-left font-semibold">Descrição do Produto</th><th className="px-2 text-right font-semibold">Quantidade</th><th className="px-2 text-left font-semibold">Un.</th><th className="px-2 text-right font-semibold">Preço Unit. (R$)</th><th className="px-2 text-right font-semibold">Desc. (%)</th><th className="px-2 text-right font-semibold">Total (R$)</th><th className="px-2 text-right font-semibold">Margem</th><th className="px-2 text-center font-semibold">Ações</th></tr></thead>
      <tbody>{gridItens.map((i,k)=><tr key={i.produto_id+'-'+k} onClick={()=>setSelectedItem(k)} className={`h-8 cursor-pointer border-b border-slate-100 even:bg-slate-50 hover:bg-blue-50 ${selectedItem===k?'bg-blue-50':''}`}><td className="px-2">{k+1}</td><td className="px-2 font-medium">{i.codigo}</td><td className="px-2">{i.descricao}</td><td className="px-2 text-right tabular-nums">{i.quantidade}</td><td className="px-2">{i.unidade}</td><td className="px-2 text-right tabular-nums">{brl(i.valor_unitario)}</td><td className="px-2 text-right tabular-nums">{i.desconto.toFixed(2)}</td><td className="px-2 text-right font-medium tabular-nums">{brl(i.quantidade*i.valor_unitario*(1-i.desconto/100))}</td><td className="px-2 text-right tabular-nums text-slate-500">{(()=>{const venda=i.quantidade*i.valor_unitario*(1-i.desconto/100);const custo=i.quantidade*i.preco_custo_industrial;return venda>0?((venda-custo)/venda*100).toFixed(1)+'%':'0.0%'})()}</td><td className="px-2 text-center"><div className="inline-flex items-center gap-1"><button type="button" title="Editar item" onClick={e=>{e.stopPropagation();setSelectedItem(k);setEditingItem(k);setEdCodigoInterno(i.codigo);setEdDescricaoProduto(i.descricao);setEdQuantidade(String(i.quantidade));setEdUnidade(i.unidade);setEdValorUnitario(String(i.valor_unitario));setEdDescontoPercentual(String(i.desconto));setEdPrecoCustoIndustrial(String(i.preco_custo_industrial));produtoRef.current?.focus()}} className="inline-flex h-6 w-6 items-center justify-center rounded-[2px] border border-slate-300 bg-white text-slate-600 hover:bg-slate-100"><Edit3 size={11}/></button><button type="button" title="Excluir item" onClick={e=>{e.stopPropagation();setGridItens(v=>v.filter((_,x)=>x!==k));setSelectedItem(null);setEditingItem(null)}} className="inline-flex h-6 w-6 items-center justify-center rounded-[2px] border border-slate-300 bg-white text-slate-600 hover:border-red-300 hover:bg-red-50 hover:text-red-600"><Trash2 size={11}/></button></div></td></tr>)}{!gridItens.length&&<tr><td colSpan={10} className="h-20 text-center text-[11px] text-slate-400">Nenhum item adicionado. Localize um produto cadastrado para começar.</td></tr>}</tbody>
     </table>
    </div>
    <div className="flex items-center justify-end border-t border-slate-200 bg-slate-50 px-2 py-1.5"><span className="text-[10px] text-slate-500">{gridItens.length} {gridItens.length===1?'item':'itens'} no pedido</span></div>
   </section>

   <div className="grid grid-cols-1 gap-2 lg:grid-cols-[minmax(0,1fr)_minmax(280px,360px)]">
    <section className="rounded-[2px] border border-slate-200 bg-white">
     <h3 className="border-b border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px] font-semibold text-slate-700">Informações Adicionais</h3>
     <div className="p-2"><Field label="Preço de custo industrial do item selecionado"><input value={selectedItem===null?'':brl(gridItens[selectedItem]?.preco_custo_industrial??0)} readOnly className={inputStyle+' bg-slate-50'}/></Field><p className="mt-1 text-[9px] text-slate-500">Margem apresentada na grade é calculada com base no custo industrial retornado pelo ERP.</p></div>
    </section>
    <section className="rounded-[2px] border border-slate-200 bg-white">
     <h3 className="border-b border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px] font-semibold text-slate-700">Resumo do Pedido</h3>
     <div className="space-y-1.5 p-2">
      <div className="flex items-center justify-between text-[10px] text-slate-600"><span>Subtotal dos itens</span><span className="tabular-nums">{brl(subtotal)}</span></div>
      <div className="grid grid-cols-2 gap-2"><Field label="Frete (R$)"><input value={frete} onChange={e=>setFrete(e.target.value)} className={inputStyle}/></Field><Field label="Outras despesas (R$)"><input value={outras} onChange={e=>setOutras(e.target.value)} className={inputStyle}/></Field></div>
      <div className="flex items-center justify-between border-t border-slate-200 pt-2 text-[13px] font-semibold text-blue-800"><span>Total Líquido</span><span className="tabular-nums">{brl(total)}</span></div>
     </div>
    </section>
   </div>


   {consulta&&<div className="fixed inset-0 z-50 flex items-start justify-center bg-black/10 pt-24" onMouseDown={()=>setConsulta(null)}><div className="w-[min(760px,92vw)] rounded-[2px] border border-gray-300 bg-white shadow-xl" onMouseDown={e=>e.stopPropagation()}><div className="flex h-8 items-center justify-between border-b px-2 text-[11px] font-medium"><span>{consulta==='cliente'?'CONSULTA DE CLIENTES':consulta==='transportadora'?'CONSULTA DE TRANSPORTADORAS':'CONSULTA DE PRODUTOS'}</span><button type="button" onClick={()=>setConsulta(null)} className="h-7 w-7 border-0 bg-transparent p-0 text-[18px] leading-none text-slate-500 hover:text-slate-800" title="Fechar">×</button></div><div className="p-2"><input autoFocus value={busca} onChange={e=>setBusca(e.target.value)} className={inputStyle}/><div className="mt-2 max-h-72 overflow-auto border">{consulta==='cliente'?clientesFiltro.map(c=><button type="button" key={c.id} onClick={()=>{setCliente(c);setEdCodigoCliente(c.codigo??c.documento??'');setEdNomeCliente(c.nome);setConsulta(null)}} className="grid w-full grid-cols-[110px_1fr_160px] border-b px-2 py-1 text-left text-[10px] hover:bg-slate-50"><span>{c.codigo??''}</span><span>{c.nome}</span><span>{c.documento??''}</span></button>):consulta==='transportadora'?transportadorasFiltro.map(t=><button type="button" key={t.id} onClick={()=>{setTransportadora(t.codigo);setConsulta(null)}} className="grid w-full grid-cols-[120px_1fr] border-b px-2 py-1 text-left text-[10px] hover:bg-slate-50"><span>{t.codigo}</span><span>{t.razao_social}</span></button>):produtosFiltro.map(p=><button type="button" key={p.id} onClick={()=>{void produtoBusca(p.codigo);setConsulta(null)}} className="grid w-full grid-cols-[110px_1fr_70px_90px] border-b px-2 py-1 text-left text-[10px] hover:bg-slate-50"><span>{p.codigo}</span><span>{p.nome}</span><span>{unit(p.unidade_venda||p.unidade)}</span><span>{brl(p.preco_venda??0)}</span></button>)}</div></div></div></div>}
  </div>
 </VendasLayout>
}
