import { useEffect, useState } from 'react'
import { CheckCircle } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import EntityCodeLookup, { type LookupRecord } from '../components/industrial/EntityCodeLookup'
import { fetchAllPages } from '../lib/supabasePagination'
type OP=LookupRecord
export default function PCPAcabamento(){const[ops,setOps]=useState<OP[]>([]),[op,setOp]=useState(''),[posto,setPosto]=useState('Bancada de Rebarbação Manual'),[recebida,setRecebida]=useState(0),[acabada,setAcabada]=useState(0),[refugo,setRefugo]=useState(0),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
useEffect(()=>{let active=true;void(async()=>{try{const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)throw c.error??new Error('Empresa da sessão não identificada.');const rows=await fetchAllPages<{id:string;numero_op:string|null;quantidade:number|null}>((from,to)=>supabase.from('erp_ordens_producao').select('id,numero_op,quantidade',{count:'exact'}).eq('empresa_id',String(c.data)).order('created_at',{ascending:false}).range(from,to));if(active)setOps(rows.map(x=>({id:x.id,codigo:String(x.numero_op||''),nome:'OP',estoque_atual:x.quantidade??0})))}catch(e){if(active)setError(e instanceof Error?e.message:'Falha ao carregar ordens de produção.')}})();return()=>{active=false}},[])
const disponivel=acabada
async function save(){if(!op){setError('Selecione a OP.');return}if(!Number.isFinite(recebida)||!Number.isFinite(acabada)||!Number.isFinite(refugo)||recebida<=0){setError('Informe quantidades válidas.');return}if(acabada<0||refugo<0||acabada+refugo>recebida){setError('Quantidades inválidas: acabada + refugo não pode superar o recebido.');return}setBusy(true);setError('');setMsg('');try{const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)throw c.error??new Error('Empresa da sessão não identificada.');const now=new Date().toISOString();const r=await supabase.from('erp_apontamentos_processo').insert({empresa_id:String(c.data),ordem_producao_id:op,quantidade_planejada:recebida,quantidade_boa:acabada,quantidade_refugada:refugo,quantidade_reprocessada:0,inicio_em:now,fim_em:now,observacoes:'Acabamento / rebarbação / embalagem — posto: '+posto});if(r.error)throw r.error;setMsg('Apontamento de acabamento registrado no histórico real de produção. O saldo de estoque não foi alterado automaticamente por esta tela.');setRecebida(0);setAcabada(0);setRefugo(0)}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar o acabamento.')}finally{setBusy(false)}}
return <main className="min-h-screen bg-slate-100 p-5 text-slate-900"><header className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-3 border-b border-slate-200 pb-4"><div><p className="text-sm font-bold text-sky-700">PCP &gt; ACABAMENTO</p><h1 className="text-2xl font-black text-slate-950">Acabamento, Rebarbação e Embalagem</h1></div><div className="flex gap-2"><button type="button" disabled={busy} onClick={()=>void save()} className="h-[30px] rounded-[2px] bg-[#2D8DB8] px-3 text-[10px] font-medium text-white disabled:opacity-50"><CheckCircle className="mr-2 inline"/>CONCLUIR LOTE</button></div></header><section className="mx-auto mt-5 max-w-[1700px] rounded-[2px] border border-slate-200 bg-white p-3 shadow-sm">{error&&<div role="alert" className="mb-4 rounded-md border border-red-300 bg-red-50 p-3 font-semibold text-red-900">{error}</div>}<EntityCodeLookup label="LOTE / OP DE ORIGEM" value={op} records={ops} onChange={setOp} onSelect={r=>setOp(r.id)} required/><div className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-2"><label className="text-[9px] font-medium uppercase text-slate-600">POSTO DE TRABALHO<select className="mt-[2px] h-[30px] w-full rounded-[2px] border border-slate-300 bg-white px-2 text-[11px] text-slate-900" value={posto} onChange={e=>setPosto(e.target.value)}><option>Bancada de Rebarbação Manual</option><option>Posto de Pintura / Jateamento</option></select></label><label className="text-sm font-bold text-slate-800">QUANTIDADE RECEBIDA<input className="mt-[2px] h-[30px] w-full rounded-[2px] border border-slate-300 px-2 text-[11px] text-slate-900" type="number" min="0" step="0.001" value={recebida} onChange={e=>setRecebida(Number(e.target.value))}/></label><label className="text-sm font-bold text-slate-800">QUANTIDADE ACABADA<input className="mt-2 min-h-16 w-full rounded-md border border-slate-300 px-4 text-2xl font-black text-slate-900" type="number" min="0" step="0.001" value={acabada} onChange={e=>setAcabada(Number(e.target.value))}/></label><label className="text-sm font-bold text-slate-800">REFUGO<input className="mt-2 min-h-16 w-full rounded-md border border-slate-300 px-4 text-2xl font-black text-slate-900" type="number" min="0" step="0.001" value={refugo} onChange={e=>setRefugo(Number(e.target.value))}/></label></div><div className="mt-3 rounded-[2px] border border-emerald-300 bg-emerald-50 p-3"><span className="text-sm font-bold text-emerald-800">DISPONÍVEL PARA EMBALAGEM</span><div className="text-xl font-semibold text-emerald-900">{disponivel.toLocaleString('pt-BR')} un</div><p className="mt-2 font-medium text-emerald-800">Quantidade acabada informada</p></div>{msg&&<div role="status" className="mt-4 rounded-md bg-slate-100 p-4 font-bold">{msg}</div>}</section></main>}
