import { useEffect, useMemo, useState } from 'react'
import { CheckCircle } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import EntityCodeLookup, { type LookupRecord } from '../components/industrial/EntityCodeLookup'
type OP=LookupRecord
export default function PCPAcabamento(){const[ops,setOps]=useState<OP[]>([]),[op,setOp]=useState(''),[posto,setPosto]=useState('Bancada de Rebarbação Manual'),[recebida,setRecebida]=useState(0),[acabada,setAcabada]=useState(0),[refugo,setRefugo]=useState(0),[msg,setMsg]=useState('')
useEffect(()=>{void(async()=>{const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)return;const r=await supabase.from('erp_ordens_producao').select('id,numero_op,numero,quantidade').eq('empresa_id',c.data).order('created_at',{ascending:false}).limit(200);setOps((r.data??[]).map(x=>({id:x.id,codigo:x.numero_op||x.numero,nome:'OP',estoque_atual:x.quantidade??0})) as OP[])})()},[])
const disponivel=useMemo(()=>acabada,[acabada])
async function save(){const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data||!op){setMsg('Selecione a OP.');return}if(recebida<=0){setMsg('Informe a quantidade recebida.');return}if(acabada<0||refugo<0||acabada+refugo>recebida){setMsg('Quantidades inválidas: acabada + refugo não pode superar o recebido.');return}const r=await supabase.from('erp_acabamentos').insert({empresa_id:c.data,ordem_producao_id:op,posto_trabalho:posto,quantidade_recebida:recebida,quantidade_acabada:acabada,quantidade_refugo:refugo,status:'CONCLUIDO'});setMsg(r.error?r.error.message:'Lote de acabamento gravado e enviado para expedição.')}
return <main className="min-h-screen bg-slate-100 p-5 text-slate-900"><header className="mx-auto flex max-w-[1700px] items-center justify-between border-b border-slate-200 pb-4"><div><p className="text-sm font-bold text-sky-700">PCP &gt; ACABAMENTO</p><h1 className="text-2xl font-black text-slate-950">Acabamento, Rebarbação e Embalagem</h1></div><div className="flex gap-2"><button onClick={()=>void save()} className="rounded-md bg-emerald-600 px-5 py-3 font-bold text-white"><CheckCircle className="mr-2 inline"/>CONCLUIR E ENVIAR</button></div></header><section className="mx-auto mt-5 max-w-[1700px] rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><EntityCodeLookup label="LOTE / OP DE ORIGEM" value={op} records={ops} onChange={setOp} onSelect={r=>setOp(r.id)} required/><div className="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-800">POSTO DE TRABALHO<select className="mt-2 min-h-12 w-full rounded-md border border-slate-300 bg-white px-3 text-base text-slate-900" value={posto} onChange={e=>setPosto(e.target.value)}><option>Bancada de Rebarbação Manual</option><option>Posto de Pintura / Jateamento</option></select></label><label className="text-sm font-bold text-slate-800">QUANTIDADE RECEBIDA<input className="mt-2 min-h-16 w-full rounded-md border border-slate-300 px-4 text-2xl font-black text-slate-900" type="number" min="0" value={recebida} onChange={e=>setRecebida(Number(e.target.value))}/></label><label className="text-sm font-bold text-slate-800">QUANTIDADE ACABADA<input className="mt-2 min-h-16 w-full rounded-md border border-slate-300 px-4 text-2xl font-black text-slate-900" type="number" min="0" value={acabada} onChange={e=>setAcabada(Number(e.target.value))}/></label><label className="text-sm font-bold text-slate-800">REFUGO<input className="mt-2 min-h-16 w-full rounded-md border border-slate-300 px-4 text-2xl font-black text-slate-900" type="number" min="0" value={refugo} onChange={e=>setRefugo(Number(e.target.value))}/></label></div><div className="mt-6 rounded-lg border-2 border-emerald-300 bg-emerald-50 p-6"><span className="text-sm font-bold text-emerald-800">DISPONÍVEL PARA EMBALAGEM</span><div className="text-4xl font-black text-emerald-900">{disponivel.toLocaleString('pt-BR')} un</div><p className="mt-2 font-medium text-emerald-800">Recebida − Refugo do Acabamento</p></div>{msg&&<div className="mt-4 rounded-md bg-slate-100 p-4 font-bold">{msg}</div>}</section></main>}
