import { useEffect,useState } from "react";
import { Save,XCircle,Printer,Search } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
type T={id:string;codigo:string;nome:string;numero_cavidades:number;vida_ciclos:number;ciclos_realizados:number};type M={id:string;codigo:string;nome:string};
export default function PCPAprovacaoSetup(){
 const [ts,setTs]=useState<T[]>([]);const [ms,setMs]=useState<M[]>([]);const [tool,setTool]=useState("");const [machine,setMachine]=useState("");const [checks,setChecks]=useState([false,false,false]);const [status,setStatus]=useState("APROVADO");const [msg,setMsg]=useState("");
 useEffect(()=>{void Promise.all([supabase.from("erp_ferramentas_industriais").select("id,codigo,nome,numero_cavidades,vida_ciclos,ciclos_realizados").eq("ativo",true).order("codigo"),supabase.from("erp_maquinas").select("id,codigo,nome").eq("ativo",true).order("codigo")]).then(([t,m])=>{setTs((t.data??[]) as T[]);setMs((m.data??[]) as M[])})},[]);
 const selected=ts.find(x=>x.codigo===tool);
 async function save(){if(!selected||!machine||checks.some(x=>!x)){setMsg("Complete os campos e o checklist.");return}const {data:e}=await supabase.rpc("erp_current_empresa_id");const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from("erp_ferramentas_industriais").update({parametros:{setup_aprovacao:{status,maquina_codigo:machine,inspecionado_em:new Date().toISOString(),checklist:{alinhamento:true,pressao_hidraulica:true,temperatura:true}}},atualizado_por:u.user?.id??null}).eq("id",selected.id).eq("empresa_id",String(e??""));setMsg(error?error.message:"Liberação gravada no ferramental real.");}
 return <main className="min-h-screen bg-slate-50 text-slate-900 p-6"><div className="max-w-[1400px] mx-auto space-y-5"><header className="flex flex-wrap justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-sm font-bold text-slate-600">MÓDULO: PCP › ENGENHARIA</p><h1 className="text-xl font-bold text-slate-950">Aprovação e Liberação de Setup</h1></div><div className="flex gap-2"><button onClick={()=>void save()} className="rounded-md bg-blue-600 text-white h-11 px-4 font-bold"><Save size={18} className="inline mr-2"/>GRAVAR LIBERAÇÃO</button><button onClick={()=>setStatus("RETIDO")} className="rounded-md bg-rose-600 text-white h-11 px-4 font-bold"><XCircle size={18} className="inline mr-2"/>REPROVAR / RETER</button><button onClick={()=>window.print()} className="rounded-md bg-slate-700 text-white h-11 px-4 font-bold"><Printer size={18} className="inline mr-2"/>EMITIR LAUDO</button></div></header>
 <section className="bg-white border border-slate-200 rounded-md shadow-sm p-5"><h2 className="text-xl font-bold mb-4">1. Rastreabilidade do utensílio e equipamento</h2><div className="grid lg:grid-cols-2 gap-4"><label className="font-semibold">Número do Molde<div className="flex mt-1"><input list="tools" value={tool} onChange={e=>setTool(e.target.value)} className="h-12 flex-1 border border-slate-300 rounded-l-md px-3 text-slate-900"/><button className="w-14 bg-slate-800 text-white rounded-r-md"><Search size={20} className="mx-auto"/></button></div><datalist id="tools">{ts.map(t=><option key={t.id} value={t.codigo}>{t.nome}</option>)}</datalist>{selected&&<span className="text-sm block mt-1 text-slate-600">{selected.nome} • {selected.numero_cavidades} cavidades • {Number(selected.ciclos_realizados).toLocaleString("pt-BR")} ciclos</span>}</label><label className="font-semibold">Máquina/Prensa<div className="flex mt-1"><input list="machines" value={machine} onChange={e=>setMachine(e.target.value)} className="h-12 flex-1 border border-slate-300 rounded-l-md px-3 text-slate-900"/><button className="w-14 bg-slate-800 text-white rounded-r-md"><Search size={20} className="mx-auto"/></button></div><datalist id="machines">{ms.map(m=><option key={m.id} value={m.codigo}>{m.nome}</option>)}</datalist></label></div></section>
 <section className="bg-white border border-slate-200 rounded-md shadow-sm p-5"><h2 className="text-xl font-bold mb-3">2. Parâmetros obrigatórios conferidos</h2>{["Centralização física e fixação dos grampos traseiros do molde.","Pressão hidráulica ajustada para fechamento nominal.","Temperatura das zonas de cura estabilizadas."].map((x,i)=><label key={x} className="h-[50px] border-b border-slate-200 flex items-center gap-4 font-semibold"><input type="checkbox" className="w-6 h-6" checked={checks[i]} onChange={e=>setChecks(c=>c.map((v,j)=>j===i?e.target.checked:v))}/>{x}</label>)}</section>
 <section className="bg-white border border-slate-200 rounded-md shadow-sm p-5"><h2 className="text-xl font-bold mb-3">Laudo Técnico Final</h2><select value={status} onChange={e=>setStatus(e.target.value)} className="h-12 w-full border border-slate-300 rounded-md px-3 font-bold"><option value="APROVADO">🟢 SETUP APROVADO — LIBERADO PARA O TABLET</option><option value="RETIDO">🔴 SETUP REPROVADO — RETER MOLDE</option></select>{msg&&<p className="mt-4 font-semibold">{msg}</p>}</section></div></main>
}
