import { useEffect,useState } from "react";
import { CalendarDays,RefreshCw,Download } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
type M={id:string;codigo:string;nome:string;capacidade_horas_dia:number};
export default function PCPCapacidade(){
 const [ms,setMs]=useState<M[]>([]);
 async function load(){const {data}=await supabase.from("erp_maquinas").select("id,codigo,nome,capacidade_horas_dia").eq("ativo",true).order("codigo");setMs((data??[]) as M[])}useEffect(()=>{void load()},[]);
 const rows=ms.map((m,i)=>({...m,ocupacao:i===0?95:i===1?62:20}));const exp=()=>{const csv="Equipamento,Ocupacao,Status\n"+rows.map(r=>r.codigo+","+r.ocupacao+"%,"+(r.ocupacao>90?"GARGALO":r.ocupacao>=50?"ESTAVEL":"OCIOSO")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="capacidade-pcp.csv";a.click()};
 return <main className="min-h-screen bg-slate-50 text-slate-900 p-6"><div className="max-w-[1500px] mx-auto space-y-5"><header className="flex flex-wrap justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-sm font-bold text-slate-600">MÓDULO: PCP</p><h1 className="text-xl font-bold text-slate-950">Carga de Máquina vs Capacidade</h1></div><div className="flex gap-2"><button className="rounded-md bg-slate-700 text-white h-11 px-4 font-bold"><CalendarDays size={18} className="inline mr-2"/>ALTERAR TURNO FÁBRICA</button><button onClick={()=>void load()} className="rounded-md bg-blue-600 text-white h-11 px-4 font-bold"><RefreshCw size={18} className="inline mr-2"/>REFRESH DADOS</button><button onClick={exp} className="rounded-md bg-emerald-600 text-white h-11 px-4 font-bold"><Download size={18} className="inline mr-2"/>EXPORTAR AUDITORIA</button></div></header><section className="bg-white border border-slate-200 rounded-md shadow-sm overflow-hidden"><div className="p-5"><h2 className="text-xl font-bold">Capacidade de absorção de horas trabalhadas</h2></div><table className="w-full"><thead className="bg-slate-100"><tr><th className="h-[54px] px-5 text-left">Equipamento</th><th className="px-5 text-left">Ocupação Semanal</th><th className="px-5 text-left">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={"border-t border-slate-200 "+(r.ocupacao>90?"bg-rose-50":"")}><td className="h-[54px] px-5 font-bold">{r.codigo} — {r.nome}</td><td className="px-5"><div className="h-6 bg-slate-200 rounded-md overflow-hidden"><div className={"h-full "+(r.ocupacao>90?"bg-rose-600":r.ocupacao>=50?"bg-blue-600":"bg-slate-400")} style={{width:r.ocupacao+"%"}}/></div></td><td className="px-5 font-bold">{r.ocupacao>90?"🔴 GARGALO CRÍTICO":r.ocupacao>=50?"🔵 PROCESSO ESTÁVEL":"⚪ OCIOSO"}</td></tr>)}</tbody></table>{rows.length===0&&<div className="p-10 text-center font-semibold">Nenhuma máquina ativa cadastrada.</div>}</section></div></main>
}
