import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";
type Metric={label:string;value:number;note:string};
type Apont={inicio:string|null;fim:string|null;quantidade_boa:number;quantidade_refugo:number};
const colors=["#2563eb","#f59e0b","#10b981"];
function gauge(value:number,color:string){return <ResponsiveContainer width="100%" height={180}><PieChart><Pie data={[{v:value},{v:100-value}]} dataKey="v" innerRadius={52} outerRadius={72} startAngle={90} endAngle={-270}><Cell fill={color}/><Cell fill="#e2e8f0"/></Pie><Tooltip/></PieChart></ResponsiveContainer>}
export default function PCPDashboardOEE(){const[m,setM]=useState<Metric[]>([]);const[period,setPeriod]=useState("30");const[loading,setLoading]=useState(true);
useEffect(()=>{void(async()=>{setLoading(true);const since=new Date(Date.now()-Number(period)*86400000).toISOString();const r=await supabase.from("erp_producao_apontamentos").select("inicio,fim,quantidade_boa,quantidade_refugo").gte("inicio",since);const rows=(r.data??[]) as Apont[];let run=0,planned=0,b=0,s=0;for(const x of rows){b+=Number(x.quantidade_boa)||0;s+=Number(x.quantidade_refugo)||0;if(x.inicio&&x.fim)run+=(new Date(x.fim).getTime()-new Date(x.inicio).getTime())/3600000;planned+=x.inicio&&x.fim?Math.max(1,(new Date(x.fim).getTime()-new Date(x.inicio).getTime())/3600000):0}const disponibilidade=planned?Math.min(100,run/planned*100):0;const qualidade=b+s?b/(b+s)*100:0;const performance=planned?Math.min(100,b/(planned*30)*100):0;setM([{label:"DISPONIBILIDADE",value:disponibilidade,note:"Tempo registrado em produção"},{label:"PERFORMANCE",value:performance,note:"Produção boa versus capacidade-base"},{label:"QUALIDADE",value:qualidade,note:"Peças boas versus total apontado"}]);setLoading(false)})()},[period]);
const global=useMemo(()=>m.length?Math.round((m[0].value*m[1].value*m[2].value)/10000*10)/10:0,[m]);return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-6"><header className="flex flex-wrap items-center gap-2 border-b pb-4"><div><p className="text-sm font-black text-slate-600">PCP &gt; BUSINESS INTELLIGENCE &gt; INDICADORES OEE</p><h1 className="text-2xl font-black">Dashboard Analítica de Performance e Eficiência</h1></div><div className="ml-auto flex flex-wrap gap-2 print:hidden"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-md border bg-white px-4 py-3 font-bold text-slate-900"><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select><button onClick={()=>window.print()} className="rounded-md bg-slate-900 px-4 py-3 font-bold text-white">🖨️ EMITIR LAUDO OEE</button></div></header><section className="mt-5 rounded-md border bg-white p-5 shadow-sm"><p className="font-bold text-slate-700">MÉDIA GLOBAL DO PERÍODO</p><div className="mt-2 text-4xl font-black text-slate-950">{loading?"—":global+"%"}</div><p className="font-semibold text-slate-600">Índice calculado a partir dos apontamentos disponíveis; ausência de dados permanece como zero, sem números fictícios.</p></section><section className="mt-5 grid gap-5 md:grid-cols-3">{m.map((x,i)=><article key={x.label} className="rounded-md border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">{x.label}</h2>{gauge(x.value,colors[i])}<p className="text-center text-2xl font-black">{x.value.toFixed(1)}%</p><p className="text-center text-sm font-semibold text-slate-600">{x.note}</p></article>)}</section></main>}