import { useEffect,useState } from "react";
import { Plus,Save,RefreshCw } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
type Row={id:string;codigo:string;nome:string;vendas:number;seguranca:number;necessidade:number};
export default function PCPDemanda(){
 const [rows,setRows]=useState<Row[]>([]);const [periodo,setPeriodo]=useState(new Date().toISOString().slice(0,7));const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data:p}=await supabase.from("erp_produtos").select("id,codigo,nome,estoque_minimo,estoque_atual").eq("ativo",true).order("codigo").limit(300);const ps=(p??[]) as Array<Record<string,unknown>>;const ids=ps.map(x=>String(x.id));let sales:Record<string,number>={};if(ids.length){const {data:i}=await supabase.from("erp_pedidos_venda_itens").select("produto_id,quantidade").in("produto_id",ids).limit(5000);for(const x of (i??[]) as Array<Record<string,unknown>>){const k=String(x.produto_id);sales[k]=(sales[k]??0)+Number(x.quantidade??0)}}setRows(ps.map(x=>{const v=sales[String(x.id)]??0;const s=Number(x.estoque_minimo??0);const e=Number(x.estoque_atual??0);return {id:String(x.id),codigo:String(x.codigo??""),nome:String(x.nome??""),vendas:v,seguranca:s,necessidade:Math.max(0,v+s-e)}}));setLoading(false)}
 useEffect(()=>{void load()},[periodo]);
 return <main className="min-h-screen bg-slate-50 text-slate-900 p-6"><div className="max-w-[1500px] mx-auto space-y-5">
 <header className="flex flex-wrap justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-sm font-bold text-slate-600">MÓDULO: PCP</p><h1 className="text-xl font-bold text-slate-950">Plano de Demanda e Previsão Geral</h1></div><div className="flex gap-2"><button className="rounded-md bg-white border border-slate-300 h-11 px-4 font-bold"><Plus size={18} className="inline mr-2"/>NOVA PREVISÃO</button><button className="rounded-md bg-blue-600 text-white h-11 px-4 font-bold"><Save size={18} className="inline mr-2"/>GRAVAR PLANO</button><button onClick={()=>void load()} className="rounded-md bg-slate-900 text-white h-11 px-4 font-bold"><RefreshCw size={18} className="inline mr-2"/>PROCESSAR DEMANDA CENTRAL</button></div></header>
 <section className="bg-white border border-slate-200 rounded-md shadow-sm p-5"><h2 className="text-xl font-bold mb-4">1. Filtros gerais de consolidação</h2><label className="font-semibold text-base block max-w-sm">Período do Plano<input type="month" value={periodo} onChange={e=>setPeriodo(e.target.value)} className="mt-1 w-full h-12 rounded-md border border-slate-300 px-3 text-slate-900"/></label></section>
 <section className="bg-white border border-slate-200 rounded-md shadow-sm overflow-hidden"><div className="p-5"><h2 className="text-xl font-bold">2. Grade de necessidades calculadas</h2></div><div className="overflow-x-auto"><table className="w-full text-base"><thead className="bg-slate-100"><tr><th className="h-[54px] px-4 text-left">Cód. Item</th><th className="px-4 text-left">Descrição</th><th className="px-4 text-right">Qtd Vendas</th><th className="px-4 text-right">Estoque Segurança</th><th className="px-4 text-right">Necessidade Produzir</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-8 text-center font-semibold">Consultando dados reais...</td></tr>:rows.length===0?<tr><td colSpan={5} className="p-8 text-center font-semibold">Nenhum produto ativo encontrado.</td></tr>:rows.map(r=><tr key={r.id} className="border-t border-slate-200"><td className="h-[54px] px-4 font-bold text-blue-900">{r.codigo}</td><td className="px-4 font-semibold">{r.nome}</td><td className="px-4 text-right">{r.vendas.toLocaleString("pt-BR")}</td><td className="px-4 text-right">{r.seguranca.toLocaleString("pt-BR")}</td><td className="px-4 text-right font-bold">{r.necessidade.toLocaleString("pt-BR")}</td></tr>)}</tbody></table></div></section>
 </div></main>
}
