import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CalendarDays, CheckCircle2, Factory, HelpCircle, PauseCircle, Play, RefreshCw, Wrench } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Machine={id:string;codigo?:string;nome?:string;status?:string;tem_lado_b?:boolean;ativo?:boolean}
type Product={id:string;codigo?:string;nome?:string;unidade?:string}
type Mold={id:string;codigo?:string;nome?:string;status?:string}
type Operator={id:string;nome?:string;email?:string;ativo?:boolean}
type Slot={id:string;maquina_id:string;molde_id?:string|null;produto_id:string;operador_id?:string|null;lado_prensagem:'A'|'B'|'M';inicio_planejado:string;fim_planejado:string;quantidade_planejada:number;quantidade_produzida:number;quantidade_refugada:number;status:string;observacoes?:string|null}
const isoDay=(d:Date)=>d.toISOString().slice(0,10)
const addDays=(s:string,n:number)=>{const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+n);return isoDay(d)}
const hours=(s:string)=>{const d=new Date(s);return d.getHours()+d.getMinutes()/60}
export default function PCPIndustrial(){
 const [date,setDate]=useState(isoDay(new Date())),[machines,setMachines]=useState<Machine[]>([]),[products,setProducts]=useState<Product[]>([]),[molds,setMolds]=useState<Mold[]>([]),[operators,setOperators]=useState<Operator[]>([]),[slots,setSlots]=useState<Slot[]>([]),[selectedMachine,setSelectedMachine]=useState(''),[busy,setBusy]=useState(true),[notice,setNotice]=useState(''),[showForm,setShowForm]=useState(false),[form,setForm]=useState({produto_id:'',molde_id:'',operador_id:'',lado:'M' as 'A'|'B'|'M',inicio:'07:00',fim:'09:00',quantidade:'100'}),[menu,setMenu]=useState<{x:number;y:number;slot:Slot}|null>(null)
 const dates=useMemo(()=>Array.from({length:7},(_,i)=>addDays(date,i-3)),[date])
 const prod=(id:string)=>products.find(x=>x.id===id), mold=(id?:string|null)=>molds.find(x=>x.id===id), oper=(id?:string|null)=>operators.find(x=>x.id===id)
 async function load(){setBusy(true);setNotice('');const dayStart=`${date}T00:00:00`;const dayEnd=`${addDays(date,1)}T00:00:00`;const [m,p,mo,u,s]=await Promise.all([supabase.from('erp_maquinas').select('*').eq('ativo',true).order('codigo'),supabase.from('erp_produtos').select('id,codigo,nome,unidade').order('nome').limit(1000),supabase.from('erp_moldes').select('*').order('codigo').limit(500),supabase.from('erp_usuarios').select('id,nome,email,ativo').eq('ativo',true).order('nome').limit(500),supabase.from('erp_pcp_programacoes').select('*').lt('inicio_planejado',dayEnd).gte('fim_planejado',dayStart).neq('status','cancelada').order('inicio_planejado')]);if(m.error||p.error||mo.error||u.error||s.error)setNotice(m.error?.message||p.error?.message||mo.error?.message||u.error?.message||s.error?.message||'Falha ao carregar PCP');setMachines((m.data||[]) as Machine[]);setProducts((p.data||[]) as Product[]);setMolds((mo.data||[]) as Mold[]);setOperators((u.data||[]) as Operator[]);setSlots((s.data||[]) as Slot[]);setBusy(false)}
 useEffect(()=>{void load()},[date])
 const machineSlots=(id:string)=>slots.filter(s=>s.maquina_id===id)
 async function empresa(){const {data,error}=await supabase.rpc('erp_current_empresa_id');if(error||!data)throw new Error('Empresa da sessão não identificada');return String(data)}
 async function create(){try{if(!form.produto_id)throw new Error('Selecione o produto.');if(form.lado==='B'&&!machines.find(m=>m.id===selectedMachine)?.tem_lado_b)throw new Error('Habilite o Lado B no cadastro da máquina.');const start=new Date(`${date}T${form.inicio}:00`),end=new Date(`${date}T${form.fim}:00`);if(end<=start)throw new Error('Horário final deve ser posterior ao inicial.');const {error}=await supabase.from('erp_pcp_programacoes').insert({empresa_id:await empresa(),maquina_id:selectedMachine,produto_id:form.produto_id,molde_id:form.molde_id||null,operador_id:form.operador_id||null,lado_prensagem:form.lado,inicio_planejado:start.toISOString(),fim_planejado:end.toISOString(),quantidade_planejada:Number(form.quantidade),status:'programada'});if(error)throw error;setNotice('Programação criada no PCP e gravada no Supabase.');setShowForm(false);await load()}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível salvar.')}}
 async function finalize(slot:Slot){const boas=prompt('Quantidade produzida boa:',String(slot.quantidade_planejada));if(boas===null)return;const ref=prompt('Refugo:',String(slot.quantidade_refugada||0));if(ref===null)return;const lote=prompt('Lote (opcional):','');const {error}=await supabase.rpc('erp_pcp_finalizar_programacao',{p_programacao_id:slot.id,p_qtd_boas:Number(boas),p_qtd_refugo:Number(ref),p_lote:lote||null});setNotice(error?error.message:'Produção concluída, apontamento e rastreabilidade registrados.');if(!error)await load()}
 return <div className="pcp-page" style={{padding:24,maxWidth:1700,margin:'0 auto'}} onClick={()=>menu&&setMenu(null)}>
  <div className="pcp-toolbar"><div><button className="secondary-v2" onClick={()=>location.href='/erp-industrial'}><ArrowLeft size={17}/> Voltar</button><div style={{marginTop:12}}><span className="v2-eyebrow">PCP • CHÃO DE FÁBRICA</span><h2 style={{fontSize:32,margin:'5px 0'}}>Planejamento de produção</h2><p style={{margin:0,color:'#64777d'}}>Prensas, lados A/B, moldes, operadores, setups e apontamento em uma única visão.</p></div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><button className="secondary-v2" title="Ajuda contextual" onClick={()=>setNotice('Ajuda: selecione uma máquina, escolha lado A/B/M e programe produto, molde, operador, horário e quantidade. Conflitos de máquina, lado, operador e manutenção são bloqueados pelo banco.') }><HelpCircle size={17}/> Ajuda</button><button className="menu-green" onClick={()=>void load()}><RefreshCw size={17}/> {busy?'Atualizando…':'Atualizar'}</button></div></div>
  <div style={{display:'flex',gap:8,overflowX:'auto',padding:'8px 0 18px'}}>{dates.map(d=><button key={d} onClick={()=>setDate(d)} style={{minWidth:112,padding:11,borderRadius:14,border:d===date?'2px solid #0f6672':'1px solid #dce6e9',background:d===date?'#e8f3f5':'white'}}><small>{new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short'})}</small><div style={{fontSize:22,fontWeight:900}}>{new Date(`${d}T12:00:00`).getDate()}</div></button>)}</div>
  <div className="pcp-machine-grid">{machines.map(m=><button key={m.id} className={`pcp-machine ${selectedMachine===m.id?'active':''}`} onClick={()=>setSelectedMachine(m.id)}><div style={{display:'flex',justifyContent:'space-between'}}><Factory size={20}/><span style={{fontSize:11,fontWeight:900}}>{m.tem_lado_b?'A + B':'Lado único'}</span></div><strong style={{display:'block',marginTop:9,textAlign:'left'}}>{m.codigo||'Máquina'} · {m.nome}</strong><small style={{display:'block',marginTop:4,textAlign:'left',color:'#64777d'}}>{machineSlots(m.id).length} programação(ões) hoje</small></button>)}</div>
  {selectedMachine&&<section className="erp-card" style={{padding:18,marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><strong style={{fontSize:20}}>{machines.find(m=>m.id===selectedMachine)?.codigo} · {machines.find(m=>m.id===selectedMachine)?.nome}</strong><div style={{fontSize:12,color:'#64777d'}}>Agenda operacional • clique direito em uma programação para ações rápidas</div></div><button className="menu-green" onClick={()=>setShowForm(true)}><Play size={16}/> Nova programação</button></div><div className="pcp-side" style={{marginTop:14}}>{(['A','B'] as const).map(side=><div key={side} className="pcp-side-panel"><div style={{display:'flex',justifyContent:'space-between'}}><strong>LADO {side}</strong><span>{side==='B'&&!machines.find(m=>m.id===selectedMachine)?.tem_lado_b?'Indisponível':'Operacional'}</span></div>{machineSlots(selectedMachine).filter(s=>s.lado_prensagem===side||s.lado_prensagem==='M').map(s=><div key={s.id} style={{marginTop:10,padding:11,borderRadius:12,background:'#fff',border:'1px solid #e1eaec'}} onContextMenu={e=>{e.preventDefault();setMenu({x:e.clientX,y:e.clientY,slot:s})}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{prod(s.produto_id)?.codigo||'Produto'} · {prod(s.produto_id)?.nome||'—'}</b><span>{s.status}</span></div><small>{new Date(s.inicio_planejado).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}–{new Date(s.fim_planejado).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · Molde {mold(s.molde_id)?.codigo||'—'} · {oper(s.operador_id)?.nome||'Sem operador'}</small></div>)}{!machineSlots(selectedMachine).some(s=>s.lado_prensagem===side||s.lado_prensagem==='M')&&<div className="pcp-empty">Nenhuma programação.</div>}</div>)}</div></section>}
  <section className="pcp-timeline"><div style={{padding:15,display:'flex',alignItems:'center',gap:8,borderBottom:'1px solid #edf2f3'}}><CalendarDays size={18}/><strong>Gantt / linha do tempo — {new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR')}</strong></div>{machines.map(m=><div className="pcp-timeline-row" key={m.id}><div className="pcp-timeline-label">{m.codigo||m.nome}<small style={{display:'block',color:'#64777d'}}>{m.nome}</small></div><div className="pcp-track">{machineSlots(m.id).map(s=>{const start=Math.max(6,hours(s.inicio_planejado)),end=Math.min(22,hours(s.fim_planejado)),left=((start-6)/16)*100,width=Math.max(2,((end-start)/16)*100);return <button key={s.id} className="pcp-block" style={{left:`${left}%`,width:`${width}%`}} onContextMenu={e=>{e.preventDefault();setMenu({x:e.clientX,y:e.clientY,slot:s})}} onDoubleClick={()=>void finalize(s)}><strong>{prod(s.produto_id)?.codigo||'Produto'} · L{s.lado_prensagem}</strong><small>{new Date(s.inicio_planejado).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {s.quantidade_planejada} un.</small></button>})}</div></div>)}{!machines.length&&<div className="pcp-empty">Nenhuma máquina ativa cadastrada.</div>}</section>
  {notice&&<div role="status" style={{marginTop:14,padding:13,borderRadius:14,background:'#e9f5f6',border:'1px solid #c5dde1'}}>{notice}</div>}
  {showForm&&<div style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(7,28,34,.55)',display:'grid',placeItems:'center',padding:18}}><div className="erp-card" style={{width:'min(560px,100%)',padding:22}}><div style={{display:'flex',justifyContent:'space-between'}}><div><span className="v2-eyebrow">NOVA PROGRAMAÇÃO</span><h3 style={{margin:'5px 0 16px'}}>Programar máquina</h3></div><button onClick={()=>setShowForm(false)}>Fechar</button></div><div style={{display:'grid',gap:10}}><label>Produto<select value={form.produto_id} onChange={e=>setForm({...form,produto_id:e.target.value})}><option value="">Selecionar</option>{products.map(p=><option key={p.id} value={p.id}>{p.codigo} — {p.nome}</option>)}</select></label><label>Molde<select value={form.molde_id} onChange={e=>setForm({...form,molde_id:e.target.value})}><option value="">Sem molde</option>{molds.map(x=><option key={x.id} value={x.id}>{x.codigo} — {x.nome}</option>)}</select></label><label>Operador<select value={form.operador_id} onChange={e=>setForm({...form,operador_id:e.target.value})}><option value="">Selecionar</option>{operators.map(x=><option key={x.id} value={x.id}>{x.nome||x.email}</option>)}</select></label><label>Lado<select value={form.lado} onChange={e=>setForm({...form,lado:e.target.value as any})}><option value="M">Máquina inteira</option><option value="A">Lado A</option><option value="B">Lado B</option></select></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Início<input type="time" value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})}/></label><label>Fim<input type="time" value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})}/></label></div><label>Quantidade planejada<input type="number" min="1" value={form.quantidade} onChange={e=>setForm({...form,quantidade:e.target.value})}/></label><button className="menu-green" onClick={()=>void create()}><CheckCircle2 size={17}/> Salvar programação</button></div></div></div>}
  {menu&&<div style={{position:'fixed',left:Math.min(menu.x,window.innerWidth-230),top:Math.min(menu.y,window.innerHeight-250),zIndex:1200,width:220,padding:7,borderRadius:14,background:'#fff',border:'1px solid #dce6e9',boxShadow:'0 20px 50px rgba(0,0,0,.16)'}} onClick={e=>e.stopPropagation()}><strong style={{display:'block',padding:'8px 10px'}}>Ações da programação</strong>{['Editar','Duplicar','Trocar máquina','Trocar operador','Trocar molde','Alterar quantidade','Reprogramar','Cancelar'].map(a=><button key={a} style={{display:'block',width:'100%',padding:'9px 10px',textAlign:'left',border:0,background:'transparent',borderRadius:9}} onClick={async()=>{setNotice(`${a}: fluxo preparado para esta programação.`);setMenu(null);if(a==='Cancelar'){const {error}=await supabase.from('erp_pcp_programacoes').update({status:'cancelada'}).eq('id',menu.slot.id);if(error)setNotice(error.message);else await load()}}}>{a}</button>)}<button style={{display:'block',width:'100%',padding:'10px',marginTop:4}} onClick={()=>void finalize(menu.slot)}><CheckCircle2 size={15}/> Concluir produção</button></div>}
 </div>
}
