import { useEffect,useState } from 'react'
import { Calculator,Factory,Save,Search,Zap } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import EntityCodeLookup from '../components/industrial/EntityCodeLookup'
type Product={id:string;codigo:string;nome:string;estoque_atual:number}
type Machine={id:string;codigo:string;nome:string;status:string;capacidade_horas_dia:number}
type Pedido={id:string;codigo:string;nome:string}
type OP={id:string;numero_op:number;produto_id:string|null;pedido_venda_id:string|null;quantidade:number;quantidade_planejada:number;status:string;maquina_id:string|null;velocidade_nominal_hora:number;operacao_dupla:boolean;tempo_estimado_horas:number}
type Material={id:string;codigo:string;nome:string;need:number;stock:number;reserved:number;net:number;suggestion:string}
export default function PCPOrdens(){
 const[products,setProducts]=useState<Product[]>([]),[machines,setMachines]=useState<Machine[]>([]),[pedidos,setPedidos]=useState<Pedido[]>([]),[ops,setOps]=useState<OP[]>([]),[selectedOp,setSelectedOp]=useState(''),[produtoId,setProdutoId]=useState(''),[pedidoId,setPedidoId]=useState(''),[machineId,setMachineId]=useState(''),[qty,setQty]=useState(''),[rate,setRate]=useState('30'),[doubleOp,setDoubleOp]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[materials,setMaterials]=useState<Material[]>([])
 async function load(){setLoading(true);setError('');try{const[p,m,o,pv]=await Promise.all([supabase.from('erp_produtos').select('id,codigo,nome,estoque_atual').eq('ativo',true).order('codigo').limit(3000),supabase.from('erp_maquinas').select('id,codigo,nome,status,capacidade_horas_dia').eq('ativo',true).order('codigo'),supabase.from('erp_ordens_producao').select('id,numero_op,produto_id,pedido_venda_id,quantidade,quantidade_planejada,status,maquina_id,velocidade_nominal_hora,operacao_dupla,tempo_estimado_horas').order('created_at',{ascending:false}).limit(500),supabase.from('erp_pedidos_venda').select('id,numero,cliente_id,status').order('numero',{ascending:false}).limit(3000)]);for(const r of[p,m,o,pv])if(r.error)throw r.error;const ps=(p.data??[])as Product[],ms=(m.data??[])as Machine[],os=(o.data??[])as OP[],raw=(pv.data??[])as Array<Record<string,unknown>>;const ids=raw.map(x=>String(x.cliente_id??'')).filter(Boolean);const c=ids.length?await supabase.from('erp_clientes').select('id,nome').in('id',ids):{data:[],error:null};if(c.error)throw c.error;const cm=new Map((c.data??[]).map((x:{id:string;nome:string})=>[x.id,x.nome]));setProducts(ps);setMachines(ms);setOps(os);setPedidos(raw.map(x=>({id:String(x.id),codigo:String(x.numero),nome:cm.get(String(x.cliente_id))||'Pedido comercial'})))}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o planejador de OPs.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const selected=ops.find(o=>o.id===selectedOp),effectiveRate=Math.max(.0001,Number(rate)||0)*(doubleOp?2:1),hours=qty&&effectiveRate?Number(qty)/effectiveRate:0
 const productRecords=products.map(p=>({id:p.id,codigo:p.codigo,nome:p.nome,estoque_atual:p.estoque_atual})),machineRecords=machines.map(m=>({id:m.id,codigo:m.codigo,nome:m.nome})),pedidoRecords=pedidos.map(p=>({id:p.id,codigo:p.codigo,nome:p.nome}))
 async function explode(produto:string,quantidade:number){if(!produto||quantidade<=0){setMaterials([]);return}const run=await supabase.rpc('erp_mrp_explodir',{p_produto_id:produto,p_quantidade:quantidade,p_demanda_ref:selected?.pedido_venda_id?'PCP_OP_PEDIDO':'PCP_OP'});if(run.error)throw run.error;const need=await supabase.from('erp_mrp_necessidades').select('componente_id,quantidade_bruta,estoque_atual,reservado,necessidade_liquida,sugestao').eq('run_id',String(run.data)).order('nivel');if(need.error)throw need.error;const ids=(need.data??[]).map(x=>String(x.componente_id));const ps=ids.length?await supabase.from('erp_produtos').select('id,codigo,nome').in('id',ids):{data:[],error:null};if(ps.error)throw ps.error;const map=new Map((ps.data??[]).map((x:{id:string;codigo:string;nome:string})=>[x.id,x]));setMaterials((need.data??[]).map(x=>({id:String(x.componente_id),codigo:map.get(String(x.componente_id))?.codigo||'—',nome:map.get(String(x.componente_id))?.nome||'—',need:Number(x.quantidade_bruta||0),stock:Number(x.estoque_atual||0),reserved:Number(x.reservado||0),net:Number(x.necessidade_liquida||0),suggestion:String(x.sugestao||'SEM_NECESSIDADE')})))}
 async function saveParameters(){if(!selectedOp){setError('Selecione uma OP existente ou use NOVA OP.');return}setSaving(true);setError('');try{const u=await supabase.from('erp_ordens_producao').update({maquina_id:machineId||null,velocidade_nominal_hora:Number(rate||0),operacao_dupla:doubleOp,tempo_estimado_horas:hours}).eq('id',selectedOp);if(u.error)throw u.error;setMessage('Parâmetros técnicos gravados na OP.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível gravar os parâmetros.')}finally{setSaving(false)}}
 function newOp(){setSelectedOp('');setProdutoId('');setPedidoId('');setMachineId('');setQty('');setRate('30');setDoubleOp(false);setMaterials([]);setMessage('');setError('')}
 async function createOp(){const quantidade=Number(qty);if(!produtoId||quantidade<=0){setError('Produto e quantidade são obrigatórios.');return}setSaving(true);setError('');try{const tenant=await supabase.rpc('erp_current_empresa_id');if(tenant.error||!tenant.data)throw tenant.error||new Error('Empresa ERP não identificada.');const max=await supabase.from('erp_ordens_producao').select('numero_op').eq('empresa_id',tenant.data).order('numero_op',{ascending:false}).limit(1).maybeSingle();if(max.error)throw max.error;const numero=Number(max.data?.numero_op??0)+1;const payload={empresa_id:tenant.data,numero_op:numero,produto_id:produtoId,pedido_venda_id:pedidoId||null,quantidade,quantidade_planejada:quantidade,quantidade_produzida:0,status:'pendente',maquina_id:machineId||null,velocidade_nominal_hora:Number(rate||0),operacao_dupla:doubleOp,tempo_estimado_horas:hours};const ins=await supabase.from('erp_ordens_producao').insert(payload).select('id').single();if(ins.error)throw ins.error;setSelectedOp(String(ins.data.id));const mrp=await supabase.rpc('erp_mrp_explodir',{p_produto_id:produtoId,p_quantidade:quantidade,p_demanda_ref:'PCP_OP_'+numero});if(mrp.error)throw mrp.error;setMessage('OP-'+numero+' criada e MRP explodido no banco.');await load();await explode(produtoId,quantidade)}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a OP.')}finally{setSaving(false)}}
 useEffect(()=>{if(selected){setProdutoId(selected.produto_id||'');setPedidoId(selected.pedido_venda_id||'');setMachineId(selected.maquina_id||'');setQty(String(selected.quantidade_planejada||selected.quantidade||''));setRate(String(selected.velocidade_nominal_hora||30));setDoubleOp(Boolean(selected.operacao_dupla));void explode(selected.produto_id||'',Number(selected.quantidade_planejada||selected.quantidade||0))}},[selectedOp])
 return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-[1600px] space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-sm font-black uppercase tracking-wide text-sky-700">MÓDULO: PCP › PLANEJADOR CENTRAL</p><h1 className="text-2xl font-black">Ordens de Produção e Explosão MRP</h1><p className="mt-1 text-base text-slate-600">OP real, parâmetros técnicos persistidos e MRP multinível real.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={newOp} className="flex h-[54px] items-center gap-2 rounded-md border border-slate-300 bg-white px-4 font-black"><Factory size={18}/> NOVA OP</button><button type="button" onClick={()=>void saveParameters()} disabled={saving||!selectedOp} className="flex h-[54px] items-center gap-2 rounded-md bg-slate-800 px-4 font-black text-white disabled:opacity-50"><Save size={18}/> GRAVAR PARÂMETROS</button></div></header>
  {(message||error)&&<div className={error?'rounded-md border border-rose-300 bg-rose-50 p-4 font-bold text-rose-800':'rounded-md border border-emerald-300 bg-emerald-50 p-4 font-bold text-emerald-800'}>{error||message}</div>}
  <section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-2"><Search size={21} className="text-sky-700"/><h2 className="text-xl font-black">1. IDENTIFICAÇÃO E PARÂMETROS TÉCNICOS HORÁRIOS</h2></div>
   <div className="grid gap-5 lg:grid-cols-2"><label><span className="mb-2 block text-sm font-black uppercase">OP existente</span><select value={selectedOp} onChange={e=>setSelectedOp(e.target.value)} className="h-[54px] w-full rounded-md border border-slate-300 bg-white px-3 text-base font-semibold text-slate-900"><option value="">Selecione uma OP</option>{ops.map(o=><option key={o.id} value={o.id}>OP-{o.numero_op} • {o.status}</option>)}</select></label><EntityCodeLookup label="Produto alvo" value={produtoId} records={productRecords} onChange={setProdutoId} onSelect={r=>{if(r.id)setProdutoId(r.id)}} helper="Código exato ou lupa."/><EntityCodeLookup label="Pedido de venda" value={pedidoId} records={pedidoRecords} onChange={setPedidoId} onSelect={r=>{if(r.id)setPedidoId(r.id)}} helper="Vínculo opcional ao pedido real."/><EntityCodeLookup label="Máquina fixa" value={machineId} records={machineRecords} onChange={setMachineId} onSelect={r=>{if(r.id)setMachineId(r.id)}} helper="Código exato ou lupa."/><label><span className="mb-2 block text-sm font-black uppercase">Quantidade a produzir</span><input type="number" min="0.001" value={qty} onChange={e=>setQty(e.target.value)} className="h-[54px] w-full rounded-md border border-slate-300 bg-white px-3 text-base font-semibold text-slate-900"/></label><label><span className="mb-2 block text-sm font-black uppercase">Velocidade nominal (un/h)</span><input type="number" min="0.001" value={rate} onChange={e=>setRate(e.target.value)} className="h-[54px] w-full rounded-md border border-slate-300 bg-white px-3 text-base font-semibold text-slate-900"/></label></div>
   <label className="mt-5 flex min-h-[54px] items-center gap-3 rounded-md border border-slate-200 bg-slate-50 px-4 text-base font-black"><input type="checkbox" checked={doubleOp} onChange={e=>setDoubleOp(e.target.checked)} className="h-5 w-5"/> ATIVAR OPERAÇÃO DUPLA — PRENSA DE DOIS MOLDES SÍNCRONOS FRENTE/TRÁS</label>
   <div className="mt-5 grid gap-4 md:grid-cols-3"><article className="rounded-md border border-sky-200 bg-sky-50 p-4"><span className="text-sm font-black text-slate-600">VELOCIDADE CALCULADA</span><strong className="mt-1 block text-2xl">{effectiveRate.toLocaleString('pt-BR')} un/h</strong></article><article className="rounded-md border border-slate-200 bg-white p-4"><span className="text-sm font-black text-slate-600">TEMPO ESTIMADO</span><strong className="mt-1 block text-2xl">{Math.floor(hours)}h {Math.round((hours%1)*60)}min</strong></article><article className="rounded-md border border-slate-200 bg-white p-4"><span className="text-sm font-black text-slate-600">CARGA DA MÁQUINA</span><strong className="mt-1 block text-2xl">{hours.toFixed(2)} h</strong></article></div>
   <div className="mt-5 flex justify-end"><button type="button" onClick={()=>void createOp()} disabled={saving||loading} className="flex h-[54px] items-center gap-2 rounded-md bg-sky-700 px-5 font-black text-white disabled:opacity-50"><Zap size={18}/> CRIAR OP + EXPLODIR MRP</button></div>
  </section>
  <section className="overflow-hidden rounded-md border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-200 px-5 py-4"><Calculator size={21} className="text-sky-700"/><div><h2 className="text-xl font-black">2. EXPLOSÃO DA RECEITA (BOM) E DISPONIBILIDADE DO ALMOXARIFADO</h2><p className="text-sm font-semibold text-slate-600">MRP multinível executado pela função real do Supabase.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-base"><thead className="bg-slate-100 text-left text-sm font-black uppercase"><tr><th className="h-[54px] px-4">Insumo requerido</th><th className="px-4 text-right">Qtd necessária</th><th className="px-4 text-right">Estoque físico</th><th className="px-4 text-right">Reservado</th><th className="px-4 text-right">Necessidade líquida</th><th className="px-4">Situação</th></tr></thead><tbody>{materials.length===0?<tr><td colSpan={6} className="p-10 text-center font-bold text-slate-600">Selecione/crie uma OP com ficha técnica/BOM ativa para executar a explosão real.</td></tr>:materials.map(m=><tr key={m.id} className="border-t border-slate-200"><td className="h-[54px] px-4"><strong>{m.codigo}</strong><span className="ml-3 text-slate-600">{m.nome}</span></td><td className="px-4 text-right font-semibold">{m.need.toLocaleString('pt-BR',{maximumFractionDigits:3})}</td><td className="px-4 text-right">{m.stock.toLocaleString('pt-BR',{maximumFractionDigits:3})}</td><td className="px-4 text-right">{m.reserved.toLocaleString('pt-BR',{maximumFractionDigits:3})}</td><td className="px-4 text-right font-black">{m.net.toLocaleString('pt-BR',{maximumFractionDigits:3})}</td><td className="px-4 font-black">{m.suggestion==='PRODUZIR'?<span className="text-amber-700">FABRICAR</span>:m.suggestion==='COMPRAR'?<span className="text-rose-700">MANDAR COMPRAS</span>:<span className="text-emerald-700">DISPONÍVEL</span>}</td></tr>)}</tbody></table></div></section>
 </div></main>
}
