import { useEffect, useState } from 'react'
import { Square } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
type M={id:string;codigo:string;nome:string};type O={id:string;numero_op?:string;numero?:string}
const reasons=[['MANUTENÇÃO MECÂNICA / ELÉTRICA','bg-orange-500'],['TROCA DE MOLDE / SETUP','bg-blue-600'],['FALTA DE MATÉRIA-PRIMA','bg-rose-600'],['FALTA DE OPERADOR / REFEIÇÃO','bg-slate-600']]
export default function PCPParadas(){const[machines,setMachines]=useState<M[]>([]),[ops,setOps]=useState<O[]>([]),[machine,setMachine]=useState(''),[op,setOp]=useState(''),[reason,setReason]=useState(''),[obs,setObs]=useState(''),[started,setStarted]=useState<Date|null>(null),[elapsed,setElapsed]=useState(0),[msg,setMsg]=useState('')
useEffect(()=>{void(async()=>{const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)return;const[m,o]=await Promise.all([supabase.from('erp_maquinas').select('id,codigo,nome').eq('empresa_id',c.data).eq('ativo',true).order('codigo'),supabase.from('erp_ordens_producao').select('id,numero_op,numero').eq('empresa_id',c.data).order('created_at',{ascending:false}).limit(200)]);setMachines((m.data??[]) as M[]);setOps((o.data??[]) as O[]);if(m.data?.[0])setMachine(m.data[0].id);if(o.data?.[0])setOp(o.data[0].id)})()},[])
useEffect(()=>{if(!started)return;const id=window.setInterval(()=>setElapsed(Math.floor((Date.now()-started.getTime())/1000)),1000);return()=>window.clearInterval(id)},[started])
const fmt=(s:number)=>[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(v=>String(v).padStart(2,'0')).join(':')
async function close(){if(!machine||!reason||!started)return;const c=await supabase.rpc('erp_current_empresa_id');if(c.error||!c.data)return;const r=await supabase.from('erp_producao_paradas').insert({empresa_id:c.data,maquina_id:machine,ordem_producao_id:op||null,motivo:reason,inicio:started.toISOString(),fim:new Date().toISOString(),observacao:obs||null,status:'ENCERRADA'});if(r.error){setMsg(r.error.message);return}setMsg('Evento encerrado e OEE liberado.');setStarted(null);setElapsed(0);setReason('')}
return <main className="min-h-screen bg-slate-900 p-5 text-white"><header className="flex items-center justify-between border-b border-slate-700 pb-4"><div><p className="text-sm font-bold text-sky-300">PCP &gt; PARADAS / SETUP</p><h1 className="text-2xl font-black">Registro de Parada de Máquina</h1></div><button onClick={()=>void close()} disabled={!reason||!started} className="rounded-md bg-emerald-600 px-6 py-4 text-lg font-black disabled:opacity-40"><Square className="mr-2 inline"/>FECHAR EVENTO E RETORNAR PRODUÇÃO</button></header><div className="mx-auto mt-6 max-w-[1600px] grid grid-cols-1 gap-5 lg:grid-cols-2"><section className="rounded-xl border border-slate-700 bg-slate-800 p-6"><div className="grid grid-cols-2 gap-5"><div><span className="text-sm font-bold text-slate-400">MÁQUINA</span><p className="mt-2 text-xl font-black">{machines.find(x=>x.id===machine)?.codigo||'—'}</p></div><div><span className="text-sm font-bold text-slate-400">OP</span><p className="mt-2 text-xl font-black">{ops.find(x=>x.id===op)?.numero_op||ops.find(x=>x.id===op)?.numero||'—'}</p></div></div><div className="mt-6 rounded-lg bg-slate-950 p-6 text-center"><span className="text-sm font-bold text-slate-400">TEMPO DE PARADA</span><div className="mt-2 font-mono text-5xl font-black text-amber-300">{fmt(elapsed)}</div></div></section><section className="rounded-xl border border-slate-700 bg-slate-800 p-6"><h2 className="text-xl font-black">MOTIVO OBRIGATÓRIO</h2><div className="mt-4 grid gap-3">{reasons.map(([label,color])=><button key={label} onClick={()=>{setReason(label);if(!started)setStarted(new Date())}} className={'min-h-20 rounded-lg px-5 text-left text-lg font-black '+color}>{label}</button>)}</div><textarea className="mt-4 min-h-32 w-full rounded-lg border border-slate-600 bg-slate-950 p-4 text-base text-white" value={obs} onChange={e=>setObs(e.target.value)} placeholder="Observação rápida do operador..."/></section></div>{msg&&<div className="mx-auto mt-5 max-w-[1600px] rounded-md bg-emerald-900 p-4 font-bold text-emerald-100">{msg}</div>}</main>}
