/**
 * =========================================================================
 * REVISÃO DE ENGENHARIA DE SOFTWARE INDUSTRIAL
 * Data/Hora: 24/09/2026 - 11:43 BRT
 * Desenvolvedor: IA Co-Pilot (Homologado por Fernando)
 * ID da Revisão: REV-050
 * Alterações: Corrigir referências antigas qtd para o campo estrito quantidade.
 * Status do Build Local: Não executado — ambiente local sem acesso de rede ao repositório.
 * =========================================================================
 */

/**
 * =========================================================================
 * REVISÃO DE ENGENHARIA DE SOFTWARE INDUSTRIAL
 * Data/Hora: 24/09/2026 - 11:43 BRT
 * Desenvolvedor: IA Co-Pilot (Homologado por Fernando)
 * ID da Revisão: REV-036
 * Alterações: Eliminar any da coleção de pedidos e do atualizador de itens, usando tipos Order e valores estritos.
 * Status do Build Local: Não executado — ambiente local sem acesso de rede ao repositório.
 * =========================================================================
 */

import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabaseClient'
import {Plus,Save,Trash2,PackageCheck,Factory,Search,RefreshCw,CheckCircle2} from 'lucide-react'
type Client={id:string;nome:string;documento:string|null};type Product={id:string;codigo:string;nome:string;estoque_atual:number;preco_venda:number;unidade:string}
type Item={produto_id:string;codigo:string;descricao:string;quantidade:string;valor:string;estoque:number;reservado:boolean;produzir:boolean}
type Order={id:string;numero:number;status:string;total:number;data_entrega_prometida:string|null;cliente_id:string}
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
export default function PedidoVendaCompleto(){
 const[empresa,setEmpresa]=useState(''),[savedOrderId,setSavedOrderId]=useState(''),[clients,setClients]=useState<Client[]>([]),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[client,setClient]=useState(''),[clientDoc,setClientDoc]=useState(''),[number,setNumber]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[delivery,setDelivery]=useState(''),[items,setItems]=useState<Item[]>([]),[draft,setDraft]=useState({produto:'',qtd:'1',valor:'0'}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 const load=async()=>{setErr('');const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada');const id=String(e.data);setEmpresa(id);const [c,p,o]=await Promise.all([supabase.from('erp_clientes').select('id,nome,documento').eq('empresa_id',id).eq('ativo',true).order('nome'),supabase.from('erp_produtos').select('id,codigo,nome,estoque_atual,preco_venda,unidade').eq('empresa_id',id).eq('ativo',true).order('codigo').limit(2000),supabase.from('erp_pedidos_venda').select('id,numero,status,total,data_entrega_prometida,cliente_id').eq('empresa_id',id).order('numero',{ascending:false}).limit(100)]);for(const x of[c,p,o])if(x.error)throw x.error;setClients(c.data||[]);setProducts(p.data||[]);setOrders(o.data||[]);setNumber(String((Number(o.data?.[0]?.numero||0)+1)).padStart(6,'0'))}
 useEffect(()=>{void load().catch(e=>setErr(e.message))},[])
 const selected=products.find(p=>p.id===draft.produto);const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.quantidade)*Number(i.valor),0),[items]);const needs=items.filter(i=>Number(i.quantidade)>i.estoque&&!i.produzir);const prodItems=items.filter(i=>i.produzir||Number(i.quantidade)>i.estoque)
 function choose(id:string){const p=products.find(x=>x.id===id);if(!p)return;setDraft({...draft,produto:id,valor:String(p.preco_venda||0)})}
 function add(){if(!selected||Number(draft.qtd)<=0)return;setItems([...items,{produto_id:selected.id,codigo:selected.codigo,descricao:selected.nome,quantidade:draft.qtd,valor:draft.valor||String(selected.preco_venda||0),estoque:Number(selected.estoque_atual||0),reservado:false,produzir:Number(draft.qtd)>Number(selected.estoque_atual||0)}]);setDraft({produto:'',qtd:'1',valor:'0'})}
 function update(i:number,k:keyof Item,v:string|number|boolean){setItems(x=>x.map((a,n)=>n===i?{...a,[k]:v}:a))}
 async function save(){if(!empresa||!client||!items.length)return setErr('Cliente e pelo menos um item são obrigatórios.');setBusy(true);setErr('');try{const p=await supabase.from('erp_pedidos_venda').insert({empresa_id:empresa,numero:Number(number),cliente_id:client,status:'Pendente',total,created_at:new Date(date).toISOString(),data_entrega_prometida:delivery||null}).select('id,numero').single();if(p.error)throw p.error;const rows=items.map(i=>({empresa_id:empresa,pedido_id:p.data.id,produto_id:i.produto_id,descricao:i.descricao,quantidade:Number(i.quantidade),valor_unitario:Number(i.valor),desconto:0,total:Number(i.quantidade)*Number(i.valor)}));const ins=await supabase.from('erp_pedidos_venda_itens').insert(rows).select('id,produto_id,quantidade');if(ins.error)throw ins.error;setSavedOrderId(p.data.id);setMsg('Pedido '+p.data.numero+' gravado. Agora reserve o estoque disponível e gere OP para os itens sem saldo.');setItems(items.map(i=>({...i,reservado:false})));await load()}catch(e){setErr(e instanceof Error?e.message:'Falha ao gravar pedido.')}finally{setBusy(false)}}
 async function reserve(item:Item){const last=savedOrderId?{id:savedOrderId}:orders.find(o=>Number(o.numero)===Number(number));if(!last)return setErr('Grave o pedido antes de reservar.');const pi=await supabase.from('erp_pedidos_venda_itens').select('id').eq('pedido_id',last.id).eq('produto_id',item.produto_id).maybeSingle();if(pi.error||!pi.data)return setErr(pi.error?.message||'Item não encontrado.');const r=await supabase.from('erp_estoque_reservas').insert({empresa_id:empresa,pedido_venda_id:last.id,pedido_item_id:pi.data.id,produto_id:item.produto_id,quantidade:Number(item.quantidade)});if(r.error)setErr(r.error.message);else{setMsg('Estoque reservado para '+item.codigo+'.');setItems(items.map(i=>i===item?{...i,reservado:true}:i))}}
 async function generateOP(){const last=savedOrderId?{id:savedOrderId}:orders.find(o=>Number(o.numero)===Number(number));if(!last)return setErr('Grave o pedido antes de gerar OP.');setBusy(true);try{for(const i of prodItems){const op=await supabase.from('erp_ordens_producao').insert({empresa_id:empresa,numero_op:'OP-'+number+'-'+i.codigo,produto_id:i.produto_id,quantidade:Number(i.quantidade),status:'Aguardando PCP',pedido_venda_id:last.id,data_prevista:delivery||null,observacoes:'Gerada automaticamente pelo Pedido de Venda'});if(op.error)throw op.error}setMsg('Ordens de produção criadas e encaminhadas ao PCP.');}catch(e){setErr(e instanceof Error?e.message:'Falha ao gerar OP.')}finally{setBusy(false)}}
 return <main className="erp-page-v3" style={{maxWidth:1550,margin:'0 auto',padding:24}}><header className="erp-page-header-v3"><div><span className="erp-eyebrow">COMERCIAL • VENDAS</span><h1>Novo Pedido de Venda</h1><p>Pedido completo: cliente → itens → estoque → reserva → OP → PCP.</p></div><button className="erp-btn-secondary" onClick={()=>void load()}><RefreshCw/>Atualizar</button></header>
 {(msg||err)&&<div className={err?'error':'notice'}>{err||msg}</div>}
 <section className="erp-card-v3" style={{padding:20}}><div className="grid md:grid-cols-5 gap-4"><label>Nº Pedido<input value={number} readOnly/></label><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="md:col-span-2">Cliente<select value={client} onChange={e=>{setClient(e.target.value);setClientDoc(clients.find(c=>c.id===e.target.value)?.documento||'')}}><option value="">Selecione o cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Documento<input value={clientDoc} readOnly/></label><label>Data de entrega<input type="date" value={delivery} onChange={e=>setDelivery(e.target.value)}/></label></div>
 <div className="grid md:grid-cols-6 gap-3 mt-5 items-end"><label className="md:col-span-3">Código interno / Produto<select value={draft.produto} onChange={e=>choose(e.target.value)}><option value="">Digite/selecione o produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.codigo} • {p.nome}</option>)}</select></label><label>Quantidade<input type="number" min="1" value={draft.qtd} onChange={e=>setDraft({...draft,qtd:e.target.value})}/></label><label>Valor unitário<input type="number" step="0.01" value={draft.valor} onChange={e=>setDraft({...draft,valor:e.target.value})}/></label><button className="erp-btn-primary" onClick={add}><Plus/>Adicionar item</button></div>
 {selected&&<div className="mt-3 p-4 rounded-xl bg-slate-50 border"><b>{selected.codigo} • {selected.nome}</b><span className="ml-5">Estoque disponível: <strong>{selected.estoque_atual} {selected.unidade}</strong></span>{Number(draft.qtd)>Number(selected.estoque_atual)&&<span className="ml-5 text-amber-700 font-bold">Saldo insuficiente → OP necessária</span>}</div>}
 <div className="erp-table-scroll mt-5"><table className="erp-table-v3"><thead><tr><th>Código</th><th>Descrição</th><th>Qtd.</th><th>Estoque</th><th>Valor</th><th>Total</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{items.map((i,n)=><tr key={n}><td>{i.codigo}</td><td>{i.descricao}</td><td>{i.quantidade}</td><td>{i.estoque}</td><td>{money(Number(i.valor))}</td><td>{money(Number(i.quantidade)*Number(i.valor))}</td><td>{i.reservado?'Reservado':Number(i.quantidade)>i.estoque?'Produzir':'Disponível'}</td><td className="flex gap-2">{!i.reservado&&Number(i.quantidade)<=i.estoque&&<button className="erp-btn-secondary" onClick={()=>void reserve(i)}><PackageCheck/>Reservar</button>}{Number(i.quantidade)>i.estoque&&<button className="erp-btn-secondary" onClick={()=>update(n,'produzir',true)}><Factory/>Gerar OP</button>}<button className="erp-btn-secondary" onClick={()=>setItems(items.filter((_,x)=>x!==n))}><Trash2/></button></td></tr>)}{!items.length&&<tr><td colSpan={8}>Adicione os produtos do pedido.</td></tr>}</tbody></table></div>
 <div className="flex justify-between items-center mt-5 p-4 rounded-xl bg-slate-50 border"><div><b>Total do pedido: {money(total)}</b><div className="text-sm text-slate-500">Itens para produção: {prodItems.length} • Itens com saldo insuficiente: {needs.length}</div></div><div className="flex gap-3"><button className="erp-btn-primary" disabled={busy||!items.length} onClick={()=>void save()}><Save/>Gravar Pedido</button><button className="erp-btn-secondary" disabled={busy||!prodItems.length} onClick={()=>void generateOP()}><Factory/>Gerar OP e enviar ao PCP</button></div></div></section>
 <section className="erp-card-v3 mt-5" style={{padding:20}}><h2>Pedidos recentes</h2><div className="erp-table-scroll"><table className="erp-table-v3"><thead><tr><th>Pedido</th><th>Status</th><th>Total</th><th>Entrega</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>PV-{o.numero}</td><td>{o.status}</td><td>{money(Number(o.total))}</td><td>{o.data_entrega_prometida||'—'}</td></tr>)}</tbody></table></div></section>
 </main>
}
