import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,CheckCircle2,FileText,Printer,RefreshCw,Save,ShieldCheck,TriangleAlert} from 'lucide-react'
import {BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts'
import {supabase} from '../lib/supabaseClient'
import '../styles/ppap-ria-psw.css'

type Plan={id:string;codigo:string;caracteristica:string;unidade:string|null;limite_inferior:number|null;limite_superior:number|null;frequencia:string|null;status:string|null}
type Item={id:string;sequencia:number;caracteristica:string;especificacao:string|null;unidade:string|null;nominal:number|null;limite_inferior:number|null;limite_superior:number|null;metodo_inspecao:string|null;frequencia:string|null;amostras:number[];valor_encontrado:number|null;media:number|null;desvio_padrao:number|null;minimo_encontrado:number|null;maximo_encontrado:number|null;status:string}
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):null
const stats=(values:number[])=>{if(!values.length)return{mean:null,sd:null,min:null,max:null};const mean=values.reduce((a,b)=>a+b,0)/values.length;const sd=values.length>1?Math.sqrt(values.reduce((s,v)=>s+(v-mean)**2,0)/(values.length-1)):0;return{mean,sd,min:Math.min(...values),max:Math.max(...values)}}
export default function PPAPRiaPSW(){
 const[empresaId,setEmpresaId]=useState(''),[plans,setPlans]=useState<Plan[]>([]),[items,setItems]=useState<Item[]>([]),[codigo,setCodigo]=useState(''),[produtoId,setProdutoId]=useState(''),[cliente,setCliente]=useState(''),[clienteCodigo,setClienteCodigo]=useState(''),[fornecedor,setFornecedor]=useState(''),[nivel,setNivel]=useState('3'),[tipo,setTipo]=useState('Inicial'),[lote,setLote]=useState(''),[quantidadeLote,setQuantidadeLote]=useState('0'),[quantidadeAmostra,setQuantidadeAmostra]=useState('0'),[observacoes,setObservacoes]=useState(''),[ppapId,setPpapId]=useState(''),[psw,setPsw]=useState({partNumber:'',partName:'',drawingNumber:'',engineeringChangeLevel:'',weight:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')

 async function load(){setBusy(true);setError('');try{const{data:empresa,error:ee}=await supabase.rpc('erp_current_empresa_id');if(ee)throw ee;const id=String(empresa||'');if(!id)throw new Error('Empresa da sessão não identificada.');setEmpresaId(id);const r=await supabase.from('erp_planos_inspecao').select('id,codigo,caracteristica,unidade,limite_inferior,limite_superior,frequencia,status').eq('empresa_id',id).order('codigo').limit(500);if(r.error)throw r.error;setPlans((r.data||[]) as Plan[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar planos de inspeção.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const addPlan=(p:Plan)=>{if(items.some(i=>i.plano_inspecao_id===p.id))return;setItems(x=>[...x,{id:'new-'+p.id+'-'+Date.now(),sequencia:x.length+1,caracteristica:p.caracteristica,especificacao:p.codigo,unidade:p.unidade,nominal:p.limite_inferior!=null&&p.limite_superior!=null?(p.limite_inferior+p.limite_superior)/2:null,limite_inferior:p.limite_inferior,limite_superior:p.limite_superior,metodo_inspecao:'Medição dimensional',frequencia:p.frequencia,amostras:[],valor_encontrado:null,media:null,desvio_padrao:null,minimo_encontrado:null,maximo_encontrado:null,status:'PENDENTE'}])}
 const addAll=()=>setItems(plans.map((p,n)=>({id:'new-'+p.id+'-'+n,sequencia:n+1,caracteristica:p.caracteristica,especificacao:p.codigo,unidade:p.unidade,nominal:p.limite_inferior!=null&&p.limite_superior!=null?(p.limite_inferior+p.limite_superior)/2:null,limite_inferior:p.limite_inferior,limite_superior:p.limite_superior,metodo_inspecao:'Medição dimensional',frequencia:p.frequencia,amostras:[],valor_encontrado:null,media:null,desvio_padrao:null,minimo_encontrado:null,maximo_encontrado:null,status:'PENDENTE'})))
 const setValue=(index:number,value:string)=>{const v=num(value);setItems(x=>x.map((it,i)=>{if(i!==index)return it;const status=v==null?'PENDENTE':((it.limite_inferior!=null&&v<it.limite_inferior)||(it.limite_superior!=null&&v>it.limite_superior))?'NAO_CONFORME':'CONFORME';const values=[...it.amostras];if(v!=null)values.push(v);const clean=values.filter(Number.isFinite);const s=stats(clean);return {...it,valor_encontrado:v,status,media:s.mean,desvio_padrao:s.sd,minimo_encontrado:s.min,maximo_encontrado:s.max,amostras:clean}}))}
 const overall=useMemo(()=>{const measured=items.filter(i=>i.valor_encontrado!=null);const ok=measured.filter(i=>i.status==='CONFORME').length;return{measured:measured.length,total:items.length,pct:measured.length?Math.round(ok/measured.length*10000)/100:0,ok}},[items])
 const chart=useMemo(()=>items.filter(i=>i.valor_encontrado!=null).map(i=>({name:i.caracteristica.slice(0,16),valor:Number(i.valor_encontrado),min:i.limite_inferior,max:i.limite_superior})),[items])
 async function save(){setBusy(true);setError('');try{if(!codigo.trim())throw new Error('Informe o código do PPAP/RIA.');if(!items.length)throw new Error('Adicione pelo menos uma característica do plano de inspeção.');const header={empresa_id:empresaId,codigo:codigo.trim(),produto_id:produtoId||null,cliente_nome:cliente||null,cliente_codigo:clienteCodigo||null,fornecedor_nome:fornecedor||null,nivel_submissao:nivel,tipo_submissao:tipo,lote_piloto:lote||null,quantidade_lote:Number(quantidadeLote||0),quantidade_amostra:Number(quantidadeAmostra||0),observacoes:observacoes||null,status:overall.pct===100?'CONFORME':'EM_ANALISE',conformidade_percentual:overall.pct,psw_liberado:overall.pct===100&&overall.measured>0};const h=ppapId?await supabase.from('erp_ppap_ria').update(header).eq('id',ppapId).eq('empresa_id',empresaId).select('id').single():await supabase.from('erp_ppap_ria').insert(header).select('id').single();if(h.error)throw h.error;const id=String(h.data.id);setPpapId(id);await supabase.from('erp_ppap_ria_itens').delete().eq('ppap_id',id);const rows=items.map((i,n)=>({empresa_id:empresaId,ppap_id:id,plano_inspecao_id:i.especificacao?plans.find(p=>p.codigo===i.especificacao)?.id||null:null,sequencia:n+1,caracteristica:i.caracteristica,especificacao:i.especificacao,unidade:i.unidade,nominal:i.nominal,limite_inferior:i.limite_inferior,limite_superior:i.limite_superior,metodo_inspecao:i.metodo_inspecao,frequencia:i.frequencia,amostras:i.amostras,valor_encontrado:i.valor_encontrado,media:i.media,desvio_padrao:i.desvio_padrao,minimo_encontrado:i.minimo_encontrado,maximo_encontrado:i.maximo_encontrado,status:i.status}));const ins=await supabase.from('erp_ppap_ria_itens').insert(rows);if(ins.error)throw ins.error;const p=await supabase.from('erp_ppap_psw').upsert({empresa_id:empresaId,ppap_id:id,part_number:psw.partNumber||null,part_name:psw.partName||null,drawing_number:psw.drawingNumber||null,engineering_change_level:psw.engineeringChangeLevel||null,weight:psw.weight?Number(psw.weight):null},{onConflict:'ppap_id'});if(p.error)throw p.error;setMessage('PPAP/RIA salvo no banco real.');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar PPAP/RIA.')}finally{setBusy(false)}}
 async function evaluate(index:number){const it=items[index];if(!it.id||it.id.startsWith('new-')||it.valor_encontrado==null)return;const r=await supabase.rpc('erp_ppap_avaliar_item',{p_item_id:it.id,p_valor:it.valor_encontrado});if(r.error)return;const status=String(r.data);setItems(x=>x.map((v,i)=>i===index?{...v,status}:v));if(ppapId)await supabase.rpc('erp_ppap_recalcular_resumo',{p_ppap_id:ppapId})}
 function printPSW(){window.print()}
 return <main className="ppap-page"><header className="ppap-header no-print"><div><button className="ppap-back" onClick={()=>location.href='/qualidade'}><ArrowLeft size={18}/> Voltar à Qualidade</button><span>SGQ • PPAP / RIA</span><h1>PPAP & RIA — PSW / Certificado FAI</h1><p>Ficha de aprovação de peça com plano dimensional, amostras, tolerâncias e decisão automática.</p></div><div className="ppap-actions"><button onClick={()=>void load()} disabled={busy}><RefreshCw size={17}/> Atualizar</button><button onClick={()=>void save()} disabled={busy}><Save size={17}/> Salvar</button><button className="primary" disabled={overall.pct!==100||overall.measured===0} onClick={printPSW}><Printer size={17}/> Imprimir Capa PSW / FAI</button></div></header>
 <section className="ppap-paper"><div className="ppap-titlebar"><div><small>PLANTA 01 • SGQ ERP INDUSTRIAL</small><h2>RELATÓRIO DE APROVAÇÃO DE PEÇA — RIA / PSW</h2></div><div className={overall.pct===100?'status-ok':'status-warn'}>{overall.pct}% CONFORME</div></div>
 {(error||message)&&<div className={error?'ppap-alert error':'ppap-alert'}>{error||message}</div>}
 <div className="ppap-grid four"><label>Código PPAP/RIA<input value={codigo} onChange={e=>setCodigo(e.target.value)} placeholder="PPAP-2026-0001"/></label><label>Cliente<input value={cliente} onChange={e=>setCliente(e.target.value)} /></label><label>Código cliente<input value={clienteCodigo} onChange={e=>setClienteCodigo(e.target.value)} /></label><label>Fornecedor<input value={fornecedor} onChange={e=>setFornecedor(e.target.value)} /></label><label>Nível de submissão<select value={nivel} onChange={e=>setNivel(e.target.value)}><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Tipo de submissão<select value={tipo} onChange={e=>setTipo(e.target.value)}><option>Inicial</option><option>Alteração de engenharia</option><option>Correção</option><option>Revalidação</option></select></label><label>Lote piloto<input value={lote} onChange={e=>setLote(e.target.value)} /></label><label>Quantidade do lote<input type="number" value={quantidadeLote} onChange={e=>setQuantidadeLote(e.target.value)} /></label><label>Amostra<input type="number" value={quantidadeAmostra} onChange={e=>setQuantidadeAmostra(e.target.value)} /></label><label>Part number<input value={psw.partNumber} onChange={e=>setPsw({...psw,partNumber:e.target.value})} /></label><label>Part name<input value={psw.partName} onChange={e=>setPsw({...psw,partName:e.target.value})} /></label><label>Desenho / revisão<input value={psw.drawingNumber} onChange={e=>setPsw({...psw,drawingNumber:e.target.value})} /></label></div>
 <div className="ppap-section"><div className="ppap-section-head"><div><span>PLANO DE INSPEÇÃO</span><h3>Características e critérios de aceitação</h3></div><button className="no-print" onClick={addAll}><ShieldCheck size={16}/> Adicionar todos</button></div><div className="ppap-plan-list">{plans.slice(0,80).map(p=><button className="ppap-plan-row no-print" key={p.id} onClick={()=>addPlan(p)}><span>{p.codigo}</span><b>{p.caracteristica}</b><small>{p.limite_inferior??'—'} ≤ valor ≤ {p.limite_superior??'—'} {p.unidade||''}</small></button>)}</div></div>
 <div className="ppap-section"><div className="ppap-section-head"><div><span>COLETA DIMENSIONAL</span><h3>Valor encontrado da amostra</h3></div><div className="ppap-legend"><span className="ok-dot"/> Conforme <span className="bad-dot"/> Não conforme</div></div><div className="ppap-table-wrap"><table className="ppap-table"><thead><tr><th>#</th><th>Característica</th><th>Especificação</th><th>Un.</th><th>Mín.</th><th>Máx.</th><th>Valor encontrado</th><th>Média</th><th>Desvio</th><th>Status</th></tr></thead><tbody>{items.map((i,n)=><tr key={i.id} className={i.status==='NAO_CONFORME'?'row-bad':''}><td>{n+1}</td><td><b>{i.caracteristica}</b><small>{i.metodo_inspecao}</small></td><td>{i.especificacao||'—'}</td><td>{i.unidade||'—'}</td><td>{i.limite_inferior??'—'}</td><td>{i.limite_superior??'—'}</td><td><input className={i.status==='NAO_CONFORME'?'measure bad':''} type="number" step="0.0001" value={i.valor_encontrado??''} onChange={e=>setValue(n,e.target.value)} onBlur={()=>void evaluate(n)} placeholder="Digite a medição"/></td><td>{i.media==null?'—':i.media.toFixed(4)}</td><td>{i.desvio_padrao==null?'—':i.desvio_padrao.toFixed(4)}</td><td><span className={i.status==='CONFORME'?'ppap-status ok':i.status==='NAO_CONFORME'?'ppap-status bad':'ppap-status pending'}>{i.status==='CONFORME'?'CONFORME':i.status==='NAO_CONFORME'?'NÃO CONFORME':'PENDENTE'}</span></td></tr>)}</tbody></table>{!items.length&&<div className="ppap-empty">Selecione características no plano de inspeção acima.</div>}</div></div>
 <div className="ppap-dashboard-grid no-print"><section className="ppap-chart"><h3>Distribuição das medições</h3>{chart.length?<ResponsiveContainer width="100%" height={280}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="valor" name="Encontrado"/></BarChart></ResponsiveContainer>:<div className="ppap-empty">Ainda não há medições.</div>}</section><section className="ppap-summary"><h3>Decisão do lote piloto</h3><div className="ppap-big">{overall.pct}%</div><p>{overall.ok} de {overall.measured} características medidas estão dentro da faixa nominal.</p><div className="ppap-progress"><i style={{width:overall.pct+'%'}}/></div>{overall.pct===100&&overall.measured>0?<div className="ppap-ready"><CheckCircle2/> PSW/FAI liberado para impressão.</div>:<div className="ppap-blocked"><TriangleAlert/> A impressão fica bloqueada até 100% de conformidade dimensional.</div>}</section></div>
 <label className="ppap-notes">Observações<textarea value={observacoes} onChange={e=>setObservacoes(e.target.value)} rows={4}/></label>
 </section>
 <section className="psw-print-sheet print-only"><h1>PART SUBMISSION WARRANT — PSW / CERTIFICADO FAI</h1><div className="psw-meta"><b>PPAP/RIA:</b> {codigo||'—'} <b>Cliente:</b> {cliente||'—'} <b>Part Number:</b> {psw.partNumber||'—'}</div><h2>Declaração de conformidade</h2><p>Declaramos que as características dimensionais registradas nesta ficha foram verificadas conforme os critérios de aceitação definidos no plano de inspeção.</p><table><thead><tr><th>Característica</th><th>Mín.</th><th>Máx.</th><th>Encontrado</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.caracteristica}</td><td>{i.limite_inferior??'—'}</td><td>{i.limite_superior??'—'}</td><td>{i.valor_encontrado??'—'}</td><td>{i.status}</td></tr>)}</tbody></table><div className="psw-signatures"><div>Preparado por<br/><br/>____________________________</div><div>Verificado por<br/><br/>____________________________</div><div>Aprovado pelo cliente<br/><br/>____________________________</div></div></section>
 </main>
}
