import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Check, Edit3, Plus, RefreshCw, Search, ShoppingCart, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Product={id:string;codigo:string;nome:string;unidade:string;tipo:string;estoque_minimo:number;estoque_atual:number;custo_medio:number;custo_ultimo:number;custo_fabricacao:number;preco_venda:number;markup_percentual:number;margem_valor:number;margem_percentual:number;ativo:boolean}
type Client={id:string;nome:string}
type Sale={id:string;cliente_id:string|null;status:string;subtotal:number;desconto:number;total:number;created_at:string}
type CartItem={produto_id:string;quantidade:number;valor_unitario:number}

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)
const n=(v:string)=>Number(String(v).replace(',','.'))||0

export default function ProdutosVendasIndustrial(){
 const [tab,setTab]=useState<'produtos'|'vendas'>('produtos'),[products,setProducts]=useState<Product[]>([]),[clients,setClients]=useState<Client[]>([]),[sales,setSales]=useState<Sale[]>([])
 const [search,setSearch]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState<string|null>(null),[showForm,setShowForm]=useState(false)
 const [form,setForm]=useState({codigo:'',nome:'',unidade:'UN',tipo:'produto',estoque_minimo:'0',estoque_atual:'0',custo_medio:'0',custo_ultimo:'0',custo_fabricacao:'0',preco_venda:'0',ativo:true})
 const [cart,setCart]=useState<CartItem[]>([]),[clienteId,setClienteId]=useState(''),[desconto,setDesconto]=useState('0'),[productPick,setProductPick]=useState(''),[qty,setQty]=useState('1')
 const load=async()=>{setBusy(true);setError('');try{const [p,c,s]=await Promise.all([supabase.from('erp_produtos').select('*').order('codigo').limit(1000),supabase.from('erp_clientes').select('id,nome').order('nome').limit(1000),supabase.from('erp_vendas').select('id,cliente_id,status,subtotal,desconto,total,created_at').order('created_at',{ascending:false}).limit(300)]);for(const r of [p,c,s])if(r.error)throw r.error;setProducts((p.data||[]) as Product[]);setClients((c.data||[]) as Client[]);setSales((s.data||[]) as Sale[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar produtos e vendas.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?products.filter(p=>`${p.codigo} ${p.nome} ${p.tipo}`.toLowerCase().includes(q)):products},[products,search])
 const cartTotal=cart.reduce((s,i)=>s+i.quantidade*i.valor_unitario,0),total=Math.max(0,cartTotal-n(desconto))
 const productById=(id:string)=>products.find(p=>p.id===id)
 const openNew=()=>{setEditing(null);setForm({codigo:'',nome:'',unidade:'UN',tipo:'produto',estoque_minimo:'0',estoque_atual:'0',custo_medio:'0',custo_ultimo:'0',custo_fabricacao:'0',preco_venda:'0',ativo:true});setShowForm(true);setMsg('');setError('')}
 const edit=(p:Product)=>{setEditing(p.id);setForm({codigo:p.codigo,nome:p.nome,unidade:p.unidade,tipo:p.tipo,estoque_minimo:String(p.estoque_minimo),estoque_atual:String(p.estoque_atual),custo_medio:String(p.custo_medio),custo_ultimo:String(p.custo_ultimo),custo_fabricacao:String(p.custo_fabricacao),preco_venda:String(p.preco_venda),ativo:p.ativo});setShowForm(true);setError('');setMsg('')}
 const saveProduct=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');setMsg('');try{if(!form.codigo.trim()||!form.nome.trim())throw new Error('Código e nome são obrigatórios.');const payload={codigo:form.codigo.trim(),nome:form.nome.trim(),unidade:form.unidade.trim().toUpperCase()||'UN',tipo:form.tipo,estoque_minimo:n(form.estoque_minimo),custo_medio:n(form.custo_medio),custo_ultimo:n(form.custo_ultimo),custo_fabricacao:n(form.custo_fabricacao),preco_venda:n(form.preco_venda),ativo:form.ativo};let r=editing?await supabase.from('erp_produtos').update(payload).eq('id',editing):await supabase.from('erp_produtos').insert({...payload,estoque_atual:n(form.estoque_atual)});if(r.error)throw r.error;setShowForm(false);setMsg(editing?'Produto atualizado no banco.':'Produto cadastrado no banco.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o produto.')}finally{setBusy(false)}}
 const deleteProduct=async(id:string)=>{if(!confirm('Excluir este produto? Se houver histórico, o sistema bloqueará a exclusão e você deverá inativá-lo.'))return;setBusy(true);setError('');try{const {data,error}=await supabase.rpc('erp_excluir_produto',{p_produto_id:id});if(error)throw error;if(data!==true)throw new Error('Produto não foi excluído.');setMsg('Produto excluído.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir o produto.')}finally{setBusy(false)}}
 const addCart=()=>{const p=productById(productPick);const q=n(qty);if(!p)return setError('Selecione um produto.');if(q<=0)return setError('Quantidade inválida.');const old=cart.find(x=>x.produto_id===p.id);const next=(old?.quantidade||0)+q;if(next>p.estoque_atual)return setError(`Estoque insuficiente de ${p.nome}.`);setCart(old?cart.map(x=>x.produto_id===p.id?{...x,quantidade:next}:x):[...cart,{produto_id:p.id,quantidade:q,valor_unitario:p.preco_venda}]);setProductPick('');setQty('1');setError('')}
 const finishSale=async()=>{if(!cart.length)return setError('Adicione pelo menos um produto à venda.');if(n(desconto)>cartTotal)return setError('Desconto maior que o subtotal.');setBusy(true);setError('');try{const {data,error}=await supabase.rpc('erp_finalizar_venda',{p_cliente_id:clienteId||null,p_desconto:n(desconto),p_itens:cart});if(error)throw error;setCart([]);setDesconto('0');setClienteId('');setMsg(`Venda ${String(data).slice(0,8)} finalizada e estoque atualizado automaticamente.`);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível finalizar a venda.')}finally{setBusy(false)}}
 return <main style={{padding:24,maxWidth:1500,margin:'0 auto',color:'#172033'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:20,flexWrap:'wrap'}}><div><span style={{fontSize:12,fontWeight:900,letterSpacing:1.2,color:'#64748b'}}>COMERCIAL • ESTOQUE • VENDAS</span><h1 style={{margin:'5px 0',fontSize:30}}>Produtos e Vendas</h1><p style={{margin:0,color:'#64748b'}}>Cadastro mestre, estoque, carrinho e fechamento gravados diretamente no Supabase.</p></div><div style={{display:'flex',gap:8}}><button onClick={()=>void load()} disabled={busy} style={btn('secondary')}><RefreshCw size={16}/> Atualizar</button><button onClick={openNew} style={btn('primary')}><Plus size={16}/> Novo produto</button></div></header>
  {(msg||error)&&<div style={{padding:12,borderRadius:12,marginBottom:14,background:error?'#fff1f2':'#ecfdf5',color:error?'#be123c':'#047857'}}>{error||msg}</div>}
  <nav style={{display:'flex',gap:8,marginBottom:18}}><button onClick={()=>setTab('produtos')} style={btn(tab==='produtos'?'primary':'secondary')}>Produtos / Estoque</button><button onClick={()=>setTab('vendas')} style={btn(tab==='vendas'?'primary':'secondary')}><ShoppingCart size={16}/> Frente de Venda</button></nav>
  {tab==='produtos'?<section><div style={{display:'flex',gap:10,alignItems:'center',marginBottom:14}}><label style={{flex:1,position:'relative'}}><Search size={17} style={{position:'absolute',left:12,top:12,color:'#64748b'}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar código, produto ou tipo" style={inp({paddingLeft:38})}/></label><strong>{filtered.length} produto(s)</strong></div><div style={{overflowX:'auto',background:'#fff',border:'1px solid #e2e8f0',borderRadius:16}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1000}}><thead><tr>{['Código','Produto','Un.','Estoque','Mínimo','Custo','Venda','Margem','Status','Ações'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td style={td}><b>{p.codigo}</b></td><td style={td}>{p.nome}</td><td style={td}>{p.unidade}</td><td style={{...td,fontWeight:800,color:p.estoque_atual<=p.estoque_minimo?'#be123c':'#172033'}}>{p.estoque_atual}</td><td style={td}>{p.estoque_minimo}</td><td style={td}>{money(p.custo_medio)}</td><td style={td}>{money(p.preco_venda)}</td><td style={td}>{Number(p.margem_percentual||0).toFixed(1)}%</td><td style={td}>{p.ativo?'Ativo':'Inativo'}</td><td style={{...td,display:'flex',gap:6}}><button onClick={()=>edit(p)} style={iconBtn}><Edit3 size={15}/></button><button onClick={()=>void deleteProduct(p.id)} style={{...iconBtn,color:'#be123c'}}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></section>:<section style={{display:'grid',gridTemplateColumns:'1.5fr 1fr',gap:18}}>
   <div style={panel}><h2 style={h2}>Nova venda</h2><div style={{display:'grid',gridTemplateColumns:'1fr 150px auto',gap:10,alignItems:'end'}}><label style={lab}>Produto<select value={productPick} onChange={e=>setProductPick(e.target.value)} style={inp()}><option value="">Selecione</option>{products.filter(p=>p.ativo&&p.estoque_atual>0).map(p=><option key={p.id} value={p.id}>{p.codigo} • {p.nome} — {money(p.preco_venda)}</option>)}</select></label><label style={lab}>Quantidade<input type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(e.target.value)} style={inp()}/></label><button onClick={addCart} style={btn('primary')}><Plus size={16}/> Adicionar</button></div><div style={{marginTop:18}}>{cart.map(i=>{const p=productById(i.produto_id)!;return <div key={i.produto_id} style={{display:'grid',gridTemplateColumns:'1fr 100px 120px 40px',gap:8,alignItems:'center',padding:'12px 0',borderBottom:'1px solid #e2e8f0'}}><span><b>{p.codigo}</b> • {p.nome}</span><input type="number" min="0.01" step="0.01" value={i.quantidade} onChange={e=>setCart(cart.map(x=>x.produto_id===i.produto_id?{...x,quantidade:n(e.target.value)}:x))} style={inp()}/><b>{money(i.quantidade*i.valor_unitario)}</b><button onClick={()=>setCart(cart.filter(x=>x.produto_id!==i.produto_id))} style={iconBtn}><X size={15}/></button></div>})}</div></div>
   <aside style={panel}><h2 style={h2}>Fechamento</h2><label style={lab}>Cliente<select value={clienteId} onChange={e=>setClienteId(e.target.value)} style={inp()}><option value="">Consumidor não identificado</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label style={{...lab,marginTop:10}}>Desconto<input type="number" min="0" step="0.01" value={desconto} onChange={e=>setDesconto(e.target.value)} style={inp()}/></label><div style={{margin:'20px 0',display:'grid',gap:8}}><div style={{display:'flex',justifyContent:'space-between'}}><span>Subtotal</span><b>{money(cartTotal)}</b></div><div style={{display:'flex',justifyContent:'space-between'}}><span>Desconto</span><b>- {money(n(desconto))}</b></div><div style={{display:'flex',justifyContent:'space-between',fontSize:24,paddingTop:10,borderTop:'1px solid #e2e8f0'}}><span>Total</span><b>{money(total)}</b></div></div><button onClick={()=>void finishSale()} disabled={busy||!cart.length} style={{...btn('primary'),width:'100%',justifyContent:'center'}}><Check size={17}/> Finalizar venda</button></aside>
  </section>}
  {tab==='vendas'&&<section style={{...panel,marginTop:18}}><h2 style={h2}>Histórico de vendas</h2>{sales.map(s=><div key={s.id} style={{display:'grid',gridTemplateColumns:'1fr 160px 120px 130px',gap:10,padding:'12px 0',borderBottom:'1px solid #e2e8f0'}}><span><b>{s.id.slice(0,8)}</b> • {clients.find(c=>c.id===s.cliente_id)?.nome||'Consumidor não identificado'}</span><span>{new Date(s.created_at).toLocaleString('pt-BR')}</span><span>{s.status}</span><b>{money(s.total)}</b></div>)}</section>}
  {showForm&&<div style={{position:'fixed',inset:0,background:'rgba(15,23,42,.55)',display:'grid',placeItems:'center',padding:20,zIndex:20}}><form onSubmit={saveProduct} style={{...panel,width:'min(760px,100%)',maxHeight:'90vh',overflow:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={h2}>{editing?'Editar produto':'Cadastrar produto'}</h2><button type="button" onClick={()=>setShowForm(false)} style={iconBtn}><X/></button></div><div style={{display:'grid',gridTemplateColumns:'1fr 2fr 120px 160px',gap:12}}>{field('Código','codigo','text')}{field('Nome','nome','text')}{field('Unidade','unidade','text')}{field('Tipo','tipo','text')}{field('Estoque mínimo','estoque_minimo','number')}{field('Estoque atual','estoque_atual','number',!!editing)}{field('Custo médio','custo_medio','number')}{field('Último custo','custo_ultimo','number')}{field('Custo fabricação','custo_fabricacao','number')}{field('Preço venda','preco_venda','number')}<label style={lab}>Status<select value={form.ativo?'true':'false'} onChange={e=>setForm({...form,ativo:e.target.value==='true'})} style={inp()}><option value="true">Ativo</option><option value="false">Inativo</option></select></label></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button type="button" onClick={()=>setShowForm(false)} style={btn('secondary')}>Cancelar</button><button disabled={busy} style={btn('primary')}><Check size={16}/> Salvar no banco</button></div></form></div>}
 </main>
 function field(label:keyof typeof form,_key:keyof typeof form,type='text',disabled=false){const key=_key;return <label style={lab}>{label}<input type={type} disabled={disabled} value={String(form[key])} onChange={e=>setForm({...form,[key]:e.target.value})} style={inp()} /></label>}
}
const panel:React.CSSProperties={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:20,boxShadow:'0 8px 28px rgba(15,23,42,.05)'}
const h2:React.CSSProperties={fontSize:20,margin:'0 0 14px'}
const th:React.CSSProperties={textAlign:'left',padding:12,borderBottom:'1px solid #e2e8f0',fontSize:12,color:'#64748b'}
const td:React.CSSProperties={padding:12,borderBottom:'1px solid #f1f5f9',fontSize:14}
const lab:React.CSSProperties={display:'grid',gap:6,fontSize:12,fontWeight:800,color:'#334155'}
const inp=(extra:React.CSSProperties={})=>({width:'100%',minHeight:42,border:'1px solid #cbd5e1',borderRadius:9,padding:'0 10px',fontSize:14,background:'#fff',...extra})
const iconBtn:React.CSSProperties={border:'1px solid #cbd5e1',background:'#fff',borderRadius:8,minWidth:34,height:34,display:'grid',placeItems:'center',cursor:'pointer'}
const btn=(kind:'primary'|'secondary'):React.CSSProperties=>({display:'inline-flex',alignItems:'center',gap:7,border:kind==='primary'?'0':'1px solid #cbd5e1',background:kind==='primary'?'#172033':'#fff',color:kind==='primary'?'#fff':'#172033',borderRadius:9,padding:'10px 14px',fontWeight:800,cursor:'pointer'})