import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft, BarChart3, ClipboardCheck, FileText, Gauge, RefreshCw, Ruler, Search, ShieldCheck, TriangleAlert, Plus, Save, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import QualidadeSGQAvancado from './QualidadeSGQAvancado'
type Tab='dashboard'|'inspecao'|'defeitos'|'rpnc'|'auditorias'|'documentos'|'calibracao'|'planos'|'avancado'
type Defect={id:string;ordem_producao_id:string;produto_id:string|null;defeito:string;quantidade:number;observacao:string|null;created_at:string}
type Inspection={id:string;tipo:string;resultado:string;quantidade_inspecionada:number|null;quantidade_aprovada:number|null;quantidade_reprovada:number|null;ordem_producao_id:string|null;observacao:string|null;created_at:string}
type Rpn={id:string;numero_rpnc:string|null;descricao_nao_conformidade:string|null;acao_corretiva:string|null;status:string|null}
type Audit={id:string;auditor:string|null;criterio:string|null;data_auditoria:string|null;resultado:string|null}
type Doc={id:string;codigo:string|null;titulo:string|null;area:string|null;status:string|null;revisao:number|null;proxima_revisao:string|null}
type Gauge={id:string;codigo:string;descricao:string;status:string|null;proxima_calibracao:string|null}
type Plan={id:string;codigo:string|null;caracteristica:string|null;unidade:string|null;frequencia:string|null;status:string|null}
export default function QualidadeIndustrial(){
 const[tab,setTab]=useState<Tab>('dashboard'),[showForm,setShowForm]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[defects,setDefects]=useState<Defect[]>([]),[inspections,setInspections]=useState<Inspection[]>([]),[rpnc,setRpnc]=useState<Rpn[]>([]),[audits,setAudits]=useState<Audit[]>([]),[docs,setDocs]=useState<Doc[]>([]),[gauges,setGauges]=useState<Gauge[]>([]),[plans,setPlans]=useState<Plan[]>([]),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);setError('');try{const[d,i,r,a,do_,g,p]=await Promise.all([supabase.from('erp_producao_defeitos').select('id,ordem_producao_id,produto_id,defeito,quantidade,observacao,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('erp_inspecoes').select('id,tipo,resultado,quantidade_inspecionada,quantidade_aprovada,quantidade_reprovada,ordem_producao_id,observacao,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('erp_rpnc').select('id,numero_rpnc,descricao_nao_conformidade,acao_corretiva,status').order('criado_em',{ascending:false}).limit(300),supabase.from('erp_auditorias').select('id,auditor,criterio,data_auditoria,resultado').order('data_auditoria',{ascending:false}).limit(200),supabase.from('erp_documentos_qualidade').select('id,codigo,titulo,area,status,revisao,proxima_revisao').order('updated_at',{ascending:false}).limit(300),supabase.from('erp_equipamentos_medicao').select('id,codigo,descricao,status,proxima_calibracao').order('codigo').limit(300),supabase.from('erp_planos_inspecao').select('id,codigo,caracteristica,unidade,frequencia,status').order('codigo').limit(300)]);for(const x of[d,i,r,a,do_,g,p])if(x.error)throw x.error;setDefects((d.data||[]) as Defect[]);setInspections((i.data||[]) as Inspection[]);setRpnc((r.data||[]) as Rpn[]);setAudits((a.data||[]) as Audit[]);setDocs((do_.data||[]) as Doc[]);setGauges((g.data||[]) as Gauge[]);setPlans((p.data||[]) as Plan[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar qualidade.')}finally{setBusy(false)}}
 useEffect(()=>{void load();const q=new URLSearchParams(location.search).get('tab') as Tab|null;const novo=new URLSearchParams(location.search).get('novo');if(q&&['dashboard','inspecao','defeitos','rpnc','auditorias','documentos','calibracao','planos','avancado'].includes(q))setTab(q);if(novo==='1'&&q&&['inspecao','rpnc','auditorias','calibracao','planos'].includes(q)){setShowForm(true);setForm({})}},[])
 const defectAgg=useMemo(()=>{const m=new Map<string,number>();for(const d of defects)m.set(d.defeito,(m.get(d.defeito)||0)+Number(d.quantidade||0));return [...m.entries()].sort((a,b)=>b[1]-a[1])},[defects])
 const metrics=useMemo(()=>({defects:defects.reduce((s,d)=>s+Number(d.quantidade||0),0),open:rpnc.filter(x=>!['encerrada','fechada','concluida'].includes(String(x.status||'').toLowerCase())).length,rejected:inspections.reduce((s,i)=>s+Number(i.quantidade_reprovada||0),0),cal:gauges.filter(g=>g.proxima_calibracao&&g.proxima_calibracao<=new Date(Date.now()+30*86400000).toISOString().slice(0,10)).length}),[defects,rpnc,inspections,gauges])
 const filter=(x:unknown)=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())
 const openNew=()=>{setForm(tab==='rpnc'?{numero_rpnc:'',descricao_nao_conformidade:'',acao_corretiva:'',status:'aberta'}:tab==='inspecao'?{tipo:'final',resultado:'pendente',quantidade_inspecionada:'',quantidade_aprovada:'',quantidade_reprovada:'',valor_medido:'',observacao:'',evidencias:''}:tab==='auditorias'?{auditor:'',criterio:'',data_auditoria:new Date().toISOString().slice(0,10),resultado:'pendente',evidencia:''}:tab==='calibracao'?{codigo:'',descricao:'',fabricante:'',modelo:'',faixa:'',resolucao:'',unidade:'',status:'ativo',proxima_calibracao:''}:{codigo:'',caracteristica:'',unidade:'',limite_inferior:'',limite_superior:'',frequencia:'',status:'ativo'});setShowForm(true);setError('');setMessage('')}
 const saveNew=async()=>{setBusy(true);setError('');try{const{data:empresa,error:ee}=await supabase.rpc('erp_current_empresa_id');if(ee||!empresa)throw ee??new Error('Empresa da sessão não identificada.');let table='';let payload:Record<string,unknown>={empresa_id:String(empresa)};if(tab==='rpnc'){table='erp_rpnc';payload={...payload,numero_rpnc:form.numero_rpnc||'RPNC-'+Date.now(),descricao_nao_conformidade:form.descricao_nao_conformidade,acao_corretiva:form.acao_corretiva||null,status:form.status||'aberta'}}else if(tab==='inspecao'){table='erp_inspecoes';payload={...payload,tipo:form.tipo||'final',resultado:form.resultado||'pendente',quantidade_inspecionada:form.quantidade_inspecionada?Number(form.quantidade_inspecionada):null,quantidade_aprovada:form.quantidade_aprovada?Number(form.quantidade_aprovada):null,quantidade_reprovada:form.quantidade_reprovada?Number(form.quantidade_reprovada):null,valor_medido:form.valor_medido?Number(form.valor_medido):null,observacao:form.observacao||null,evidencias:form.evidencias||null}}else if(tab==='auditorias'){table='erp_auditorias';payload={...payload,auditor:form.auditor||null,criterio:form.criterio||null,data_auditoria:form.data_auditoria||null,resultado:form.resultado||null,evidencia:form.evidencia||null}}else if(tab==='calibracao'){table='erp_equipamentos_medicao';payload={...payload,codigo:form.codigo,descricao:form.descricao,fabricante:form.fabricante||null,modelo:form.modelo||null,faixa:form.faixa||null,resolucao:form.resolucao||null,unidade:form.unidade||null,status:form.status||'ativo',proxima_calibracao:form.proxima_calibracao||null}}else{table='erp_planos_inspecao';payload={...payload,codigo:form.codigo,caracteristica:form.caracteristica,unidade:form.unidade||null,limite_inferior:form.limite_inferior?Number(form.limite_inferior):null,limite_superior:form.limite_superior?Number(form.limite_superior):null,frequencia:form.frequencia||null,status:form.status||'ativo'}}if(!String(payload.descricao_nao_conformidade??payload.codigo??payload.auditor??'').trim())throw new Error('Preencha os campos obrigatórios.');const{error}=await supabase.from(table).insert(payload);if(error)throw error;setMessage('Registro criado no banco real.');setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o registro.')}finally{setBusy(false)}}
 const createRpn=async(d:Defect)=>{setBusy(true);setError('');try{const{error}=await supabase.from('erp_rpnc').insert({numero_rpnc:'RPNC-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6),descricao_nao_conformidade:'Defeito '+d.defeito+' na OP '+d.ordem_producao_id+' — quantidade '+d.quantidade,acao_corretiva:'Analisar causa e contenção na Qualidade.',status:'aberta'});if(error)throw error;setMessage('RPNC criada a partir do defeito e enviada para análise.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar RPNC.')}finally{setBusy(false)}}
 return <main className="pcp-page" style={{padding:24,maxWidth:1750,margin:'0 auto'}}><header className="pcp-toolbar"><div><button className="secondary-v2" onClick={()=>location.href='/erp-industrial'}><ArrowLeft size={17}/> Voltar</button><span className="v2-eyebrow">SGQ • QUALIDADE</span><h1 style={{margin:'6px 0'}}>Tablet da Qualidade</h1><p style={{margin:0,color:'#64777d'}}>Inspeção, defeitos, RPNC, auditorias, documentos, calibração e planos — todos ligados aos registros reais do ERP.</p></div><button className="menu-green" onClick={()=>void load()} disabled={busy}><RefreshCw size={17}/> {busy?'Atualizando…':'Atualizar'}</button></header>{(message||error)&&<div className={error?'error':'notice'} style={{margin:'12px 0'}}>{error||message}</div>}<nav className="quality-tabs">{([['dashboard','Visão geral',BarChart3],['inspecao','Inspeção final',ClipboardCheck],['defeitos','Defeitos / Pareto',TriangleAlert],['rpnc','RPNC / CAPA',ShieldCheck],['auditorias','Auditorias',Search],['documentos','Documentos',FileText],['calibracao','Calibração',Ruler],['planos','Planos de inspeção',Gauge]] as const).map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={16}/>{label}</button>)}</nav><button className={tab==='avancado'?'quality-advanced-launch active':'quality-advanced-launch'} onClick={()=>setTab('avancado')}><ShieldCheck size={16}/> SGQ Avançado</button>{['inspecao','rpnc','auditorias','calibracao','planos'].includes(tab)&&<button className="menu-green" style={{margin:'12px 0'}} onClick={openNew}><Plus size={16}/> {tab==='rpnc'?'Novo RPNC':tab==='inspecao'?'Nova inspeção':tab==='auditorias'?'Nova auditoria':tab==='calibracao'?'Novo equipamento':'Novo plano de inspeção'}</button>}
 {tab==='avancado'&&<QualidadeSGQAvancado/>}{tab==='dashboard'&&<section><div className="quality-kpis"><article><TriangleAlert/><span>Defeitos registrados</span><strong>{metrics.defects}</strong></article><article><ClipboardCheck/><span>Reprovado em inspeções</span><strong>{metrics.rejected}</strong></article><article><ShieldCheck/><span>RPNC abertas</span><strong>{metrics.open}</strong></article><article><Ruler/><span>Calibração ≤ 30 dias</span><strong>{metrics.cal}</strong></article></div><div className="quality-dashboard-grid"><article className="erp-card" style={{padding:18}}><span className="v2-eyebrow">FLUXO</span><h2>Produção → Inspeção → Decisão</h2><p>O material conferido pelo Almoxarifado entra em inspeção. O que passa vai para estoque liberado; o defeito gera registro e pode abrir RPNC.</p></article><article className="erp-card" style={{padding:18}}><span className="v2-eyebrow">PARETO</span><h2>Principais defeitos</h2>{defectAgg.slice(0,6).map(([name,n])=><div key={name} style={{margin:'9px 0'}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{name}</b><span>{n}</span></div><div style={{height:8,background:'#e8efed',borderRadius:99}}><i style={{display:'block',height:'100%',width:Math.min(100,(n/(defectAgg[0]?.[1]||1))*100)+'%',background:'#0f766e',borderRadius:99}}/></div></div>)}</article></div></section>}
 {tab==='inspecao'&&<Table title="Inspeções finais" search={query} setSearch={setQuery} cols={['Tipo','Resultado','Inspecionada','Aprovada','Reprovada','OP','Observação']} rows={inspections.filter(filter).map(x=>[x.tipo,x.resultado,x.quantidade_inspecionada??0,x.quantidade_aprovada??0,x.quantidade_reprovada??0,x.ordem_producao_id||'—',x.observacao||'—'])}/>}
 {tab==='defeitos'&&<section><div className="quality-dashboard-grid"><article className="erp-card" style={{padding:18}}><span className="v2-eyebrow">ANÁLISE</span><h2>Defeitos por ocorrência</h2>{defectAgg.map(([name,n])=><div key={name} style={{padding:'11px 0',borderBottom:'1px solid #e4ebe8'}}><b>{name}</b><span style={{float:'right'}}>{n}</span></div>)}</article><article className="erp-card" style={{padding:18}}><span className="v2-eyebrow">REGISTROS</span><h2>Peças e OPs afetadas</h2><Table title="" search={query} setSearch={setQuery} cols={['Defeito','Qtd','OP','Produto']} rows={defects.filter(filter).slice(0,100).map(d=>[d.defeito,d.quantidade,d.ordem_producao_id,d.produto_id||'—'])}/></article></div><section className="crud-list" style={{marginTop:14}}><div className="crud-list-head"><div><strong>Enviar defeito para análise</strong><small>Cria RPNC sem apagar o evento original.</small></div></div><div className="crud-table-wrap"><table><thead><tr><th>Defeito</th><th>Qtd</th><th>OP</th><th>Ação</th></tr></thead><tbody>{defects.filter(filter).map(d=><tr key={d.id}><td>{d.defeito}</td><td>{d.quantidade}</td><td>{d.ordem_producao_id}</td><td><button className="secondary-v2" disabled={busy} onClick={()=>void createRpn(d)}>Criar RPNC</button></td></tr>)}</tbody></table></div></section></section>}
 {tab==='rpnc'&&<Table title="RPNC / CAPA" search={query} setSearch={setQuery} cols={['Número','Descrição','Ação','Status']} rows={rpnc.filter(filter).map(x=>[x.numero_rpnc||x.id,x.descricao_nao_conformidade||'—',x.acao_corretiva||'—',x.status||'—'])}/>}
 {tab==='auditorias'&&<Table title="Auditorias" search={query} setSearch={setQuery} cols={['Auditor','Critério','Data','Resultado']} rows={audits.filter(filter).map(x=>[x.auditor||'—',x.criterio||'—',x.data_auditoria||'—',x.resultado||'—'])}/>}
 {tab==='documentos'&&<Table title="Controle de documentos" search={query} setSearch={setQuery} cols={['Código','Título','Área','Status','Revisão','Próxima']} rows={docs.filter(filter).map(x=>[x.codigo||'—',x.titulo||'—',x.area||'—',x.status||'—',x.revisao??'—',x.proxima_revisao||'—'])}/>}
 {tab==='calibracao'&&<Table title="Equipamentos de medição" search={query} setSearch={setQuery} cols={['Código','Descrição','Status','Próxima calibração']} rows={gauges.filter(filter).map(x=>[x.codigo,x.descricao,x.status||'—',x.proxima_calibracao||'—'])}/>}
 {tab==='planos'&&<Table title="Planos de inspeção" search={query} setSearch={setQuery} cols={['Código','Característica','Unidade','Frequência','Status']} rows={plans.filter(filter).map(x=>[x.codigo||'—',x.caracteristica||'—',x.unidade||'—',x.frequencia||'—',x.status||'—'])}/>}
 {showForm&&<div className="industrial-modal-backdrop" role="presentation"><section className="industrial-modal" style={{maxWidth:900}} role="dialog" aria-modal="true"><header className="industrial-modal-head"><div><span className="industrial-eyebrow">SGQ • FORMULÁRIO</span><h2>{tab==='rpnc'?'RPNC / CAPA':tab==='inspecao'?'Inspeção final':tab==='auditorias'?'Auditoria':tab==='calibracao'?'Equipamento de medição':'Plano de inspeção'}</h2></div><button className="icon-button" onClick={()=>setShowForm(false)} aria-label="Fechar"><X size={20}/></button></header><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{Object.entries(form).map(([key,value])=><label key={key} style={{fontWeight:800,fontSize:11,color:'#475569'}}>{key.replaceAll('_',' ')}<input value={value} type={key.includes('data')||key.includes('calibracao')?'date':key.includes('quantidade')||key.includes('limite')||key.includes('valor')?'number':'text'} onChange={e=>setForm({...form,[key]:e.target.value})} style={{marginTop:5,width:'100%',boxSizing:'border-box',padding:10,border:'1px solid #cbd5e1',borderRadius:9}} /></label>)}</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button className="secondary-v2" onClick={()=>setShowForm(false)}>Cancelar</button><button className="menu-green" disabled={busy} onClick={()=>void saveNew()}><Save size={16}/> {busy?'Salvando…':'Salvar'}</button></div></section></div>} </main>
}
function Table({title,search,setSearch,cols,rows}:{title:string;search:string;setSearch:(v:string)=>void;cols:string[];rows:(string|number)[][]}){return <section className="crud-list"><div className="crud-list-head"><div><strong>{title}</strong><small>{rows.length} registro(s)</small></div><div className="module-search"><Search size={16}/><input placeholder="Pesquisar..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="crud-table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{String(v??'—')}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={cols.length} className="crud-empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div></section>}
