import { ChangeEvent,useState } from 'react'
import { ArrowLeft,FileUp,PackageCheck,Plus,Printer,RefreshCw,Trash2,XCircle } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
type Item={item_nfe:number;codigo_produto:string;descricao_produto:string;unidade:string;quantidade_total:number;valor_unitario:number;valor_total:number}
type Lote={id:string;item_nfe:number;lote_fabricante:string;lote_interno:string;data_validade:string;quantidade:number}
type Header={numero_nfe:string;serie:string;chave_acesso:string;data_emissao:string;cnpj_fornecedor:string;valor_total:string;xml_nome_arquivo:string}
const blankH=():Header=>({numero_nfe:'',serie:'',chave_acesso:'',data_emissao:new Date().toISOString().slice(0,10),cnpj_fornecedor:'',valor_total:'',xml_nome_arquivo:'manual'})
const blankI=(n:number):Item=>({item_nfe:n,codigo_produto:'',descricao_produto:'',unidade:'UN',quantidade_total:0,valor_unitario:0,valor_total:0})
const text=(root:Element,n:string)=>Array.from(root.getElementsByTagName('*')).find(e=>e.localName===n)?.textContent?.trim()||''
function parse(xml:string){const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))throw new Error('XML inválido.');const inf=Array.from(d.getElementsByTagName('*')).find(e=>e.localName==='infNFe');if(!inf)throw new Error('XML sem infNFe.');const ide=Array.from(inf.getElementsByTagName('*')).find(e=>e.localName==='ide')||inf;const emit=Array.from(inf.getElementsByTagName('*')).find(e=>e.localName==='emit')||inf;const tot=Array.from(inf.getElementsByTagName('*')).find(e=>e.localName==='ICMSTot')||inf;const ds=Array.from(inf.getElementsByTagName('*')).filter(e=>e.localName==='det');const h:Header={numero_nfe:text(ide,'nNF'),serie:text(ide,'serie'),chave_acesso:(inf.getAttribute('Id')||'').replace(/^NFe/,''),data_emissao:text(ide,'dhEmi')||text(ide,'dEmi'),cnpj_fornecedor:text(emit,'CNPJ'),valor_total:text(tot,'vNF'),xml_nome_arquivo:''};const items=ds.map((x,i)=>{const p=Array.from(x.getElementsByTagName('*')).find(e=>e.localName==='prod')||x;return{item_nfe:Number(x.getAttribute('nItem')||i+1),codigo_produto:text(p,'cProd'),descricao_produto:text(p,'xProd'),unidade:text(p,'uCom')||'UN',quantidade_total:Number(text(p,'qCom')||0),valor_unitario:Number(text(p,'vUnCom')||0),valor_total:Number(text(p,'vProd')||0)}});if(!items.length)throw new Error('NF-e sem itens.');return{h,items}}
export default function RecebimentoMateriais(){
 const[header,setHeader]=useState<Header>(blankH()),[items,setItems]=useState<Item[]>([blankI(1)]),[lotes,setLotes]=useState<Lote[]>([]),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[saving,setSaving]=useState(false)
 const setH=(k:keyof Header,v:string)=>setHeader(h=>({...h,[k]:v}))
 const setI=(i:number,k:keyof Item,v:string|number)=>setItems(xs=>xs.map((x,n)=>n===i?{...x,[k]:v}:x))
 const addItem=()=>setItems(xs=>[...xs,blankI(xs.length+1)])
 const addLote=(item:Item)=>setLotes(xs=>[...xs,{id:crypto.randomUUID(),item_nfe:item.item_nfe,lote_fabricante:'',lote_interno:'',data_validade:'',quantidade:Math.max(item.quantidade_total-xs.filter(l=>l.item_nfe===item.item_nfe).reduce((a,l)=>a+l.quantidade,0),0)}])
 const updLote=(id:string,k:keyof Lote,v:string|number)=>setLotes(xs=>xs.map(l=>l.id===id?{...l,[k]:v}:l))
 const load=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;f.text().then(t=>{const p=parse(t);p.h.xml_nome_arquivo=f.name;setHeader(p.h);setItems(p.items);setLotes(p.items.map(i=>({id:crypto.randomUUID(),item_nfe:i.item_nfe,lote_fabricante:'',lote_interno:'',data_validade:'',quantidade:i.quantidade_total})));setMsg('XML carregado. Confira os dados antes de confirmar.')}).catch(x=>setErr(x instanceof Error?x.message:'Falha ao ler XML.'));e.target.value=''}
 const reset=()=>{setHeader(blankH());setItems([blankI(1)]);setLotes([]);setMsg('');setErr('')}
 const ready=items.every(i=>i.codigo_produto&&i.descricao_produto&&i.quantidade_total>0&&lotes.some(l=>l.item_nfe===i.item_nfe)&&lotes.filter(l=>l.item_nfe===i.item_nfe).every(l=>l.lote_interno&&l.quantidade>0)&&Math.abs(lotes.filter(l=>l.item_nfe===i.item_nfe).reduce((a,l)=>a+l.quantidade,0)-i.quantidade_total)<.00001)
 const save=async()=>{if(!ready)return;setSaving(true);setErr('');try{const{data,error}=await supabase.rpc('erp_confirmar_recebimento_nfe',{p_header:header,p_items:items,p_lotes:lotes});if(error)throw error;setMsg(`Recebimento ${data||''} confirmado e enviado ao estoque.`)}catch(e){setErr(e instanceof Error?e.message:'Não foi possível confirmar o recebimento.')}finally{setSaving(false)}}
 return <div className="industrial-form-page receipt-workspace">
 <header className="industrial-page-head"><div><span className="industrial-eyebrow">ALMOXARIFADO • RECEBIMENTO</span><h1>Recebimento de materiais</h1><p>Entrada manual ou por XML da NF-e, com conferência de itens, lotes e rastreabilidade.</p></div><div className="receipt-actions"><button className="industrial-secondary" onClick={reset}><RefreshCw size={17}/> Novo</button><button className="industrial-secondary" onClick={()=>window.print()}><Printer size={17}/> Imprimir</button><a className="industrial-secondary" href="/erp-industrial"><ArrowLeft size={17}/> Voltar</a></div></header>
 <section className="industrial-panel"><div className="industrial-section-head"><div><h2>1. Dados da NF-e</h2><p>Todos os campos podem ser preenchidos manualmente. O XML é opcional.</p></div><label className="receipt-upload"><FileUp size={17}/> Importar XML<input hidden type="file" accept=".xml,text/xml,application/xml" onChange={load}/></label></div>
 <div className="receipt-form-grid">{[['numero_nfe','Número NF-e *','Ex.: 12345'],['serie','Série','1'],['data_emissao','Data de emissão',''],['cnpj_fornecedor','CNPJ fornecedor','00.000.000/0000-00'],['valor_total','Valor total','0,00'],['chave_acesso','Chave de acesso','44 dígitos']].map(([k,l,p])=><label key={k}>{l}<input type={k==='data_emissao'?'date':'text'} value={header[k as keyof Header]||''} placeholder={p} onChange={e=>setH(k as keyof Header,e.target.value)}/></label>)}</div></section>
 <section className="industrial-panel"><div className="industrial-section-head"><div><h2>2. Itens recebidos</h2><p>Informe o material, unidade e quantidade efetivamente recebida.</p></div><button className="industrial-primary" type="button" onClick={addItem}><Plus size={17}/> Adicionar item</button></div><div className="receipt-items">{items.map((i,n)=><article className="receipt-item" key={i.item_nfe}><b>Item {i.item_nfe}</b><label>Código *<input value={i.codigo_produto} onChange={e=>setI(n,'codigo_produto',e.target.value)}/></label><label className="wide">Descrição *<input value={i.descricao_produto} onChange={e=>setI(n,'descricao_produto',e.target.value)}/></label><label>Unidade<select value={i.unidade} onChange={e=>setI(n,'unidade',e.target.value)}><option>UN</option><option>KG</option><option>PC</option><option>M</option><option>L</option></select></label><label>Quantidade *<input type="number" min="0" step="0.0001" value={i.quantidade_total||''} onChange={e=>setI(n,'quantidade_total',Number(e.target.value))}/></label><label>Vlr. unitário<input type="number" min="0" step="0.0001" value={i.valor_unitario||''} onChange={e=>setI(n,'valor_unitario',Number(e.target.value))}/></label><button className="icon-button danger" type="button" onClick={()=>{if(items.length>1){setItems(xs=>xs.filter(x=>x.item_nfe!==i.item_nfe).map((x,j)=>({...x,item_nfe:j+1})));setLotes(xs=>xs.filter(x=>x.item_nfe!==i.item_nfe))}}}><Trash2 size={17}/></button></article>)}</div></section>
 <section className="industrial-panel"><div className="industrial-section-head"><div><h2>3. Lotes e rastreabilidade</h2><p>Distribua a quantidade recebida entre os lotes. A soma deve fechar exatamente.</p></div></div><div className="receipt-lots">{items.map(i=><div className="receipt-lot-block" key={i.item_nfe}><strong>Item {i.item_nfe} • {i.codigo_produto||'produto não informado'}</strong><button className="industrial-secondary" type="button" onClick={()=>addLote(i)}><Plus size={16}/> Adicionar lote</button>{lotes.filter(l=>l.item_nfe===i.item_nfe).map(l=><div className="receipt-lot-row" key={l.id}><input placeholder="Lote fabricante" value={l.lote_fabricante} onChange={e=>updLote(l.id,'lote_fabricante',e.target.value)}/><input placeholder="Lote interno *" value={l.lote_interno} onChange={e=>updLote(l.id,'lote_interno',e.target.value)}/><input type="date" value={l.data_validade} onChange={e=>updLote(l.id,'data_validade',e.target.value)}/><input type="number" min="0" step="0.0001" placeholder="Quantidade *" value={l.quantidade||''} onChange={e=>updLote(l.id,'quantidade',Number(e.target.value))}/><button className="icon-button danger" type="button" onClick={()=>setLotes(xs=>xs.filter(x=>x.id!==l.id))}><Trash2 size={16}/></button></div>)}</div>)}</div></section>
 <div className="receipt-result">{err&&<span className="error"><XCircle size={17}/>{err}</span>}{msg&&<span className="ok">{msg}</span>}<button className="industrial-primary" disabled={!ready||saving} onClick={save}><PackageCheck size={18}/>{saving?'Confirmando…':'Confirmar entrada no estoque'}</button></div>
 <style>{`.receipt-actions{display:flex;gap:8px;flex-wrap:wrap}.receipt-form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.receipt-upload{display:inline-flex;align-items:center;gap:7px;background:#2D8DB8;color:#fff;border-radius:10px;padding:10px 14px;font-weight:900;cursor:pointer}.receipt-items{display:grid;gap:10px}.receipt-item{display:grid;grid-template-columns:80px 1fr 2fr 110px 130px 130px 38px;gap:10px;align-items:end;padding:13px;border:1px solid #d9e6eb;border-radius:12px;background:#f8fcfd}.receipt-item .wide{min-width:0}.receipt-lots{display:grid;gap:14px}.receipt-lot-block{border:1px solid #d9e6eb;border-radius:12px;padding:14px;background:#f8fcfd}.receipt-lot-block>strong{display:inline-block;margin-right:12px}.receipt-lot-row{display:grid;grid-template-columns:1fr 1fr 170px 150px 38px;gap:8px;margin-top:10px}.receipt-result{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:16px;background:#123B50;border-radius:14px;color:#fff}.receipt-result span{display:flex;align-items:center;gap:7px}.receipt-result .error{color:#fecaca}.receipt-result .ok{color:#bbf7d0}@media(max-width:1000px){.receipt-form-grid{grid-template-columns:1fr 1fr}.receipt-item{grid-template-columns:70px 1fr 1fr}.receipt-item .wide{grid-column:span 2}.receipt-lot-row{grid-template-columns:1fr 1fr 1fr}}@media(max-width:650px){.receipt-form-grid{grid-template-columns:1fr}.receipt-item{grid-template-columns:1fr}.receipt-item .wide{grid-column:auto}.receipt-lot-row{grid-template-columns:1fr}.receipt-result{flex-direction:column;align-items:stretch}}`}</style></div>
