import { FormEvent, useEffect, useState } from 'react'
import { supabase, supabaseConfigurado } from '../lib/supabaseClient'

export default function RecuperarSenha(){
 const [email,setEmail]=useState(''),[senha,setSenha]=useState(''),[confirm,setConfirm]=useState(''),[recovery,setRecovery]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{let alive=true;const hash=new URLSearchParams(location.hash.replace(/^#/,'')).get('type');if(hash==='recovery')setRecovery(true);const {data}=supabase.auth.onAuthStateChange((event)=>{if(alive&&event==='PASSWORD_RECOVERY')setRecovery(true)});return()=>{alive=false;data.subscription.unsubscribe()}},[])
 async function request(e:FormEvent){e.preventDefault();setMsg('');if(!supabaseConfigurado)return setMsg('Supabase não está configurado.');if(!/^\S+@\S+\.\S+$/.test(email.trim()))return setMsg('Informe um e-mail válido.');setBusy(true);try{const {error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:'https://erp-sistema-industrial.vercel.app/recuperar-senha'});if(error)throw error;setMsg('Se o e-mail estiver cadastrado, o link de recuperação foi enviado.')}catch(err){setMsg(err instanceof Error?err.message:'Não foi possível solicitar a recuperação.')}finally{setBusy(false)}}
 async function update(e:FormEvent){e.preventDefault();setMsg('');if(senha.length<8)return setMsg('A nova senha precisa ter pelo menos 8 caracteres.');if(senha!==confirm)return setMsg('As senhas não conferem.');setBusy(true);try{const {error}=await supabase.auth.updateUser({password:senha});if(error)throw error;await supabase.auth.signOut();setRecovery(false);setSenha('');setConfirm('');setMsg('Senha alterada com sucesso. Volte ao login para entrar.')}catch(err){setMsg(err instanceof Error?err.message:'O link expirou ou não é mais válido.')}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'#071012',color:'#fff',fontFamily:'Inter,system-ui,sans-serif'}}><section style={{width:'min(100%,520px)',padding:32,borderRadius:24,border:'1px solid rgba(201,168,76,.3)',background:'#101719',boxShadow:'0 30px 80px rgba(0,0,0,.4)'}}><a href="/login" style={{color:'#d8bd71',fontSize:12,fontWeight:800,textDecoration:'none'}}>← Voltar ao login</a><h1 style={{fontSize:30,margin:'22px 0 8px'}}>Recuperar acesso</h1><p style={{color:'rgba(255,255,255,.65)',lineHeight:1.6,fontSize:14}}>{recovery?'Defina uma nova senha para sua conta SGQ ERP Industrial.':'Informe seu e-mail e enviaremos o link seguro de recuperação.'}</p>{msg&&<div style={{marginTop:18,padding:13,borderRadius:12,background:'rgba(15,118,110,.15)',color:'#bff0e8',fontSize:13,lineHeight:1.5}}>{msg}</div>}{recovery?<form onSubmit={update} style={{marginTop:22}}><label style={{display:'block',fontSize:12,fontWeight:900}}>Nova senha<input type="password" minLength={8} required value={senha} onChange={e=>setSenha(e.target.value)} style={{display:'block',width:'100%',marginTop:7,marginBottom:14,height:50,padding:'0 14px',borderRadius:11,border:'1px solid #344348',background:'#0a0d0f',color:'#fff'}}/></label><label style={{display:'block',fontSize:12,fontWeight:900}}>Confirmar senha<input type="password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)} style={{display:'block',width:'100%',marginTop:7,marginBottom:14,height:50,padding:'0 14px',borderRadius:11,border:'1px solid #344348',background:'#0a0d0f',color:'#fff'}}/></label><button disabled={busy} style={{width:'100%',height:50,border:0,borderRadius:11,background:'#c9a84c',fontWeight:900}}>{busy?'Alterando…':'Alterar senha'}</button></form>:<form onSubmit={request} style={{marginTop:22}}><label style={{display:'block',fontSize:12,fontWeight:900}}>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} style={{display:'block',width:'100%',marginTop:7,marginBottom:14,height:50,padding:'0 14px',borderRadius:11,border:'1px solid #344348',background:'#0a0d0f',color:'#fff'}}/></label><button disabled={busy} style={{width:'100%',height:50,border:0,borderRadius:11,background:'#c9a84c',fontWeight:900}}>{busy?'Enviando…':'Enviar link de recuperação'}</button></form>}</section></main>
}
