import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BarChart3, CalendarCheck2, CheckCircle2, GraduationCap, Plus, RefreshCw, Save, Users, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
type Tab='funcionarios'|'ponto'|'treinamentos'|'planos'|'avaliacoes'|'indicadores'
type Employee={id:string;matricula:string|null;nome:string;cpf:string|null;cargo:string|null;data_admissao:string|null;data_demissao:string|null;status:string;email:string|null;telefone:string|null}
type Training={id:string;titulo:string;instrutor:string|null;data:string|null;carga_horas:number|null;status:string}
type Plan={id:string;codigo:string;titulo:string;competencia:string|null;periodo:string|null;status:string}
type Point={id:string;funcionario_id:string;data:string;entrada:string|null;saida:string|null;observacao:string|null}
type Evaluation={id:string;funcionario_id:string;periodo_inicio:string;periodo_fim:string;nota:number|null;pontos_fortes:string|null;pontos_melhoria:string|null;plano_acao:string|null;status:string}
const today=()=>new Date().toISOString().slice(0,10)
export default function RHIndustrial(){
 const[tab,setTab]=useState<Tab>('funcionarios'),[employees,setEmployees]=useState<Employee[]>([]),[trainings,setTrainings]=useState<Training[]>([]),[plans,setPlans]=useState<Plan[]>([]),[points,setPoints]=useState<Point[]>([]),[evaluations,setEvaluations]=useState<Evaluation[]>([]),[show,setShow]=useState(false),[kind,setKind]=useState<'employee'|'training'|'plan'|'point'|'evaluation'|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[form,setForm]=useState<Record<string,string>>({})
 const company=async()=>{const{data,error}=await supabase.rpc('erp_current_empresa_id');if(error||!data)throw error??new Error('Empresa da sessão não identificada.');return String(data)}
 const load=async()=>{setBusy(true);setError('');try{const id=await company();const[e,t,p,pt,a]=await Promise.all([supabase.from('erp_funcionarios').select('id,matricula,nome,cpf,cargo,data_admissao,data_demissao,status,email,telefone').eq('empresa_id',id).order('nome').limit(1000),supabase.from('erp_treinamentos').select('id,titulo,instrutor,data,carga_horas,status').eq('empresa_id',id).order('data',{ascending:false}).limit(500),supabase.from('erp_planos_treinamento').select('id,codigo,titulo,competencia,periodo,status').eq('empresa_id',id).order('periodo',{ascending:false}).limit(500),supabase.from('erp_ponto_registros').select('id,funcionario_id,data,entrada,saida,observacao').eq('empresa_id',id).order('data',{ascending:false}).limit(2000),supabase.from('erp_avaliacoes_funcionarios').select('id,funcionario_id,periodo_inicio,periodo_fim,nota,pontos_fortes,pontos_melhoria,plano_acao,status').eq('empresa_id',id).order('created_at',{ascending:false}).limit(500)]);for(const x of[e,t,p,pt,a])if(x.error)throw x.error;setEmployees((e.data||[]) as Employee[]);setTrainings((t.data||[]) as Training[]);setPlans((p.data||[]) as Plan[]);setPoints((pt.data||[]) as Point[]);setEvaluations((a.data||[]) as Evaluation[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar RH.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 useEffect(()=>{const q=new URLSearchParams(location.search).get('tab');if(['ponto','treinamentos','planos','avaliacoes','indicadores'].includes(q||''))setTab(q as Tab)},[])
 const filtered=employees.filter(e=>{const q=query.trim().toLowerCase();return !q||[e.nome,e.matricula,e.cargo,e.cpf].join(' ').toLowerCase().includes(q)})
 const start=(k:NonNullable<typeof kind>)=>{setKind(k);setShow(true);setMessage('');setError('');setForm(k==='employee'?{matricula:'',nome:'',cpf:'',cargo:'',data_admissao:today(),email:'',telefone:'',status:'ativo'}:k==='training'?{titulo:'',instrutor:'',data:today(),carga_horas:'',status:'programado'}:k==='plan'?{codigo:'',titulo:'',competencia:'',periodo:today(),status:'aberto'}:k==='point'?{funcionario_id:employees[0]?.id||'',data:today(),entrada:'',saida:'',observacao:''}:{funcionario_id:employees[0]?.id||'',periodo_inicio:today(),periodo_fim:today(),nota:'',pontos_fortes:'',pontos_melhoria:'',plano_acao:'',status:'aberta'})}
 const save=async()=>{if(!kind)return;setBusy(true);setError('');try{const empresa_id=await company();let table='';let payload:Record<string,unknown>={empresa_id};if(kind==='employee'){table='erp_funcionarios';payload={...payload,matricula:form.matricula||null,nome:form.nome.trim(),cpf:form.cpf||null,cargo:form.cargo||null,data_admissao:form.data_admissao||null,email:form.email||null,telefone:form.telefone||null,status:form.status||'ativo'}}else if(kind==='training'){table='erp_treinamentos';payload={...payload,titulo:form.titulo.trim(),instrutor:form.instrutor||null,data:form.data||null,carga_horas:form.carga_horas?Number(form.carga_horas):null,status:form.status||'programado'}}else if(kind==='plan'){table='erp_planos_treinamento';payload={...payload,codigo:form.codigo.trim(),titulo:form.titulo.trim(),competencia:form.competencia||null,periodo:form.periodo||null,status:form.status||'aberto'}}else if(kind==='point'){table='erp_ponto_registros';payload={...payload,funcionario_id:form.funcionario_id,data:form.data,entrada:form.entrada?new Date(form.data+'T'+form.entrada).toISOString():null,saida:form.saida?new Date(form.data+'T'+form.saida).toISOString():null,observacao:form.observacao||null}}else{table='erp_avaliacoes_funcionarios';payload={...payload,funcionario_id:form.funcionario_id,periodo_inicio:form.periodo_inicio,periodo_fim:form.periodo_fim,nota:form.nota?Number(form.nota):null,pontos_fortes:form.pontos_fortes||null,pontos_melhoria:form.pontos_melhoria||null,plano_acao:form.plano_acao||null,status:form.status||'aberta'}}if(!String(payload.nome??payload.titulo??payload.codigo??'').trim()&&['employee','training','plan'].includes(kind))throw new Error('Preencha os campos obrigatórios.');const{error}=await supabase.from(table).insert(payload);if(error)throw error;setMessage('Registro salvo no banco real.');setShow(false);setKind(null);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}
 const empName=(id:string)=>employees.find(e=>e.id===id)?.nome||id
 const attendance=useMemo(()=>{const by=new Map<string,{presentes:number;faltas:number}>();for(const p of points){const k=p.data.slice(0,7);const v=by.get(k)||{presentes:0,faltas:0};if(p.entrada)v.presentes++;else v.faltas++;by.set(k,v)}return [...by.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-12)},[points])
 const tabs:[Tab,string,typeof Users][]=[['funcionarios','Funcionários',Users],['ponto','Ponto / Presença',CalendarCheck2],['treinamentos','Treinamentos',GraduationCap],['planos','Cronograma',CalendarCheck2],['avaliacoes','Avaliações',BarChart3],['indicadores','Gráficos RH',BarChart3]]
 return <main className="pcp-page" style={{padding:24,maxWidth:1700,margin:'0 auto'}}><header className="pcp-toolbar"><div><button className="secondary-v2" onClick={()=>location.href='/erp-industrial'}><ArrowLeft size={17}/> Voltar</button><span className="v2-eyebrow">SGQ • RH</span><h1 style={{margin:'6px 0'}}>Central de Recursos Humanos</h1><p style={{margin:0,color:'#64777d'}}>Funcionários, ponto, treinamentos, cronograma, avaliações e indicadores calculados do banco.</p></div><button className="menu-green" onClick={()=>void load()} disabled={busy}><RefreshCw size={17}/> {busy?'Atualizando…':'Atualizar'}</button></header>{(message||error)&&<div className={error?'error':'notice'} style={{margin:'12px 0'}}>{error||message}</div>}<nav className="quality-tabs">{tabs.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={16}/>{label}</button>)}</nav>
 {tab==='funcionarios'&&<section><div className="quality-kpis"><article><Users/><span>Funcionários</span><strong>{employees.length}</strong></article><article><CheckCircle2/><span>Ativos</span><strong>{employees.filter(e=>e.status==='ativo').length}</strong></article><article><GraduationCap/><span>Treinamentos</span><strong>{trainings.length}</strong></article><article><CalendarCheck2/><span>Registros de ponto</span><strong>{points.length}</strong></article></div><section className="crud-list"><div className="crud-list-head"><div><strong>Cadastro de funcionários</strong><small>Inativos permanecem no histórico.</small></div><div style={{display:'flex',gap:8}}><input placeholder="Pesquisar..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="menu-green" onClick={()=>start('employee')}><Plus size={16}/> Novo funcionário</button></div></div><div className="crud-table-wrap"><table><thead><tr><th>Matrícula</th><th>Nome</th><th>Cargo</th><th>Admissão</th><th>Status</th><th>Contato</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td>{e.matricula||'—'}</td><td>{e.nome}</td><td>{e.cargo||'—'}</td><td>{e.data_admissao||'—'}</td><td>{e.status}</td><td>{e.email||e.telefone||'—'}</td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="crud-empty">Nenhum funcionário encontrado.</td></tr>}</tbody></table></div></section></section>}
 {tab==='ponto'&&<section><div className="quality-kpis"><article><span>Registros</span><strong>{points.length}</strong></article><article><span>Com entrada</span><strong>{points.filter(p=>p.entrada).length}</strong></article><article><span>Sem entrada</span><strong>{points.filter(p=>!p.entrada).length}</strong></article><article><span>Funcionários</span><strong>{employees.length}</strong></article></div><section className="crud-list"><div className="crud-list-head"><strong>Controle de ponto</strong><button className="menu-green" onClick={()=>start('point')}><Plus size={16}/> Lançar ponto</button></div><div className="crud-table-wrap"><table><thead><tr><th>Data</th><th>Funcionário</th><th>Entrada</th><th>Saída</th><th>Observação</th></tr></thead><tbody>{points.slice(0,300).map(p=><tr key={p.id}><td>{p.data}</td><td>{empName(p.funcionario_id)}</td><td>{p.entrada?new Date(p.entrada).toLocaleTimeString('pt-BR'):'FALTA / SEM ENTRADA'}</td><td>{p.saida?new Date(p.saida).toLocaleTimeString('pt-BR'):'—'}</td><td>{p.observacao||'—'}</td></tr>)}</tbody></table></div></section></section>}
 {tab==='treinamentos'&&<section className="crud-list"><div className="crud-list-head"><strong>Treinamentos</strong><button className="menu-green" onClick={()=>start('training')}><Plus size={16}/> Novo treinamento</button></div><div className="crud-table-wrap"><table><thead><tr><th>Título</th><th>Instrutor</th><th>Data</th><th>Carga</th><th>Status</th></tr></thead><tbody>{trainings.map(t=><tr key={t.id}><td>{t.titulo}</td><td>{t.instrutor||'—'}</td><td>{t.data||'—'}</td><td>{t.carga_horas??'—'} h</td><td>{t.status}</td></tr>)}</tbody></table></div></section>}
 {tab==='planos'&&<section className="crud-list"><div className="crud-list-head"><strong>Cronograma de Treinamento</strong><button className="menu-green" onClick={()=>start('plan')}><Plus size={16}/> Novo plano</button></div><div className="crud-table-wrap"><table><thead><tr><th>Código</th><th>Título</th><th>Competência</th><th>Período</th><th>Status</th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td>{p.codigo}</td><td>{p.titulo}</td><td>{p.competencia||'—'}</td><td>{p.periodo||'—'}</td><td>{p.status}</td></tr>)}</tbody></table></div></section>}
 {tab==='avaliacoes'&&<section className="crud-list"><div className="crud-list-head"><strong>Avaliação de Funcionários</strong><button className="menu-green" onClick={()=>start('evaluation')}><Plus size={16}/> Nova avaliação</button></div><div className="crud-table-wrap"><table><thead><tr><th>Funcionário</th><th>Período</th><th>Nota</th><th>Status</th></tr></thead><tbody>{evaluations.map(a=><tr key={a.id}><td>{empName(a.funcionario_id)}</td><td>{a.periodo_inicio} → {a.periodo_fim}</td><td>{a.nota??'—'}</td><td>{a.status}</td></tr>)}</tbody></table></div></section>}
 {tab==='indicadores'&&<section><div className="quality-kpis"><article><span>Presença</span><strong>{points.filter(p=>p.entrada).length}</strong></article><article><span>Sem entrada</span><strong>{points.filter(p=>!p.entrada).length}</strong></article><article><span>Treinamentos</span><strong>{trainings.length}</strong></article><article><span>Avaliações</span><strong>{evaluations.length}</strong></article></div><section className="erp-card" style={{padding:18}}><h2>Gráfico de faltas e presenças</h2><div style={{display:'flex',alignItems:'flex-end',gap:12,height:220,overflowX:'auto',padding:'20px 0'}}>{attendance.map(([month,v])=>{const ph=Math.max(4,Math.min(160,v.presentes*10));const fh=Math.max(4,Math.min(160,v.faltas*10));return <div key={month} style={{minWidth:72,textAlign:'center'}}><div style={{display:'flex',alignItems:'flex-end',justifyContent:'center',gap:4,height:170}}><span title={'Presenças: '+v.presentes} style={{display:'block',width:22,height:ph,background:'#0f766e',borderRadius:'5px 5px 0 0'}}/><span title={'Faltas: '+v.faltas} style={{display:'block',width:22,height:fh,background:'#f97316',borderRadius:'5px 5px 0 0'}}/></div><small>{month}</small></div>})}</div></section></section>}
 {show&&kind&&<div className="industrial-modal-backdrop" role="presentation"><section className="industrial-modal" style={{maxWidth:900}} role="dialog"><header className="industrial-modal-head"><div><span className="industrial-eyebrow">RH • FORMULÁRIO</span><h2>{kind==='employee'?'Cadastro de Funcionário':kind==='training'?'Cadastro de Treinamento':kind==='plan'?'Plano / Cronograma':kind==='point'?'Lançamento de Ponto':'Avaliação de Funcionário'}</h2></div><button className="icon-button" onClick={()=>setShow(false)}><X size={20}/></button></header><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{Object.entries(form).map(([key,value])=><label key={key} style={{fontWeight:800,fontSize:11,color:'#475569'}}>{key.replaceAll('_',' ')}<input type={key.includes('data')||key.includes('periodo')?'date':key.includes('carga')||key==='nota'?'number':'text'} value={value} onChange={e=>setForm({...form,[key]:e.target.value})} style={{marginTop:5,width:'100%',boxSizing:'border-box',padding:10,border:'1px solid #cbd5e1',borderRadius:9}}/></label>)}</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button className="secondary-v2" onClick={()=>setShow(false)}>Cancelar</button><button className="menu-green" disabled={busy} onClick={()=>void save()}><Save size={16}/>{busy?'Salvando…':'Salvar'}</button></div></section></div>}
 </main>
}