/* REVISÃO DE ENGENHARIA | Projeto: SGQ ERP Industrial | Pasta: src/pages/ | Arquivo: SetupADMInicial.tsx | Data: 2026-09-17 | Correções: tela única de provisionamento do Master nível 9 e Demo proprietário nível 8; bloqueio após conclusão | Segurança: senhas somente no formulário e enviadas à Edge Function; service_role nunca chega ao frontend; e-mails oficiais validados no servidor | Testes/Homologação: revisão estática; build/Vercel pendente | Status: REVISADO — NÃO HOMOLOGADO */

import { FormEvent, useEffect, useState, type CSSProperties } from 'react';
import { supabase, supabaseConfigurado } from '../lib/supabaseClient';

const MASTER_EMAIL='fernandosch2012@hotmail.com';
const DEMO_EMAIL='demo.industrial@plushbeauty.com';

export default function SetupADMInicial(){
  const [locked,setLocked]=useState<boolean|null>(null),[masterPassword,setMasterPassword]=useState(''),[demoPassword,setDemoPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function check(){if(!supabaseConfigurado){setLocked(false);setError('Supabase não está configurado neste ambiente.');return}try{const {data,error}=await supabase.functions.invoke('erp-login',{body:{action:'setup_status'}});if(error)throw error;setLocked(Boolean(data?.locked))}catch(e){setError(e instanceof Error?e.message:'Não foi possível verificar o setup inicial.');setLocked(false)}}
  useEffect(()=>{void check()},[]);
  async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if(masterPassword.length<8||demoPassword.length<8){setError('As duas senhas precisam ter pelo menos 8 caracteres.');return}setBusy(true);try{const {data,error}=await supabase.functions.invoke('erp-login',{body:{action:'setup_initial',master:{email:MASTER_EMAIL,password:masterPassword},demo:{email:DEMO_EMAIL,password:demoPassword}}});if(error)throw error;if(!data?.ok)throw new Error(String(data?.error??'Não foi possível concluir o cadastro inicial.'));setMasterPassword('');setDemoPassword('');setLocked(true);setMessage('Cadastro inicial concluído. A configuração foi bloqueada. Agora use somente o login normal.')}catch(e){setError(e instanceof Error?e.message:'Falha ao provisionar os usuários oficiais.')}finally{setBusy(false)}}
  if(locked===null)return <main style={shell}><section style={card}><span style={eyebrow}>SGQ ERP INDUSTRIAL • CONFIGURAÇÃO INICIAL</span><h1>Verificando o cadastro ADM Master…</h1></section></main>;
  if(locked)return <main style={shell}><section style={card}><span style={eyebrow}>CONFIGURAÇÃO CONCLUÍDA</span><h1>ADM Master já cadastrado</h1><p style={text}>Esta tela é de uso único e foi bloqueada após o provisionamento oficial.</p><a href="/login" style={button}>Ir para o login</a></section></main>;
  return <main style={shell}><section style={card}><span style={eyebrow}>SGQ ERP INDUSTRIAL • CONFIGURAÇÃO INICIAL</span><h1>Cadastro do ADM Master</h1><p style={text}>Cadastre uma vez o Master nível 9 e o Demo proprietário nível 8. As senhas não ficam gravadas no código.</p><form onSubmit={submit}><label style={label}>Master nível 9</label><input value={MASTER_EMAIL} readOnly style={input}/><input type="password" required minLength={8} value={masterPassword} onChange={e=>setMasterPassword(e.target.value)} placeholder="Defina a senha do Master" style={input}/><label style={label}>Demo proprietário nível 8</label><input value={DEMO_EMAIL} readOnly style={input}/><input type="password" required minLength={8} value={demoPassword} onChange={e=>setDemoPassword(e.target.value)} placeholder="Defina a senha do Demo" style={input}/>{error&&<div style={errorBox}>{error}</div>}{message&&<div style={okBox}>{message}</div>}<button disabled={busy} type="submit" style={button}>{busy?'Cadastrando…':'Cadastrar ADM Master + Demo'}</button></form><a href="/login" style={back}>Voltar ao login</a></section></main>
}
const shell:CSSProperties={minHeight:'100vh',display:'grid',placeItems:'center',background:'radial-gradient(circle at top,#173f48,#070b0d 62%)',padding:24,color:'#fff'};
const card:CSSProperties={width:'min(100%,620px)',background:'#101619',border:'1px solid rgba(201,168,76,.28)',borderRadius:24,padding:32,boxShadow:'0 30px 90px rgba(0,0,0,.4)'};
const eyebrow:CSSProperties={fontSize:11,fontWeight:900,letterSpacing:'.18em',color:'#e0c56f'}; const text:CSSProperties={color:'rgba(255,255,255,.68)',lineHeight:1.7,fontSize:14}; const label:CSSProperties={display:'block',margin:'18px 0 7px',fontSize:12,fontWeight:900}; const input:CSSProperties={display:'block',width:'100%',height:48,marginBottom:10,padding:'0 14px',borderRadius:10,border:'1px solid rgba(255,255,255,.14)',background:'#0a0d0f',color:'#fff',fontSize:14}; const button:CSSProperties={display:'inline-flex',alignItems:'center',justifyContent:'center',width:'100%',minHeight:50,marginTop:16,border:0,borderRadius:10,background:'#c9a84c',color:'#0b0d0e',fontWeight:900,textDecoration:'none',cursor:'pointer'}; const back:CSSProperties={display:'block',marginTop:18,textAlign:'center',color:'#e0c56f',fontSize:12,textDecoration:'none'}; const errorBox:CSSProperties={marginTop:12,padding:12,borderRadius:10,background:'rgba(150,25,25,.2)',border:'1px solid rgba(255,100,100,.3)',color:'#ffb6b6',fontSize:12}; const okBox:CSSProperties={marginTop:12,padding:12,borderRadius:10,background:'rgba(40,130,90,.2)',border:'1px solid rgba(100,220,160,.3)',color:'#baf1d0',fontSize:12};
