import { useEffect,useMemo,useState } from 'react'
import { ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import VendasLayout from './VendasLayout'
type P={id:string;codigo:string;nome:string;grupo:string|null;preco_venda:number|null}
export default function TabelaPrecos(){
 const [ps,setPs]=useState<P[]>([]),[grupo,setGrupo]=useState(''),[tipo,setTipo]=useState(''),[pct,setPct]=useState('5'),[tipoReajuste,setTipoReajuste]=useState<'vendas'|'postos'>('vendas'),[msg,setMsg]=useState(''),[error,setError]=useState('')
 const load=async()=>{const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.');const r=await supabase.from('erp_produtos').select('id,codigo,nome,grupo,preco_venda').eq('empresa_id',String(e.data)).eq('ativo',true).order('codigo').limit(5000);if(r.error)throw r.error;setPs((r.data??[]) as P[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar.'))},[])
 const preview=useMemo(()=>{const p=Number(pct);return new Map(ps.map(x=>{const base=Number(x.preco_venda);return [x.id,Number.isFinite(base)&&base>0&&Number.isFinite(p)?base*(1+p/100):null] as const}))},[ps,pct])
 const execute=async()=>{setError('');setMsg('');const v=Number(pct);if(!Number.isFinite(v)||v<=-100){setError('Percentual inválido.');return}const r=tipoReajuste==='vendas'?await supabase.rpc('erp_reajuste_global_vendas',{p_percentual:v,p_grupo:grupo||null,p_tipo_cliente:tipo||null}):await supabase.rpc('erp_reajuste_global_postos_trabalho',{p_percentual:v});if(r.error){setError(r.error.message);return}setMsg(`Reajuste aplicado em ${Number(r.data??0)} registro(s).`);await load()}
 return <VendasLayout title="Tabela de Preços / Reajuste" subtitle="Área administrativa" onRefresh={()=>void load()}><div className="space-y-2 text-[11px]"><section className="border border-slate-300 bg-white p-2"><div className="flex items-center gap-2"><ShieldCheck size={15}/><b>AJUSTE GLOBAL CONTROLADO POR PERMISSÃO</b></div><div className="mt-2 grid grid-cols-12 gap-2"><label className="col-span-2 font-normal">Tipo<select className="mt-1 h-7 w-full border px-1" value={tipoReajuste} onChange={e=>setTipoReajuste(e.target.value as 'vendas'|'postos')}><option value="vendas">Preço de venda comercial</option><option value="postos">Custo hora-máquina</option></select></label><label className="col-span-2 font-normal">Percentual %<input className="mt-0.5 h-7 w-[80px] border px-1 text-[11px]" type="number" step="0.01" value={pct} onChange={e=>setPct(e.target.value)}/></label><label className="col-span-3 font-normal">Grupo produto<input className="mt-0.5 h-7 w-[160px] border px-1 text-[11px]" value={grupo} onChange={e=>setGrupo(e.target.value)}/></label><label className="col-span-3 font-normal">Perfil cliente<input className="mt-0.5 h-7 w-[160px] border px-1 text-[11px]" value={tipo} onChange={e=>setTipo(e.target.value)}/></label><button type="button" onClick={()=>void execute()} className="h-7 w-[130px] self-end whitespace-nowrap rounded border border-gray-200 bg-[#3A9D78] px-2 text-[11px] font-normal leading-none text-white">APLICAR</button></div>{error&&<div className="mt-2 border border-red-200 bg-red-50 p-2 text-red-800">{error}</div>}{msg&&<div className="mt-2 border border-emerald-200 bg-emerald-50 p-2 text-emerald-800">{msg}</div>}</section><section className="overflow-x-auto border border-slate-300 bg-white"><table className="w-full border-collapse text-[10px] leading-none"><thead><tr className="bg-[#DEE2E6] text-left text-[9px] uppercase"><th className="p-1.5">SKU</th><th>Produto</th><th>Grupo</th><th>Preço Atual</th><th>PREÇO VENDA • SIMULAÇÃO</th></tr></thead><tbody>{ps.slice(0,300).map(p=><tr key={p.id} className="h-7 border-t"><td className="px-1.5 py-0">{p.codigo}</td><td>{p.nome}</td><td>{p.grupo??'—'}</td><td>{brl(Number(p.preco_venda??0))}</td><td className="font-semibold text-[#17445A]">{preview.get(p.id)!=null?brl(preview.get(p.id) as number):'—'}</td></tr>)}</tbody></table></section></div></VendasLayout>
}
function brl(v:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(v)?v:0)}
