/*
📝 IDENTIFICAÇÃO DE LEITURA E REVISÃO DE CÓDIGO:
- Arquivo: src/pages/TabelaPrecos.tsx
- Status Atual: Revisão 3 (Tabelas Comerciais)
- Total de Linhas Gerado: 26
- Assinatura de Entrada (Primeiros 3 Imports): import { FormEvent, useEffect, useState } from 'react' | import { Check, Pencil, Plus, Search, Trash2, X } from 'lucide-react' | import { supabase } from '../lib/supabaseClient'
- Regra de Negócio Incorporada: Tabela de preços por segmento de cliente e preço específico por produto, com vínculo posterior ao cliente.
*/
import { FormEvent, useEffect, useState } from 'react'
import { Check, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Table={id:string;codigo:string;nome:string;descricao:string|null;ativo:boolean}
type Product={id:string;codigo:string;nome:string;preco_venda:number|null}
type Item={id:string;tabela_preco_id:string;produto_id:string;preco:number}
const input:React.CSSProperties={width:'100%',minHeight:42,border:'1px solid #cbd5e1',borderRadius:10,padding:'0 11px',boxSizing:'border-box',background:'#fff',color:'#111827'}
export default function TabelaPrecos(){
 const [tables,setTables]=useState<Table[]>([]),[products,setProducts]=useState<Product[]>([]),[items,setItems]=useState<Item[]>([]),[tableId,setTableId]=useState(''),[form,setForm]=useState({codigo:'',nome:'',descricao:''}),[productId,setProductId]=useState(''),[price,setPrice]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState<string|null>(null)
 const load=async()=>{setBusy(true);setError('');try{const {data:empresa,error:ee}=await supabase.rpc('erp_current_empresa_id');if(ee||!empresa)throw ee??new Error('Empresa não identificada.');const id=String(empresa);const [t,p]=await Promise.all([supabase.from('erp_tabelas_preco').select('*').eq('empresa_id',id).order('nome'),supabase.from('erp_produtos').select('id,codigo,nome,preco_venda').eq('empresa_id',id).eq('ativo',true).order('codigo').limit(2000)]);if(t.error)throw t.error;if(p.error)throw p.error;setTables((t.data??[]) as Table[]);setProducts((p.data??[]) as Product[]);if(!tableId&&t.data?.[0])setTableId(t.data[0].id)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar tabelas de preço.')}finally{setBusy(false)}}
 const loadItems=async(id:string)=>{if(!id){setItems([]);return}const {data,error:e}=await supabase.from('erp_tabelas_preco_itens').select('id,tabela_preco_id,produto_id,preco').eq('tabela_preco_id',id).order('created_at');if(e)setError(e.message);else setItems((data??[]) as Item[])}
 useEffect(()=>{void load()},[])
 useEffect(()=>{void loadItems(tableId)},[tableId])
 const saveTable=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data:empresa,error:ee}=await supabase.rpc('erp_current_empresa_id');if(ee||!empresa)throw ee??new Error('Empresa não identificada.');const payload={empresa_id:String(empresa),codigo:form.codigo.trim(),nome:form.nome.trim(),descricao:form.descricao.trim()||null,ativo:true};if(!payload.codigo||!payload.nome)throw new Error('Código e nome da tabela são obrigatórios.');const r=editing?await supabase.from('erp_tabelas_preco').update(payload).eq('id',editing):await supabase.from('erp_tabelas_preco').insert(payload).select('id').single();if(r.error)throw r.error;if(!editing&&r.data)setTableId(r.data.id);setEditing(null);setForm({codigo:'',nome:'',descricao:''});setMessage('Tabela de preço gravada.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a tabela.')}finally{setBusy(false)}}
 const addItem=async()=>{const p=products.find(x=>x.id===productId);const v=Number(price);if(!tableId||!p)return setError('Selecione uma tabela e um produto.');if(!Number.isFinite(v)||v<0)return setError('Informe um preço válido.');setBusy(true);setError('');try{const {data:empresa,error:ee}=await supabase.rpc('erp_current_empresa_id');if(ee||!empresa)throw ee??new Error('Empresa não identificada.');const r=await supabase.from('erp_tabelas_preco_itens').upsert({empresa_id:String(empresa),tabela_preco_id:tableId,produto_id:p.id,preco:v},{onConflict:'tabela_preco_id,produto_id'});if(r.error)throw r.error;setProductId('');setPrice('');setMessage('Preço específico gravado para a tabela.');await loadItems(tableId)}catch(e){setError(e instanceof Error?e.message:'Não foi possível gravar o preço.')}finally{setBusy(false)}}
 const remove=async(id:string)=>{setBusy(true);try{const r=await supabase.from('erp_tabelas_preco_itens').delete().eq('id',id);if(r.error)throw r.error;await loadItems(tableId)}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover o preço.')}finally{setBusy(false)}}
 return (
  <main style={{minHeight:'100vh',background:'#FAFAFA',color:'#111827',padding:24,boxSizing:'border-box'}}>
    <div style={{maxWidth:1400,margin:'0 auto'}}><header style={{marginBottom:20}}><span style={{fontSize:12,fontWeight:900,color:'#64748b'}}>VENDAS • FORMAÇÃO DE PREÇOS</span><h1>Tabelas de preços</h1><p style={{color:'#475569'}}>Preços específicos por produto e tabela comercial.</p></header>
      <div style={{display:'grid',gridTemplateColumns:'340px 1fr',gap:18}}>
        <section style={{background:'#fff',padding:20,borderRadius:18}}><h2>Nova tabela</h2><form onSubmit={saveTable} style={{display:'grid',gap:10}}><input placeholder="Código" style={input} value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/><input placeholder="Nome" style={input} value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><textarea placeholder="Descrição" style={{...input,paddingTop:10}} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/><button disabled={busy} style={{background:'#172033',color:'#fff',padding:10}}><Check size={16}/> {editing?'Atualizar':'Criar tabela'}</button></form><div style={{marginTop:18}}>{tables.map(t=><button key={t.id} onClick={()=>setTableId(t.id)} style={{display:'block',width:'100%',textAlign:'left',padding:12,marginBottom:8}}><b>{t.codigo}</b><span style={{display:'block'}}>{t.nome}</span></button>)}</div></section>
        <section style={{background:'#fff',padding:20,borderRadius:18}}><h2>{tables.find(t=>t.id===tableId)?.nome||'Selecione uma tabela'}</h2><div style={{display:'grid',gridTemplateColumns:'1fr 160px auto',gap:10}}><label>Produto<select style={input} value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.codigo} • {p.nome}</option>)}</select></label><label>Preço<input type="number" min="0" step="0.0001" style={input} value={price} onChange={e=>setPrice(e.target.value)}/></label><button onClick={()=>void addItem()} disabled={busy||!tableId} style={{background:'#172033',color:'#fff',padding:'11px 14px'}}><Plus size={16}/> Gravar preço</button></div>{(message||error)&&<p style={{color:error?'#b91c1c':'#047857'}}>{error||message}</p>}<table style={{width:'100%',borderCollapse:'collapse',marginTop:18}}><thead><tr>{['Produto','Preço tabela','Preço base','Diferença','Ação'].map(h=><th key={h} style={{textAlign:'left',padding:11}}>{h}</th>)}</tr></thead><tbody>{items.map(i=>{const p=products.find(x=>x.id===i.produto_id);const base=Number(p?.preco_venda||0);const diff=base?((i.preco-base)/base)*100:0;return <tr key={i.id}><td style={{padding:11}}>{p?.codigo} • {p?.nome}</td><td style={{padding:11}}><b>R$ {Number(i.preco).toFixed(4)}</b></td><td style={{padding:11}}>R$ {base.toFixed(4)}</td><td style={{padding:11}}>{diff.toFixed(2)}%</td><td style={{padding:11}}><button onClick={()=>void remove(i.id)}><Trash2 size={16}/></button></td></tr>})}</tbody></table></section>
      </div>
    </div>
  </main>
)
}
/* Revisão 3 registrada após validação estrutural do arquivo. */