import { useEffect, useState } from 'react'
import { BarChart3, Boxes, ClipboardCheck, LogOut, ShoppingCart, Wrench } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Metric = { value: string; label: string }
type Profile = { nome: string | null; perfil: string | null }
async function count(table:string):Promise<number|null>{const {count,error}=await supabase.from(table).select('id',{count:'exact',head:true});return error?null:count??0}

export default function TabletDashboard(){
  const [profile,setProfile]=useState<Profile|null>(null)
  const [now,setNow]=useState(new Date())
  const [metrics,setMetrics]=useState<Record<string,Metric>>({})
  const [warning,setWarning]=useState('')
  useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id)},[])
  useEffect(()=>{void(async()=>{const {data:user}=await supabase.auth.getUser();if(!user.user){location.href='/tablet/home';return}const {data:p}=await supabase.from('erp_usuarios').select('nome,perfil').eq('auth_user_id',user.user.id).eq('ativo',true).is('deleted_at',null).maybeSingle();setProfile(p);const [orders,ops,rncs,stock]=await Promise.all([count('erp_pedidos_venda'),count('erp_ordens_producao'),count('erp_rncs'),count('erp_produto_estoque')]);setMetrics({vendas:{value:orders===null?'—':String(orders),label:'Pedidos ativos'},pcp:{value:ops===null?'—':String(ops),label:'Ordens de produção'},qualidade:{value:rncs===null?'—':String(rncs),label:'RNC registradas'},estoque:{value:stock===null?'—':String(stock),label:'Registros de estoque'}});if([orders,ops,rncs,stock].some(v=>v===null))setWarning('Alguns indicadores não puderam ser consultados no banco atual.')})() },[])
  const logout=async()=>{await supabase.auth.signOut();location.href='/tablet/home'}
  const cards=[{key:'vendas',title:'SETOR COMERCIAL / VENDAS',icon:<ShoppingCart/>,links:[['Novo Pedido','/vendas/novo-pedido'],['Carteira Ativa','/vendas/carteira']]},{key:'pcp',title:'SETOR DE PCP CENTRAL',icon:<Wrench/>,links:[['Planejador de OPs','/pcp/demanda'],['Sequenciamento Semanal','/pcp/sequenciamento']]},{key:'qualidade',title:'SETOR GESTÃO DA QUALIDADE / SGQ',icon:<ClipboardCheck/>,links:[['Inspeção em Processo','/qualidade/inspecao-processo'],['RNC','/qualidade/rnc']]},{key:'estoque',title:'SETOR ALMOXARIFADO & LOTES',icon:<Boxes/>,links:[['Etiquetas Mestre','/estoque/etiquetas'],['Separação','/estoque/separacao']]}]
  return <main className="min-h-screen bg-slate-900 text-slate-100"><header className="flex flex-wrap items-center gap-4 border-b border-slate-700 px-4 py-4 lg:px-8"><div><p className="text-xl font-black">🧰 PAINEL OPERACIONAL</p><p className="text-sm font-bold text-slate-400">📅 {now.toLocaleDateString('pt-BR')} • 🕒 {now.toLocaleTimeString('pt-BR')}</p></div><div className="ml-auto flex items-center gap-3"><span className="text-base font-black">👤 {profile?.nome??'Usuário'} ({profile?.perfil??'Perfil'})</span><button onClick={()=>void logout()} className="rounded-md bg-rose-600 px-5 py-2.5 text-base font-black text-white shadow-lg hover:bg-rose-500"><LogOut size={20} className="mr-2 inline"/> SAIR / FECHAR TERMINAL</button></div></header><section className="mx-auto max-w-[1600px] p-4 lg:p-8"><div className="mb-5 flex items-center gap-3"><BarChart3 size={28} className="text-sky-400"/><h1 className="text-xl font-black">AMBIENTES DE TRABALHO E GRÁFICOS DE SETORES</h1></div>{warning&&<div className="mb-4 rounded-md border border-amber-500 bg-amber-950/40 p-3 font-bold text-amber-200">{warning}</div>}<div className="grid gap-5 md:grid-cols-2">{cards.map(card=>{const metric=metrics[card.key];return <article key={card.key} className="rounded-lg border border-slate-700 bg-slate-800 p-5 shadow-xl"><div className="flex items-center gap-3 border-b border-slate-700 pb-4"><div className="text-sky-400">{card.icon}</div><h2 className="text-xl font-black">{card.title}</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{card.links.map(([label,href])=><a key={href} href={href} className="flex min-h-14 items-center rounded-md border border-slate-600 bg-slate-700 px-4 text-lg font-black text-white hover:bg-slate-600">{label}</a>)}</div><div className="mt-5 rounded-md border border-slate-700 bg-slate-900 p-4"><p className="text-3xl font-black">{metric?.value??'…'}</p><p className="text-sm font-bold text-slate-400">{metric?.label??'Consultando banco...'}</p><div className="mt-3 h-2 overflow-hidden rounded bg-slate-700"><div className="h-full w-full bg-sky-500"/></div></div></article>})}</div></section></main>
}
