import { useEffect, useState } from 'react'
import { ArrowRight, Clock3, LayoutDashboard, LogOut, Palette } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
type ThemeName='blue'|'green'|'gray'
const accent:Record<ThemeName,string>={blue:'bg-sky-600 hover:bg-sky-500',green:'bg-emerald-600 hover:bg-emerald-500',gray:'bg-slate-600 hover:bg-slate-500'}
export default function TabletHome(){const[theme,setTheme]=useState<ThemeName>(()=>{const v=localStorage.getItem('erp-tablet-theme');return v==='green'||v==='gray'?v:'blue'}),[now,setNow]=useState(new Date()),[name,setName]=useState('Usuário'),[profile,setProfile]=useState(''),[error,setError]=useState('')
useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id)},[])
useEffect(()=>{localStorage.setItem('erp-tablet-theme',theme);document.documentElement.dataset.tabletTheme=theme},[theme])
useEffect(()=>{void(async()=>{const u=await supabase.auth.getUser();if(!u.data.user){location.href='/login?returnTo=/tablet/home';return}const p=await supabase.from('erp_usuarios').select('nome,perfil').eq('auth_user_id',u.data.user.id).eq('ativo',true).is('deleted_at',null).maybeSingle();if(p.error)setError(p.error.message);if(p.data){setName(p.data.nome??'Usuário');setProfile(p.data.perfil??'')}})()},[])
const logout=async()=>{await supabase.auth.signOut();location.href='/login'}
return <main className='min-h-screen bg-slate-900 text-slate-100'><header className='flex flex-wrap items-center justify-between gap-4 border-b border-slate-700 px-5 py-4 lg:px-10'><div><p className='text-sm font-black uppercase tracking-widest text-sky-300'>SGQ ERP INDUSTRIAL</p><h1 className='text-xl font-black'>CENTRAL DE ENTRADA DO TABLET</h1></div><div className='flex items-center gap-3'><span className='hidden text-sm font-bold text-slate-300 md:inline'>{now.toLocaleDateString('pt-BR')} • {now.toLocaleTimeString('pt-BR')}</span><label className='flex items-center gap-2 text-sm font-black'><Palette size={18}/><select value={theme} onChange={e=>setTheme(e.target.value as ThemeName)} className='h-11 rounded-md border border-slate-600 bg-slate-800 px-3 font-black text-white'><option value='blue'>Azul Industrial</option><option value='green'>Verde Produção</option><option value='gray'>Cinza Escuro</option></select></label><button onClick={()=>void logout()} className='rounded-md bg-rose-600 px-4 py-3 font-black text-white'><LogOut size={18} className='mr-1 inline'/> SAIR</button></div></header><section className='mx-auto flex min-h-[calc(100vh-88px)] max-w-6xl items-center justify-center p-5'><div className='w-full rounded-lg border border-slate-700 bg-slate-800 p-6 text-center shadow-2xl lg:p-10'><img src='/logo/sgq-erp.png' alt='SGQ ERP Industrial' className='mx-auto h-28 w-auto object-contain sm:h-40 lg:h-48'/><h2 className='mt-5 text-3xl font-black'>ERP INDUSTRIAL</h2><p className='mt-2 text-lg font-bold text-slate-300'>Escolha como deseja trabalhar</p><div className='mt-8 grid gap-5 md:grid-cols-2'><button onClick={()=>location.href='/tablet/dashboard'} className={'min-h-40 rounded-lg px-6 text-left text-white shadow-xl '+accent[theme]}><LayoutDashboard size={34}/><strong className='mt-4 block text-2xl font-black'>TABLET OPERACIONAL</strong><span className='mt-2 block text-base font-semibold'>Vendas, PCP, Qualidade e Almoxarifado em modo touch.</span><span className='mt-4 block font-black'>ENTRAR NO TABLET <ArrowRight className='ml-1 inline'/></span></button><button onClick={()=>location.href='/erp-industrial'} className='min-h-40 rounded-lg border border-slate-500 bg-slate-700 px-6 text-left shadow-xl hover:bg-slate-600'><LayoutDashboard size={34} className='text-sky-300'/><strong className='mt-4 block text-2xl font-black'>PAINEL DESKTOP</strong><span className='mt-2 block text-base font-semibold text-slate-300'>Dashboard completo, módulos, indicadores e gestão.</span><span className='mt-4 block font-black'>CONTINUAR NO DESKTOP <ArrowRight className='ml-1 inline'/></span></button></div><div className='mt-8 flex flex-wrap items-center justify-center gap-5 text-sm font-bold text-slate-400'><span>Logado: {name}</span><span>Perfil: {profile||'—'}</span><span><Clock3 size={15} className='mr-1 inline'/> {now.toLocaleTimeString('pt-BR')}</span></div>{error&&<p className='mt-4 font-bold text-rose-300'>{error}</p>}</div></section></main>}