import { useEffect, useMemo, useState } from 'react'
import { RefreshCw, Search, ShieldCheck, UserCheck, UserX } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type User={id:string;empresa_id:string|null;auth_user_id:string|null;nome:string;email:string|null;nivel_admin:number;ativo:boolean;role_id:string|null;login_nome:string|null}
type Company={id:string;razao_social:string|null;nome_fantasia:string|null;codigo:string|null;ativo:boolean;plano:string|null;plano_status:string|null}

export default function UsuariosAdmin(){
 const[users,setUsers]=useState<User[]>([]),[companies,setCompanies]=useState<Company[]>([]),[actor,setActor]=useState<User|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[companyFilter,setCompanyFilter]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setLoading(true);setMessage('');try{const auth=(await supabase.auth.getUser()).data.user;if(!auth)throw new Error('Sessão não encontrada.');const {data:a,error:ae}=await supabase.from('erp_usuarios').select('id,empresa_id,auth_user_id,nome,email,nivel_admin,ativo,role_id,login_nome').eq('auth_user_id',auth.id).is('deleted_at',null).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Usuário autenticado não está vinculado ao ERP.');setActor(a as User);const master=Number(a.nivel_admin)>=9;let uq=supabase.from('erp_usuarios').select('id,empresa_id,auth_user_id,nome,email,nivel_admin,ativo,role_id,login_nome').is('deleted_at',null).order('nome');if(!master)uq=uq.eq('empresa_id',a.empresa_id);const [ur,cr]=await Promise.all([uq,supabase.from('erp_empresas').select('id,razao_social,nome_fantasia,codigo,ativo,plano,plano_status').order('nome_fantasia')]);if(ur.error)throw ur.error;if(cr.error)throw cr.error;setUsers((ur.data||[]) as User[]);setCompanies((cr.data||[]) as Company[])}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível carregar usuários.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>users.filter(u=>(!companyFilter||u.empresa_id===companyFilter)&&JSON.stringify(u).toLowerCase().includes(search.toLowerCase())),[users,companyFilter,search])
 const toggle=async(user:User)=>{if(!actor)return;const master=Number(actor.nivel_admin)>=9;if(!master&&user.empresa_id!==actor.empresa_id){setMessage('Operação recusada: empresa diferente.');return}setBusy(true);setMessage('');try{const{error}=await supabase.from('erp_usuarios').update({ativo:!user.ativo}).eq('id',user.id).eq('empresa_id',user.empresa_id);if(error)throw error;setMessage(user.ativo?'Usuário desativado.':'Usuário ativado.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível alterar o usuário.')}finally{setBusy(false)}}
 return <div className="crud-page" style={{padding:28,maxWidth:1500,margin:'0 auto'}}><div className="feature-v2 crud-header"><div><span className="v2-eyebrow">SEGURANÇA • RBAC • MULTIEMPRESA</span><h1>Usuários e permissões</h1><p>Usuários reais do Supabase vinculados à empresa e protegidos por tenant.</p></div><button className="menu-green" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={17}/>{loading?'Atualizando…':'Atualizar'}</button></div>{message&&<div className="notice" style={{margin:'12px 0'}}>{message}</div>}<section className="erp-card" style={{padding:18,marginBottom:16}}><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><label className="crud-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar usuário"/></label>{Number(actor?.nivel_admin)>=9&&<select value={companyFilter} onChange={e=>setCompanyFilter(e.target.value)}><option value="">Todas as empresas</option>{companies.map(c=><option key={c.id} value={c.id}>{c.nome_fantasia||c.razao_social||c.codigo||c.id}</option>)}</select>}<span>{filtered.length} usuário(s)</span></div></section><section className="crud-list"><div className="crud-list-head"><strong>Contas cadastradas</strong><span>{Number(actor?.nivel_admin)>=9?'MASTER':'Empresa atual'}</span></div>{!filtered.length?<div className="crud-empty">Sem usuários para os filtros atuais.</div>:<div className="crud-table-wrap"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Empresa</th><th>Nível</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><strong>{u.nome}</strong><br/><small>{u.login_nome||'—'}</small></td><td>{u.email||'—'}</td><td>{companies.find(c=>c.id===u.empresa_id)?.nome_fantasia||u.empresa_id||'—'}</td><td>{u.nivel_admin>=9?<span><ShieldCheck size={14}/> MASTER</span>:u.nivel_admin}</td><td>{u.ativo?<span className="master-active"><UserCheck size={14}/> Ativo</span>:<span className="master-off"><UserX size={14}/> Inativo</span>}</td><td><button type="button" disabled={busy||(!Number(actor?.nivel_admin)&&true)} onClick={()=>void toggle(u)}>{u.ativo?'Desativar':'Ativar'}</button></td></tr>)}</tbody></table></div>}</section></div>
}
