import { FormEvent, useEffect, useState } from 'react'
import { Edit3, Lock, Plus, RefreshCw, Search, ShieldCheck, Trash2, UserCheck, UserX } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type ERPUser={id:string;nome:string;email:string|null;nivel_admin:number;ativo:boolean;setor_id:string|null;cargo_id:string|null;matricula:string|null;login_nome:string|null;created_at:string}
const api=async(body:Record<string,unknown>)=>{const {data,error}=await supabase.functions.invoke('erp-user-admin',{body});if(error)throw new Error(error.message);if(!data?.ok)throw new Error(data?.error||'Operação não concluída.');return data}

export default function UsuariosAdmin(){
 const [users,setUsers]=useState<ERPUser[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[editing,setEditing]=useState<ERPUser|null>(null),[show,setShow]=useState(false)
 const [form,setForm]=useState({nome:'',email:'',login_nome:'',matricula:'',nivel_admin:'1',password:''})
 const load=async()=>{setBusy(true);setMsg('');try{const r=await api({action:'list_users'});setUsers(r.users||[])}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível carregar usuários.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const openCreate=()=>{setEditing(null);setForm({nome:'',email:'',login_nome:'',matricula:'',nivel_admin:'1',password:''});setShow(true);setMsg('')}
 const openEdit=(u:ERPUser)=>{setEditing(u);setForm({nome:u.nome,email:u.email||'',login_nome:u.login_nome||'',matricula:u.matricula||'',nivel_admin:String(u.nivel_admin),password:''});setShow(true);setMsg('')}
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMsg('');try{if(editing){await api({action:'update_user',user_id:editing.id,nome:form.nome,email:form.email,login_nome:form.login_nome,matricula:form.matricula,nivel_admin:Number(form.nivel_admin)});setMsg('Usuário atualizado com sucesso.')}else{if(!form.password)throw new Error('Informe uma senha inicial.');await api({action:'create_user',...form,nivel_admin:Number(form.nivel_admin)});setMsg('Usuário criado com sucesso.')}setShow(false);await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível salvar o usuário.')}finally{setBusy(false)}}
 const toggle=async(u:ERPUser)=>{setBusy(true);setMsg('');try{await api({action:'set_active',user_id:u.id,ativo:!u.ativo});await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível alterar o acesso.')}finally{setBusy(false)}}
 const remove=async(u:ERPUser)=>{if(!confirm(`Excluir definitivamente o usuário ${u.nome}? Esta ação remove o acesso Auth e o cadastro ERP.`))return;setBusy(true);setMsg('');try{await api({action:'delete_user',user_id:u.id});setMsg('Usuário excluído definitivamente.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível excluir o usuário.')}finally{setBusy(false)}}
 const filtered=users.filter(u=>`${u.nome} ${u.email||''} ${u.login_nome||''} ${u.matricula||''}`.toLowerCase().includes(query.toLowerCase()))
 return <div className="users-admin">
   <div className="users-head"><div><span className="eyebrow">ADMINISTRAÇÃO • ACESSOS</span><h2>Usuários do ERP</h2><p>Cadastro, edição, bloqueio e exclusão sincronizados entre o ERP e o Supabase Auth.</p></div><div className="users-actions"><button type="button" className="secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Atualizar</button><button type="button" className="primary" onClick={openCreate}><Plus size={17}/> Novo usuário</button></div></div>
   <div className="users-toolbar"><label className="form-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar por nome, login, e-mail ou matrícula"/></label><span>{filtered.length} usuário(s)</span></div>
   {msg&&<div className="form-message">{msg}</div>}
   <div className="users-grid">{filtered.map(u=><article className={`user-card ${u.ativo?'':'inactive'}`} key={u.id}><div className="user-card-top"><div className="user-avatar">{u.nome.slice(0,1).toUpperCase()}</div><div><strong>{u.nome}</strong><span>{u.login_nome||u.email||'Sem login'}</span></div><b className={u.ativo?'status-on':'status-off'}>{u.ativo?'Ativo':'Bloqueado'}</b></div><div className="user-meta"><span><ShieldCheck size={14}/> Nível {u.nivel_admin}</span><span><Lock size={14}/> {u.email||'Sem e-mail'}</span>{u.matricula&&<span>Matrícula {u.matricula}</span>}</div><div className="user-card-actions"><button type="button" onClick={()=>openEdit(u)} disabled={busy}><Edit3 size={15}/> Editar</button><button type="button" onClick={()=>void toggle(u)} disabled={busy}>{u.ativo?<><UserX size={15}/> Bloquear</>:<><UserCheck size={15}/> Ativar</>}</button><button type="button" className="danger" onClick={()=>void remove(u)} disabled={busy}><Trash2 size={15}/> Excluir</button></div></article>)}{!filtered.length&&<div className="empty-users"><UserCheck size={30}/><strong>Nenhum usuário encontrado</strong><span>Crie o primeiro acesso administrativo ou ajuste a pesquisa.</span></div>}</div>
   {show&&<div className="user-modal"><div className="user-modal-card"><div className="user-modal-head"><div><span className="eyebrow">ACESSO SEGURO</span><h3>{editing?'Editar usuário':'Novo usuário'}</h3></div><button type="button" onClick={()=>setShow(false)}>×</button></div><form onSubmit={save} className="user-form"><label>Nome completo<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} required autoFocus/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Login<input value={form.login_nome} onChange={e=>setForm({...form,login_nome:e.target.value})} placeholder="ex.: joao.silva"/></label><label>Matrícula<input value={form.matricula} onChange={e=>setForm({...form,matricula:e.target.value})}/></label><label>Nível administrativo<select value={form.nivel_admin} onChange={e=>setForm({...form,nivel_admin:e.target.value})}><option value="1">1 — Operador</option><option value="2">2 — Supervisor</option><option value="3">3 — Gestor</option><option value="4">4 — Administrador</option><option value="8">8 — Administrador Master</option></select></label>{!editing&&<label>Senha inicial<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo 8 caracteres, letras e números" required minLength={8}/></label>}<div className="user-form-foot"><button type="button" className="secondary" onClick={()=>setShow(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':editing?'Salvar alterações':'Criar usuário'}</button></div></form></div></div>}
 </div>
}
