import { useEffect, useState } from "react";
import { Copy, ExternalLink, RefreshCw, Search, Send } from "lucide-react";
import { supabase } from "../lib/supabaseClient";

type Pedido={id:string;numero:number;pedido_cliente:string|null;status:string;total:number;data_entrega_prometida:string|null;cliente:{nome:string}|null};
const brl=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);

export default function VendasCarteira(){
 const [rows,setRows]=useState<Pedido[]>([]); const [q,setQ]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);setError("");const e=await supabase.rpc("erp_current_empresa_id");if(e.error||!e.data){setError(e.error?.message||"Empresa não identificada.");setBusy(false);return}const r=await supabase.from("erp_pedidos_venda").select("id,numero,pedido_cliente,status,total,data_entrega_prometida,cliente:erp_clientes(nome)").eq("empresa_id",String(e.data)).order("numero",{ascending:false}).limit(500);if(r.error)setError(r.error.message);setRows((r.data??[]) as unknown as Pedido[]);setBusy(false)};
 useEffect(()=>{void load()},[]);
 const filtered=rows.filter(x=>!q||String(x.numero).includes(q)||(x.cliente?.nome??"").toLowerCase().includes(q.toLowerCase())||(x.pedido_cliente??"").toLowerCase().includes(q.toLowerCase()));
 const url=window.location.origin+"/vendas/catalogo-digital";
 const copy=async()=>navigator.clipboard.writeText(url);
 const share=()=>{const subject=encodeURIComponent("Catálogo digital ERP Industrial");const body=encodeURIComponent("Acesse nosso catálogo digital: "+url);window.location.href="mailto:?subject="+subject+"&body="+body};
 return <div className="min-h-screen bg-slate-50 text-slate-900">
  <header className="sticky top-0 z-20 bg-white border-b border-slate-200"><div className="min-h-[78px] px-4 lg:px-6 flex items-center justify-between gap-4"><div><div className="text-xs font-black tracking-widest text-blue-700">ERP INDUSTRIAL • VENDAS</div><h1 className="text-xl font-black">CARTEIRA DE PEDIDOS ATIVOS</h1></div><div className="flex flex-wrap gap-2 justify-end"><button onClick={()=>location.assign("/vendas/novo-pedido")} className="min-h-[46px] rounded-md bg-blue-700 text-white px-4 font-black">NOVO PEDIDO</button><button onClick={()=>void copy()} className="min-h-[46px] rounded-md border border-slate-300 px-4 font-black flex gap-2 items-center"><Copy size={17}/> COPIAR LINK CATÁLOGO</button><button onClick={share} className="min-h-[46px] rounded-md bg-slate-900 text-white px-4 font-black flex gap-2 items-center"><Send size={17}/> ENVIAR LINK</button><button disabled={busy} onClick={()=>void load()} className="min-h-[46px] rounded-md border px-3 font-black"><RefreshCw size={17}/></button></div></div></header>
  <main className="p-4 lg:p-6 max-w-[1600px] mx-auto"><section className="bg-white border border-slate-200 rounded-md shadow-sm p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">FILA GERAL DE PEDIDOS EM CARTEIRA</h2><p className="mt-1 text-base text-slate-700">Pedidos reais da empresa atual. Nenhuma linha demonstrativa é criada.</p></div><div className="flex items-center gap-2"><Search size={18} className="text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} className="min-h-[46px] w-72 border rounded-md px-3 text-slate-900" placeholder="Nº, cliente ou pedido cliente"/></div></div>{error&&<div className="mt-4 p-3 rounded-md bg-rose-100 text-rose-900 font-bold">{error}</div>}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[950px]"><thead><tr className="h-[54px] bg-slate-100 text-left text-base font-bold"><th>Nº Ped.</th><th>Pedido Cliente</th><th>Cliente</th><th>Data Entrega</th><th>Valor (R$)</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="h-[54px] border-t border-slate-200"><td className="font-black">{String(x.numero).padStart(6,"0")}</td><td>{x.pedido_cliente||"—"}</td><td>{x.cliente?.nome||"—"}</td><td>{x.data_entrega_prometida||"—"}</td><td className="font-bold">{brl(Number(x.total||0))}</td><td><span className="inline-flex min-h-[32px] items-center rounded-full bg-slate-100 px-3 font-bold">{x.status}</span></td><td><button onClick={()=>location.assign("/vendas/carteira")} className="font-black text-blue-700 flex gap-1 items-center"><ExternalLink size={17}/> Abrir</button></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="py-12 text-center text-slate-600 font-semibold">Nenhum pedido real encontrado com os filtros atuais.</td></tr>}</tbody></table></div><div className="mt-5 border-t pt-4 text-base font-semibold text-slate-700">Link público/B2B configurado para o catálogo: <button onClick={()=>void copy()} className="text-blue-700 font-black underline">{url}</button></div></section></main>
 </div>
}
