import { useEffect, useState } from "react";
import { Plus, Save, RefreshCw } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
type Func={id:string;nome:string;matricula:string|null};
type Meta={id:string;competencia:string;meta_faturamento:number;meta_pedidos:number};
const brl=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
export default function VendasMetas(){const [empresa,setEmpresa]=useState("");const [func,setFunc]=useState<Func[]>([]);const [meta,setMeta]=useState<Meta|null>(null);const [mes,setMes]=useState(new Date().toISOString().slice(0,7));const [valor,setValor]=useState("0");const [pedidos,setPedidos]=useState("0");const [realizado,setRealizado]=useState(0);const [msg,setMsg]=useState("");
 const load=async()=>{const e=await supabase.rpc("erp_current_empresa_id");if(e.error||!e.data){setMsg(e.error?.message||"Empresa não identificada.");return}const id=String(e.data);setEmpresa(id);const [f,m,p]=await Promise.all([supabase.from("erp_funcionarios").select("id,nome,matricula").eq("empresa_id",id).eq("status","ATIVO").order("nome"),supabase.from("erp_vendas_metas").select("id,competencia,meta_faturamento,meta_pedidos").eq("empresa_id",id).eq("competencia",mes+"-01").maybeSingle(),supabase.from("erp_pedidos_venda").select("total,status").eq("empresa_id",id).gte("data_entrega_prometida",mes+"-01").lt("data_entrega_prometida",new Date(new Date(mes+"-01T00:00:00").setMonth(new Date(mes+"-01T00:00:00").getMonth()+1)).toISOString().slice(0,10))]);if(f.error)setMsg(f.error.message);setFunc((f.data??[]) as Func[]);setMeta((m.data??null) as Meta|null);setValor(String(Number(m.data?.meta_faturamento??0)));setPedidos(String(Number(m.data?.meta_pedidos??0)));setRealizado((p.data??[]).filter(x=>!["cancelado"].includes(x.status)).reduce((s,x)=>s+Number(x.total??0),0))};
 useEffect(()=>{void load()},[mes]);
 const save=async()=>{const r=await supabase.from("erp_vendas_metas").upsert({empresa_id:empresa,competencia:mes+"-01",meta_faturamento:Number(valor)||0,meta_pedidos:Number(pedidos)||0},{onConflict:"empresa_id,competencia"});setMsg(r.error?r.error.message:"Meta gravada com sucesso.");void load()};
 const pct=Math.min((realizado/(Number(valor)||1))*100,999);
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 bg-white border-b"><div className="min-h-[76px] px-4 lg:px-6 flex justify-between items-center gap-3"><div><div className="text-xs font-black tracking-widest text-blue-700">ERP INDUSTRIAL • VENDAS</div><h1 className="text-xl font-black">CONTROLE DE METAS DA EQUIPE COMERCIAL</h1></div><div className="flex gap-2"><label className="min-h-[46px] border rounded-md px-3 flex items-center font-bold">Competência<input type="month" className="ml-2" value={mes} onChange={e=>setMes(e.target.value)}/></label><button onClick={()=>void load()} className="min-h-[46px] border rounded-md px-4 font-black"><RefreshCw size={17}/></button><button onClick={()=>void save()} className="min-h-[46px] bg-blue-700 text-white rounded-md px-4 font-black flex gap-2"><Save size={17}/> GRAVAR</button></div></div></header><main className="p-4 lg:p-6 max-w-[1400px] mx-auto"><section className="bg-white border rounded-md shadow-sm p-5"><div className="flex justify-between"><h2 className="text-xl font-bold text-slate-950">INDICADORES DE DESEMPENHO E ATINGIMENTO</h2><button className="min-h-[46px] border rounded-md px-4 font-black"><Plus size={17} className="inline"/> NOVA META</button></div><div className="mt-5 grid md:grid-cols-3 gap-4"><label className="grid gap-1 font-bold">Meta faturamento<input type="number" className="min-h-[46px] border rounded-md px-3 text-slate-900" value={valor} onChange={e=>setValor(e.target.value)}/></label><label className="grid gap-1 font-bold">Meta de pedidos<input type="number" className="min-h-[46px] border rounded-md px-3 text-slate-900" value={pedidos} onChange={e=>setPedidos(e.target.value)}/></label><div className="p-4 bg-slate-100 rounded-md"><span className="font-bold">Realizado</span><strong className="block text-2xl">{brl(realizado)}</strong></div></div>{msg&&<div className="mt-4 p-3 bg-slate-100 text-slate-900 rounded-md font-bold">{msg}</div>}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="h-[54px] bg-slate-100 text-left text-base font-bold"><th>Nome Vendedor</th><th>Barra de Progresso Real</th><th>% Atingido</th></tr></thead><tbody>{func.map(f=><tr key={f.id} className="h-[54px] border-t"><td className="font-semibold">{f.nome}</td><td><div className="h-4 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-blue-600" style={{width:`${Math.min(pct,100)}%`}}/></div></td><td className="font-black">{pct.toFixed(0)}%</td></tr>)}{!func.length&&<tr><td colSpan={3} className="py-10 text-center text-slate-600 font-semibold">Nenhum vendedor ativo cadastrado. O ranking não será inventado.</td></tr>}</tbody></table></div></section></main></div>}
