import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Boxes, Factory, Lock, Package, RefreshCw, Ruler, Search, Truck, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import { fetchAllPages } from '../lib/supabasePagination'
import VendasLayout from './VendasLayout'

type Cliente={nome:string}
type Row={id:string;numero:number;pedido_cliente:string|null;status:string;total:number;data_entrega_prometida:string|null;cliente:Cliente|null}
type RowFromDb=Omit<Row,'cliente'> & {cliente:Cliente|Cliente[]|null}
type Item={id:string;produto_id:string|null;descricao:string;quantidade:number;data_fabricacao:string|null;produto?:{codigo:string;unidade:string}|null}
type Anexo={id:string;url_arquivo:string;nome_arquivo:string;criado_em:string}
type Stage='comercial'|'engenharia'|'pcp'|'producao'|'almoxarifado'|'faturamento'
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(v)?v:0)
const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d}
const formatDate=(v:string|null)=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(v+'T00:00:00')):'—'
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const stageOrder:Stage[]=['comercial','engenharia','pcp','producao','almoxarifado','faturamento']

export default function VendasStatusPedidos(){
 const [rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState('todos'),[error,setError]=useState(''),[selected,setSelected]=useState<Row|null>(null),[items,setItems]=useState<Item[]>([]),[anexos,setAnexos]=useState<Anexo[]>([]),[canRectify,setCanRectify]=useState(false)
 const load=async()=>{const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.');const rows=await fetchAllPages<RowFromDb>((from,to)=>supabase.from('erp_pedidos_venda').select('id,numero,pedido_cliente,status,total,data_entrega_prometida,cliente:erp_clientes(nome)',{count:'exact'}).eq('empresa_id',String(e.data)).order('numero',{ascending:false}).range(from,to));setRows(rows.map(row=>({...row,cliente:Array.isArray(row.cliente)?row.cliente[0]??null:row.cliente})))}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar pedidos.'));void (async()=>{const {data}=await supabase.auth.getUser();if(!data.user)return;const p=await supabase.from('erp_usuarios').select('perfil,is_master,ativo,deleted_at').eq('auth_user_id',data.user.id).eq('ativo',true).is('deleted_at',null).maybeSingle();if(!p.error){const role=String(p.data?.perfil??'').trim().toUpperCase();setCanRectify(Boolean(p.data?.is_master)||role==='ADMINISTRADOR'||role==='CONTROLADORIA')}})()},[])
 const loadItems=async(row:Row)=>{setSelected(row);setAnexos([]);const r=await supabase.from('erp_pedidos_venda_itens').select('id,produto_id,descricao,quantidade,data_fabricacao,produto:erp_produtos(codigo,unidade)').eq('empresa_id',await empresa()).eq('pedido_id',row.id).order('id');if(r.error){setError(r.error.message);return}setItems((r.data??[]) as unknown as Item[]);const a=await supabase.from('erp_pedidos_anexos').select('id,url_arquivo,nome_arquivo,criado_em').eq('empresa_id',await empresa()).eq('pedido_id',row.id).order('criado_em',{ascending:false});if(!a.error)setAnexos((a.data??[]) as Anexo[])}
 const empresa=async()=>{const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.');return String(e.data)}
 const stateFor=(row:Row,stage:Stage)=>{
  const s=norm(row.status)
  if(row.data_entrega_prometida&&new Date(row.data_entrega_prometida+'T00:00:00')<today()&&!s.includes('fatur'))return {label:'ATRASADO',tone:'red' as const,blocked:false}
  if(stage==='comercial')return s.includes('rascun')||s.includes('aberto')?{label:'DIGITAÇÃO',tone:'yellow' as const,blocked:false}:{label:'CONCLUÍDO',tone:'green' as const,blocked:false}
  if(stage==='engenharia')return s.includes('engen')||s.includes('projeto')?{label:'ANÁLISE DE PROJETO',tone:'yellow' as const,blocked:false}:{label:'LIBERADO',tone:'green' as const,blocked:false}
  if(stage==='pcp'||stage==='almoxarifado')return s.includes('mater')||s.includes('almox')?{label:'FALTA MATÉRIA-PRIMA',tone:'red' as const,blocked:false}:{label:'RESERVADO',tone:'green' as const,blocked:false}
  if(stage==='producao')return s.includes('produc')||s.includes('fabric')?{label:s.includes('final')?'EM ESTOQUE':'EM FABRICAÇÃO',tone:s.includes('final')?'green' as const:'yellow' as const,blocked:false}:{label:'AGUARDANDO',tone:'gray' as const,blocked:false}
  return s.includes('fatur')?{label:'FATURADO',tone:'green' as const,blocked:false}:{label:'AGUARDANDO',tone:'gray' as const,blocked:false}
 }
 const blockerIndex=(row:Row)=>{const s=norm(row.status);if(s.includes('fatur'))return -1;if(s.includes('produc'))return 3;if(s.includes('almox')||s.includes('mater'))return 2;if(s.includes('pcp'))return 2;if(s.includes('engen')||s.includes('projeto'))return 1;if(s.includes('rascun')||s.includes('aberto'))return 0;return 0}
 const cell=(row:Row,stage:Stage)=>{const blocked=stageOrder.indexOf(stage)>blockerIndex(row);if(blocked)return <Lock size={10} style={{opacity:.3}}/>;const s=stateFor(row,stage);return <span className={`inline-flex rounded-none px-1.5 py-0.5 text-[8px] font-medium ${s.tone==='red'?'bg-red-100 text-red-700':s.tone==='yellow'?'bg-amber-100 text-amber-700':s.tone==='green'?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{s.label}</span>}
 const visible=useMemo(()=>rows.filter(o=>{const s=norm(o.status);const delayed=!!o.data_entrega_prometida&&new Date(o.data_entrega_prometida+'T00:00:00')<today()&&!s.includes('fatur');const m=!q||String(o.numero).includes(q)||norm(o.cliente?.nome??'').includes(norm(q));const f=filter==='todos'||(filter==='atrasados'&&delayed)||(filter==='eng'&&(s.includes('engen')||s.includes('projeto')))||(filter==='pcp'&&s.includes('pcp'))||(filter==='producao'&&(s.includes('produc')||s.includes('fabric')))||(filter==='almoxarifado'&&(s.includes('almox')||s.includes('mater')))||(filter==='faturamento'&&s.includes('fatur'));return m&&f}),[rows,q,filter])
 const filters=[['todos','TODOS',Package],['atrasados','ATRASADOS',AlertTriangle],['eng','ENG',Ruler],['pcp','PCP',Factory],['producao','PRODUÇÃO',Factory],['almoxarifado','ALMOXARIFADO',Boxes],['faturamento','FATURAMENTO',Truck]] as const
 return <VendasLayout title="Pedidos Pendentes / Workflow Geral" subtitle="Rastreabilidade do pedido" onRefresh={()=>void load()}>
  <div className="relative space-y-1.5 text-[11px]">
   <div className="flex items-center gap-1">{filters.map(([key,label,Icon])=><button key={key} type="button" onClick={()=>setFilter(key)} className={`flex h-7 items-center gap-1 border px-2 text-[9px] font-semibold ${filter===key?'bg-[#3A9D78] text-white':'bg-white'}`}><Icon size={11}/>{label}</button>)}<div className="ml-auto flex items-center gap-1 border bg-white px-1"><Search size={11}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nº ou cliente" className="h-6 w-44 border-0 px-1 text-[10px] outline-none"/></div></div>
   <section className="overflow-x-auto border border-slate-300 bg-white"><table className="w-full min-w-[1250px] border-collapse text-[9px]"><thead><tr className="bg-[#DEE2E6] text-left uppercase"><th className="p-1.5">Pedido</th><th>Cliente</th><th>Entrega</th><th>Valor</th><th>Comercial</th><th>Engenharia</th><th>PCP</th><th>Produção</th><th>Almoxarifado</th><th>Faturamento</th></tr></thead><tbody>{visible.map(row=>{const delayed=!!row.data_entrega_prometida&&new Date(row.data_entrega_prometida+'T00:00:00')<today()&&!norm(row.status).includes('fatur');return <tr key={row.id} onClick={()=>void loadItems(row)} className={`cursor-pointer border-t hover:bg-slate-50 ${delayed?'border-l-2 border-l-red-500 bg-red-50/20':''}`}><td className="p-1.5 font-semibold">{String(row.numero).padStart(6,'0')}</td><td>{row.cliente?.nome??'—'}</td><td>{formatDate(row.data_entrega_prometida)}</td><td>{brl(Number(row.total))}</td><td>{cell(row,'comercial')}</td><td>{cell(row,'engenharia')}</td><td>{cell(row,'pcp')}</td><td>{cell(row,'producao')}</td><td>{cell(row,'almoxarifado')}</td><td>{cell(row,'faturamento')}</td></tr>})}{!visible.length&&<tr><td colSpan={10} className="p-6 text-center text-slate-500">Nenhum pedido real encontrado.</td></tr>}</tbody></table></section>
   {selected&&<><button aria-label="Fechar painel" type="button" onClick={()=>setSelected(null)} className="fixed inset-0 z-40 cursor-default bg-black/10"/><aside className="fixed inset-y-0 right-0 z-50 w-[35vw] min-w-[420px] border-l border-slate-300 bg-white shadow-xl"><header className="flex h-10 items-center justify-between border-b bg-[#212529] px-2 text-white"><div className="text-[11px]"><b>Pedido {String(selected.numero).padStart(6,'0')}</b><span className="ml-2 text-slate-300">{selected.cliente?.nome??'—'}</span></div><button type="button" onClick={()=>setSelected(null)} className="h-6 w-6 border border-slate-500"><X size={12}/></button></header><div className="p-2"><div className="mb-2 flex items-center justify-between"><div className="text-[9px] text-slate-500">ITENS DO PEDIDO • ENTREGA {formatDate(selected.data_entrega_prometida)}</div>{canRectify&&!["rascunho","aberto","cotação","cotacao"].includes(norm(selected.status))&&<button id="btnAtualizarPedido" type="button" onClick={()=>window.location.assign("/controladoria/retificacao-pedido/"+selected.id)} className="flex h-7 items-center gap-1 rounded-md bg-blue-600 px-2 text-[10px] font-medium text-white"><RefreshCw size={12} className="mr-1"/>Ajustar Campos</button>}</div><table className="w-full border-collapse text-[9px]"><thead><tr className="bg-[#DEE2E6] text-left"><th className="p-1">SKU</th><th>Descrição</th><th>Qtd</th><th>UN</th><th>Entrega</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-t"><td className="p-1">{i.produto?.codigo??''}</td><td>{i.descricao}</td><td>{i.quantidade}</td><td>{i.produto?.unidade??''}</td><td>{formatDate(selected.data_entrega_prometida)}</td></tr>)}{!items.length&&<tr><td colSpan={5} className="p-4 text-center text-slate-500">Pedido sem itens.</td></tr>}</tbody></table>{anexos.length>0&&<div className="mt-2 border-t pt-2"><div className="mb-1 text-[9px] font-medium text-slate-500">ANEXOS DE ORIGEM / AUDITORIA</div>{anexos.map(a=><button key={a.id} type="button" className="mr-1 mb-1 inline-flex border px-1.5 py-1 text-[9px] text-[#17445A]" onClick={()=>void supabase.storage.from('pedidos-origem').createSignedUrl(a.url_arquivo,600).then(x=>{if(x.data?.signedUrl)window.open(x.data.signedUrl,'_blank','noopener,noreferrer')})}>{a.nome_arquivo}</button>)}</div>}</div></aside></>}
  </div>
 </VendasLayout>
}
