import { useEffect, useMemo, useState } from 'react'
import { Check, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import EntityCodeLookup, { type LookupRecord } from '../components/industrial/EntityCodeLookup'

type Client={id:string;codigo:string|null;nome:string;documento:string|null;email:string|null;telefone:string|null;endereco:string|null;tipo_cliente:string|null;tabela_preco_id:string|null;desconto_padrao_percentual:number;ativo:boolean}
type DePara={id:string;cliente_id:string;produto_id:string;codigo_interno:string;codigo_cliente:string;dimensoes:string|null;canal:string|null;molde:string|null;ativo:boolean}
type Product=LookupRecord & { descricao?:string|null }
type Form={codigo:string;nome:string;documento:string;email:string;telefone:string;endereco:string;tipo_cliente:string;desconto:string;ativo:boolean}
const empty:Form={codigo:'',nome:'',documento:'',email:'',telefone:'',endereco:'',tipo_cliente:'PADRAO',desconto:'0',ativo:true}
const input='h-[54px] w-full rounded-md border border-slate-300 bg-white px-3 text-base font-semibold text-slate-900 outline-none focus:border-sky-600 focus:ring-2 focus:ring-sky-100'
export default function VendasClientes(){
 const[empresa,setEmpresa]=useState(''),[rows,setRows]=useState<Client[]>([]),[products,setProducts]=useState<Product[]>([]),[mappings,setMappings]=useState<DePara[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[produto,setProduto]=useState(''),[codigoCliente,setCodigoCliente]=useState(''),[dimensoes,setDimensoes]=useState(''),[canal,setCanal]=useState(''),[molde,setMolde]=useState('')
 const load=async()=>{setBusy(true);setError('');try{const t=await supabase.rpc('erp_current_empresa_id');if(t.error||!t.data)throw t.error??new Error('Empresa ERP não identificada.');const id=String(t.data);setEmpresa(id);const[c,p,d]=await Promise.all([supabase.from('erp_clientes').select('id,codigo,nome,documento,email,telefone,endereco,tipo_cliente,tabela_preco_id,desconto_padrao_percentual,ativo').eq('empresa_id',id).order('nome'),supabase.from('erp_produtos').select('id,codigo,nome,descricao,estoque_atual').eq('empresa_id',id).eq('ativo',true).order('codigo').limit(3000),supabase.from('erp_cliente_produto_de_para').select('id,cliente_id,produto_id,codigo_interno,codigo_cliente,dimensoes,canal,molde,ativo').eq('empresa_id',id).eq('ativo',true).order('codigo_cliente')]);if(c.error)throw c.error;if(p.error)throw p.error;if(d.error)throw d.error;setRows((c.data??[]) as Client[]);setProducts((p.data??[]) as Product[]);setMappings((d.data??[]) as DePara[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar clientes.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>rows.filter(r=>{const q=query.trim().toLowerCase();return !q||[r.codigo,r.nome,r.documento,r.email].filter(Boolean).join(' ').toLowerCase().includes(q)}),[rows,query])
 const selectedClient=rows.find(r=>r.id===selected)??null
 const openNew=()=>{setSelected(null);setForm(empty);setOpen(true);setMsg('');setError('')}
 const edit=(r:Client)=>{setSelected(r.id);setForm({codigo:r.codigo??'',nome:r.nome,documento:r.documento??'',email:r.email??'',telefone:r.telefone??'',endereco:r.endereco??'',tipo_cliente:r.tipo_cliente??'PADRAO',desconto:String(r.desconto_padrao_percentual??0),ativo:r.ativo});setOpen(true);setMsg('');setError('')}
 const save=async()=>{if(!empresa||!form.nome.trim()){setError('Razão social/nome é obrigatório.');return}setBusy(true);setError('');try{const payload={empresa_id:empresa,codigo:form.codigo.trim()||null,nome:form.nome.trim(),documento:form.documento.trim()||null,email:form.email.trim()||null,telefone:form.telefone.trim()||null,endereco:form.endereco.trim()||null,tipo_cliente:form.tipo_cliente.trim()||'PADRAO',desconto_padrao_percentual:Number(form.desconto)||0,ativo:form.ativo};const r=selected?await supabase.from('erp_clientes').update(payload).eq('id',selected).eq('empresa_id',empresa):await supabase.from('erp_clientes').insert(payload);if(r.error)throw r.error;setOpen(false);setMsg(selected?'Cliente atualizado.':'Cliente cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar cliente.')}finally{setBusy(false)}}
 const remove=async()=>{if(!selected||!window.confirm('Excluir este cliente?'))return;setBusy(true);try{const r=await supabase.from('erp_clientes').delete().eq('id',selected).eq('empresa_id',empresa);if(r.error)throw r.error;setSelected(null);setMsg('Cliente excluído.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir cliente.')}finally{setBusy(false)}}
 const addMapping=async()=>{if(!selected||!produto||!codigoCliente.trim()){setError('Selecione o cliente, o produto e informe o código do cliente.');return}const p=products.find(x=>x.id===produto);const r=await supabase.from('erp_cliente_produto_de_para').upsert({empresa_id:empresa,cliente_id:selected,produto_id:produto,codigo_interno:p?.codigo??'',codigo_cliente:codigoCliente.trim(),dimensoes:dimensoes.trim()||null,canal:canal.trim()||null,molde:molde.trim()||null,ativo:true},{onConflict:'empresa_id,cliente_id,produto_id'});if(r.error)setError(r.error.message);else{setCodigoCliente('');setDimensoes('');setCanal('');setMolde('');setMsg('De-Para gravado.');await load()}}
 const delMapping=async(id:string)=>{const r=await supabase.from('erp_cliente_produto_de_para').delete().eq('id',id).eq('empresa_id',empresa);if(r.error)setError(r.error.message);else await load()}
 const productRecords=products.map(p=>({id:p.id,codigo:p.codigo,nome:p.nome,descricao:p.descricao??undefined}))
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-900"><div className="mx-auto max-w-[1700px] space-y-5">
  <header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-sm font-black uppercase tracking-widest text-sky-700">VENDAS › CADASTRO E FICHA DE CLIENTES</p><h1 className="text-3xl font-black text-slate-950">Clientes e De-Para de Engenharia</h1><p className="mt-1 text-base font-semibold text-slate-600">Cadastro fiscal/comercial e códigos usados pelo cliente em pedidos e XML.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={openNew} className="flex h-[54px] items-center gap-2 rounded-md bg-sky-700 px-5 font-black text-white"><Plus size={18}/> NOVO CLIENTE</button><button type="button" disabled={!selectedClient} onClick={()=>selectedClient&&edit(selectedClient)} className="flex h-[54px] items-center gap-2 rounded-md border border-slate-300 bg-white px-5 font-black disabled:opacity-50"><Pencil size={18}/> EDITAR</button><button type="button" disabled={!selected} onClick={()=>void remove()} className="flex h-[54px] items-center gap-2 rounded-md border border-rose-300 bg-rose-50 px-5 font-black text-rose-800 disabled:opacity-50"><Trash2 size={18}/> EXCLUIR</button><button type="button" onClick={()=>void load()} className="flex h-[54px] items-center gap-2 rounded-md border border-slate-300 bg-white px-5 font-black"><RefreshCw size={18}/> ATUALIZAR</button></div></header>
  {(msg||error)&&<div className={error?'rounded-md border border-rose-300 bg-rose-50 p-4 font-bold text-rose-800':'rounded-md border border-emerald-300 bg-emerald-50 p-4 font-bold text-emerald-800'}>{error||msg}</div>}
  <section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><Search size={20} className="text-sky-700"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar por código, razão social, CNPJ ou e-mail" className={input}/></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-base"><thead className="bg-slate-100"><tr className="h-[54px] text-left font-black"><th className="px-4">Código</th><th className="px-4">Cliente</th><th className="px-4">Documento</th><th className="px-4">E-mail</th><th className="px-4">Tipo</th><th className="px-4">Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} onClick={()=>setSelected(r.id)} className={'h-[54px] cursor-pointer border-t border-slate-200 '+(selected===r.id?'bg-sky-50':'hover:bg-slate-50')}><td className="px-4 font-black">{r.codigo??'—'}</td><td className="px-4 font-semibold">{r.nome}</td><td className="px-4">{r.documento??'—'}</td><td className="px-4">{r.email??'—'}</td><td className="px-4">{r.tipo_cliente??'PADRAO'}</td><td className="px-4 font-bold">{r.ativo?'ATIVO':'INATIVO'}</td></tr>)}</tbody></table></div>{!busy&&!filtered.length&&<p className="p-10 text-center font-bold text-slate-600">Nenhum cliente real encontrado.</p>}</section>
  {selected&&<section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-sky-700">VÍNCULO DE CÓDIGOS DE ENGENHARIA</p><h2 className="text-xl font-black">{selectedClient?.nome??'Cliente'}</h2></div><span className="rounded-md bg-slate-100 px-3 py-2 text-sm font-black">{mappings.filter(m=>m.cliente_id===selected).length} vínculo(s)</span></div><div className="grid gap-4 lg:grid-cols-[1.4fr_1fr_1fr_1fr_1fr_auto]"><EntityCodeLookup label="Produto interno" value={produto} records={productRecords} onChange={setProduto} onSelect={r=>setProduto(r.id)}/><label className="grid gap-2 text-sm font-black">CÓDIGO DO CLIENTE<input value={codigoCliente} onChange={e=>setCodigoCliente(e.target.value)} className={input}/></label><label className="grid gap-2 text-sm font-black">DIMENSÕES<input value={dimensoes} onChange={e=>setDimensoes(e.target.value)} className={input}/></label><label className="grid gap-2 text-sm font-black">CANAL<input value={canal} onChange={e=>setCanal(e.target.value)} className={input}/></label><label className="grid gap-2 text-sm font-black">MOLDE<input value={molde} onChange={e=>setMolde(e.target.value)} className={input}/></label><button type="button" onClick={()=>void addMapping()} className="mt-7 h-[54px] rounded-md bg-slate-900 px-4 font-black text-white">+ VINCULAR</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-base"><thead className="bg-slate-100"><tr className="h-[54px] text-left font-black"><th className="px-4">Nosso Cód. Interno</th><th className="px-4">Código do Cliente</th><th className="px-4">Dimensões</th><th className="px-4">Canal</th><th className="px-4">Molde</th><th className="px-4"></th></tr></thead><tbody>{mappings.filter(m=>m.cliente_id===selected).map(m=><tr key={m.id} className="h-[54px] border-t border-slate-200"><td className="px-4 font-black">{m.codigo_interno}</td><td className="px-4 font-semibold">{m.codigo_cliente}</td><td className="px-4">{m.dimensoes??'—'}</td><td className="px-4">{m.canal??'—'}</td><td className="px-4">{m.molde??'—'}</td><td className="px-4 text-right"><button type="button" onClick={()=>void delMapping(m.id)} className="text-rose-700"><Trash2 size={18}/></button></td></tr>)}</tbody></table></div></section>}
 </div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><section className="w-full max-w-4xl rounded-md bg-white p-6 shadow-2xl"><header className="flex items-center justify-between border-b border-slate-200 pb-4"><h2 className="text-xl font-black">{selected?'EDITAR CLIENTE':'NOVO CLIENTE'}</h2><button type="button" onClick={()=>setOpen(false)} className="rounded-md p-2 text-slate-700 hover:bg-slate-100"><X/></button></header><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-black">CÓDIGO<input className={input} value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/></label><label className="grid gap-2 text-sm font-black">RAZÃO SOCIAL / NOME<input className={input} value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label className="grid gap-2 text-sm font-black">CNPJ / DOCUMENTO<input className={input} value={form.documento} onChange={e=>setForm({...form,documento:e.target.value})}/></label><label className="grid gap-2 text-sm font-black">E-MAIL<input className={input} type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="grid gap-2 text-sm font-black">TELEFONE<input className={input} value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/></label><label className="grid gap-2 text-sm font-black">TIPO<input className={input} value={form.tipo_cliente} onChange={e=>setForm({...form,tipo_cliente:e.target.value})}/></label><label className="grid gap-2 text-sm font-black md:col-span-2">ENDEREÇO<input className={input} value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})}/></label><label className="grid gap-2 text-sm font-black">DESCONTO PADRÃO %<input className={input} type="number" min="0" max="100" step="0.01" value={form.desconto} onChange={e=>setForm({...form,desconto:e.target.value})}/></label><label className="flex h-[54px] items-center gap-3 self-end rounded-md border border-slate-300 px-3 text-base font-black"><input type="checkbox" checked={form.ativo} onChange={e=>setForm({...form,ativo:e.target.checked})} className="h-5 w-5"/> CLIENTE ATIVO</label></div><footer className="mt-6 flex justify-end border-t border-slate-200 pt-4"><button type="button" onClick={()=>void save()} disabled={busy} className="flex h-[54px] items-center gap-2 rounded-md bg-sky-700 px-6 font-black text-white disabled:opacity-50"><Check size={18}/> SALVAR CADASTRO</button></footer></section></div>}</main>
}