import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ArrowLeft, Printer, RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Order={id:string;numero:number;pedido_cliente:string|null;status:string;total:number;data_entrega_prometida:string|null;cliente:{nome:string}|null}
type Filter='todos'|'atrasado'|'producao'|'expedicao'|'nf_saida'
const brl=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)
const norm=(v:string)=>v.trim().toLowerCase()

function isOverdue(o:Order){if(!o.data_entrega_prometida)return false;const d=new Date(o.data_entrega_prometida);d.setHours(0,0,0,0);const t=new Date();t.setHours(0,0,0,0);return d<t&&!['faturado','cancelado'].includes(norm(o.status))}
function matches(o:Order,f:Filter){const s=norm(o.status);if(f==='atrasado')return isOverdue(o);if(f==='producao')return ['necessita_producao','em_producao','producao'].includes(s);if(f==='expedicao')return ['separado','expedicao','em_expedicao','expedido'].includes(s);if(f==='nf_saida')return ['faturado','nf_saida','nota_fiscal_saida','nota_emitida'].includes(s);return true}

export default function VendasStatusPedidos(){
 const [searchParams]=useSearchParams();const initialFilter=(searchParams.get('filtro') as Filter|null);const [rows,setRows]=useState<Order[]>([]);const [filter,setFilter]=useState<Filter>(initialFilter&&['todos','atrasado','producao','expedicao','nf_saida'].includes(initialFilter)?initialFilter:'todos');const [selected,setSelected]=useState<Record<string,boolean>>({});const [q,setQ]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data){setError(e.error?.message||'Empresa não identificada.');setBusy(false);return}const r=await supabase.from('erp_pedidos_venda').select('id,numero,pedido_cliente,status,total,data_entrega_prometida,cliente:erp_clientes(nome)').eq('empresa_id',String(e.data)).order('numero',{ascending:false}).limit(1000);if(r.error)setError(r.error.message);setRows((r.data??[]) as unknown as Order[]);setBusy(false)}
 useEffect(()=>{void load()},[])
 const visible=useMemo(()=>rows.filter(o=>matches(o,filter)&&(!q||String(o.numero).includes(q)||(o.cliente?.nome??'').toLowerCase().includes(q.toLowerCase())||(o.pedido_cliente??'').toLowerCase().includes(q.toLowerCase()))),[rows,filter,q])
 const print=()=>window.print()
 useEffect(()=>{const value=searchParams.get('filtro');if(value==='atrasados')setFilter('atrasado');else if(value==='producao')setFilter('producao');else if(value==='expedicao')setFilter('expedicao');else if(value==='nf_saida')setFilter('nf_saida')},[searchParams])
 const selectedRows=visible.filter(o=>selected[o.id])
 const cards:[Filter,string,string,string][]=[['todos','Todos','bg-slate-100','text-slate-800'],['atrasado','Atrasado','bg-red-100','text-red-800'],['producao','Produção','bg-orange-100','text-orange-900'],['expedicao','Expedição','bg-yellow-100','text-yellow-900'],['nf_saida','NF Saída','bg-blue-100','text-blue-800']]
 return <div className="min-h-screen bg-[#F4F7FE] text-slate-900">
  <header className="sticky top-0 z-20 border-b bg-white print:hidden"><div className="min-h-[70px] px-5 lg:px-8 flex items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#2D8DB8]">ERP Industrial • Vendas</p><h1 className="text-xl font-medium text-[#123B50]">Status dos Pedidos</h1></div><div className="flex gap-2"><button onClick={()=>location.assign('/vendas')} className="h-9 px-3 border rounded-md text-xs flex items-center gap-2"><ArrowLeft size={15}/> Voltar</button><button onClick={()=>void load()} disabled={busy} className="h-9 px-3 border rounded-md text-xs"><RefreshCw size={15} className={busy?'animate-spin':''}/></button><button onClick={print} className="h-9 px-3 rounded-md bg-[#123B50] text-white text-xs flex items-center gap-2"><Printer size={15}/> Imprimir relatório</button></div></div></header>
  <main className="p-5 lg:p-8 max-w-[1700px] mx-auto">
   <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5 mb-5 print:hidden">{cards.map(([key,label,bg,text])=><button key={key} onClick={()=>setFilter(key)} className={`rounded-lg border p-4 text-left transition ${filter===key?'ring-2 ring-[#2D8DB8]':''} ${bg}`}><div className={`text-sm font-medium ${text}`}>{label}</div><div className={`mt-1 text-2xl font-medium ${text}`}>{rows.filter(o=>matches(o,key)).length}</div></button>)}</section>
   <section className="bg-white border rounded-lg shadow-sm p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-medium text-[#123B50]">{cards.find(c=>c[0]===filter)?.[1]??'Todos os pedidos'}</h2><p className="text-xs text-slate-500 mt-1">Selecione pedidos para compor o relatório macro.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nº, cliente ou pedido cliente" className="h-10 w-72 border rounded-md px-3 text-sm print:hidden"/></div>
    {error&&<div className="mt-4 p-3 rounded bg-red-50 text-red-800 text-sm">{error}</div>}
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px]"><thead><tr className="h-[54px] bg-slate-100 text-left text-sm"><th className="w-12"><input type="checkbox" checked={visible.length>0&&visible.every(o=>selected[o.id])} onChange={e=>setSelected(v=>{const n={...v};visible.forEach(o=>n[o.id]=e.target.checked);return n})}/></th><th>Nº</th><th>Pedido Cliente</th><th>Cliente</th><th>Entrega</th><th>Valor</th><th>Status</th><th className="print:hidden">Abrir</th></tr></thead><tbody>{visible.map(o=>{const overdue=isOverdue(o);return <tr key={o.id} className="h-[54px] border-t"><td><input type="checkbox" checked={!!selected[o.id]} onChange={e=>setSelected(v=>({...v,[o.id]:e.target.checked}))}/></td><td className="font-medium">{String(o.numero).padStart(6,'0')}</td><td>{o.pedido_cliente||'—'}</td><td>{o.cliente?.nome||'—'}</td><td className={overdue?'font-medium text-red-700':''}>{o.data_entrega_prometida||'—'}</td><td>{brl(Number(o.total||0))}</td><td><span className={`inline-flex rounded-full border px-3 py-1 text-xs ${overdue?'bg-red-100 text-red-800 border-red-200':filter==='producao'?'bg-orange-100 text-orange-900 border-orange-200':filter==='expedicao'?'bg-yellow-100 text-yellow-900 border-yellow-200':filter==='nf_saida'?'bg-blue-100 text-blue-800 border-blue-200':'bg-slate-100 text-slate-700 border-slate-200'}`}>{o.status}</span></td><td className="print:hidden"><button onClick={()=>location.assign('/vendas/pedido/'+o.id)} className="text-[#2D8DB8] text-sm">Abrir status</button></td></tr>)}{!visible.length&&<tr><td colSpan={8} className="py-12 text-center text-slate-500">Nenhum pedido real encontrado neste status.</td></tr>}</tbody></table></div>
    <div className="mt-4 border-t pt-4 flex justify-between text-sm"><span>Pedidos exibidos: {visible.length}</span><span>Selecionados: {selectedRows.length}</span></div>
   </section>
  </main>
  <div className="hidden print:block p-8"><h1 className="text-2xl font-medium">Relatório Macro — Status de Pedidos</h1><p className="mt-2">Pedidos selecionados: {selectedRows.length}</p></div>
 </div>
}
