import { useEffect,useMemo,useState } from 'react'
import VendasLayout from './VendasLayout'
import { supabase } from '../lib/supabaseClient'
type O={id:string;numero:number;status:string;total:number;data_entrada:string|null;cliente_id:string}
type C={id:string;nome:string;tipo_cliente:string|null}
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
export default function VendasCentral(){
 const [orders,setOrders]=useState<O[]>([]),[clients,setClients]=useState<C[]>([]),[error,setError]=useState('')
 const load=async()=>{const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.');const id=String(e.data);const [o,c]=await Promise.all([supabase.from('erp_pedidos_venda').select('id,numero,status,total,data_entrada,cliente_id').eq('empresa_id',id).order('numero',{ascending:false}).limit(2000),supabase.from('erp_clientes').select('id,nome,tipo_cliente').eq('empresa_id',id).eq('ativo',true).limit(5000)]);if(o.error)throw o.error;if(c.error)throw c.error;setOrders((o.data??[]) as O[]);setClients((c.data??[]) as C[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar dashboard.'))},[])
 const pending=orders.filter(o=>!['faturado','cancelado'].includes(o.status.toLowerCase())).length
 const month=useMemo(()=>{const now=new Date();return orders.filter(o=>{const d=new Date(o.data_entrada??'');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,o)=>s+Number(o.total||0),0)},[orders])
 const profile=useMemo(()=>{const m=new Map<string,number>();for(const o of orders){const c=clients.find(x=>x.id===o.cliente_id);const k=c?.tipo_cliente||'Não informado';m.set(k,(m.get(k)||0)+Number(o.total||0))}return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[orders,clients])
 const recent=orders.slice(0,12)
 return <VendasLayout title="Dashboard Comercial" subtitle="Carteira real do ERP" onRefresh={()=>void load()}><div className="space-y-2 text-[11px]">{error&&<div className="border border-red-200 bg-red-50 p-2 text-red-800">{error}</div>}<div className="grid grid-cols-4 gap-2"><K label="Pedidos pendentes" v={pending}/><K label="Faturamento do mês" v={brl(month)}/><K label="Pedidos totais" v={orders.length}/><K label="Meta" v="Consultar metas"/></div><div className="grid grid-cols-2 gap-2"><section className="border border-slate-300 bg-white p-2"><b>FATURAMENTO POR PERFIL DE CLIENTE</b><div className="mt-2 space-y-1">{profile.map(([k,v])=><div key={k}><div className="flex justify-between"><span>{k}</span><b>{brl(v)}</b></div><div className="h-2 bg-slate-100"><div className="h-2 bg-[#2D8DB8]" style={{width:`${Math.min((v/Math.max(profile[0]?.[1]??1,1))*100,100)}%`}}/></div></div>)}{!profile.length&&<p className="p-4 text-slate-500">Sem dados reais.</p>}</section><section className="border border-slate-300 bg-white p-2"><b>PEDIDOS RECENTES</b><table className="mt-2 w-full border-collapse"><thead><tr className="bg-[#DEE2E6] text-left text-[9px] uppercase"><th className="p-1">Pedido</th><th>Cliente</th><th>Status</th><th>Total</th></tr></thead><tbody>{recent.map(o=><tr key={o.id} className="border-t"><td className="p-1">{String(o.numero).padStart(6,'0')}</td><td>{clients.find(c=>c.id===o.cliente_id)?.nome??'—'}</td><td>{o.status}</td><td>{brl(Number(o.total))}</td></tr>)}</tbody></table></section></div></div></VendasLayout>
}
function K({label,v}:{label:string;v:string|number}){return <div className="border border-slate-300 bg-white p-2"><div className="text-[9px] uppercase text-slate-500">{label}</div><div className="mt-1 text-[16px] font-semibold text-[#123B50]">{v}</div></div>}
