import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Copy, Search, ShoppingCart, Send, X } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
import EntityCodeLookup from "../components/industrial/EntityCodeLookup";

type Produto={id:string;codigo:string;nome:string;descricao:string|null;preco_venda:number|null;estoque_atual:number|null;unidade:string;foto_url:string|null;catalogo_disponivel:boolean};
type Item={produto_id:string;codigo:string;descricao:string;preco:number;quantidade:number};

const brl=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
export default function VendasCatalogoDigital(){
 const [empresa,setEmpresa]=useState(""); const [produtos,setProdutos]=useState<Produto[]>([]); const [selected,setSelected]=useState<Record<string,boolean>>({}); const [quantidades,setQuantidades]=useState<Record<string,number>>({}); const [filtro,setFiltro]=useState(""); const [busy,setBusy]=useState(true); const [error,setError]=useState(""); const [cliente,setCliente]=useState("");
 useEffect(()=>{void (async()=>{setBusy(true);const e=await supabase.rpc("erp_current_empresa_id");if(e.error||!e.data){setError(e.error?.message||"Empresa não identificada.");setBusy(false);return}const id=String(e.data);setEmpresa(id);const r=await supabase.from("erp_produtos").select("id,codigo,nome,descricao,preco_venda,estoque_atual,unidade,foto_url,catalogo_disponivel").eq("empresa_id",id).eq("ativo",true).eq("catalogo_disponivel",true).order("codigo");if(r.error)setError(r.error.message);setProdutos((r.data??[]) as Produto[]);setBusy(false)})()},[]);
 const rows=useMemo(()=>produtos.filter(p=>{const q=filtro.toLowerCase();return !q||p.codigo.toLowerCase().includes(q)||p.nome.toLowerCase().includes(q)||(p.descricao??"").toLowerCase().includes(q)}),[produtos,filtro]);
 const cart=rows.filter(p=>selected[p.id]).map(p=>({produto_id:p.id,codigo:p.codigo,descricao:p.nome,preco:Number(p.preco_venda??0),quantidade:Math.max(1,quantidades[p.id]??1)}));
 const total=cart.reduce((s,x)=>s+x.preco*x.quantidade,0);
 const link=window.location.origin+"/vendas/catalogo-digital";
 const copy=async()=>{await navigator.clipboard.writeText(link)};
 const send=async()=>{const text="Catálogo: "+link+"\n\nItens selecionados:\n"+cart.map(x=>x.codigo+" - "+x.descricao+" x "+x.quantidade).join("\n");if(navigator.share){await navigator.share({title:"Solicitação de cotação",text}).catch(()=>undefined)}else{await navigator.clipboard.writeText(text)}};
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 bg-white border-b border-slate-200"><div className="min-h-[76px] px-4 lg:px-6 flex items-center justify-between gap-4"><div><div className="text-xs font-black tracking-widest text-blue-700">ERP INDUSTRIAL • VENDAS</div><h1 className="text-xl font-black">CATÁLOGO DIGITAL DE PRODUTOS</h1></div><div className="flex gap-2"><button onClick={()=>location.assign("/vendas/catalogo-digital/gestao")} className="min-h-[46px] rounded-md border border-slate-300 px-4 font-black flex items-center gap-2"><ArrowLeft size={17}/> VOLTAR</button><button onClick={()=>void copy()} className="min-h-[46px] rounded-md border border-slate-300 px-4 font-black flex items-center gap-2"><Copy size={17}/> COPIAR LINK</button><button onClick={send} disabled={!cart.length} className="min-h-[46px] rounded-md bg-blue-700 text-white px-4 font-black flex items-center gap-2 disabled:opacity-50"><Send size={17}/> ENVIAR PEDIDO</button></div></div></header>
 <main className="p-4 lg:p-6 max-w-[1600px] mx-auto"><div className="grid lg:grid-cols-[260px_1fr] gap-5"><aside className="bg-white border border-slate-200 rounded-md p-4 shadow-sm"><h2 className="font-black text-lg">ACESSO DO CLIENTE</h2><div className="mt-4 space-y-2"><button type="button" onClick={()=>document.getElementById("catalog-cart")?.scrollIntoView({behavior:"smooth"})} className="w-full min-h-[54px] text-left rounded-md bg-blue-50 text-blue-900 font-bold px-3">Ver Meu Carrinho ({cart.length})</button><button type="button" onClick={()=>location.href="/comercial?view=carteira"} className="w-full min-h-[54px] text-left rounded-md border px-3 font-bold">Meus Pedidos</button><button type="button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="w-full min-h-[54px] text-left rounded-md border px-3 font-bold">Catálogo Ativo</button></div><label className="mt-5 grid gap-1 text-base font-bold">Cliente / vínculo<input value={cliente} onChange={e=>setCliente(e.target.value)} className="min-h-[46px] border border-slate-300 rounded-md px-3 text-slate-900" placeholder="Opcional"/></label><div className="mt-5 rounded-md bg-slate-100 p-3"><div className="text-sm font-bold">Total selecionado</div><div className="text-2xl font-black mt-1">{brl(total)}</div></div></aside>
 <section id="catalog-cart" className="bg-white border border-slate-200 rounded-md shadow-sm p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">PRODUTOS DISPONÍVEIS E SOLICITAÇÃO DE COTAÇÃO</h2><p className="text-base text-slate-700 mt-1">Fotos, descrição e preço vêm do cadastro mestre de produtos.</p></div><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-500" size={18}/><input value={filtro} onChange={e=>setFiltro(e.target.value)} className="min-h-[46px] w-72 border rounded-md pl-10 pr-3 text-slate-900" placeholder="Filtrar produto"/></div></div>
 {error&&<div className="mt-4 p-3 bg-rose-100 text-rose-900 rounded-md font-bold">{error}</div>}
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="h-[54px] bg-slate-100 text-left text-base font-bold"><th className="w-16">Sel.</th><th>Cód Item</th><th>Descrição</th><th>Unid.</th><th>Preço Base</th><th>Qtd.</th><th>Imagem</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} className="h-[54px] border-t border-slate-200"><td><input type="checkbox" className="h-5 w-5" checked={!!selected[p.id]} onChange={e=>setSelected(v=>({...v,[p.id]:e.target.checked}))}/></td><td className="font-black">{p.codigo}</td><td>{p.nome}</td><td>{p.unidade}</td><td className="font-bold">{brl(Number(p.preco_venda??0))}</td><td><input type="number" min="1" className="h-[42px] w-24 border rounded-md px-2 text-slate-900" value={quantidades[p.id]??1} onChange={e=>setQuantidades(v=>({...v,[p.id]:Number(e.target.value)||1}))}/></td><td>{p.foto_url?<img src={p.foto_url} alt={p.nome} className="h-10 w-14 object-cover rounded border"/>:<span className="text-slate-500">Sem foto</span>}</td></tr>)}{!rows.length&&!busy&&<tr><td colSpan={7} className="py-12 text-center text-slate-600 font-semibold">Nenhum produto disponível no catálogo.</td></tr>}</tbody></table></div></section></div></main></div>
}
