import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CreditCard, RefreshCw, Search, ShoppingCart, Wallet } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Product={id:string;codigo:string;codigo_barras:string|null;nome:string;preco_venda:number;unidade:string;categoria:string|null;estoque_atual:number;permite_estoque_negativo:boolean}
type CartItem=Product&{quantidade:number}
type Box={id:string;codigo:string;descricao:string}\ntype Customer={id:string;codigo:string|null;nome:string;documento:string|null}

const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function VendasPDV(){
 const [products,setProducts]=useState<Product[]>([]),[boxes,setBoxes]=useState<Box[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[cart,setCart]=useState<CartItem[]>([])
 const [box,setBox]=useState(''),[query,setQuery]=useState(''),[payment,setPayment]=useState('DINHEIRO'),[discount,setDiscount]=useState('0'),[customerId,setCustomerId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setError('');const company=await supabase.rpc('erp_current_empresa_id');if(company.error||!company.data){setError(company.error?.message||'Empresa não identificada.');setBusy(false);return}
  const [p,b,cu]=await Promise.all([supabase.from('erp_produtos').select('id,codigo,codigo_barras,nome,preco_venda,unidade,categoria,estoque_atual,permite_estoque_negativo').eq('empresa_id',String(company.data)).eq('ativo',true).order('nome').limit(2000),supabase.from('erp_caixas').select('id,codigo,descricao').eq('empresa_id',String(company.data)).eq('ativo',true).order('codigo'),supabase.from('erp_clientes').select('id,codigo,nome,documento').eq('empresa_id',String(company.data)).eq('ativo',true).order('nome').limit(2000)])
  if(p.error) throw p.error;if(b.error) throw b.error;if(cu.error) throw cu.error;setProducts((p.data||[]) as Product[]);setBoxes((b.data||[]) as Box[]);setCustomers((cu.data||[]) as Customer[]);if(!box&&b.data?.[0])setBox(b.data[0].id);setBusy(false)}
 useEffect(()=>{void load()},[])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return products.filter(p=>!q||p.codigo.toLowerCase().includes(q)||p.nome.toLowerCase().includes(q)||(p.codigo_barras||'').includes(q))},[products,query])
 const subtotal=cart.reduce((s,i)=>s+i.quantidade*Number(i.preco_venda||0),0),disc=Math.min(subtotal,Math.max(0,Number(discount)||0)),total=subtotal-disc
 const add=(p:Product)=>{if(!p.permite_estoque_negativo&&p.estoque_atual<=0){setError(`Produto ${p.codigo} sem estoque disponível.`);return}setError('');setCart(c=>{const found=c.find(i=>i.id===p.id);return found?c.map(i=>i.id===p.id?{...i,quantidade:i.quantidade+1}:i):[...c,{...p,quantidade:1}]})}
 const finish=async()=>{if(!box){setError('Selecione o caixa operacional.');return}if(!cart.length){setError('Carrinho vazio.');return}setBusy(true);setError('');setMessage('')
  try{const company=await supabase.rpc('erp_current_empresa_id');if(company.error||!company.data)throw company.error||new Error('Empresa não identificada.')
   const u=await supabase.auth.getUser();const movimento=await supabase.from('erp_caixas_movimentos').insert({empresa_id:company.data,caixa_id:box,operador_id:u.data.user?.id||null,cliente_id:customerId||null,subtotal,desconto:disc,total,forma_pagamento:payment,status:'FINALIZADA'}).select('id,numero').single();if(movimento.error)throw movimento.error
   const itens=await supabase.from('erp_caixas_movimentos_itens').insert(cart.map(i=>({empresa_id:company.data,movimento_id:movimento.data.id,produto_id:i.id,descricao:i.nome,quantidade:i.quantidade,valor_unitario:i.preco_venda,desconto:0,total:i.quantidade*i.preco_venda})));if(itens.error)throw itens.error
   setMessage('Venda PDV #'+movimento.data.numero+' finalizada.');setCart([]);setDiscount('')
  }catch(e){setError(e instanceof Error?e.message:'Não foi possível finalizar o PDV.')}finally{setBusy(false)}}
 return <div className="min-h-screen bg-[#F4F7FE] text-slate-900"><header className="sticky top-0 z-20 border-b bg-white"><div className="flex min-h-[70px] items-center justify-between px-5 lg:px-8"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#2D8DB8]">POS / PDV • Vendas</p><h1 className="text-xl font-medium text-[#123B50]">Caixa Operacional</h1></div><div className="flex items-center gap-2"><select value={box} onChange={e=>setBox(e.target.value)} className="h-9 rounded-md border px-3 text-sm">{boxes.map(b=><option key={b.id} value={b.id}>{b.codigo} — {b.descricao}</option>)}</select><button onClick={()=>location.assign('/vendas')} className="flex h-9 items-center gap-2 rounded-md border px-3 text-xs"><ArrowLeft size={15}/>Vendas</button></div></div></header>
 <main className="grid gap-5 p-5 lg:grid-cols-[1fr_440px] lg:p-8"><section className="rounded-lg border bg-white p-5"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3.5" size={16}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código de barras ou nome do artigo..." className="h-11 w-full rounded-md border pl-9 pr-3"/></div><button onClick={()=>void load()} className="h-11 rounded-md border px-4"><RefreshCw size={16}/></button></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">Todos</span>{Array.from(new Set(products.map(p=>p.categoria).filter(Boolean))).map(c=><span key={c} className="rounded-full border px-3 py-1 text-xs">{c}</span>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visible.map(p=><button key={p.id} onClick={()=>add(p)} className="rounded-lg border p-4 text-left transition hover:border-[#2D8DB8]"><div className="text-[10px] text-slate-500">{p.codigo}</div><div className="mt-1 font-medium text-[#123B50]">{p.nome}</div><div className="mt-3 flex justify-between"><span className="text-xs text-slate-500">Estoque {p.estoque_atual}</span><strong>{money(Number(p.preco_venda))}</strong></div></button>)}</div></section>
 <section className="rounded-lg border bg-white p-5"><div className="flex items-center gap-2"><ShoppingCart size={19}/><h2 className="font-medium text-[#123B50]">Carrinho</h2></div><div className="mt-4 max-h-[420px] overflow-auto">{cart.map(i=><div key={i.id} className="flex items-center gap-3 border-b py-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{i.nome}</div><div className="text-xs text-slate-500">{money(i.preco_venda)} / {i.unidade}</div></div><input type="number" min="1" value={i.quantidade} onChange={e=>setCart(c=>c.map(x=>x.id===i.id?{...x,quantidade:Math.max(1,Number(e.target.value))}:x))} className="w-16 rounded border p-2 text-center"/><strong>{money(i.quantidade*i.preco_venda)}</strong></div>)}{!cart.length&&<div className="py-16 text-center text-sm text-slate-500">Nenhum item no carrinho.</div>}</div><div className="mt-4 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="flex justify-between items-center"><span>Desconto</span><input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} className="w-28 rounded border p-2 text-right"/></div><div className="flex justify-between text-xl font-semibold text-[#123B50]"><span>Total</span><strong>{money(total)}</strong></div></div><div className="mt-4"><label className="mb-1 block text-xs font-medium text-slate-600">Cliente (opcional)</label><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="h-9 w-full rounded border px-2 text-sm"><option value="">Consumidor não identificado</option>{customers.map(c=><option key={c.id} value={c.id}>{c.codigo?`${c.codigo} — `:''}{c.nome}{c.documento?` • ${c.documento}`:''}</option>)}</select></div><div className="mt-4 grid grid-cols-3 gap-2">{[['DINHEIRO',Wallet],['CARTAO',CreditCard],['PIX',ShoppingCart]].map(([name,Icon])=><button key={String(name)} onClick={()=>setPayment(String(name))} className={payment===name?'rounded-md bg-[#123B50] p-3 text-xs text-white':'rounded-md border p-3 text-xs'}><Icon size={15} className="mx-auto mb-1"/>{String(name)}</button>)}</div>{error&&<div className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{message&&<div className="mt-4 rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}<button disabled={busy||!cart.length} onClick={()=>void finish()} className="mt-4 h-12 w-full rounded-md bg-[#3A9D78] text-sm font-medium text-white disabled:opacity-50">FINALIZAR VENDA</button></section></main></div>
}