import { useEffect,useMemo,useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import VendasLayout from './VendasLayout'
type O={id:string;numero:number;pedido_cliente:string|null;status:string;total:number;data_entrega_prometida:string|null;cliente:{nome:string}|null}
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
export default function VendasStatusPedidos(){
 const [rows,setRows]=useState<O[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState('todos'),[error,setError]=useState('')
 const load=async()=>{const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data)throw e.error??new Error('Empresa não identificada.');const r=await supabase.from('erp_pedidos_venda').select('id,numero,pedido_cliente,status,total,data_entrega_prometida,cliente:erp_clientes(nome)').eq('empresa_id',String(e.data)).order('numero',{ascending:false}).limit(2000);if(r.error)throw r.error;setRows((r.data??[]) as unknown as O[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar pedidos.'))},[])
 const visible=useMemo(()=>rows.filter(o=>{const s=o.status.toLowerCase();const m=!q||String(o.numero).includes(q)||String(o.cliente?.nome??'').toLowerCase().includes(q.toLowerCase());const f=filter==='todos'||(filter==='producao'&&s.includes('produ'))||(filter==='expedicao'&&s.includes('expedi'))||(filter==='faturamento'&&s.includes('fatur'))||(filter==='atrasado'&&!!o.data_entrega_prometida&&new Date(o.data_entrega_prometida)<new Date());return m&&f}),[rows,q,filter])
 return <VendasLayout title="Pedidos Pendentes / Workflow Geral" subtitle="Comercial → Engenharia → PCP → Produção → Almoxarifado → Faturamento" onRefresh={()=>void load()}><div className="space-y-2 text-[11px]">{error&&<div className="border border-red-200 bg-red-50 p-2 text-red-800">{error}</div>}<div className="flex flex-wrap gap-1">{['todos','atrasado','producao','expedicao','faturamento'].map(x=><button key={x} type="button" onClick={()=>setFilter(x)} className={`h-7 border px-2 text-[10px] ${filter===x?'bg-[#3A9D78] text-white':''}`}>{x.toUpperCase()}</button>)}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nº ou cliente" className="ml-auto h-7 w-56 border px-2 text-[11px]"/></div><section className="overflow-x-auto border border-slate-300 bg-white"><table className="w-full min-w-[1150px] border-collapse"><thead><tr className="bg-[#DEE2E6] text-left text-[9px] uppercase"><th className="p-1.5">Pedido</th><th>Cliente</th><th>Entrega</th><th>Valor</th><th>Status</th><th>Comercial</th><th>Engenharia</th><th>PCP</th><th>Produção</th><th>Almoxarifado</th><th>Faturamento</th></tr></thead><tbody>{visible.map(o=><tr key={o.id} className="border-t"><td className="p-1.5 font-semibold">{String(o.numero).padStart(6,'0')}</td><td>{o.cliente?.nome??'—'}</td><td>{o.data_entrega_prometida??'—'}</td><td>{brl(Number(o.total))}</td><td>{o.status}</td><td>—</td><td>—</td><td>{o.status.toLowerCase().includes('produção')?'Aguardando':'—'}</td><td>—</td><td>—</td><td>—</td></tr>)}{!visible.length&&<tr><td colSpan={11} className="p-8 text-center text-slate-500">Nenhum pedido real encontrado.</td></tr>}</tbody></table></section></div></VendasLayout>
}