import { useEffect,useState } from 'react'
import { ArrowLeft, RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'

type Item={id:string;produto_id:string;descricao:string;quantidade:number;valor_unitario:number;total:number}
type OP={numero_op:string;status:string;quantidade:number;quantidade_planejada:number;quantidade_produzida:number;data_prevista:string|null}
type Exp={numero:number;status:string;transportadora:string|null;rastreio:string|null;data_expedicao:string|null}
type Fiscal={tipo:string;status:string;quantidade_solicitada:number;quantidade_liberada:number;quantidade_pendente:number}
export default function VendasPedidoStatus({id}:{id?:string}){
 const [pedido,setPedido]=useState<{numero:number;status:string;pedido_cliente:string|null;total:number;data_entrega_prometida:string|null;cliente:{nome:string}|null}|null>(null);const [items,setItems]=useState<Item[]>([]);const [ops,setOps]=useState<OP[]>([]);const [exps,setExps]=useState<Exp[]>([]);const [fisc,setFisc]=useState<Fiscal[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const load=async()=>{if(!id)return;setBusy(true);setError('');const [p,i,o,e,f]=await Promise.all([supabase.from('erp_pedidos_venda').select('numero,status,pedido_cliente,total,data_entrega_prometida,cliente:erp_clientes(nome)').eq('id',id).maybeSingle(),supabase.from('erp_pedidos_venda_itens').select('id,produto_id,descricao,quantidade,valor_unitario,total').eq('pedido_id',id).order('id'),supabase.from('erp_ordens_producao').select('numero_op,status,quantidade,quantidade_planejada,quantidade_produzida,data_prevista').eq('pedido_venda_id',id),supabase.from('erp_expedicoes').select('numero,status,transportadora,rastreio,data_expedicao').eq('pedido_venda_id',id),supabase.from('erp_liberacoes_fiscais').select('tipo,status,quantidade_solicitada,quantidade_liberada,quantidade_pendente').eq('pedido_venda_id',id)]);if(p.error) setError(p.error.message);setPedido((p.data??null) as typeof pedido);setItems((i.data??[]) as Item[]);setOps((o.data??[]) as OP[]);setExps((e.data??[]) as Exp[]);setFisc((f.data??[]) as Fiscal[]);setBusy(false)}
 useEffect(()=>{void load()},[id])
 if(!id)return <div className="p-8">Pedido não informado.</div>
 return <div className="min-h-screen bg-[#F4F7FE] text-slate-900"><header className="sticky top-0 bg-white border-b z-20"><div className="min-h-[70px] px-5 lg:px-8 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#2D8DB8]">ERP Industrial • Vendas</p><h1 className="text-xl font-medium text-[#123B50]">Acompanhamento do Pedido</h1></div><div className="flex gap-2"><button onClick={()=>location.assign('/vendas/status')} className="h-9 px-3 border rounded-md text-xs flex gap-2 items-center"><ArrowLeft size={15}/> Status Pedido</button><button onClick={()=>void load()} className="h-9 px-3 border rounded-md"><RefreshCw size={15} className={busy?'animate-spin':''}/></button></div></div></header><main className="p-5 lg:p-8 max-w-[1500px] mx-auto">{error&&<div className="mb-4 p-3 bg-red-50 text-red-800 rounded">{error}</div>}{pedido&&<><section className="bg-white border rounded-lg p-5 shadow-sm"><div className="grid md:grid-cols-5 gap-4"><div><div className="text-xs text-slate-500">Pedido</div><div className="font-medium">PV-{String(pedido.numero).padStart(6,'0')}</div></div><div><div className="text-xs text-slate-500">Cliente</div><div>{pedido.cliente?.nome||'—'}</div></div><div><div className="text-xs text-slate-500">Pedido cliente</div><div>{pedido.pedido_cliente||'—'}</div></div><div><div className="text-xs text-slate-500">Entrega</div><div>{pedido.data_entrega_prometida||'—'}</div></div><div><div className="text-xs text-slate-500">Status</div><div className="inline-flex mt-1 rounded-full bg-slate-100 px-3 py-1 text-sm">{pedido.status}</div></div></div></section><section className="mt-5 bg-white border rounded-lg p-5"><h2 className="font-medium text-[#123B50]">Itens do pedido</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px]"><thead><tr className="h-[50px] bg-slate-100 text-left text-sm"><th>Descrição</th><th>Quantidade</th><th>Valor unitário</th><th>Total</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="h-[50px] border-t"><td>{i.descricao}</td><td>{i.quantidade}</td><td>{Number(i.valor_unitario).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{Number(i.total).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td></tr>)}</tbody></table></div></section><section className="mt-5 grid lg:grid-cols-3 gap-5"><StatusBlock title="Produção" rows={ops.map(x=>`OP ${x.numero_op} • ${x.status} • ${x.quantidade_produzida??0}/${x.quantidade_planejada??x.quantidade}`)} empty="Nenhuma OP vinculada a este pedido."/><StatusBlock title="Expedição" rows={exps.map(x=>`Expedição ${x.numero} • ${x.status}${x.transportadora?' • '+x.transportadora:''}`)} empty="Nenhuma expedição vinculada."/><StatusBlock title="NF / Saída" rows={fisc.map(x=>`${x.tipo} • ${x.status} • pendente ${x.quantidade_pendente??0}`)} empty="Nenhuma liberação fiscal vinculada."/></section></>}</main></div>
}
function StatusBlock({title,rows,empty}:{title:string;rows:string[];empty:string}){return <div className="bg-white border rounded-lg p-5 shadow-sm"><h2 className="font-medium text-[#123B50]">{title}</h2><div className="mt-4 space-y-2">{rows.length?rows.map((r,i)=><div key={i} className="rounded border bg-slate-50 p-3 text-sm">{r}</div>):<p className="text-sm text-slate-500">{empty}</p>}</div></div>}
