import { LockKeyhole, ShieldCheck, Smartphone, Zap, Factory } from 'lucide-react'
const items=[
 ['RLS + PostgreSQL',LockKeyhole,'Dados isolados por empresa com Row Level Security diretamente no banco.'],
 ['Anti-conflito transacional',ShieldCheck,'Agenda e programação respeitam restrições no banco para impedir sobreposição quando a regra estiver configurada.'],
 ['Vercel + Supabase',Zap,'Frontend distribuído e Edge Functions para autenticação e integrações server-side.'],
 ['Experiência responsiva',Smartphone,'Interface adaptada para desktop, tablet e celular, com a mesma operação.'],
 ['PCP + SGQ',Factory,'Lote, produção, refugo, RPNC, CAPA e rastreabilidade conectados.'],
] as const
export default function InfrastructureTrust(){return <section className="infrastructure-trust" style={{padding:'64px 20px',borderRadius:28,background:'linear-gradient(135deg,#071f22,#0d3f40)',color:'#fff',overflow:'hidden',position:'relative'}}><div style={{position:'absolute',inset:0,background:'url(/images/sgq/sgq-erp-dashboard.png) center/cover no-repeat',opacity:.12}}/><div style={{position:'relative',zIndex:1,maxWidth:1240,margin:'0 auto'}}><div className="infrastructure-trust-head"><span>INFRAESTRUTURA PROFISSIONAL</span><h2>Segurança e tecnologia que trabalham por trás da operação.</h2><p>Não é apenas aparência: o sistema foi estruturado para separar empresas, controlar transações e preservar rastreabilidade.</p></div><div className="infrastructure-trust-grid" style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(0,1fr))',gap:14,marginTop:28}}>{items.map(([badge,Icon,text])=><article key={badge} style={{padding:20,borderRadius:20,border:'1px solid rgba(255,255,255,.14)',background:'rgba(255,255,255,.08)',backdropFilter:'blur(12px)'}}><Icon size={22}/><small style={{display:'block',marginTop:10,fontWeight:900,letterSpacing:'.08em'}}>{badge}</small><p style={{color:'rgba(255,255,255,.72)',lineHeight:1.6}}>{text}</p></article>)}</div></div></section>}
