import { Activity, Gauge, Package, Wrench } from 'lucide-react'
import { demoInjection, demoMoldes, demoOee, demoProductionQueue, demoSetups, demoTools } from '../data/demoData'
import DashboardQuickActions from './DashboardQuickActions'
export default function UnifiedTabletDashboard(){
 const cycleDelta=demoInjection.map(item=>({...item,delta:((item.cicloRealSec-item.cicloTeoricoSec)/item.cicloTeoricoSec)*100}))
 return <div className="erp-tablet-dashboard">
  <section className="erp-production-hero"><div><span>CHÃO DE FÁBRICA • VISÃO OPERACIONAL</span><h1>Controle de Produção</h1><p>Injeção plástica e prensados com foco em ciclo, perdas, ferramentas, setup e sequenciamento.</p></div><div className="erp-oee-ring"><Gauge size={24}/><strong>{demoOee.oee.toFixed(1)}%</strong><small>OEE demonstrativo</small></div></section>
  <section className="erp-metric-grid"><article><Activity/><span>Disponibilidade</span><strong>{demoOee.disponibilidade}%</strong></article><article><Activity/><span>Performance</span><strong>{demoOee.performance}%</strong></article><article><Package/><span>Qualidade</span><strong>{demoOee.qualidade}%</strong></article><article><Wrench/><span>Setups em execução</span><strong>{demoSetups.filter(s=>s.status==='EM_EXECUCAO').length}</strong></article></section>
  <DashboardQuickActions/>
  <section className="erp-dashboard-grid"><article className="erp-panel"><header><div><span>MOLDES DE INJEÇÃO</span><h2>Cavidades e vida útil</h2></div></header><div className="erp-data-table"><table><thead><tr><th>Molde</th><th>Cavidades</th><th>Ciclos</th><th>Vida útil</th></tr></thead><tbody>{demoMoldes.map(m=><tr key={m.id}><td><strong>{m.codigo}</strong><small>{m.descricao}</small></td><td>{m.cavidadesAtivas}/{m.cavidadesTotais}</td><td>{m.ciclosAtuais.toLocaleString('pt-BR')}</td><td>{m.percentualVidaUtil.toFixed(1)}%</td></tr>)}</tbody></table></div></article>
  <article className="erp-panel"><header><div><span>FERRAMENTAS DE PRENSADOS</span><h2>Golpes até afiação</h2></div></header><div className="erp-data-table"><table><thead><tr><th>Ferramenta</th><th>Prensa</th><th>Golpes</th><th>Vida útil</th></tr></thead><tbody>{demoTools.map(t=><tr key={t.codigo}><td>{t.codigo}</td><td>{t.prensa}</td><td>{t.golpesAtuais.toLocaleString('pt-BR')}</td><td>{t.percentualVidaUtil.toFixed(1)}%</td></tr>)}</tbody></table></div></article></section>
  <section className="erp-dashboard-grid"><article className="erp-panel"><header><div><span>SETUP</span><h2>Troca de molde + canhão + cor</h2></div></header><div className="erp-setup-grid">{demoSetups.map(s=><div key={s.id} className="erp-setup-card"><strong>{s.maquina}</strong><span>{s.moldeOuEstampo}</span><b>{s.setupTotalMin} min</b><small>Molde {s.trocaMoldeMin} • Canhão {s.aquecimentoCanhaoMin} • Cor {s.trocaCorMin}</small></div>)}</div></article>
  <article className="erp-panel"><header><div><span>CICLO REAL × TEÓRICO</span><h2>Perdas de performance</h2></div></header><div className="erp-cycle-list">{cycleDelta.map(item=><div key={item.op}><div><strong>{item.op}</strong><span>{item.cicloRealSec.toFixed(1)}s / {item.cicloTeoricoSec.toFixed(1)}s</span></div><b>{item.delta>=0?'+':''}{item.delta.toFixed(1)}%</b></div>)}</div></article></section>
  <section className="erp-panel"><header><div><span>APS SIMPLIFICADO</span><h2>Sequenciamento de carga de máquina</h2></div></header><div className="erp-queue-grid">{demoProductionQueue.map(item=><article key={item.op}><span>#{item.prioridade}</span><strong>{item.op}</strong><b>{item.maquina}</b><small>{item.produto}</small><em>{item.quantidadeProduzida.toLocaleString('pt-BR')} / {item.quantidade.toLocaleString('pt-BR')} UN</em></article>)}</div></section>
 </div>
}
