import { useEffect,useState } from 'react'
import { Send } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import SgqShell from '../../features/sgq/components/SgqShell'
type Sector={id:string;codigo:string|null;nome:string|null};type Rev={id:string;codigo_documento:string;titulo_documento:string;revisao:number;status:string};type Dist={id:string;setor_id:string;status:string;prazo_leitura:string|null;lida_em:string|null}
export default function SgqDistribuicao(){const [p]=useSearchParams(),[codigo,setCodigo]=useState(p.get('codigo')||''),[rev,setRev]=useState<Rev|null>(null),[sectors,setSectors]=useState<Sector[]>([]),[selected,setSelected]=useState<string[]>([]),[deadline,setDeadline]=useState(new Date(Date.now()+604800000).toISOString().slice(0,10)),[dist,setDist]=useState<Dist[]>([]),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
useEffect(()=>{void(async()=>{if(!codigo)return;const [r,s]=await Promise.all([supabase.from('erp_qualidade_documentos_revisoes').select('id,codigo_documento,titulo_documento,revisao,status').eq('codigo_documento',codigo).order('revisao',{ascending:false}).limit(1).maybeSingle(),supabase.from('erp_setores').select('id,codigo,nome').eq('ativo',true).order('nome')]);if(r.error||s.error){setError((r.error||s.error)?.message||'Falha');return}setRev(r.data as Rev|null);setSectors((s.data||[]) as Sector[]);if(r.data){const d=await supabase.from('erp_qms_documento_distribuicoes').select('id,setor_id,status,prazo_leitura,lida_em').eq('revisao_id',r.data.id);if(!d.error)setDist((d.data||[]) as Dist[])}})()},[codigo])
const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):x.concat(id))
const send=async()=>{if(!rev||!selected.length){setError('Selecione ao menos um departamento.');return}setBusy(true);setError('');try{const r=await supabase.rpc('erp_qms_distribuir_revisao',{p_revisao_id:rev.id,p_setores:selected,p_prazo:deadline});if(r.error)throw r.error;setMsg(String(r.data)+' distribuição(ões) registrada(s) como leitura obrigatória.');const d=await supabase.from('erp_qms_documento_distribuicoes').select('id,setor_id,status,prazo_leitura,lida_em').eq('revisao_id',rev.id);if(!d.error)setDist((d.data||[]) as Dist[])}catch(e){setError(e instanceof Error?e.message:'Falha na distribuição.')}finally{setBusy(false)}}
return <SgqShell title="Distribuição controlada" subtitle="A revisão assinada deve ser reconhecida pelos departamentos selecionados.">{(error||msg)&&<div className={'mb-4 border p-3 text-sm '+(error?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-800')}>{error||msg}</div>}<section className="border border-slate-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_180px]"><label className="text-[11px] uppercase text-slate-500">Código<input value={codigo} onChange={e=>setCodigo(e.target.value)} className="mt-1 h-9 w-full border px-2 text-sm"/></label><div className="border border-slate-200 p-2"><div className="text-[10px] uppercase text-slate-500">Revisão selecionada</div><div className="mt-1 text-sm">{rev?rev.codigo_documento+' • R-'+String(rev.revisao).padStart(2,'0')+' • '+rev.titulo_documento:'Não encontrada'}</div></div><label className="text-[11px] uppercase text-slate-500">Prazo<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} className="mt-1 h-9 w-full border px-2 text-sm"/></label></div></section><section className="mt-4 border border-slate-200 bg-white"><div className="border-b p-3 text-sm font-medium">Departamentos</div><div className="grid gap-px bg-slate-200 md:grid-cols-3">{sectors.map(s=><label key={s.id} className="flex min-h-14 items-center gap-3 bg-white px-4 text-sm"><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/><span>{s.nome||s.codigo||s.id}</span></label>)}</div><div className="border-t p-3"><button disabled={busy||!rev} onClick={()=>void send()} className="flex h-9 items-center gap-2 bg-[#17736f] px-3 text-xs text-white"><Send size={15}/>{busy?'Disparando…':'Disparar leitura obrigatória'}</button></div></section><section className="mt-4 overflow-x-auto border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-800 text-white"><tr>{['Departamento','Status','Prazo','Leitura'].map(x=><th key={x} className="h-10 px-3 text-left text-[11px] font-medium uppercase">{x}</th>)}</tr></thead><tbody>{dist.map(d=><tr key={d.id} className="border-t"><td className="px-3 py-3">{sectors.find(s=>s.id===d.setor_id)?.nome||d.setor_id}</td><td className="px-3 py-3">{d.status}</td><td className="px-3 py-3">{d.prazo_leitura||'—'}</td><td className="px-3 py-3">{d.lida_em?new Date(d.lida_em).toLocaleString('pt-BR'):'Pendente'}</td></tr>)}</tbody></table></section></SgqShell>}
