import { useEffect,useMemo,useState } from 'react'
import { Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import { supabase } from '../../lib/supabaseClient'
import SgqShell from '../../features/sgq/components/SgqShell'
type R={status:string|null;gravidade:string|null;setor_envolvido_id:string|null};type S={id:string;nome:string|null}
export default function SgqDashboard(){const [rows,setRows]=useState<R[]>([]),[sectors,setSectors]=useState<S[]>([]),[revisions,setRevisions]=useState<{revisao:number;status:string}[]>([]),[actions,setActions]=useState<{status:string;eficacia:string|null}[]>([]),[error,setError]=useState('')
useEffect(()=>{void(async()=>{const [r,s,v,a]=await Promise.all([supabase.from('erp_rpnc').select('status,gravidade,setor_envolvido_id').limit(2000),supabase.from('erp_setores').select('id,nome').eq('ativo',true).order('nome').limit(200),supabase.from('erp_qualidade_documentos_revisoes').select('revisao,status').limit(2000),supabase.from('erp_qualidade_acoes').select('status,eficacia').eq('origem_tipo','RPNC').limit(3000)]);for(const x of [r,s,v,a])if(x.error)throw x.error;setRows((r.data||[]) as R[]);setSectors((s.data||[]) as S[]);setRevisions((v.data||[]) as {revisao:number;status:string}[]);setActions((a.data||[]) as {status:string;eficacia:string|null}[])})().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar indicadores.'))},[])
const byDept=useMemo(()=>sectors.map(s=>({departamento:s.nome||s.id,total:rows.filter(r=>r.setor_envolvido_id===s.id&&!['encerrada','fechada'].includes(String(r.status))).length})).filter(x=>x.total>0),[rows,sectors])
const efficacy=useMemo(()=>{const m=new Map<string,number>();for(const a of actions){const k=a.eficacia?.trim()||'Não avaliada';m.set(k,(m.get(k)||0)+1)}return Array.from(m).map(([name,value])=>({name,value}))},[actions])
const pending=useMemo(()=>{const m=new Map<number,number>();for(const r of revisions)if(!['VIGENTE','OBSOLETO'].includes(r.status))m.set(r.revisao,(m.get(r.revisao)||0)+1);return Array.from(m).map(([revisao,total])=>({revisao:'R-'+String(revisao).padStart(2,'0'),total}))},[revisions])
const open=rows.filter(r=>!['encerrada','fechada'].includes(String(r.status))).length
return <SgqShell title="Indicadores e Gestão à Vista" subtitle="RPNC por departamento, eficácia de ações e controle do ciclo documental.">{error&&<div className="mb-4 border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}<div className="grid gap-3 md:grid-cols-4">{[['RPNCs abertas',open],['Críticas',rows.filter(r=>r.gravidade==='critica').length],['Ações sem eficácia',actions.filter(a=>!a.eficacia).length],['Revisões pendentes',pending.reduce((s,x)=>s+x.total,0)]].map(([label,value])=><section key={String(label)} className="border border-slate-200 bg-white p-4"><div className="text-xs uppercase tracking-wider text-slate-500">{label}</div><div className="mt-1 text-2xl font-medium">{value}</div></section>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="h-[360px] border border-slate-200 bg-white p-4"><h2 className="mb-2 text-sm font-medium">RPNCs abertas por departamento</h2><ResponsiveContainer width="100%" height="90%"><BarChart data={byDept}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="departamento" fontSize={11}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="total" fill="#17736f"/></BarChart></ResponsiveContainer></section><section className="h-[360px] border border-slate-200 bg-white p-4"><h2 className="mb-2 text-sm font-medium">Eficácia das ações</h2><ResponsiveContainer width="100%" height="90%"><PieChart><Pie data={efficacy} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={105} label>{efficacy.map((x,i)=><Cell key={x.name} fill={['#17736f','#2d8db8','#d6a24a','#c65b62'][i%4]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></section></div><section className="mt-4 h-[330px] border border-slate-200 bg-white p-4"><h2 className="mb-2 text-sm font-medium">Revisões que exigem tratamento</h2><ResponsiveContainer width="100%" height="90%"><BarChart data={pending}><XAxis dataKey="revisao"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="total" fill="#2d8db8"/></BarChart></ResponsiveContainer></section></SgqShell>}
