import { useEffect,useState } from 'react'
import { Eye,FileEdit,Plus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import SgqShell from '../../features/sgq/components/SgqShell'
import type { SgqDocument } from '../../features/sgq/types'
export default function SgqProcedimentos(){const [docs,setDocs]=useState<SgqDocument[]>([]),[error,setError]=useState(''),nav=useNavigate()
useEffect(()=>{void(async()=>{const r=await supabase.from('erp_qualidade_documentos_revisoes').select('id,codigo_documento,titulo_documento,revisao,status,departamento,responsavel,conteudo_texto,motivo_alteracao').order('codigo_documento').order('revisao',{ascending:false});if(r.error)setError(r.error.message);else setDocs((r.data||[]) as SgqDocument[])})()},[])
const latest=docs.filter((d,i,a)=>i===a.findIndex(x=>x.codigo_documento===d.codigo_documento))
return <SgqShell title="Procedimentos controlados" subtitle="Documentos, revisões, status e rastreabilidade."><div className="mb-4 flex items-center justify-between gap-3"><div className="text-sm text-slate-500">{latest.length} documento(s) vigente(s)</div><button onClick={()=>nav('/sgq/procedimentos/editar')} className="flex h-9 items-center gap-2 border border-[#17736f] bg-[#17736f] px-3 text-xs text-white"><Plus size={15}/> Novo procedimento</button></div>{error&&<div className="mb-4 border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}<div className="overflow-x-auto border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-800 text-white"><tr>{['Código','Título','Revisão','Setor','Status','Ações'].map(h=><th key={h} className="h-10 px-3 text-left text-[11px] font-medium uppercase">{h}</th>)}</tr></thead><tbody>{latest.map(d=><tr key={d.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-3 py-3 font-medium">{d.codigo_documento}</td><td className="px-3 py-3">{d.titulo_documento}</td><td className="px-3 py-3">R-{String(d.revisao).padStart(2,'0')}</td><td className="px-3 py-3">{d.departamento}</td><td className="px-3 py-3">{d.status}</td><td className="px-3 py-3"><button onClick={()=>nav('/sgq/procedimentos/editar?codigo='+encodeURIComponent(d.codigo_documento))} className="mr-2 inline-flex h-8 items-center gap-1 border px-2 text-xs"><FileEdit size={14}/> Editar</button><button onClick={()=>nav('/sgq/procedimentos/visualizar?codigo='+encodeURIComponent(d.codigo_documento))} className="inline-flex h-8 items-center gap-1 border px-2 text-xs"><Eye size={14}/> Visualizar</button></td></tr>)}</tbody></table></div></SgqShell>}
