import { useEffect,useState } from 'react'
import { History,Save,Send } from 'lucide-react'
import { useNavigate,useSearchParams } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import SgqShell from '../../features/sgq/components/SgqShell'
type Rev={id:string;codigo_documento:string;titulo_documento:string;revisao:number;departamento:string;status:string;conteudo_texto:string;motivo_alteracao:string|null;criado_em:string}
export default function SgqProcedimentoEditor(){const [params]=useSearchParams(),nav=useNavigate(),[codigo,setCodigo]=useState(params.get('codigo')||'POP-001'),[titulo,setTitulo]=useState(''),[setor,setSetor]=useState('QUALIDADE'),[conteudo,setConteudo]=useState(''),[motivo,setMotivo]=useState(''),[revs,setRevs]=useState<Rev[]>([]),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
const load=async()=>{const r=await supabase.from('erp_qualidade_documentos_revisoes').select('id,codigo_documento,titulo_documento,revisao,departamento,status,conteudo_texto,motivo_alteracao,criado_em').eq('codigo_documento',codigo).order('revisao',{ascending:false});if(r.error){setError(r.error.message);return}const rows=(r.data||[]) as Rev[];setRevs(rows);if(rows[0]){setTitulo(rows[0].titulo_documento);setSetor(rows[0].departamento);setConteudo(rows[0].conteudo_texto)}}
useEffect(()=>{if(codigo)void load()},[codigo])
const save=async()=>{setError('');setMsg('');if(!codigo.trim()||!titulo.trim()||!conteudo.trim()||motivo.trim().length<5){setError('Código, título, conteúdo e motivo da alteração são obrigatórios.');return}setBusy(true);try{const r=await supabase.rpc('erp_qms_salvar_revisao',{p_codigo:codigo,p_titulo:titulo,p_departamento:setor,p_conteudo:conteudo,p_motivo:motivo,p_setor_responsavel:setor});if(r.error)throw r.error;setMsg('Revisão criada com sucesso.');setMotivo('');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar revisão.')}finally{setBusy(false)}}
const latest=revs[0]
return <SgqShell title="Editor controlado de procedimento" subtitle="Toda alteração gera nova revisão; revisões vigentes não são sobrescritas.">{(error||msg)&&<div className={'mb-4 border p-3 text-sm '+(error?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-800')}>{error||msg}</div>}<div className="grid gap-4 lg:grid-cols-[1fr_340px]"><section className="border border-slate-200 bg-white"><div className="grid grid-cols-2 border-b-2 border-slate-800 md:grid-cols-5">{[['Código',codigo,setCodigo],['Título',titulo,setTitulo],['Revisão',latest?'R-'+String(latest.revisao).padStart(2,'0'):'R-01',()=>{}],['Setor',setor,setSetor],['Status',latest?.status||'VIGENTE',()=>{}]].map(([label,value,onChange],i)=><label key={String(label)} className={'border-r border-slate-300 p-2 '+(i===1?'md:col-span-2':'')}><span className="block text-[10px] uppercase text-slate-500">{label}</span><input value={String(value)} onChange={e=>(onChange as (v:string)=>void)(e.target.value)} readOnly={i===2||i===4} className="mt-1 h-8 w-full border-0 bg-transparent text-sm outline-none"/></label>)}</div><div className="p-4"><label className="block text-[11px] uppercase text-slate-500">Corpo do procedimento<textarea value={conteudo} onChange={e=>setConteudo(e.target.value)} className="mt-2 min-h-[520px] w-full border border-slate-300 p-3 text-sm leading-6 outline-none focus:border-[#17736f]"/></label></div><div className="border-t border-slate-200 bg-slate-50 p-4"><label className="block text-[11px] uppercase text-slate-500">Motivo da alteração <span className="text-rose-600">*</span><textarea value={motivo} onChange={e=>setMotivo(e.target.value)} className="mt-2 min-h-20 w-full border border-slate-300 p-3 text-sm outline-none"/></label><div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>void save()} className="flex h-9 items-center gap-2 bg-[#17736f] px-3 text-xs text-white"><Save size={15}/>{busy?'Salvando…':'Salvar nova revisão'}</button><button onClick={()=>nav('/sgq/distribuicao?codigo='+encodeURIComponent(codigo))} className="flex h-9 items-center gap-2 border border-slate-300 bg-white px-3 text-xs"><Send size={15}/> Distribuir</button></div></div></section><aside className="border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 p-3 text-sm font-medium"><History size={16}/> Histórico / trilha</div><div className="max-h-[720px] overflow-auto">{revs.map(r=><div key={r.id} className="border-b border-slate-100 p-3"><div className="flex justify-between"><strong>R-{String(r.revisao).padStart(2,'0')}</strong><span className="text-xs text-slate-500">{r.status}</span></div><div className="mt-1 text-xs text-slate-600">{r.motivo_alteracao||'Sem motivo registrado'}</div><div className="mt-1 text-[11px] text-slate-400">{new Date(r.criado_em).toLocaleString('pt-BR')}</div></div>)}</div></aside></div></SgqShell>}
