import { useEffect,useState } from 'react'
import { ArrowLeft,Send } from 'lucide-react'
import { useNavigate,useSearchParams } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import SgqShell from '../../features/sgq/components/SgqShell'
type D={id:string;codigo_documento:string;titulo_documento:string;revisao:number;departamento:string;status:string;responsavel:string|null;conteudo_texto:string}
export default function SgqProcedimentoVisualizar(){const [p]=useSearchParams(),nav=useNavigate(),[d,setD]=useState<D|null>(null),[error,setError]=useState('')
useEffect(()=>{void(async()=>{const q=p.get('codigo');if(!q)return;const r=await supabase.from('erp_qualidade_documentos_revisoes').select('id,codigo_documento,titulo_documento,revisao,departamento,status,responsavel,conteudo_texto').eq('codigo_documento',q).order('revisao',{ascending:false}).limit(1).maybeSingle();if(r.error)setError(r.error.message);else setD(r.data as D|null)})()},[p])
return <SgqShell title="Visualização controlada" subtitle="Cabeçalho documental ISO 9001 e conteúdo da revisão vigente."><div className="mb-3 flex gap-2"><button onClick={()=>nav('/sgq/procedimentos')} className="flex h-9 items-center gap-2 border bg-white px-3 text-xs"><ArrowLeft size={15}/> Voltar</button>{d&&<button onClick={()=>nav('/sgq/distribuicao?codigo='+encodeURIComponent(d.codigo_documento))} className="flex h-9 items-center gap-2 bg-[#17736f] px-3 text-xs text-white"><Send size={15}/> Distribuir revisão</button>}</div>{error&&<div className="border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}{d&&<article className="border border-slate-300 bg-white"><div className="grid border-b-2 border-slate-800 md:grid-cols-5">{[['Código',d.codigo_documento],['Título',d.titulo_documento],['Revisão atual','R-'+String(d.revisao).padStart(2,'0')],['Setor responsável',d.departamento],['Status',d.status]].map(([l,v],i)=><div key={l} className={'border-r border-slate-300 p-3 '+(i===1?'md:col-span-2':'')}><div className="text-[10px] uppercase text-slate-500">{l}</div><div className="mt-1 text-sm font-medium">{v}</div></div>)}</div><div className="min-h-[620px] whitespace-pre-wrap p-8 text-sm leading-7">{d.conteudo_texto}</div><footer className="border-t border-slate-200 bg-slate-50 p-3 text-xs text-slate-500">Responsável: {d.responsavel||'—'} • Documento controlado • Revisão {d.revisao}</footer></article>}</SgqShell>}
