import { ArrowLeft, Lock, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
type Year={id:string;ano:number;status:'ABERTO'|'FECHADO';data_abertura:string;data_fechamento:string|null}
const i='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]';const l='mb-0.5 block text-[10px] font-bold uppercase text-gray-500';const b='inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-[11px] font-bold'
export default function AnoFiscal(){const n=useNavigate();const [ano,setAno]=useState(String(new Date().getFullYear()));const [rows,setRows]=useState<Year[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('')
 const load=async()=>{const r=await supabase.from('erp_anos_fiscais').select('id,ano,status,data_abertura,data_fechamento').order('ano',{ascending:false});if(r.error)setError(r.error.message);else setRows((r.data??[]) as Year[])}
 useEffect(()=>{void load()},[])
 const save=async()=>{setError('');setMessage('');const empresa=await supabase.rpc('erp_current_empresa_id');if(empresa.error||!empresa.data){setError('Empresa não identificada.');return}const r=await supabase.from('erp_anos_fiscais').upsert({empresa_id:empresa.data,ano:Number(ano),status:'ABERTO',data_abertura:new Date().toISOString().slice(0,10)},{onConflict:'empresa_id,ano'});if(r.error){setError(r.error.message);return}setMessage('Exercício fiscal aberto.');await load()}
 const close=async(row:Year)=>{if(row.status==='FECHADO')return;const r=await supabase.from('erp_anos_fiscais').update({status:'FECHADO',data_fechamento:new Date().toISOString().slice(0,10)}).eq('id',row.id);if(r.error)setError(r.error.message);else await load()}
 return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mx-auto max-w-[1200px] space-y-2"><div className="flex items-center gap-2"><button type="button" onClick={()=>n(-1)} className={b+' border border-gray-200 bg-white text-gray-600'}><ArrowLeft size={12}/>Voltar</button><h1 className="text-[13px] font-bold">ANO FISCAL — EXERCÍCIOS DA EMPRESA</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div className="w-[90px]"><label className={l}>Ano</label><input className={i+' w-[90px]'} type="number" min="2000" max="2100" value={ano} onChange={e=>setAno(e.target.value)}/></div><button type="button" onClick={()=>void save()} className={b+' w-[95px] bg-blue-600 text-white'}><Save size={12}/>Abrir Ano</button></div></section><section className="scroll-fade-x max-h-[250px] overflow-auto rounded-md border border-gray-200 bg-white shadow-sm"><table className="w-full text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr className="h-7"><th className="px-2 text-left font-normal">Ano</th><th className="px-2 text-left font-normal">Abertura</th><th className="px-2 text-left font-normal">Fechamento</th><th className="px-2 text-left font-normal">Status</th><th className="w-[100px] px-2 text-center font-normal">Ação</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="h-[26px] border-b border-gray-100 even:bg-slate-50"><td className="px-2 font-bold">{r.ano}</td><td className="px-2">{r.data_abertura}</td><td className="px-2">{r.data_fechamento??'—'}</td><td className="px-2">{r.status}</td><td className="px-2 text-center">{r.status==='ABERTO'&&<button type="button" onClick={()=>void close(r)} className="inline-flex h-7 items-center gap-1 rounded-md border border-amber-200 px-2 text-[10px] text-amber-700"><Lock size={11}/>Fechar</button>}</td></tr>)}</tbody></table></section>{message&&<div className="text-[10px] font-bold text-emerald-700">{message}</div>}{error&&<div className="text-[10px] text-red-700">{error}</div>}</div></main>
}