import { Plus } from 'lucide-react'
import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabaseClient'
type Rule={id:string;nome_fiscal:string;ncm_codigo:string;aliquota:number;data_vigencia:string}
export default function ClassificacaoFiscal(){const [rows,setRows]=useState<Rule[]>([]);const [nome,setNome]=useState('');const [ncm,setNcm]=useState('');const [aliquota,setAliquota]=useState('');const [vig,setVig]=useState('');const [msg,setMsg]=useState('')
const load=async()=>{const r=await supabase.from('erp_classificacao_fiscal').select('id,nome_fiscal,ncm_codigo,aliquota,data_vigencia').order('data_vigencia',{ascending:false});if(r.error)setMsg(r.error.message);else setRows((r.data??[]) as Rule[])}
useEffect(()=>{void load()},[])
const save=async()=>{setMsg('');const e=await supabase.rpc('erp_current_empresa_id');if(e.error||!e.data){setMsg('Empresa não identificada.');return}const r=await supabase.from('erp_classificacao_fiscal').insert({empresa_id:e.data,nome_fiscal:nome.trim(),ncm_codigo:ncm.trim(),aliquota:Number(aliquota),data_vigencia:vig});if(r.error){setMsg(r.error.message);return}setNome('');setNcm('');setAliquota('');setVig('');void load()}
const input='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px]'
return <main className="min-h-full bg-slate-50 p-3"><div className="mb-2 flex items-center gap-2"><button className={input+' px-2 font-bold'} onClick={()=>window.history.back()}>← Voltar</button><h1 className="text-[12px] font-bold">📐 CADASTRO E CLASSIFICAÇÃO FISCAL DE PRODUTOS (NCM / ICMS)</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">Classificação</label><input className={input+' w-[160px]'} value={nome} onChange={e=>setNome(e.target.value)}/></div><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">NCM / Código Fiscal</label><input className={input+' w-[110px]'} value={ncm} onChange={e=>setNcm(e.target.value)}/></div><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">Alíquota Base %</label><input type="number" className={input+' w-[80px]'} value={aliquota} onChange={e=>setAliquota(e.target.value)}/></div><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">Vigência Início</label><input type="date" className={input+' w-[110px]'} value={vig} onChange={e=>setVig(e.target.value)}/></div><button onClick={()=>void save()} className="flex h-7 w-7 items-center justify-center rounded-md bg-green-600 text-white"><Plus size={12}/></button></div><div className="scroll-fade-x mt-2 max-h-[250px] overflow-auto rounded border border-gray-200"><table className="w-full text-[10px]"><thead className="bg-slate-700 text-white"><tr className="h-7"><th className="p-1 text-left">Classificação</th><th className="p-1 text-left">NCM</th><th className="p-1">Alíquota</th><th className="p-1">Vigência</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="h-[26px] border-b even:bg-slate-50"><td className="p-1">{r.nome_fiscal}</td><td className="p-1">{r.ncm_codigo}</td><td className="p-1 text-center">{Number(r.aliquota).toFixed(2)}%</td><td className="p-1 text-center">{r.data_vigencia}</td></tr>)}</tbody></table></div>{msg&&<div className="mt-1 text-[10px] text-red-600">{msg}</div>}</section></main>