import { RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabaseClient'

type Account={id:string;codigo:string;nome:string;banco:string|null;saldo_inicial:number;ativo:boolean}
type Row={id:string;documento:string|null;descricao:string;debito:number;credito:number;criado_em:string}
const input='h-7 rounded-md border border-gray-200 bg-white px-2 text-[11px] outline-none'
export default function PainelRazaoGeral(){const [accounts,setAccounts]=useState<Account[]>([]);const [accountId,setAccountId]=useState('');const [rows,setRows]=useState<Row[]>([]);const [balance,setBalance]=useState(0);const [error,setError]=useState('')
const load=async()=>{setError('');const r=await supabase.from('erp_contas_bancarias').select('id,codigo,nome,banco,saldo_inicial,ativo').eq('ativo',true).order('nome');if(r.error){setError(r.error.message);return}setAccounts((r.data??[]) as Account[])}
useEffect(()=>{void load()},[])
useEffect(()=>{const run=async()=>{if(!accountId){setRows([]);setBalance(0);return}const r=await supabase.from('erp_fiscal_razao_lancamentos').select('id,documento,descricao,debito,credito,criado_em').eq('conta_bancaria_id',accountId).order('criado_em',{ascending:false}).limit(100);if(r.error){setError(r.error.message);return}const data=(r.data??[]) as Row[];setRows(data);const a=accounts.find(x=>x.id===accountId);setBalance(Number(a?.saldo_inicial??0)+data.reduce((s,x)=>s+Number(x.credito)-Number(x.debito),0))};void run()},[accountId,accounts])
return <main className="min-h-full bg-slate-50 p-3 text-gray-800"><div className="mb-2 flex items-center gap-2"><button className={input+' px-2 text-gray-600'} onClick={()=>window.history.back()}>← Voltar</button><h1 className="text-[12px] font-bold">🏦 MONITOR DO RAZÃO GERAL (GL - GENERAL LEDGER)</h1></div><section className="rounded-md border border-gray-200 bg-white p-2 shadow-sm"><div className="flex items-end gap-2"><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">Empresa / Tenant</label><input className={input+' w-[160px]'} value="Empresa atual" readOnly/></div><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">Banco / Diário</label><select className={input+' w-[160px]'} value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></div><div><label className="mb-0.5 block text-[10px] font-bold uppercase text-gray-500">Moeda Exibição</label><select className={input+' w-[110px]'} defaultValue="BRL"><option>BRL</option></select></div><button className="flex h-7 w-[110px] items-center justify-center gap-1 rounded-md bg-blue-600 text-[11px] font-bold text-white" onClick={()=>void load()}><RefreshCw size={12}/>Atualizar</button></div>{error&&<div className="mt-2 text-[10px] text-red-600">{error}</div>}<div className="scroll-fade-x mt-2 max-h-[220px] overflow-auto rounded border border-gray-200"><table className="w-full text-[10px]"><thead className="sticky top-0 bg-slate-700 text-white"><tr><th className="p-1 text-left">Data</th><th className="p-1 text-left">Documento</th><th className="p-1 text-left">Descrição</th><th className="p-1 text-right">Débito</th><th className="p-1 text-right">Crédito</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="h-[26px] border-b border-gray-100 odd:bg-white even:bg-slate-50"><td className="p-1">{new Date(r.criado_em).toLocaleDateString('pt-BR')}</td><td className="p-1">{r.documento??'—'}</td><td className="p-1">{r.descricao}</td><td className="p-1 text-right">{Number(r.debito).toLocaleString('pt-BR',{minimumFractionDigits:2})}</td><td className="p-1 text-right">{Number(r.credito).toLocaleString('pt-BR',{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div><div className="mt-2 flex h-7 items-center justify-between rounded-sm bg-slate-700 px-3 text-[11px] font-bold text-white"><span>CONTA: {accounts.find(a=>a.id===accountId)?.nome??'—'}</span><span className="rounded bg-green-200 px-2 py-0.5 font-black text-green-800">R$ {balance.toLocaleString('pt-BR',{minimumFractionDigits:2})}</span></div></section></main>}