import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { z } from 'zod'
import { AlertTriangle, RefreshCw, ShieldCheck, Users, Clock3, HardHat } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import VendasLayout from '../VendasLayout'

type Tab='funcionarios'|'turnos'|'epis'|'entregas'
type Employee={id:string;matricula:string;nome_completo:string;cpf:string;rg:string|null;data_admissao:string;cargo_funcao:string;departamento:string;custo_hora_mod:number;status:string}
type Shift={id:string;codigo:string;nome:string;hora_inicio:string;hora_fim:string;intervalo_minutos:number;escala:string;carga_mensal_horas:number;ativo:boolean}
type Epi={id:string;codigo:string;nome:string;ca_numero:string;ca_validade:string;periodicidade_troca_dias:number;funcoes_aplicaveis:string[];ativo:boolean}
type Delivery={id:string;funcionario_id:string;epi_id:string;quantidade:number;entregue_em:string;proxima_troca_em:string;confirmado_recebimento:boolean;observacao:string|null}
const employeeSchema=z.object({matricula:z.string().trim().min(1).max(32),nome_completo:z.string().trim().min(3).max(160),cpf:z.string().transform(v=>v.replace(/\D/g,'')).refine(v=>/^\d{11}$/.test(v),'CPF deve conter 11 dígitos.'),rg:z.string().trim().max(30),data_admissao:z.string().min(10),cargo_funcao:z.string().trim().min(2).max(100),departamento:z.enum(['ENGENHARIA','PCP','PRODUCAO','QUALIDADE','ALMOXARIFADO','MANUTENCAO','FISCAL','ADMINISTRATIVO','OUTRO']),custo_hora_mod:z.string().refine(v=>Number.isFinite(Number(v))&&Number(v)>=0,'Taxa horária deve ser zero ou positiva.')})
const shiftSchema=z.object({codigo:z.string().trim().min(1).max(20),nome:z.string().trim().min(2).max(100),hora_inicio:z.string().min(5),hora_fim:z.string().min(5),intervalo_minutos:z.string().refine(v=>Number.isInteger(Number(v))&&Number(v)>=0&&Number(v)<=720),escala:z.enum(['5X2','6X2','12X36','6X1','PERSONALIZADA']),carga_mensal_horas:z.string().refine(v=>Number(v)>0&&Number(v)<=300)})
const epiSchema=z.object({codigo:z.string().trim().min(1).max(30),nome:z.string().trim().min(2).max(160),ca_numero:z.string().trim().min(1).max(40),ca_validade:z.string().min(10),periodicidade_troca_dias:z.string().refine(v=>Number.isInteger(Number(v))&&Number(v)>0&&Number(v)<=3650),funcoes_aplicaveis:z.string()})
const input='h-[30px] w-full rounded-[2px] border border-slate-300 bg-white px-2 text-[11px] outline-none focus:border-[#2D8DB8] focus:ring-1 focus:ring-[#2D8DB8]/20'
const label='mb-[2px] block text-[9px] font-medium uppercase tracking-[.04em] text-slate-600'
const button='inline-flex h-[30px] items-center justify-center gap-1 rounded-[2px] border border-[#2D8DB8] bg-[#2D8DB8] px-3 text-[10px] font-medium text-white disabled:opacity-50'
const today=()=>new Date().toISOString().slice(0,10)
const blankEmployee={matricula:'',nome_completo:'',cpf:'',rg:'',data_admissao:today(),cargo_funcao:'',departamento:'PRODUCAO',custo_hora_mod:'0'}
const blankShift={codigo:'',nome:'',hora_inicio:'06:00',hora_fim:'14:00',intervalo_minutos:'60',escala:'5X2',carga_mensal_horas:'220'}
const blankEpi={codigo:'',nome:'',ca_numero:'',ca_validade:today(),periodicidade_troca_dias:'180',funcoes_aplicaveis:''}
export default function RHIndustrial(){
 const [tab,setTab]=useState<Tab>('funcionarios');const [empresa,setEmpresa]=useState('');const [employees,setEmployees]=useState<Employee[]>([]);const [shifts,setShifts]=useState<Shift[]>([]);const [epis,setEpis]=useState<Epi[]>([]);const [deliveries,setDeliveries]=useState<Delivery[]>([])
 const [employeeForm,setEmployeeForm]=useState(blankEmployee);const [shiftForm,setShiftForm]=useState(blankShift);const [epiForm,setEpiForm]=useState(blankEpi);const [deliveryForm,setDeliveryForm]=useState({funcionario_id:'',epi_id:'',quantidade:'1',entregue_em:today(),confirmado_recebimento:false,observacao:''})
 const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [query,setQuery]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const t=await supabase.rpc('erp_current_empresa_id');if(t.error)throw t.error;if(typeof t.data!=='string'||!t.data)throw new Error('Empresa da sessão não identificada.');setEmpresa(t.data)
  const [e,s,i,d]=await Promise.all([
   supabase.from('erp_rh_funcionarios').select('id,matricula,nome_completo,cpf,rg,data_admissao,cargo_funcao,departamento,custo_hora_mod,status').eq('empresa_id',t.data).order('nome_completo').limit(3000),
   supabase.from('erp_rh_turnos').select('id,codigo,nome,hora_inicio,hora_fim,intervalo_minutos,escala,carga_mensal_horas,ativo').eq('empresa_id',t.data).order('codigo').limit(1000),
   supabase.from('erp_rh_epis').select('id,codigo,nome,ca_numero,ca_validade,periodicidade_troca_dias,funcoes_aplicaveis,ativo').eq('empresa_id',t.data).order('nome').limit(2000),
   supabase.from('erp_rh_entregas_epi').select('id,funcionario_id,epi_id,quantidade,entregue_em,proxima_troca_em,confirmado_recebimento,observacao').eq('empresa_id',t.data).order('entregue_em',{ascending:false}).limit(3000)
  ]);if(e.error)throw e.error;if(s.error)throw s.error;if(i.error)throw i.error;if(d.error)throw d.error
  setEmployees((e.data??[]) as Employee[]);setShifts((s.data??[]) as Shift[]);setEpis((i.data??[]) as Epi[]);setDeliveries((d.data??[]) as Delivery[])
 }catch(e){setError(e instanceof Error?e.message:'Falha ao consultar cadastros de RH.')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const visibleEmployees=useMemo(()=>employees.filter(x=>[x.matricula,x.nome_completo,x.cpf,x.cargo_funcao,x.departamento].some(v=>String(v??'').toLocaleLowerCase('pt-BR').includes(query.trim().toLocaleLowerCase('pt-BR')))),[employees,query])
 const employeeMap=useMemo(()=>new Map(employees.map(x=>[x.id,x])),[employees]);const epiMap=useMemo(()=>new Map(epis.map(x=>[x.id,x])),[epis])
 const saveEmployee=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');const parsed=employeeSchema.safeParse(employeeForm);if(!parsed.success){setError(parsed.error.issues[0]?.message??'Revise os dados do funcionário.');return}setSaving(true);try{const v=parsed.data;const r=await supabase.from('erp_rh_funcionarios').insert({empresa_id:empresa,matricula:v.matricula,nome_completo:v.nome_completo,cpf:v.cpf,rg:v.rg||null,data_admissao:v.data_admissao,cargo_funcao:v.cargo_funcao,departamento:v.departamento,custo_hora_mod:Number(v.custo_hora_mod),criado_por:(await supabase.auth.getUser()).data.user?.id??null}).select('id').single();if(r.error)throw r.error;setEmployeeForm(blankEmployee);setNotice('Funcionário cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o funcionário.')}finally{setSaving(false)}}
 const saveShift=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');const p=shiftSchema.safeParse(shiftForm);if(!p.success){setError(p.error.issues[0]?.message??'Revise o turno.');return}if(p.data.hora_inicio===p.data.hora_fim){setError('O início e o término do turno não podem ser iguais.');return}setSaving(true);try{const v=p.data;const r=await supabase.from('erp_rh_turnos').insert({empresa_id:empresa,codigo:v.codigo,nome:v.nome,hora_inicio:v.hora_inicio,hora_fim:v.hora_fim,intervalo_minutos:Number(v.intervalo_minutos),escala:v.escala,carga_mensal_horas:Number(v.carga_mensal_horas)});if(r.error)throw r.error;setShiftForm(blankShift);setNotice('Turno cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o turno.')}finally{setSaving(false)}}
 const saveEpi=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');const p=epiSchema.safeParse(epiForm);if(!p.success){setError(p.error.issues[0]?.message??'Revise o EPI.');return}setSaving(true);try{const v=p.data;const r=await supabase.from('erp_rh_epis').insert({empresa_id:empresa,codigo:v.codigo,nome:v.nome,ca_numero:v.ca_numero,ca_validade:v.ca_validade,periodicidade_troca_dias:Number(v.periodicidade_troca_dias),funcoes_aplicaveis:v.funcoes_aplicaveis.split(',').map(x=>x.trim()).filter(Boolean)});if(r.error)throw r.error;setEpiForm(blankEpi);setNotice('EPI cadastrado.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o EPI.')}finally{setSaving(false)}}
 const saveDelivery=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');const qty=Number(deliveryForm.quantidade);if(!deliveryForm.funcionario_id||!deliveryForm.epi_id||!Number.isInteger(qty)||qty<1){setError('Selecione funcionário, EPI e quantidade inteira positiva.');return}const epi=epiMap.get(deliveryForm.epi_id);if(!epi){setError('EPI selecionado não existe no tenant.');return}if(epi.ca_validade<deliveryForm.entregue_em){setError('CA vencido na data da entrega. Não é permitido registrar entrega com CA vencido.');return}setSaving(true);try{const next=new Date(deliveryForm.entregue_em+'T12:00:00');next.setDate(next.getDate()+Number(epi.periodicidade_troca_dias));const r=await supabase.from('erp_rh_entregas_epi').insert({empresa_id:empresa,funcionario_id:deliveryForm.funcionario_id,epi_id:deliveryForm.epi_id,quantidade:qty,entregue_em:deliveryForm.entregue_em,proxima_troca_em:next.toISOString().slice(0,10),confirmado_recebimento:deliveryForm.confirmado_recebimento,observacao:deliveryForm.observacao||null,responsavel_id:(await supabase.auth.getUser()).data.user?.id??null});if(r.error)throw r.error;setDeliveryForm({funcionario_id:'',epi_id:'',quantidade:'1',entregue_em:today(),confirmado_recebimento:false,observacao:''});setNotice('Entrega de EPI registrada.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar a entrega.')}finally{setSaving(false)}}
 const tabs:[Tab,string,typeof Users][]=[['funcionarios','Funcionários',Users],['turnos','Turnos e escalas',Clock3],['epis','EPIs / CA',HardHat],['entregas','Entregas e trocas',ShieldCheck]]
 return <VendasLayout title="RH Industrial e Segurança" subtitle="Quadro operacional, escalas, custo MOD e controle de EPI/CA" onRefresh={()=>void load()} showStatusCards={false}>
 <section className="erp-global-surface erp-compact mt-3 space-y-3">
  <nav className="flex flex-wrap gap-1 border-b border-slate-200 pb-2">{tabs.map(([id,name,Icon])=><button key={id} type="button" onClick={()=>setTab(id)} className={'inline-flex h-[30px] items-center gap-1 rounded-[2px] border px-3 text-[10px] '+(tab===id?'border-[#2D8DB8] bg-[#eaf5f9] text-[#17445A]':'border-slate-200 bg-white text-slate-600')}><Icon size={13}/>{name}</button>)}</nav>
  {(error||notice)&&<div role={error?'alert':'status'} className={'rounded-[2px] border p-2 text-[11px] '+(error?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-800')}>{error||notice}</div>}
  {loading&&<p className="text-[10px] text-slate-500"><RefreshCw size={12} className="mr-1 inline animate-spin"/>Atualizando dados do tenant...</p>}
  {tab==='funcionarios'&&<><form onSubmit={saveEmployee} className="grid grid-cols-1 gap-2 rounded border border-slate-200 bg-white p-3 md:grid-cols-4">
   <div><label className={label}>Matrícula</label><input className={input} required maxLength={32} value={employeeForm.matricula} onChange={e=>setEmployeeForm({...employeeForm,matricula:e.target.value})}/></div>
   <div className="md:col-span-2"><label className={label}>Nome completo</label><input className={input} required value={employeeForm.nome_completo} onChange={e=>setEmployeeForm({...employeeForm,nome_completo:e.target.value})}/></div>
   <div><label className={label}>CPF (somente números)</label><input className={input} required inputMode="numeric" maxLength={14} value={employeeForm.cpf} onChange={e=>setEmployeeForm({...employeeForm,cpf:e.target.value})}/></div>
   <div><label className={label}>RG</label><input className={input} value={employeeForm.rg} onChange={e=>setEmployeeForm({...employeeForm,rg:e.target.value})}/></div>
   <div><label className={label}>Data de admissão</label><input className={input} type="date" required value={employeeForm.data_admissao} onChange={e=>setEmployeeForm({...employeeForm,data_admissao:e.target.value})}/></div>
   <div><label className={label}>Cargo / função</label><input className={input} required value={employeeForm.cargo_funcao} onChange={e=>setEmployeeForm({...employeeForm,cargo_funcao:e.target.value})}/></div>
   <div><label className={label}>Departamento</label><select className={input} value={employeeForm.departamento} onChange={e=>setEmployeeForm({...employeeForm,departamento:e.target.value})}>{['ENGENHARIA','PCP','PRODUCAO','QUALIDADE','ALMOXARIFADO','MANUTENCAO','FISCAL','ADMINISTRATIVO','OUTRO'].map(x=><option key={x}>{x}</option>)}</select></div>
   <div><label className={label}>Custo MOD / hora (R$)</label><input className={input} type="number" min="0" step="0.0001" required value={employeeForm.custo_hora_mod} onChange={e=>setEmployeeForm({...employeeForm,custo_hora_mod:e.target.value})}/></div>
   <div className="flex items-end"><button className={button} disabled={saving||!empresa}>{saving?'Salvando...':'Cadastrar funcionário'}</button></div>
  </form><div className="flex items-end gap-2"><div className="flex-1"><label className={label}>Pesquisar funcionário</label><input className={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Matrícula, nome, CPF, cargo..."/></div><span className="text-[10px] text-slate-500">{visibleEmployees.length} registros</span></div>
  <Grid headers={['Matrícula','Nome / CPF','Cargo / Departamento','Admissão','Custo MOD/h','Status']} rows={visibleEmployees.map(x=>[x.matricula,x.nome_completo+' • '+x.cpf,x.cargo_funcao+' • '+x.departamento,x.data_admissao,Number(x.custo_hora_mod).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),x.status])}/></>}
  {tab==='turnos'&&<><form onSubmit={saveShift} className="grid grid-cols-1 gap-2 rounded border border-slate-200 bg-white p-3 md:grid-cols-4">
   <div><label className={label}>Código do turno</label><input className={input} required value={shiftForm.codigo} onChange={e=>setShiftForm({...shiftForm,codigo:e.target.value})}/></div><div><label className={label}>Nome do turno</label><input className={input} required value={shiftForm.nome} onChange={e=>setShiftForm({...shiftForm,nome:e.target.value})}/></div><div><label className={label}>Início</label><input className={input} type="time" required value={shiftForm.hora_inicio} onChange={e=>setShiftForm({...shiftForm,hora_inicio:e.target.value})}/></div><div><label className={label}>Término</label><input className={input} type="time" required value={shiftForm.hora_fim} onChange={e=>setShiftForm({...shiftForm,hora_fim:e.target.value})}/></div>
   <div><label className={label}>Intervalo (minutos)</label><input className={input} type="number" min="0" max="720" required value={shiftForm.intervalo_minutos} onChange={e=>setShiftForm({...shiftForm,intervalo_minutos:e.target.value})}/></div><div><label className={label}>Escala</label><select className={input} value={shiftForm.escala} onChange={e=>setShiftForm({...shiftForm,escala:e.target.value})}>{['5X2','6X2','12X36','6X1','PERSONALIZADA'].map(x=><option key={x}>{x}</option>)}</select></div><div><label className={label}>Carga mensal (h)</label><input className={input} type="number" min="1" max="300" step="0.5" required value={shiftForm.carga_mensal_horas} onChange={e=>setShiftForm({...shiftForm,carga_mensal_horas:e.target.value})}/></div><div className="flex items-end"><button className={button} disabled={saving||!empresa}>{saving?'Salvando...':'Cadastrar turno'}</button></div>
  </form><Grid headers={['Código','Turno','Jornada','Intervalo','Escala','Carga mensal','Status']} rows={shifts.map(x=>[x.codigo,x.nome,x.hora_inicio.slice(0,5)+'–'+x.hora_fim.slice(0,5),x.intervalo_minutos+' min',x.escala,String(x.carga_mensal_horas)+' h',x.ativo?'ATIVO':'INATIVO'])}/></>}
  {tab==='epis'&&<><form onSubmit={saveEpi} className="grid grid-cols-1 gap-2 rounded border border-slate-200 bg-white p-3 md:grid-cols-4">
   <div><label className={label}>Código EPI</label><input className={input} required value={epiForm.codigo} onChange={e=>setEpiForm({...epiForm,codigo:e.target.value})}/></div><div className="md:col-span-2"><label className={label}>Nome do equipamento</label><input className={input} required value={epiForm.nome} onChange={e=>setEpiForm({...epiForm,nome:e.target.value})}/></div><div><label className={label}>Número do CA</label><input className={input} required value={epiForm.ca_numero} onChange={e=>setEpiForm({...epiForm,ca_numero:e.target.value})}/></div>
   <div><label className={label}>Validade do CA</label><input className={input} type="date" required value={epiForm.ca_validade} onChange={e=>setEpiForm({...epiForm,ca_validade:e.target.value})}/></div><div><label className={label}>Troca obrigatória (dias)</label><input className={input} type="number" min="1" max="3650" required value={epiForm.periodicidade_troca_dias} onChange={e=>setEpiForm({...epiForm,periodicidade_troca_dias:e.target.value})}/></div><div className="md:col-span-1"><label className={label}>Funções aplicáveis (separadas por vírgula)</label><input className={input} value={epiForm.funcoes_aplicaveis} onChange={e=>setEpiForm({...epiForm,funcoes_aplicaveis:e.target.value})}/></div><div className="flex items-end"><button className={button} disabled={saving||!empresa}>{saving?'Salvando...':'Cadastrar EPI'}</button></div>
  </form><Grid headers={['Código','Equipamento','CA','Validade CA','Troca','Funções','Status']} rows={epis.map(x=>[x.codigo,x.nome,x.ca_numero,x.ca_validade,x.periodicidade_troca_dias+' dias',x.funcoes_aplicaveis.join(', ')||'Todas / não definidas',x.ca_validade<today()?'CA VENCIDO':x.ativo?'ATIVO':'INATIVO'])}/></>}
  {tab==='entregas'&&<><form onSubmit={saveDelivery} className="grid grid-cols-1 gap-2 rounded border border-slate-200 bg-white p-3 md:grid-cols-4">
   <div className="md:col-span-2"><label className={label}>Funcionário</label><select className={input} required value={deliveryForm.funcionario_id} onChange={e=>setDeliveryForm({...deliveryForm,funcionario_id:e.target.value})}><option value="">Selecione funcionário</option>{employees.filter(x=>x.status==='ATIVO').map(x=><option key={x.id} value={x.id}>{x.matricula} • {x.nome_completo}</option>)}</select></div><div className="md:col-span-2"><label className={label}>EPI / Certificado de Aprovação</label><select className={input} required value={deliveryForm.epi_id} onChange={e=>setDeliveryForm({...deliveryForm,epi_id:e.target.value})}><option value="">Selecione EPI</option>{epis.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.codigo} • {x.nome} • CA {x.ca_numero} (até {x.ca_validade})</option>)}</select></div>
   <div><label className={label}>Quantidade entregue</label><input className={input} type="number" min="1" step="1" required value={deliveryForm.quantidade} onChange={e=>setDeliveryForm({...deliveryForm,quantidade:e.target.value})}/></div><div><label className={label}>Data da entrega</label><input className={input} type="date" required value={deliveryForm.entregue_em} onChange={e=>setDeliveryForm({...deliveryForm,entregue_em:e.target.value})}/></div><div className="md:col-span-2"><label className={label}>Observação / comprovante</label><input className={input} value={deliveryForm.observacao} onChange={e=>setDeliveryForm({...deliveryForm,observacao:e.target.value})}/></div><label className="flex items-center gap-2 text-[10px]"><input type="checkbox" checked={deliveryForm.confirmado_recebimento} onChange={e=>setDeliveryForm({...deliveryForm,confirmado_recebimento:e.target.checked})}/> Recebimento confirmado pelo colaborador</label><div className="flex items-end"><button className={button} disabled={saving||!empresa}>{saving?'Salvando...':'Registrar entrega'}</button></div>
  </form><Grid headers={['Entrega','Funcionário','EPI / CA','Qtd.','Data entrega','Próxima troca','Confirmação']} rows={deliveries.map(x=>[x.id.slice(0,8),employeeMap.get(x.funcionario_id)?.nome_completo??'Funcionário indisponível',(epiMap.get(x.epi_id)?.nome??'EPI indisponível')+' • CA '+(epiMap.get(x.epi_id)?.ca_numero??'—'),String(x.quantidade),x.entregue_em,x.proxima_troca_em,x.confirmado_recebimento?'CONFIRMADO':'PENDENTE'])}/></>}
  <p className="text-[9px] text-slate-500">Empresa: {empresa||'não identificada'}. CPF é validado e normalizado; permissões e isolamento por empresa continuam aplicados pelo Supabase/RLS.</p>
 </section></VendasLayout>
}
function Grid({headers,rows}:{headers:string[];rows:string[][]}){return <div className="overflow-x-auto rounded border border-slate-200 bg-white"><table className="industrial-table w-full min-w-[850px] text-[10px]"><thead className="bg-slate-100 text-left text-slate-600"><tr>{headers.map(x=><th key={x} className="h-[32px] px-2 text-[9px] font-medium uppercase">{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t border-slate-100 hover:bg-neutral-50/80">{row.map((cell,j)=><td key={j} className="h-[32px] px-2">{cell}</td>)}</tr>)}{rows.length===0&&<tr><td colSpan={headers.length} className="h-[32px] px-3 text-center text-slate-500">Nenhum registro cadastrado no Supabase para este tenant.</td></tr>}</tbody></table></div>}
