import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, Search, SlidersHorizontal } from 'lucide-react'

type OP={id:string;numero_op:string;produto_id:string|null;quantidade:number;status:string;pedido_venda_id:string|null;data_prevista:string|null}
type Product={id:string;codigo:string;nome:string}
type Program={id:string;ordem_producao_id:string|null;maquina_id:string|null;produto_id:string|null;inicio_planejado:string;fim_planejado:string;quantidade_planejada:number;status:string;molde_id?:string|null;quantidade_produzida?:number;quantidade_refugada?:number}
type Machine={id:string;codigo:string;nome:string;status:string}
type ProgramView=Program & {op?:OP;product?:Product}
const addDays=(d:Date,n:number)=>new Date(d.getFullYear(),d.getMonth(),d.getDate()+n)
const overlaps=(p:ProgramView,day:Date)=>{const s=new Date(p.inicio_planejado),e=new Date(p.fim_planejado),d0=new Date(day.getFullYear(),day.getMonth(),day.getDate()),d1=addDays(d0,1);return s<d1&&e>d0}

export default function PCPMonthlyPlanner({programs,machines,ops,onOpen}:{programs:ProgramView[];machines:Machine[];ops:OP[];onOpen:(opId?:string)=>void}){
 const [cursor,setCursor]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)})
 const [query,setQuery]=useState('')
 const [status,setStatus]=useState('todos')
 const [view,setView]=useState<'month'|'week'|'day'>('month')
 const [machineFilter,setMachineFilter]=useState('todos')
 const days=useMemo(()=>{if(view==='day')return [cursor];if(view==='week'){const day=cursor.getDay();const monday=addDays(cursor,day===0?-6:1-day);return Array.from({length:7},(_,i)=>addDays(monday,i))}const last=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();return Array.from({length:last},(_,i)=>new Date(cursor.getFullYear(),cursor.getMonth(),i+1))},[cursor,view])
 const scheduledIds=useMemo(()=>new Set(programs.map(p=>p.ordem_producao_id).filter(Boolean)),[programs])
 const backlog=useMemo(()=>ops.filter(o=>!scheduledIds.has(o.id)&&(!query||o.numero_op.toLowerCase().includes(query.toLowerCase()))),[ops,scheduledIds,query])
 const dayPrograms=(machineId:string,day:Date)=>active.filter(p=>p.maquina_id===machineId&&overlaps(p,day))
 const active=useMemo(()=>programs.filter(p=>days.some(d=>overlaps(p,d))&&(!query||((p.op?.numero_op||'')+' '+(p.product?.codigo||'')+' '+(p.product?.nome||'')).toLowerCase().includes(query.toLowerCase()))&&(status==='todos'||p.status===status)),[programs,days,query,status])
 const statusClass=(p:ProgramView)=>{const s=(p.status||'').toLowerCase();if(s.includes('manut')||s.includes('parad'))return 'ds-plan-segment--stop';if(s.includes('setup'))return 'ds-plan-segment--setup';if(s.includes('atras'))return 'ds-plan-segment--risk';return 'ds-plan-segment--production'}
 const visibleMachines=machines.filter(m=>machineFilter==='todos'||m.id===machineFilter)
 const monthLabel=view==='month'?cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):view==='week'?`Semana ${days[0]?.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}–${days[6]?.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}`:cursor.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})
 return <section className="pcp-month-planner">
  <aside className="pcp-backlog-rail"><div><strong>BACKLOG</strong><span>{backlog.length} OPs sem programação</span></div>{backlog.slice(0,12).map(o=><button key={o.id} onClick={()=>onOpen(o.id)}><b>{o.numero_op}</b><span>{o.status}</span><small>{o.data_prevista?`Prazo ${new Date(o.data_prevista+'T00:00:00').toLocaleDateString('pt-BR')}`:'Sem prazo'}</small></button>)}{backlog.length===0&&<small className="pcp-backlog-empty">Nenhuma OP pendente de programação.</small>}</aside>
  <div className="pcp-month-main"><div className="pcp-month-toolbar"><div><span>PLANEJAMENTO CENTRAL</span><strong>Planejamento mensal</strong><small>Máquina × dia • programação, capacidade, setup, paradas e risco</small></div><div className="pcp-month-toolbar__actions"><button onClick={()=>{const d=view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()-1,1):addDays(cursor,view==='week'?-7:-1);setCursor(d)}}><ChevronLeft size={17}/></button><div className="pcp-month-view-toggle">{(['month','week','day'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='month'?'Mês':v==='week'?'Semana':'Dia'}</button>)}</div><button className="pcp-month-today" onClick={()=>{const d=new Date();setCursor(new Date(d.getFullYear(),d.getMonth(),d.getDate()))}}>Hoje</button><button onClick={()=>{const d=view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()+1,1):addDays(cursor,view==='week'?7:1);setCursor(d)}}><ChevronRight size={17}/></button><strong>{monthLabel}</strong></div></div></div>
  <div className="pcp-month-filters"><span className="pcp-month-scope">{view==='month'?'Visão mensal':view==='week'?'Visão semanal':'Visão diária'}</span><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="OP, produto ou peça"/></label><label><span style={{fontSize:10,fontWeight:800}}>Máquina</span><select value={machineFilter} onChange={e=>setMachineFilter(e.target.value)}><option value="todos">Todas</option>{machines.map(m=><option key={m.id} value={m.id}>{m.codigo}</option>)}</select></label><label><SlidersHorizontal size={14}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos os status</option><option value="Programada">Programada</option><option value="Em produção">Em produção</option><option value="Atrasada">Atrasada</option><option value="Parada">Parada</option></select></label><div className="pcp-month-legend"><span className="production">Produção</span><span className="setup">Setup</span><span className="idle">Livre</span><span className="stop">Parada</span><span className="risk">Risco</span></div></div>
  <div className="pcp-month-grid-wrap"><div className="pcp-month-grid" style={{gridTemplateColumns:'190px repeat('+days.length+',minmax(58px,1fr))'}}>
   <div className="pcp-month-corner"><span>RECURSO</span><strong>Máquina / Injetora</strong></div>{days.map(d=><div className={'pcp-month-day '+((d.getDay()===0||d.getDay()===6)?'weekend':'')} key={d.toISOString()}><strong>{String(d.getDate()).padStart(2,'0')}</strong><span>{d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</span></div>)}
   {visibleMachines.map(machine=><div key={machine.id} className="pcp-month-row" style={{display:'contents'}}><div className="pcp-month-machine"><strong>{machine.codigo}</strong><span>{machine.nome}</span><small>{machine.status}</small></div>{days.map(day=>{const ps=dayPrograms(machine.id,day);return <button key={day.toISOString()} className={'pcp-month-cell '+(ps.length?'has-program':'')} onDoubleClick={()=>onOpen(ps[0]?.ordem_producao_id||undefined)} onClick={()=>ps[0]&&onOpen(ps[0].ordem_producao_id||undefined)}>{ps.length===0?<span className="pcp-month-empty">—</span>:ps.length===1?<span className={'pcp-month-segment '+statusClass(ps[0])}><b>{ps[0].op?.numero_op||'OP'}</b><small>{ps[0].product?.codigo||'produto'}</small><em>{Number(ps[0].quantidade_planejada||0).toLocaleString('pt-BR')}</em></span>:ps.length===2?<span className="pcp-month-dual">{ps.map(p=><span key={p.id} className={'pcp-month-segment '+statusClass(p)}><b>{p.op?.numero_op||'OP'}</b><small>{p.product?.codigo||'produto'}</small></span>)}</span>:<><span className="pcp-month-triple">{ps.slice(0,3).map(p=><span key={p.id} className={'pcp-month-segment '+statusClass(p)}><b>{p.op?.numero_op||'OP'}</b></span>)}</span><span className="pcp-month-more">+{ps.length-3}</span></>}</button>})}</div>)}
  </div></div>
  <div className="pcp-month-summary"><strong>{active.length} programações</strong><span>{machines.filter(m=>active.some(p=>p.maquina_id===m.id)).length} máquinas com carga</span><span>{active.reduce((s,p)=>s+Number(p.quantidade_planejada||0),0).toLocaleString('pt-BR')} peças planejadas</span><span>{active.filter(p=>String(p.status).toLowerCase().includes('atras')).length} em risco/atraso</span></div></div>
 </div>
 </section>
}
