import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase, supabaseConfigurado } from './lib/supabaseClient'
import { Activity, BarChart3, Boxes, CheckCircle2, ClipboardCheck, Factory, Gauge, KeyRound, LogIn, Menu, Package, Plus, Printer, Search, Settings, ShoppingCart, Truck, Users, Wrench, X } from 'lucide-react'

type Module = { name:string; icon:any; table?:string; title:string; fields?:{key:string;label:string;type?:string;required?:boolean}[] }
const modules:Module[]=[
 {name:'Dashboard',icon:Gauge,title:'Visão geral'},
 {name:'Engenharia / BOM',icon:Boxes,title:'Engenharia e fichas técnicas',table:'erp_fichas_tecnicas',fields:[{key:'produto_id',label:'Produto ID',required:true},{key:'versao',label:'Versão',type:'number',required:true},{key:'rendimento',label:'Rendimento',type:'number',required:true},{key:'unidade_rendimento',label:'Unidade'},{key:'observacoes',label:'Observações'}]},
 {name:'MRP e Planejamento',icon:BarChart3,title:'MRP e planejamento'},
 {name:'Produção / OP',icon:Factory,title:'Ordens de produção',table:'erp_ordens_producao',fields:[{key:'produto_id',label:'Produto ID',required:true},{key:'quantidade_planejada',label:'Quantidade planejada',type:'number',required:true},{key:'data_prevista',label:'Data prevista',type:'date'},{key:'status',label:'Status',required:true},{key:'observacoes',label:'Observações'}]},
 {name:'Estoque / WMS',icon:Package,title:'Produtos e movimentações',table:'erp_produtos',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'unidade',label:'Unidade',required:true},{key:'tipo',label:'Tipo',required:true},{key:'estoque_minimo',label:'Estoque mínimo',type:'number',required:true},{key:'custo_medio',label:'Custo médio',type:'number',required:true},{key:'preco_venda',label:'Preço de venda',type:'number',required:true}]},
 {name:'Compras / Fornecedores',icon:Truck,title:'Fornecedores',table:'erp_fornecedores',fields:[{key:'razao_social',label:'Razão social',required:true},{key:'nome_fantasia',label:'Nome fantasia'},{key:'documento',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone'}]},
 {name:'Vendas / CRM',icon:ShoppingCart,title:'Clientes',table:'erp_clientes',fields:[{key:'nome',label:'Nome',required:true},{key:'documento',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone'}]},
 {name:'Qualidade / QMS',icon:ClipboardCheck,title:'Não conformidades',table:'erp_nao_conformidades',fields:[{key:'origem',label:'Origem',required:true},{key:'severidade',label:'Severidade',required:true},{key:'descricao',label:'Descrição',required:true},{key:'contencao',label:'Contenção'},{key:'causa_raiz',label:'Causa raiz'},{key:'status',label:'Status',required:true}]},
 {name:'Manutenção / CMMS',icon:Wrench,title:'Máquinas',table:'erp_maquinas',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'tipo',label:'Tipo',required:true},{key:'fabricante',label:'Fabricante'},{key:'modelo',label:'Modelo'},{key:'numero_serie',label:'Número de série'},{key:'status',label:'Status',required:true},{key:'localizacao',label:'Localização'}]},
 {name:'Indicadores / OEE',icon:Activity,title:'Indicadores industriais'},
 {name:'Configurações',icon:Settings,title:'Administração'}
]

export default function App(){
 const [session,setSession]=useState<any>(null); const [active,setActive]=useState('Dashboard'); const [open,setOpen]=useState(false); const [login,setLogin]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
 if(!session)return <Login login={login} setLogin={setLogin} password={password} setPassword={setPassword} error={error} loading={loading} setError={setError} setLoading={setLoading}/>
 const mod=modules.find(m=>m.name===active)!
 return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><Factory size={28}/><div><strong>ERP Industrial</strong><span>Gestão inteligente de fábrica</span></div></div><nav>{modules.map(m=><button key={m.name} className={active===m.name?'nav-item active':'nav-item'} onClick={()=>{setActive(m.name);setOpen(false)}}><m.icon size={19}/><span>{m.name}</span></button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">OPERAÇÃO INDUSTRIAL</span><h1>{mod.title}</h1></div><div className="status"><span className="dot"/> Conectado</div></header><section className="content">{active==='Dashboard'?<Dashboard onOpen={setActive}/>:active==='Configurações'?<Configuracoes/>:mod.table?<Crud module={mod}/>:<ModuleLanding module={mod}/>}</section></main></div>
}

function Login(p:any){async function submit(e:FormEvent){e.preventDefault();p.setError('');if(!supabaseConfigurado){p.setError('Supabase não configurado.');return}p.setLoading(true);const normalized=p.login.trim().toLowerCase();const email=normalized.includes('@')?normalized:`${normalized}@usuarios.erp.local`;const {error}=await supabase.auth.signInWithPassword({email,password:p.password});p.setLoading(false);if(error)p.setError(error.message||'Usuário ou senha inválidos.')}return <div className="login-page"><div className="login-card"><div className="login-brand"><Factory size={42}/><h1>ERP Industrial</h1><p>Plataforma completa para sua indústria</p></div><form onSubmit={submit}><label>Usuário ou e-mail<input value={p.login} onChange={e=>p.setLogin(e.target.value)} autoComplete="username" required/></label><label>Senha<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} autoComplete="current-password" required/></label>{p.error&&<div className="error">{p.error}</div>}<button className="primary full" disabled={p.loading}><LogIn size={18}/>{p.loading?'Entrando...':'Entrar no sistema'}</button></form><small>Acesso protegido por Supabase Auth e RLS.</small></div></div>}

function Dashboard({onOpen}:{onOpen:(name:string)=>void}){const cards=[['Estoque / WMS',Package,'Produtos'],['Produção / OP',Factory,'Ordens de produção'],['Compras / Fornecedores',Truck,'Fornecedores'],['Vendas / CRM',ShoppingCart,'Clientes'],['Qualidade / QMS',ClipboardCheck,'Qualidade'],['Manutenção / CMMS',Wrench,'Máquinas'],['MRP e Planejamento',BarChart3,'Planejamento'],['Indicadores / OEE',Activity,'Indicadores']];return <><div className="hero"><div><span className="eyebrow">VISÃO EXECUTIVA</span><h2>Controle sua indústria em um único lugar.</h2><p>Produção, materiais, qualidade, manutenção, custos e indicadores conectados.</p></div><Factory size={58}/></div><div className="cards"><Metric title="Produção hoje" value="—" note="Dados reais do ambiente"/><Metric title="OEE" value="—" note="Disponível após apontamentos"/><Metric title="Qualidade" value="—" note="Inspeções e NCR"/><Metric title="Estoque" value="—" note="Saldo por produto"/></div><div className="panel"><h3>Acesso rápido</h3><p>Abra diretamente a área que deseja operar.</p><div className="module-grid">{cards.map(([name,Icon,label])=><button key={String(name)} className="feature" onClick={()=>onOpen(String(name))}><Icon size={22}/><span><strong>{label}</strong><small>{String(name)}</small></span></button>)}</div></div><div className="panel"><h3>Fluxo industrial</h3><div className="module-grid"><span>✓ Engenharia → BOM</span><span>✓ MRP → OP</span><span>✓ OP → Estoque</span><span>✓ Qualidade → CAPA</span><span>✓ Manutenção → Disponibilidade</span><span>✓ Vendas → Planejamento</span></div></div></>}
function ModuleLanding({module}:{module:Module}){return <div className="panel"><div className="panel-head"><div><span className="eyebrow">MÓDULO</span><h2>{module.title}</h2></div><module.icon size={42}/></div><p>Área operacional preparada para conectar os dados do Supabase. Os fluxos de produção, MRP, qualidade, manutenção e indicadores usam os mesmos registros da empresa.</p><div className="feature-grid"><Feature t="Rastreabilidade"/><Feature t="Permissões por cargo"/><Feature t="Auditoria"/><Feature t="Indicadores"/><Feature t="Validações"/><Feature t="Histórico"/></div></div>}
function Feature({t}:{t:string}){return <div className="feature"><CheckCircle2 size={18}/><span>{t}</span></div>}
function Metric({title,value,note}:{title:string,value:string,note:string}){return <div className="metric"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}

function Crud({module}:{module:Module}){const [rows,setRows]=useState<any[]>([]);const [q,setQ]=useState('');const [editing,setEditing]=useState<any|null>(null);const [show,setShow]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [empresaId,setEmpresaId]=useState<string|null>(null);const fields=module.fields||[]
 async function load(){const {data,error}=await supabase.from(module.table!).select('*').order('created_at',{ascending:false}).limit(200);if(error)setMessage(error.message);else setRows(data||[])}
 useEffect(()=>{load();supabase.auth.getUser().then(async({data})=>{if(!data.user)return;const {data:p}=await supabase.from('erp_usuarios').select('empresa_id').eq('auth_user_id',data.user.id).maybeSingle();setEmpresaId(p?.empresa_id||null)})},[module.table])
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q])
 function form(){const initial:any={};fields.forEach(f=>initial[f.key]=editing?.[f.key]??'');return initial}
 const [data,setData]=useState<any>(form());useEffect(()=>setData(form()),[editing])
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');if(!editing&&!empresaId){setMessage('Empresa do usuário não encontrada.');setSaving(false);return}const payload:any={};for(const f of fields){const v=data[f.key];if(f.required&&!String(v??'').trim()){setMessage(`Preencha ${f.label}.`);setSaving(false);return}payload[f.key]=f.type==='number'?(v===''?0:Number(v)):v}if(!editing)payload.empresa_id=empresaId;const result=editing?await supabase.from(module.table!).update(payload).eq('id',editing.id):await supabase.from(module.table!).insert(payload);if(result.error)setMessage(result.error.message);else{const wasEditing=Boolean(editing);setShow(false);setEditing(null);await load();setMessage(wasEditing?'Registro atualizado.':'Registro criado.')}setSaving(false)}
 async function remove(id:string){if(!confirm('Confirma a exclusão deste registro?'))return;const {error}=await supabase.from(module.table!).delete().eq('id',id);if(error)setMessage(error.message);else{await load();setMessage('Registro excluído.')}}
 return <div className="panel"><div className="panel-head"><div><span className="eyebrow">CADASTRO OPERACIONAL</span><h2>{module.title}</h2></div><button className="primary" onClick={()=>{setEditing(null);setShow(true)}}><Plus size={18}/> Novo</button></div><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Pesquisar..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} registros</span></div>{message&&<div className="notice">{message}</div>}<div className="table-wrap"><table><thead><tr>{fields.slice(0,6).map(f=><th key={f.key}>{f.label}</th>)}<th>Ações</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{fields.slice(0,6).map(f=><td key={f.key}>{String(r[f.key]??'—')}</td>)}<td className="actions"><button onClick={()=>{setEditing(r);setShow(true)}}>Editar</button><button className="danger" onClick={()=>remove(r.id)}>Excluir</button></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div>{show&&<div className="modal"><form className="modal-card" onSubmit={save}><div className="panel-head"><h3>{editing?'Editar registro':'Novo registro'}</h3><button type="button" className="icon-btn" onClick={()=>setShow(false)}><X/></button></div><div className="form-grid">{fields.map(f=><label key={f.key}>{f.label}<input type={f.type||'text'} value={data[f.key]??''} onChange={e=>setData({...data,[f.key]:e.target.value})} required={f.required}/></label>)}</div><div className="modal-actions"><button type="button" onClick={()=>setShow(false)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando...':'Gravar'}</button></div></form></div>}</div>}

function Configuracoes(){const [tab,setTab]=useState('usuarios');const [setores,setSetores]=useState<any[]>([]);const [selected,setSelected]=useState<string[]>([]);const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [msg,setMsg]=useState('');const [creds,setCreds]=useState<any[]>([]);useEffect(()=>{supabase.from('erp_setores').select('id,codigo,nome').eq('ativo',true).order('nome').then(({data})=>setSetores(data||[]))},[])
 async function changePassword(e:FormEvent){e.preventDefault();setMsg('');const {data:{session}}=await supabase.auth.getSession();if(!session){setMsg('Sessão expirada.');return}const {data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'change_password',currentPassword:current,newPassword:next}});if(error)setMsg(error.message);else setMsg(data?.message||data?.error||'Concluído.');if(data?.ok){setCurrent('');setNext('')}}
 async function createUsers(){setMsg('');setCreds([]);if(!selected.length){setMsg('Selecione pelo menos um setor.');return}const sectorIds=selected;const {data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'create_batch',sectors:sectorIds}});if(error)setMsg(error.message);else{const list=data?.usuarios||data?.credenciais||[];setCreds(list.map((c:any)=>({setor:c.setor,login:c.login,password:c.password,ok:c.status==='criado'||c.ok,error:c.error})));setMsg(data?.ok===false?data?.error||'Falha ao criar usuários.': 'Processamento concluído.')}}
 function print(){window.print()}
 return <div className="panel"><div className="tabs"><button className={tab==='usuarios'?'tab active':'tab'} onClick={()=>setTab('usuarios')}><Users size={17}/> Usuários por setor</button><button className={tab==='senha'?'tab active':'tab'} onClick={()=>setTab('senha')}><KeyRound size={17}/> Alterar minha senha</button></div>{tab==='usuarios'?<><div className="panel-head"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h2>Criar usuários para os setores</h2><p>Selecione os setores da empresa. O sistema monta o login pela sigla da empresa + setor e gera uma senha inicial.</p></div><button className="primary" onClick={createUsers}><Users size={18}/> Criar usuários e senhas</button></div><div className="sector-grid">{setores.map(s=><label className={selected.includes(s.id)?'sector selected':'sector'} key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(x=>x!==s.id))}/><strong>{s.codigo}</strong><span>{s.nome}</span></label>)}</div>{creds.length>0&&<div className="credentials"><div className="panel-head"><h3>Credenciais geradas</h3><button onClick={print}><Printer size={17}/> Imprimir</button></div><table><thead><tr><th>Setor</th><th>Usuário</th><th>Senha inicial</th><th>Status</th></tr></thead><tbody>{creds.map((c,i)=><tr key={i}><td>{c.setor}</td><td>{c.login}</td><td><code>{c.password||'Já existente'}</code></td><td>{c.ok?'Criado':'Erro: '+c.error}</td></tr>)}</tbody></table></div>}</>:<form className="password-box" onSubmit={changePassword}><h2>Alterar minha senha</h2><p>A senha atual será validada para o usuário autenticado.</p><label>Senha atual<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>Nova senha<input type="password" value={next} onChange={e=>setNext(e.target.value)} minLength={8} required/></label><button className="primary"><KeyRound size={18}/> Alterar senha</button></form>}{msg&&<div className="notice">{msg}</div>}</div>}
