import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, Boxes, CalendarDays, ClipboardCheck, Factory, KeyRound, LogIn, Menu, Package, Plus, Search, Settings, ShoppingCart, Truck, Users, Wrench, X } from 'lucide-react'
import { supabase, supabaseConfigurado } from './lib/supabaseClient'

type Field={key:string;label:string;type?:string;required?:boolean}
type Mod={name:string;title:string;icon:any;table?:string;fields?:Field[]}
const mods:Mod[]=[
{name:'Dashboard',title:'Visão geral',icon:BarChart3},
{name:'Engenharia / BOM',title:'Engenharia e BOM',icon:Boxes,table:'erp_fichas_tecnicas',fields:[{key:'produto_id',label:'Produto ID',required:true},{key:'versao',label:'Versão',type:'number',required:true},{key:'rendimento',label:'Rendimento',type:'number'},{key:'unidade_rendimento',label:'Unidade'},{key:'observacoes',label:'Observações'}]},
{name:'MRP e Planejamento',title:'MRP e Planejamento',icon:Activity,table:'erp_parametros_processo',fields:[{key:'processo_id',label:'Processo ID',required:true},{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'tipo',label:'Tipo'},{key:'unidade',label:'Unidade'},{key:'valor_padrao',label:'Valor padrão'}]},
{name:'Produção / OP',title:'Ordens de produção',icon:Factory,table:'erp_ordens_producao',fields:[{key:'produto_id',label:'Produto ID',required:true},{key:'quantidade_planejada',label:'Quantidade',type:'number',required:true},{key:'data_prevista',label:'Data prevista',type:'date'},{key:'status',label:'Status',required:true},{key:'observacoes',label:'Observações'}]},
{name:'PCP / Agenda de Máquinas',title:'Agenda semanal de máquinas',icon:CalendarDays,table:'erp_ordem_processos',fields:[{key:'ordem_producao_id',label:'OP ID',required:true},{key:'processo_id',label:'Processo ID',required:true},{key:'sequencia',label:'Sequência',type:'number',required:true},{key:'maquina_id',label:'Máquina ID'},{key:'status',label:'Status'}]},
{name:'Estoque / WMS',title:'Produtos e materiais',icon:Package,table:'erp_produtos',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'tipo',label:'Tipo'},{key:'unidade',label:'Unidade'},{key:'estoque_minimo',label:'Estoque mínimo',type:'number'},{key:'custo_medio',label:'Custo médio',type:'number'},{key:'preco_venda',label:'Preço venda',type:'number'}]},
{name:'Compras / Fornecedores',title:'Fornecedores',icon:Truck,table:'erp_fornecedores',fields:[{key:'razao_social',label:'Razão social',required:true},{key:'nome_fantasia',label:'Nome fantasia'},{key:'documento',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone'}]},
{name:'Vendas / CRM',title:'Clientes',icon:ShoppingCart,table:'erp_clientes',fields:[{key:'nome',label:'Nome',required:true},{key:'documento',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone'}]},
{name:'Qualidade / QMS',title:'Não conformidades / RPNC',icon:ClipboardCheck,table:'erp_nao_conformidades',fields:[{key:'origem',label:'Origem',required:true},{key:'severidade',label:'Severidade',required:true},{key:'descricao',label:'Descrição',required:true},{key:'status',label:'Status',required:true},{key:'prazo',label:'Prazo',type:'date'}]},
{name:'Manutenção / CMMS',title:'Máquinas e manutenção',icon:Wrench,table:'erp_maquinas',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'tipo',label:'Tipo',required:true},{key:'fabricante',label:'Fabricante'},{key:'modelo',label:'Modelo'},{key:'status',label:'Status'}]},
{name:'Indicadores / OEE',title:'Indicadores industriais',icon:Activity,table:'erp_apontamentos_producao',fields:[{key:'ordem_producao_id',label:'OP ID',required:true},{key:'turno',label:'Turno'},{key:'quantidade_boa',label:'Quantidade boa',type:'number'},{key:'quantidade_refugo',label:'Refugo',type:'number'},{key:'parada_min',label:'Parada (min)',type:'number'}]},
{name:'Cadastros',title:'Cadastros mestres',icon:Users},
{name:'Configurações',title:'Segurança',icon:Settings}]

const today=new Date().toISOString().slice(0,10)
const text=(v:unknown)=>String(v??'—')

export default function AppIndustrial(){
 const [session,setSession]=useState<any>(); const [loading,setLoading]=useState(true); const [active,setActive]=useState('Dashboard'); const [open,setOpen]=useState(false)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const l=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.data.subscription.unsubscribe()},[])
 if(loading)return <div className="loading-screen">Carregando ERP Sistema Industrial…</div>
 if(!session)return <Login/>
 const m=mods.find(x=>x.name===active)!
 return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><img src="/logo-industrial.svg" alt="SGQ ERP"/><div><strong>SGQ ERP</strong><span>Sistema de Gestão Industrial</span></div></div><nav>{mods.map(x=><button className={active===x.name?'nav-item active':'nav-item'} key={x.name} onClick={()=>{setActive(x.name);setOpen(false)}}><x.icon size={18}/><span>{x.name}</span></button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">OPERAÇÃO INDUSTRIAL</span><h1>{m.title}</h1></div><span className="status"><i/> Conectado</span></header><section className="content"><Page m={m}/></section><footer>FernandoSch_System • SGQ ERP • Sistema de Gestão Industrial</footer></main></div>
}

function Login(){const[u,setU]=useState('');const[p,setP]=useState('');const[e,setE]=useState('');const[b,setB]=useState(false);async function go(ev:FormEvent){ev.preventDefault();setE('');if(!supabaseConfigurado){setE('Supabase não configurado.');return}setB(true);const v=u.trim().toLowerCase();const email=v.includes('@')?v:`${v}@acesso.erp.local`;const{error}=await supabase.auth.signInWithPassword({email,password:p});setB(false);if(error)setE('Usuário ou senha inválidos.')}return <div className="login-page"><div className="login-art"><img src="/login-sgq-erp.svg" alt="SGQ ERP — Sistema de Gestão Industrial"/></div><form className="login-card" onSubmit={go}><div className="login-brand"><img src="/logo-industrial.svg" alt="SGQ ERP"/><div><h1>SGQ ERP</h1><p>Sistema de Gestão Industrial</p></div></div><label>Usuário ou e-mail<input value={u} onChange={x=>setU(x.target.value)} autoComplete="username" required/></label><label>Senha<div className="password-input"><input type="password" value={p} onChange={x=>setP(x.target.value)} autoComplete="current-password" required/><KeyRound size={18}/></div></label>{e&&<div className="error">{e}</div>}<button className="primary full" disabled={b}><LogIn size={18}/>{b?'Entrando…':'Acessar'}</button><button type="button" className="secondary full" onClick={()=>{setU('');setP('');setE('')}}>Cancelar</button></form></div>}

function Page({m}:{m:Mod}){if(m.name==='Dashboard')return <Dashboard/>;if(m.name==='Cadastros')return <Master/>;if(m.name==='Configurações')return <Security/>;if(!m.table)return <Panel m={m}/>;return <Crud m={m}/>}

function Dashboard(){const[c,setC]=useState({ops:0,rpnc:0,venc:0,manut:0,produtos:0});const[busy,setBusy]=useState(true);useEffect(()=>{let alive=true;(async()=>{setBusy(true);const [ops,rpnc,venc,manut,prod]=await Promise.all([supabase.from('erp_ordens_producao').select('id',{count:'exact',head:true}).in('status',['planejada','em_producao','aberta']),supabase.from('erp_nao_conformidades').select('id',{count:'exact',head:true}).in('status',['aberta','pendente']).lt('prazo',today),supabase.from('erp_lotes_materiais').select('id',{count:'exact',head:true}).lt('validade',today).gt('quantidade_disponivel',0),supabase.from('erp_manutencoes_maquinas').select('id',{count:'exact',head:true}).lt('inicio',new Date().toISOString()).neq('status','concluida'),supabase.from('erp_produtos').select('id',{count:'exact',head:true})]);if(alive)setC({ops:ops.count||0,rpnc:rpnc.count||0,venc:venc.count||0,manut:manut.count||0,produtos:prod.count||0});setBusy(false)})().catch(()=>setBusy(false));return()=>{alive=false}},[]);const metrics=[['Ordens abertas',c.ops,'ordens em fluxo'],['RPNC sem responder',c.rpnc,'qualidade pendente'],['Material vencido',c.venc,'lotes disponíveis'],['Equipamentos vencidos',c.manut,'manutenções pendentes']];const max=Math.max(1,...metrics.map(x=>Number(x[1])));return <><div className="hero"><div><span className="eyebrow">VISÃO EXECUTIVA</span><h2>Controle da fábrica em uma única tela.</h2><p>Indicadores calculados diretamente dos dados operacionais. Clique em qualquer módulo para trocar a tela sem sair do sistema.</p></div><Factory size={62}/></div><div className="cards">{metrics.map(([t,v,s])=><div className="metric" key={String(t)}><span>{t}</span><strong>{busy?'…':String(v)}</strong><small>{s}</small></div>)}</div><div className="dashboard-grid"><div className="panel"><h3>Indicadores em gráfico</h3><div className="bars">{metrics.map(([t,v])=><div className="bar-row" key={String(t)}><div><b>{t}</b><span>{String(v)}</span></div><div className="bar-track"><i style={{width:`${Math.min(100,Number(v)/max*100)}%`}}/></div></div>)}</div></div><div className="panel"><h3>Resumo operacional</h3><div className="feature-grid"><span><Package size={18}/> Produtos cadastrados: <b>{c.produtos}</b></span><span><Factory size={18}/> Produção: OP → processo → apontamento</span><span><Boxes size={18}/> Estoque: lote → validade → consumo</span><span><ClipboardCheck size={18}/> Qualidade: RPNC → ação → evidência</span><span><Wrench size={18}/> Manutenção: máquina → ordem → execução</span><span><Users size={18}/> Usuários por empresa e permissão</span></div></div></div></>}

function Panel({m}:{m:Mod}){return <div className="panel"><div className="panel-head"><div><span className="eyebrow">MÓDULO</span><h2>{m.title}</h2></div><m.icon size={44}/></div><p>Este módulo está conectado à estrutura industrial e será alimentado pelos registros reais.</p></div>}

function Crud({m}:{m:Mod}){const fs=m.fields||[];const[rows,setRows]=useState<any[]>([]);const[q,setQ]=useState('');const[edit,setEdit]=useState<any>();const[show,setShow]=useState(false);const[d,setD]=useState<any>({});const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);async function load(){const{data,error}=await supabase.from(m.table!).select('*').order('created_at',{ascending:false}).limit(200);if(error)setMsg(error.message);else setRows(data||[])}useEffect(()=>{void load()},[m.table]);const list=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);function novo(){const x:any={};fs.forEach(f=>x[f.key]='');setD(x);setEdit(null);setMsg('');setShow(true)}function editar(r:any){setD({...r});setEdit(r);setMsg('');setShow(true)}async function save(e:FormEvent){e.preventDefault();setMsg('');for(const f of fs)if(f.required&&!String(d[f.key]??'').trim()){setMsg(`Preencha ${f.label}.`);return}setBusy(true);const payload:any={};fs.forEach(f=>payload[f.key]=f.type==='number'?Number(d[f.key]||0):d[f.key]);const r=edit?await supabase.from(m.table!).update(payload).eq('id',edit.id):await supabase.from(m.table!).insert(payload);setBusy(false);if(r.error)setMsg(r.error.message);else{setShow(false);await load();setMsg(edit?'Registro atualizado.':'Registro criado.')}}async function del(id:string){if(!confirm('Excluir este registro?'))return;const{error}=await supabase.from(m.table!).delete().eq('id',id);if(error)setMsg(error.message);else await load()}return <div className="panel"><div className="panel-head"><div><span className="eyebrow">CRUD</span><h2>{m.title}</h2></div><button className="primary" onClick={novo}><Plus size={17}/> Novo</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Pesquisar..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{list.length} registros</span></div>{msg&&<div className="notice">{msg}</div>}<div className="table-wrap"><table><thead><tr>{fs.map(f=><th key={f.key}>{f.label}</th>)}<th>Ações</th></tr></thead><tbody>{list.map(r=><tr key={r.id}>{fs.map(f=><td key={f.key}>{text(r[f.key])}</td>)}<td className="actions"><button onClick={()=>editar(r)}>Editar</button><button className="danger" onClick={()=>void del(r.id)}>Excluir</button></td></tr>)}{!list.length&&<tr><td colSpan={fs.length+1} className="empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div>{show&&<div className="modal"><form className="modal-card" onSubmit={save}><div className="panel-head"><h3>{edit?'Editar':'Novo'} registro</h3><button type="button" onClick={()=>setShow(false)}><X/></button></div><div className="form-grid">{fs.map(f=><label key={f.key}>{f.label}<input type={f.type||'text'} value={d[f.key]??''} onChange={e=>setD({...d,[f.key]:e.target.value})} required={f.required}/></label>)}</div><button className="primary" disabled={busy}>{busy?'Salvando…':'Gravar no sistema'}</button></form></div>}</div>}

function Master(){const[tab,setTab]=useState('Setores');const defs:any={Setores:{title:'Setores',table:'erp_setores',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true}]},Máquinas:{title:'Máquinas',table:'erp_maquinas',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'tipo',label:'Tipo',required:true},{key:'fabricante',label:'Fabricante'},{key:'modelo',label:'Modelo'},{key:'status',label:'Status'}]}};return <div><div className="tabs">{['Setores','Máquinas','Usuários'].map(t=><button className={tab===t?'tab active':'tab'} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==='Usuários'?<UserAdmin/>:<Crud m={{name:tab,title:defs[tab].title,icon:Users,table:defs[tab].table,fields:defs[tab].fields}}/>}</div>}
function UserAdmin(){return <div className="panel"><span className="eyebrow">ADMINISTRAÇÃO</span><h2>Usuários</h2><p>O gerenciamento de usuários permanece protegido pelas funções administrativas do ERP. Use a área de segurança para alterar sua própria senha.</p><div className="notice">Integração com erp_usuarios ativa e isolada por empresa.</div></div>}
function Security(){const[cur,setCur]=useState('');const[next,setNext]=useState('');const[msg,setMsg]=useState('');async function change(e:FormEvent){e.preventDefault();setMsg('');if(next.length<8){setMsg('A nova senha deve ter pelo menos 8 caracteres.');return}const{data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'change_my_password',currentPassword:cur,newPassword:next}});setMsg(error?.message||data?.message||'Processamento concluído.');if(data?.ok){setCur('');setNext('')}}return <div className="panel narrow"><span className="eyebrow">SEGURANÇA</span><h2>Alterar minha senha</h2><p>A senha atual é validada antes da alteração.</p><form className="password-box" onSubmit={change}><label>Senha atual<input type="password" value={cur} onChange={e=>setCur(e.target.value)} required/></label><label>Nova senha<input type="password" value={next} onChange={e=>setNext(e.target.value)} minLength={8} required/></label><button className="primary"><KeyRound size={18}/> Alterar senha</button></form>{msg&&<div className="notice">{msg}</div>}</div>}
