import {useEffect,useMemo,useState} from 'react'
import {Activity,BarChart3,Boxes,CalendarDays,ClipboardCheck,Factory,KeyRound,LogIn,Menu,Package,Plus,Printer,Search,Settings,ShoppingCart,Truck,Users,Wrench,X} from 'lucide-react'
import {supabase,supabaseConfigurado} from './lib/supabaseClient'
import MachineAgenda from './components/MachineAgenda'

type Field={key:string;label:string;type?:string;required?:boolean}
type Mod={name:string;title:string;icon:any;table?:string;fields?:Field[]}
const mods:Mod[]=[
{name:'Dashboard',title:'Visão geral',icon:BarChart3},
{name:'Engenharia / BOM',title:'Engenharia e BOM',icon:Boxes,table:'boms',fields:[{key:'produto_id',label:'Produto ID',required:true},{key:'versao',label:'Versão',required:true},{key:'status',label:'Status',required:true}]},
{name:'MRP e Planejamento',title:'MRP e Planejamento',icon:BarChart3},{name:'Produção / OP',title:'Ordens de produção',icon:Factory,table:'ordens_producao',fields:[{key:'produto_id',label:'Produto ID',required:true},{key:'quantidade_planejada',label:'Quantidade',type:'number',required:true},{key:'data_prevista',label:'Data prevista',type:'date'},{key:'status',label:'Status',required:true}]},
{name:'PCP / Agenda de Máquinas',title:'Agenda semanal de máquinas',icon:CalendarDays},{name:'Estoque / WMS',title:'Produtos',icon:Package,table:'produtos',fields:[{key:'codigo',label:'Código',required:true},{key:'descricao',label:'Descrição',required:true},{key:'tipo',label:'Tipo',required:true},{key:'custo_padrao',label:'Custo padrão',type:'number'},{key:'preco_venda',label:'Preço venda',type:'number'}]},
{name:'Compras / Fornecedores',title:'Fornecedores',icon:Truck,table:'fornecedores',fields:[{key:'razao_social',label:'Razão social',required:true},{key:'cnpj',label:'CNPJ'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone'}]},
{name:'Vendas / CRM',title:'Clientes',icon:ShoppingCart,table:'clientes',fields:[{key:'nome',label:'Nome',required:true},{key:'documento',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone'}]},
{name:'Qualidade / QMS',title:'Não conformidades',icon:ClipboardCheck,table:'nao_conformidades',fields:[{key:'origem',label:'Origem',required:true},{key:'severidade',label:'Severidade',required:true},{key:'descricao',label:'Descrição',required:true},{key:'status',label:'Status',required:true}]},
{name:'Manutenção / CMMS',title:'Ativos de manutenção',icon:Wrench,table:'ativos_manutencao',fields:[{key:'codigo',label:'Código',required:true},{key:'descricao',label:'Descrição',required:true},{key:'setor',label:'Setor'},{key:'criticidade',label:'Criticidade',required:true}]},
{name:'Indicadores / OEE',title:'Indicadores industriais',icon:Activity},{name:'Cadastros',title:'Cadastros mestres',icon:Users},{name:'Configurações',title:'Segurança',icon:Settings}]

export default function AppIndustrial(){const[session,setSession]=useState<any>();const[loading,setLoading]=useState(true);const[active,setActive]=useState('Dashboard');const[open,setOpen]=useState(false);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const l=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.data.subscription.unsubscribe()},[]);if(loading)return <div className="loading-screen">Carregando ERP Sistema Industrial…</div>;if(!session)return <Login/>;const m=mods.find(x=>x.name===active)!;return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><Factory size={30}/><div><strong>ERP Sistema Industrial</strong><span>Gestão inteligente da fábrica</span></div></div><nav>{mods.map(x=><button className={active===x.name?'nav-item active':'nav-item'} key={x.name} onClick={()=>{setActive(x.name);setOpen(false)}}><x.icon size={18}/><span>{x.name}</span></button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">OPERAÇÃO INDUSTRIAL</span><h1>{m.title}</h1></div><span className="status"><i/> Conectado</span></header><section className="content"><Page m={m}/></section><footer>FernandoSch_System • ERP Sistema Industrial</footer></main></div>}
function Login(){const[u,setU]=useState('');const[p,setP]=useState('');const[e,setE]=useState('');const[b,setB]=useState(false);async function go(ev:any){ev.preventDefault();setE('');if(!supabaseConfigurado){setE('Supabase não configurado.');return}setB(true);const v=u.trim().toLowerCase();const email=v.includes('@')?v:`${v}@acesso.erp.local`;const{error}=await supabase.auth.signInWithPassword({email,password:p});setB(false);if(error)setE('Usuário ou senha inválidos.')}return <div className="login-page"><form className="login-card" onSubmit={go}><div className="login-brand"><Factory size={48}/><h1>ERP Sistema Industrial</h1><p>Gestão completa da sua indústria</p></div><label>Usuário ou e-mail<input value={u} onChange={x=>setU(x.target.value)} required/></label><label>Senha<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label>{e&&<div className="error">{e}</div>}<button className="primary full" disabled={b}><LogIn size={18}/>{b?'Entrando…':'Entrar no sistema'}</button></form></div>}
function Page({m}:{m:Mod}){if(m.name==='Dashboard')return <Dashboard/>;if(m.name==='PCP / Agenda de Máquinas')return <MachineAgenda/>;if(m.name==='Cadastros')return <Master/>;if(m.name==='Configurações')return <Security/>;if(!m.table)return <Panel m={m}/>;return <Crud m={m}/>}
function Dashboard(){return <><div className="hero"><div><span className="eyebrow">VISÃO EXECUTIVA</span><h2>Da venda à produção, tudo conectado.</h2><p>PCP, estoque, qualidade, manutenção, custos e indicadores em uma única operação.</p></div><Factory size={62}/></div><div className="cards"><Metric t="OPs em produção"/><Metric t="OEE"/><Metric t="NCR abertas"/><Metric t="Estoque crítico"/></div><div className="panel"><h3>Fluxo industrial</h3><div className="feature-grid"><span>Venda → MRP → OP</span><span>BOM → materiais</span><span>OP → estoque</span><span>Inspeção → NCR → CAPA</span><span>Máquina → PCP → manutenção</span><span>Auditoria e rastreabilidade</span></div></div></>}
function Metric({t}:{t:string}){return <div className="metric"><span>{t}</span><strong>—</strong><small>calculado com dados reais</small></div>};function Panel({m}:{m:Mod}){return <div className="panel"><div className="panel-head"><div><span className="eyebrow">MÓDULO</span><h2>{m.title}</h2></div><m.icon size={44}/></div><p>Sem números fictícios. Os indicadores serão calculados pelos registros operacionais reais.</p><div className="cards"><Metric t="Disponibilidade"/><Metric t="Performance"/><Metric t="Qualidade"/><Metric t="OEE"/></div></div>}
function Crud({m}:{m:Mod}){const fs=m.fields||[];const[rows,setRows]=useState<any[]>([]);const[q,setQ]=useState('');const[edit,setEdit]=useState<any>();const[show,setShow]=useState(false);const[d,setD]=useState<any>({});const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);async function load(){const{data,error}=await supabase.from(m.table!).select('*').order('created_at',{ascending:false}).limit(200);if(error)setMsg(error.message);else setRows(data||[])}useEffect(()=>{load()},[m.table]);const list=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);function novo(){const x:any={};fs.forEach(f=>x[f.key]='');setD(x);setEdit(null);setShow(true)}function editar(r:any){setD({...r});setEdit(r);setShow(true)}async function save(e:any){e.preventDefault();for(const f of fs)if(f.required&&!String(d[f.key]??'').trim()){setMsg(`Preencha ${f.label}.`);return}setBusy(true);const p:any={};fs.forEach(f=>p[f.key]=f.type==='number'?Number(d[f.key]||0):d[f.key]);const r=edit?await supabase.from(m.table!).update(p).eq('id',edit.id):await supabase.from(m.table!).insert(p);setBusy(false);if(r.error)setMsg(r.error.message);else{setShow(false);await load();setMsg(edit?'Registro atualizado.':'Registro criado.')}}async function del(id:string){if(!confirm('Excluir este registro?'))return;const{error}=await supabase.from(m.table!).delete().eq('id',id);if(error)setMsg(error.message);else load()}return <div className="panel"><div className="panel-head"><div><span className="eyebrow">CRUD COMPLETO</span><h2>{m.title}</h2></div><button className="primary" onClick={novo}><Plus size={17}/> Novo</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Pesquisar..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{list.length} registros</span></div>{msg&&<div className="notice">{msg}</div>}<div className="table-wrap"><table><thead><tr>{fs.map(f=><th key={f.key}>{f.label}</th>)}<th>Ações</th></tr></thead><tbody>{list.map(r=><tr key={r.id}>{fs.map(f=><td key={f.key}>{String(r[f.key]??'—')}</td>)}<td className="actions"><button onClick={()=>editar(r)}>Editar</button><button className="danger" onClick={()=>del(r.id)}>Excluir</button></td></tr>)}{!list.length&&<tr><td colSpan={fs.length+1} className="empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div>{show&&<div className="modal"><form className="modal-card" onSubmit={save}><div className="panel-head"><h3>{edit?'Editar':'Novo'} registro</h3><button type="button" onClick={()=>setShow(false)}><X/></button></div><div className="form-grid">{fs.map(f=><label key={f.key}>{f.label}<input type={f.type||'text'} value={d[f.key]??''} onChange={e=>setD({...d,[f.key]:e.target.value})} required={f.required}/></label>)}</div><button className="primary" disabled={busy}>{busy?'Salvando…':'Gravar'}</button></form></div>}</div>}
function Master(){const[tab,setTab]=useState('Setores');return <div><div className="tabs">{['Setores','Máquinas','Usuários'].map(t=><button className={tab===t?'tab active':'tab'} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==='Usuários'?<UserAdmin/>:<Crud m={tab==='Máquinas'?{name:tab,title:'Máquinas',icon:Factory,table:'maquinas',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true},{key:'tipo',label:'Tipo',required:true},{key:'fabricante',label:'Fabricante'},{key:'modelo',label:'Modelo'},{key:'status',label:'Status',required:true}]}:{name:tab,title:'Setores',icon:Users,table:'setores',fields:[{key:'codigo',label:'Código',required:true},{key:'nome',label:'Nome',required:true}]}}/>}</div>}
function UserAdmin(){const[s,setS]=useState<any[]>([]);const[sel,setSel]=useState<string[]>([]);const[out,setOut]=useState<any[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{supabase.from('setores').select('id,codigo,nome').eq('ativo',true).order('nome').then(({data,error})=>{setS(data||[]);if(error)setMsg(error.message)})},[]);async function create(){if(!sel.length){setMsg('Selecione os setores.');return}setBusy(true);const{data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'create_users',sector_ids:sel}});setBusy(false);if(error)setMsg(error.message);else{setOut(data?.credentials||[]);setMsg(data?.message||'Usuários processados.')}}return <div className="panel"><div className="panel-head"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h2>Criar usuários e senhas</h2><p>Selecione setores; o servidor monta sigla da empresa + setor e gera senha inicial.</p></div><button onClick={()=>window.print()}><Printer size={17}/> Imprimir</button></div><div className="sector-grid">{s.map(x=><label className={sel.includes(x.id)?'sector selected':'sector'} key={x.id}><input type="checkbox" checked={sel.includes(x.id)} onChange={e=>setSel(e.target.checked?[...sel,x.id]:sel.filter(i=>i!==x.id))}/><strong>{x.codigo}</strong><span>{x.nome}</span></label>)}</div><button className="primary" disabled={busy} onClick={create}><Users size={18}/>{busy?'Criando…':'Criar usuários e senhas'}</button>{msg&&<div className="notice">{msg}</div>}{out.length>0&&<div className="credentials"><h3>Credenciais geradas</h3>{out.map((x,i)=><div className="credential" key={i}><b>{x.setor}</b><span>Usuário: {x.login}</span><span>Senha: {x.password}</span></div>)}</div>}</div>}
function Security(){const[cur,setCur]=useState('');const[next,setNext]=useState('');const[msg,setMsg]=useState('');async function change(e:any){e.preventDefault();if(next.length<8){setMsg('A nova senha deve ter pelo menos 8 caracteres.');return}const{data,error}=await supabase.functions.invoke('erp-user-admin',{body:{action:'change_my_password',currentPassword:cur,newPassword:next}});setMsg(error?.message||data?.message||'Processamento concluído.');if(data?.ok){setCur('');setNext('')}}return <div className="panel narrow"><span className="eyebrow">SEGURANÇA</span><h2>Alterar minha senha</h2><p>A senha atual é validada antes da alteração.</p><form className="password-box" onSubmit={change}><label>Senha atual<input type="password" value={cur} onChange={e=>setCur(e.target.value)} required/></label><label>Nova senha<input type="password" value={next} onChange={e=>setNext(e.target.value)} minLength={8} required/></label><button className="primary"><KeyRound size={18}/> Alterar senha</button></form>{msg&&<div className="notice">{msg}</div>}</div>}
