import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Activity, Boxes, Building2, CalendarDays, CheckCircle2, ClipboardCheck, Factory, FileText, LayoutGrid, Package, Search, Settings, ShoppingCart, Store, Truck, Users, Wrench, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { supabase } from './lib/supabaseClient'

type Field={key:string;label:string;type?:'text'|'number'|'date'|'email';required?:boolean}
type Module={name:string;title:string;description:string;icon:LucideIcon;table?:string;fields?:Field[]}
type Segment={name:string;description:string;icon:LucideIcon;modules:Module[]}
type Row=Record<string,unknown>&{id:string}
const F=(key:string,label:string,required=false,type:Field['type']='text'):Field=>({key,label,required,type})
const M=(name:string,title:string,description:string,icon:LucideIcon,table?:string,fields:Field[]=[]):Module=>({name,title,description,icon,table,fields})

const industrialModules:Module[]=[
 M('Dashboard','Dashboard industrial','Indicadores de produção, estoque, qualidade, custos e financeiro.',Activity),
 M('Clientes','Clientes','Clientes industriais, contatos, documentos e histórico.',Users,'erp_clientes',[F('nome','Nome / Razão social',true),F('documento','CPF / CNPJ'),F('email','E-mail',false,'email'),F('telefone','Telefone')]),
 M('Produtos','Produtos e materiais','Produtos acabados, componentes, matérias-primas e insumos.',Package,'erp_produtos',[F('codigo','Código',true),F('nome','Nome',true),F('unidade','Unidade'),F('tipo','Tipo'),F('estoque_minimo','Estoque mínimo',false,'number'),F('custo_medio','Custo médio',false,'number'),F('preco_venda','Preço de venda',false,'number')]),
 M('Engenharia','Engenharia / BOM','Fichas técnicas, versões, estruturas e roteiro de fabricação.',Boxes,'erp_fichas_tecnicas',[F('produto_id','Produto ID',true),F('versao','Versão',true,'number'),F('rendimento','Rendimento',false,'number'),F('unidade_rendimento','Unidade'),F('observacoes','Observações')]),
 M('Moldes e Ferramentas','Moldes e ferramentas','Controle de moldes, dispositivos, cavidades, vida útil e localização.',Wrench,'erp_moldes',[F('codigo','Código',true),F('nome','Nome',true),F('tipo','Tipo'),F('status','Status'),F('cavidades','Cavidades',false,'number')]),
 M('Máquinas','Máquinas e equipamentos','Injetoras, prensas, estampadoras e demais recursos produtivos.',Wrench,'erp_maquinas',[F('codigo','Código',true),F('nome','Nome',true),F('tipo','Tipo',true),F('fabricante','Fabricante'),F('modelo','Modelo'),F('status','Status')]),
 M('Processos','Processos produtivos','Operações, tempos padrão, recursos e sequência de fabricação.',Activity,'erp_parametros_processo',[F('processo_id','Processo ID',true),F('grupo','Grupo'),F('codigo','Código',true),F('nome','Nome',true),F('tipo','Tipo'),F('unidade','Unidade'),F('valor_padrao','Valor padrão')]),
 M('PCP','PCP','Planejamento mestre, capacidade, sequenciamento e programação.',CalendarDays,'erp_ordem_processos',[F('ordem_producao_id','OP ID',true),F('processo_id','Processo ID',true),F('sequencia','Sequência',true,'number'),F('maquina_id','Máquina ID'),F('status','Status')]),
 M('MRP','MRP','Necessidades de materiais, compras planejadas e disponibilidade.',Activity),
 M('Ordens de Produção','Ordens de produção','OPs, quantidades, datas, status e execução.',Factory,'erp_ordens_producao',[F('produto_id','Produto ID',true),F('quantidade_planejada','Quantidade',true,'number'),F('status','Status',true),F('data_prevista','Data prevista',false,'date'),F('observacoes','Observações')]),
 M('Apontamentos','Apontamento de produção','Produção boa, refugo, tempos e paradas do chão de fábrica.',Activity,'erp_apontamentos_producao',[F('ordem_producao_id','OP ID',true),F('turno','Turno'),F('quantidade_boa','Quantidade boa',false,'number'),F('quantidade_refugo','Refugo',false,'number'),F('parada_min','Parada (min)',false,'number')]),
 M('Setup','Setup e troca','Tempos de setup, troca de molde, preparação e perdas.',CalendarDays),
 M('Refugo','Refugo e perdas','Apuração de perdas por máquina, produto, turno, causa e lote.',ClipboardCheck),
 M('OEE','OEE e indicadores','Disponibilidade, performance, qualidade e eficiência global.',Activity),
 M('Matéria-prima','Matéria-prima','Consumo, reservas, lotes e saldo de materiais.',Package,'erp_lotes_materia_prima',[F('produto_id','Produto ID',true),F('lote','Lote',true),F('quantidade','Quantidade',true,'number'),F('unidade','Unidade'),F('validade','Validade',false,'date')]),
 M('Estoque','Estoque','Entradas, saídas, transferências, inventário e saldo.',Package,'erp_movimentacoes_estoque',[F('produto_id','Produto ID',true),F('tipo','Tipo',true),F('quantidade','Quantidade',true,'number'),F('documento','Documento'),F('observacoes','Observações')]),
 M('Compras','Compras','Solicitações, pedidos, fornecedores, recebimento e aprovação.',ShoppingCart,'erp_pedidos_compra',[F('fornecedor_id','Fornecedor ID'),F('status','Status',true),F('data_prevista','Data prevista',false,'date'),F('observacoes','Observações')]),
 M('Qualidade','Qualidade','Plano de inspeção, recebimento, processo, produto e liberação.',ClipboardCheck,'erp_inspecoes_qualidade',[F('produto_id','Produto ID'),F('lote','Lote'),F('resultado','Resultado',true),F('data_inspecao','Data',false,'date'),F('observacoes','Observações')]),
 M('RPNC','RPNC / Não conformidades','Desvios, causa raiz, ações corretivas, prazos e eficácia.',ClipboardCheck,'erp_nao_conformidades',[F('origem','Origem',true),F('severidade','Severidade',true),F('descricao','Descrição',true),F('status','Status',true),F('prazo','Prazo',false,'date'),F('rpn','RPN',false,'number')]),
 M('Rastreabilidade','Rastreabilidade','Lote de matéria-prima → produção → produto acabado → expedição.',FileText),
 M('Manutenção','Manutenção','Preventiva, corretiva, peças, horas, máquinas e histórico.',Wrench,'erp_manutencao_ordens',[F('maquina_id','Máquina ID'),F('tipo','Tipo',true),F('status','Status',true),F('prioridade','Prioridade'),F('data_prevista','Data prevista',false,'date'),F('descricao','Descrição')]),
 M('Custos','Custos industriais','Materiais + mão de obra + máquinas + indiretos + perdas + margem.',Activity),
 M('Expedição','Expedição','Separação, conferência, embalagem, romaneio e entrega.',Truck),
 M('Financeiro','Financeiro','Contas a pagar, receber, caixa, conciliação e fluxo.',ShoppingCart),
 M('Fiscal','Fiscal','Documentos fiscais, tributos, XML e acompanhamento de emissão.',FileText),
 M('Relatórios','Relatórios industriais','Indicadores operacionais, financeiros e históricos.',FileText),
]
const commonModules:Module[]=[M('Clientes','Clientes','Cadastro e relacionamento com clientes.',Users,'erp_clientes',[F('nome','Nome / Razão social',true),F('documento','CPF / CNPJ'),F('email','E-mail',false,'email'),F('telefone','Telefone')]),M('Produtos','Produtos','Catálogo, preços e itens.',Package,'erp_produtos',[F('codigo','Código',true),F('nome','Nome',true),F('unidade','Unidade')]),M('Estoque','Estoque','Saldo, inventário e movimentações.',Package),M('Compras','Compras','Fornecedores, cotações e pedidos.',ShoppingCart),M('Vendas','Vendas','Orçamentos, pedidos e faturamento.',ShoppingCart),M('Financeiro','Financeiro','Contas, caixa e fluxo financeiro.',Activity),M('Fiscal','Fiscal','Documentos e obrigações fiscais.',FileText),M('CRM','CRM','Leads, oportunidades e relacionamento.',Users),M('Relatórios','Relatórios','Indicadores e análises.',Activity)]
const segments:Segment[]=[
 {name:'Injetados / Prensados / Estampados',description:'Indústria de transformação com máquinas, moldes, matéria-prima, PCP, qualidade, refugo, custos e rastreabilidade.',icon:Factory,modules:industrialModules},
 {name:'Metalúrgica',description:'Corte, dobra, solda, usinagem, produção, qualidade, estoque e custos.',icon:Factory,modules:commonModules},
 {name:'Usinagem',description:'CNC, tornos, fresas, roteiros, tempos, ferramentas e custos por operação.',icon:Wrench,modules:commonModules},
 {name:'Química',description:'Formulações, lotes, matérias-primas, rastreabilidade, qualidade e segurança.',icon:Boxes,modules:commonModules},
 {name:'Autopeças',description:'Produção, lotes, rastreabilidade, qualidade, entregas e requisitos de clientes.',icon:Truck,modules:commonModules},
 {name:'Ferramentaria',description:'Projetos, moldes, ferramentas, horas, manutenção e custos de fabricação.',icon:Wrench,modules:commonModules},
 {name:'Móveis',description:'Projetos, ficha técnica, corte, montagem, estoque e entrega.',icon:Boxes,modules:commonModules},
 {name:'Atacado / Distribuição',description:'Compras, vendas, estoque, WMS, preços, representantes, rotas e expedição.',icon:Truck,modules:commonModules},
 {name:'Varejo / Lojas',description:'Lojas, PDV, estoque por filial, vendas, caixa, clientes e fiscal.',icon:Store,modules:commonModules},
 {name:'Automotivo / Oficina',description:'Clientes, veículos, orçamentos, ordens de serviço, peças, mecânicos e financeiro.',icon:Wrench,modules:commonModules},
 {name:'Transportadora / Logística',description:'Frota, motoristas, cargas, rotas, entregas, manutenção e custos.',icon:Truck,modules:commonModules},
 {name:'Serviços',description:'Clientes, propostas, agenda, ordens de serviço, técnicos, contratos e cobrança.',icon:Wrench,modules:commonModules},
 {name:'Agronegócio',description:'Compras, estoque, produção, custos, vendas e gestão operacional.',icon:Boxes,modules:commonModules},
 {name:'Saúde',description:'Atendimento, clientes, estoque, compras, financeiro e gestão administrativa.',icon:ClipboardCheck,modules:commonModules},
 {name:'Restaurantes / Alimentação',description:'Produtos, fichas, compras, estoque, vendas, caixa e custos.',icon:ShoppingCart,modules:commonModules},
 {name:'Tecnologia',description:'Clientes, contratos, projetos, serviços, financeiro e indicadores.',icon:Activity,modules:commonModules},
 {name:'Educação',description:'Clientes/alunos, contratos, cobrança, serviços e gestão administrativa.',icon:Users,modules:commonModules},
 {name:'Representação Comercial',description:'Leads, clientes, oportunidades, propostas, pedidos e comissões.',icon:Users,modules:commonModules},
]
const value=(v:unknown)=>v==null?'':String(v)
const payload=(fields:Field,form:Record<string,string>)=>fields
function makePayload(fields:Field[],form:Record<string,string>){const out:Record<string,unknown>={};for(const f of fields){const raw=(form[f.key]??'').trim();if(!raw){if(f.required)throw new Error(`Informe ${f.label}.`);out[f.key]=null;continue}if(f.type==='number'){const n=Number(raw);if(!Number.isFinite(n))throw new Error(`${f.label} deve ser numérico.`);out[f.key]=n}else out[f.key]=raw}return out}

export default function AppIndustrialV7(){
 const [segment,setSegment]=useState(segments[0].name),[active,setActive]=useState('Dashboard'),[launcher,setLauncher]=useState(false),[profile,setProfile]=useState<{nome:string;empresa_id:string;nivel_admin:number}|null>(null),[loading,setLoading]=useState(true)
 const current=segments.find(s=>s.name===segment)??segments[0]; const module=current.modules.find(m=>m.name===active)
 useEffect(()=>{let alive=true;void(async()=>{const{data:a}=await supabase.auth.getUser();if(a.user){const{data:p}=await supabase.from('erp_usuarios').select('nome,empresa_id,nivel_admin').eq('auth_user_id',a.user.id).maybeSingle();if(alive&&p)setProfile(p)}if(alive)setLoading(false)})();return()=>{alive=false}},[])
 if(loading)return <div className="loading-screen">Carregando SGQ ERP…</div>
 function choose(s:Segment,m:string){setSegment(s.name);setActive(m);setLauncher(false)}
 return <div className="v7-shell"><aside className="v7-sidebar"><div className="v7-brand"><img src="/logo-industrial.svg" alt="SGQ ERP"/><div><strong>SGQ ERP</strong><span>ERP Multissegmento</span></div></div><button className="v7-all" onClick={()=>setLauncher(true)}><LayoutGrid size={18}/> Todos os módulos</button><div className="v7-segment-label">SEGMENTO ATIVO</div><button className="v7-segment-current" onClick={()=>setLauncher(true)}><Factory size={17}/><span>{segment}</span><span>⌄</span></button><nav><button className={active==='Dashboard'?'v7-nav active':'v7-nav'} onClick={()=>setActive('Dashboard')}><Activity size={17}/>Dashboard</button>{current.modules.filter(m=>m.name!=='Dashboard').slice(0,18).map(m=><Nav key={m.name} module={m} active={active} setActive={setActive}/>)}</nav><button className="v7-nav" onClick={()=>setActive('Configurações')}><Settings size={17}/>Configurações</button><button className="v7-exit" onClick={()=>void supabase.auth.signOut().then(()=>{location.href='/login'})}>Sair</button></aside><main className="v7-main"><header className="v7-header"><div><span>SGQ ERP • {segment.toUpperCase()}</span><h1>{active==='Dashboard'?`Dashboard — ${segment}`:module?.title??active}</h1><p>{active==='Dashboard'?current.description:module?.description}</p></div><div className="v7-user"><b>{profile?.nome??'Usuário'}</b><small>Empresa {profile?.empresa_id??'—'}</small></div></header><section className="v7-content">{active==='Dashboard'?<Dashboard segment={current} setActive={setActive}/>:active==='Configurações'?<Feature title="Configurações" description="Parâmetros, usuários, permissões e módulos são separados por empresa e segmento." icon={Settings}/>:module?.table?<Crud module={module} profile={profile}/>:<Feature title={module?.title??active} description={module?.description??'Módulo preparado para a configuração deste segmento.'} icon={module?.icon??LayoutGrid}/>}</section><footer>FernandoSch_System • SGQ ERP • {segment} • Ambiente isolado por empresa</footer></main>{launcher&&<Launcher close={()=>setLauncher(false)} choose={choose} activeSegment={segment} activeModule={active}/>}</div>
}
function Nav({module,active,setActive}:{module:Module;active:string;setActive:(v:string)=>void}){const I=module.icon;return <button className={active===module.name?'v7-nav active':'v7-nav'} onClick={()=>setActive(module.name)}><I size={17}/>{module.name}</button>}
function Launcher({close,choose,activeSegment,activeModule}:{close:()=>void;choose:(s:Segment,m:string)=>void;activeSegment:string;activeModule:string}){const [selected,setSelected]=useState(activeSegment);const s=segments.find(x=>x.name===selected)??segments[0];return <div className="v7-overlay"><div className="v7-panel"><div className="v7-panel-head"><div><span>CATÁLOGO COMPLETO</span><h2>Soluções e segmentos do SGQ ERP</h2><p>Escolha o segmento. Depois escolha o submenu específico do negócio.</p></div><button onClick={close} aria-label="Fechar"><X/></button></div><div className="v7-layout"><div className="v7-segment-list">{segments.map(x=>{const I=x.icon;return <button key={x.name} className={selected===x.name?'selected':''} onClick={()=>setSelected(x.name)}><I size={17}/><span>{x.name}</span></button>})}</div><div className="v7-module-area"><div className="v7-segment-hero"><div><span>SEGMENTO</span><h3>{s.name}</h3><p>{s.description}</p></div><b>{s.modules.length} módulos</b></div><div className="v7-module-grid">{s.modules.map(m=>{const I=m.icon;return <button key={m.name} className={activeSegment===s.name&&activeModule===m.name?'selected':''} onClick={()=>choose(s,m.name)}><I size={19}/><strong>{m.name}</strong><small>{m.description}</small></button>})}</div></div></div></div></div>}
function Dashboard({segment,setActive}:{segment:Segment;setActive:(v:string)=>void}){const quick=segment.modules.filter(m=>m.name!=='Dashboard').slice(0,8);return <div className="v7-dashboard"><div className="v7-kpis"><article><span>Operação</span><strong>Conectada</strong><small>Dados do ambiente da empresa</small></article><article><span>Módulos do segmento</span><strong>{segment.modules.length}</strong><small>Especializados para {segment.name}</small></article><article><span>Segurança</span><strong>Multiempresa</strong><small>RLS + sessão autenticada</small></article><article><span>Integração</span><strong>Supabase</strong><small>Dados persistidos no backend</small></article></div><div className="v7-welcome"><div><span>AMBIENTE DO CLIENTE</span><h2>{segment.name}</h2><p>{segment.description}</p></div><button onClick={()=>setActive('Produtos')}>Abrir cadastros <Search size={16}/></button></div><div className="v7-quick"><h2>Módulos principais</h2><div>{quick.map(m=>{const I=m.icon;return <button key={m.name} onClick={()=>setActive(m.name)}><I size={21}/><strong>{m.name}</strong><small>{m.description}</small></button>})}</div></div></div>}
function Feature({title,description,icon:Icon}:{title:string;description:string;icon:LucideIcon}){return <div className="v7-feature"><Icon size={36}/><h2>{title}</h2><p>{description}</p><div><CheckCircle2 size={18}/> Estrutura pronta para receber o processo específico do segmento.</div></div>}
function Crud({module,profile}:{module:Module;profile:{empresa_id:string}|null}){const fields=module.fields??[];const [rows,setRows]=useState<Row[]>([]),[form,setForm]=useState<Record<string,string>>({}),[editing,setEditing]=useState<string|null>(null),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const pipeline=useMemo(()=>supabase.from(module.table!),[module.table]);
 async function load(){setBusy(true);setMsg('');const{data,error}=await pipeline.select('*').order('created_at',{ascending:false}).limit(200);if(error){setMsg(`Erro ao carregar: ${error.message}`)}else setRows((data??[]) as Row[]);setBusy(false)}
 useEffect(()=>{void load()},[module.table])
 async function save(e:FormEvent){e.preventDefault();setMsg('');setBusy(true);try{const data=makePayload(fields,form);if(editing){const{error}=await supabase.from(module.table!).update(data).eq('id',editing);if(error)throw error;setMsg('Registro atualizado com sucesso.')}else{if(profile?.empresa_id)data.empresa_id=profile.empresa_id;const{error}=await supabase.from(module.table!).insert(data);if(error)throw error;setMsg('Registro criado com sucesso.')}setEditing(null);setForm({});await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Excluir este registro?'))return;setBusy(true);const{error}=await supabase.from(module.table!).delete().eq('id',id);setMsg(error?`Erro ao excluir: ${error.message}`:'Registro excluído.');await load();setBusy(false)}
 const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));return <div className="v7-crud"><div className="v7-crud-head"><div><span>CRUD REAL • SUPABASE</span><h2>{module.title}</h2><p>{module.description}</p></div><label className="v7-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar..."/></label></div>{msg&&<div className="v7-msg">{msg}</div>}<form className="v7-form" onSubmit={save}>{fields.map(f=><label key={f.key}>{f.label}<input type={f.type==='number'?'number':f.type==='date'?'date':f.type==='email'?'email':'text'} value={form[f.key]??''} required={f.required} onChange={e=>setForm({...form,[f.key]:e.target.value})}/></label>)}<button disabled={busy}>{busy?'Salvando…':editing?'Atualizar':'Salvar'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm({})}}>Cancelar</button>}</form><div className="v7-table"><table><thead><tr>{fields.slice(0,6).map(f=><th key={f.key}>{f.label}</th>)}<th>Ações</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{fields.slice(0,6).map(f=><td key={f.key}>{value(r[f.key])}</td>)}<td><button onClick={()=>{setEditing(r.id);setForm(Object.fromEntries(fields.map(f=>[f.key,value(r[f.key])])) )}}>Editar</button><button onClick={()=>void remove(r.id)}>Excluir</button></td></tr>)}{!filtered.length&&<tr><td colSpan={fields.length+1}>{busy?'Carregando…':'Nenhum registro encontrado.'}</td></tr>}</tbody></table></div></div>}
