import { ArrowRight, BarChart3, Boxes, Check, ClipboardCheck, Factory, FileText, Package, ShoppingCart, Wrench } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
type Screen = { title:string; icon:LucideIcon; kpis:string[]; rows:string[] }
const segments = [
 ['Plásticos','Injeção, extrusão, moldes, matéria-prima, refugo e rastreabilidade.'],['Metalúrgica','Corte, dobra, solda, usinagem, produção e custos.'],['Usinagem','Roteiros, tempos, máquinas, apontamentos e custo por operação.'],['Química','Lotes, formulações, matérias-primas e controle de qualidade.'],['Autopeças','Rastreabilidade, qualidade, lotes, entregas e requisitos de clientes.'],['Ferramentaria','Projetos, moldes, manutenção, horas e custos.'],['Móveis','Ficha técnica, corte, montagem, estoque e entrega.'],['Atacado / Distribuição','Compras, WMS, vendas, preços, rotas e expedição.'],['Lojas / Varejo','Filiais, estoque por loja, vendas, clientes e fiscal.'],['Serviços','CRM, propostas, agenda, ordens de serviço e cobrança.']
]
const screens:Screen[] = [
 {title:'Dashboard executivo',icon:BarChart3,kpis:['OPs 24','OEE 87%','Estoque R$ 184 mil','RPNC 03'],rows:['Produção do dia • 92% do planejado','Pedidos em aberto • 18','Estoque crítico • 7 itens']},
 {title:'PCP / Produção',icon:Factory,kpis:['OPs 24','Atrasadas 02','Capacidade 86%','Refugo 1,8%'],rows:['OP-00482 • Injeção • 78%','OP-00483 • Usinagem • 41%','OP-00484 • Montagem • Aguardando']},
 {title:'Estoque / WMS',icon:Package,kpis:['Itens 1.284','Lotes 318','Críticos 07','Valor R$ 1,2 mi'],rows:['PP-00041 • Matéria-prima • 820 kg','MP-00218 • Polímero • 240 kg','PA-00991 • Produto acabado • 94 un']},
 {title:'Qualidade / RPNC',icon:ClipboardCheck,kpis:['Inspeções 42','RPNC 03','Ações 07','Risco alto 01'],rows:['RPNC-0012 • Dimensional • Em análise','RPNC-0013 • Visual • Ação corretiva','Lote L-2026-091 • Liberado']},
 {title:'Custos industriais',icon:BarChart3,kpis:['Material 58%','Mão de obra 17%','Máquinas 12%','Margem 23%'],rows:['Produto A • Custo R$ 42,80 • Venda R$ 68,00','Produto B • Custo R$ 18,40 • Venda R$ 31,90','Perdas • R$ 4.820 no período']},
 {title:'Financeiro',icon:ShoppingCart,kpis:['A receber R$ 328 mil','A pagar R$ 214 mil','Caixa R$ 96 mil','Margem 21%'],rows:['Hoje • 12 títulos a vencer','Semana • 8 pagamentos programados','Mês • DRE em acompanhamento']},
 {title:'Fiscal',icon:FileText,kpis:['NF-e 128','Autorizadas 126','Rejeitadas 02','XML 100%'],rows:['NF-e 000128 • Autorizada','NF-e 000127 • Autorizada','NF-e 000126 • Rejeitada • corrigir']},
 {title:'Manutenção',icon:Wrench,kpis:['Máquinas 42','Preventivas 11','Corretivas 03','Disponibilidade 94%'],rows:['INJ-04 • Preventiva • amanhã','TOR-02 • Corretiva • em execução','CNC-08 • Disponível']}
]
const plans = [
 {name:'Essencial',price:'R$ 199',desc:'Para organizar a operação',items:['Dashboard','Produtos e estoque','Compras','Clientes','Produção / OP']},
 {name:'Profissional',price:'R$ 349',desc:'Para ganhar escala',items:['Tudo do Essencial','MRP / PCP','Qualidade / RPNC','Manutenção','OEE e indicadores']},
 {name:'Diamante',price:'R$ 549',desc:'Para operação completa',items:['Tudo do Profissional','Fiscal NF-e / NFC-e','Outlook + IA/OCR','Auditoria ampliada','Visão integrada da fábrica']}
]
const posts=[['O que é MRP?','PCP / MRP'],['Como calcular o custo real de produção?','Custos'],['ERP industrial: o que uma fábrica precisa controlar?','Gestão'],['Como reduzir perdas no estoque industrial?','Estoque']]
export default function PublicIndustrialHomeV3(){return <div className="public-industrial industrial-home-v3"><header className="industrial-public-nav"><a className="industrial-logo" href="/"><img src="/logo-industrial.svg" alt="SGQ ERP"/></a><nav><a href="#solucoes">Soluções</a><a href="#segmentos">Segmentos</a><a href="#por-dentro">Por dentro</a><a href="/blog">Blog</a><a href="#planos">Planos</a><a href="#contato">Contato</a></nav><div className="industrial-nav-actions"><a href="/login">Entrar</a><a className="industrial-cta" href="/cadastro-empresa">Teste grátis por 15 dias <ArrowRight size={16}/></a></div></header>
<section className="industrial-hero-v3"><div><span className="public-kicker">SGQ ERP • GESTÃO INDUSTRIAL MULTISSEGMENTO</span><h1>O ERP que conecta toda a sua operação.</h1><p>Produção, PCP, MRP, estoque, qualidade, custos, manutenção, compras, vendas, logística, fiscal e financeiro em uma única plataforma.</p><div className="industrial-hero-actions"><a className="industrial-cta" href="/cadastro-empresa">Teste grátis por 15 dias <ArrowRight size={18}/></a><a className="industrial-outline" href="#planos">Conhecer os planos</a></div><div className="industrial-proof"><span><Check/> Dados por empresa</span><span><Check/> Computador, tablet e celular</span><span><Check/> Arquitetura modular</span></div></div><div className="executive-screen"><div className="screen-top"><b>SGQ ERP</b><span>● Conectado</span></div><h3>Visão executiva</h3><div className="screen-kpis">{['OPs 24','OEE 87%','Estoque R$184k','RPNC 03'].map(x=><div key={x}>{x}</div>)}</div><div className="screen-bars">{[38,62,51,78,67,91,73].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="screen-list"><span>Produção em fluxo</span><span>7 itens em estoque crítico</span><span>3 RPNCs em tratamento</span></div></div></section>
<section id="solucoes" className="industrial-section"><div className="industrial-heading"><span className="public-kicker">DO PEDIDO AO RESULTADO</span><h2>Um fluxo. Todos os departamentos.</h2><p>O SGQ ERP conecta a informação uma única vez e faz cada área trabalhar sobre o mesmo dado.</p></div><div className="industrial-flow">{['CRM / Pedido','PCP / MRP','Compras','Estoque','Produção','Qualidade','Expedição','Fiscal','Financeiro'].map((x,i)=><div key={x}><strong>{i+1}</strong><span>{x}</span>{i<8&&<b>→</b>}</div>)}</div></section>
<section className="industrial-section benefits"><div className="benefit-grid">{[['Planeje antes de produzir','Demanda → MRP → capacidade → sequência → OP.'],['Controle o chão de fábrica','OP → máquina → operador → produção → refugo.'],['Trate o desvio a tempo','Inspeção → lote → RPNC → causa → ação.'],['Conheça o custo real','Material + mão de obra + máquina + energia + perdas + indiretos.'],['Rastreie cada movimento','Entrada → lote → endereço → consumo → produto acabado.'],['Decida com dados','KPIs, margem, OEE, estoque e financeiro na mesma visão.']].map(([t,d])=><article key={t}><Check/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section id="segmentos" className="industrial-section"><div className="industrial-heading"><span className="public-kicker">SEGMENTOS</span><h2>O mesmo ERP. Configurado para cada negócio.</h2><p>Em vez de criar um sistema diferente para cada mercado, usamos um núcleo comum e ativamos os módulos necessários.</p></div><div className="segment-grid-v3">{segments.map(([t,d])=><article key={t}><span>SGQ</span><h3>{t}</h3><p>{d}</p><a href="#contato">Ver solução <ArrowRight size={14}/></a></article>)}</div></section>
<section id="por-dentro" className="industrial-section"><div className="industrial-heading"><span className="public-kicker">POR DENTRO DO SGQ ERP</span><h2>Telas reais do fluxo do sistema.</h2><p>Os mesmos conceitos que o usuário encontra dentro do ERP: indicadores, cadastros, listas, status e ações.</p></div><div className="real-screen-grid">{screens.map(s=><article className="real-screen" key={s.title}><div className="screen-top"><b>{s.title}</b><span>● Online</span></div><div className="screen-kpis">{s.kpis.map(k=><div key={k}>{k}</div>)}</div><div className="screen-list">{s.rows.map(r=><span key={r}>{r}</span>)}</div><a href="/login">Abrir no sistema <ArrowRight size={14}/></a></article>)}</div></section>
<section className="industrial-section"><div className="industrial-heading"><span className="public-kicker">AUTOMAÇÃO</span><h2>Do e-mail ao processo, sem redigitação.</h2><p>Outlook → IA/OCR → pedido pendente → aprovação → produção → fiscal.</p></div><div className="automation-strip">{[['01','Captura','E-mail, remetente, assunto e anexos'],['02','Leitura','PDF, imagem e texto estruturados'],['03','Revisão','Operador confirma antes de liberar'],['04','Execução','Pedido, produção, estoque e fiscal']].map(([n,t,d])=><article key={n}><strong>{n}</strong><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section id="blog" className="industrial-section blog-preview-v3"><div className="industrial-heading"><span className="public-kicker">BLOG INDUSTRIAL</span><h2>Conhecimento para uma indústria mais eficiente.</h2></div><div className="post-grid-v3">{posts.map(([t,c])=><a href="/blog" key={t}><span>{c}</span><h3>{t}</h3><b>Leia o artigo <ArrowRight size={14}/></b></a>)}</div><a className="industrial-outline" href="/blog">Ver todo o Blog</a></section>
<section id="planos" className="industrial-section"><div className="industrial-heading"><span className="public-kicker">PLANOS</span><h2>Comece pelo tamanho da sua operação.</h2><p>O núcleo é o mesmo. O plano define os recursos ativados.</p></div><div className="plan-grid-v3">{plans.map((p,i)=><article className={i===1?'plan-card-v3 featured':'plan-card-v3'} key={p.name}><span>{i===1?'MAIS ESCOLHIDO':'SGQ ERP'}</span><h3>{p.name}</h3><p>{p.desc}</p><strong>{p.price}<small>/mês</small></strong><ul>{p.items.map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="industrial-cta" href="/cadastro-empresa">Começar teste grátis <ArrowRight size={15}/></a></article>)}</div></section>
<section id="contato" className="industrial-final-cta"><div><span className="public-kicker">15 DIAS GRÁTIS</span><h2>Teste o SGQ ERP na sua empresa.</h2><p>Crie seu ambiente, conheça os recursos e use gratuitamente por 15 dias. Depois, escolha o plano que melhor atende sua operação.</p><a className="industrial-cta" href="/cadastro-empresa">Começar teste grátis <ArrowRight size={18}/></a></div></section>
<footer className="industrial-footer-v3"><span>SGQ ERP • Sistema de Gestão Industrial</span><div><a href="/login">Entrar</a><a href="/blog">Blog</a><a href="#planos">Planos</a></div></footer></div>}
