-- Industrial submodules: quality calibration, 8D/5S, purchasing requisitions, lot traceability, downtime, finishing and separation.
-- Applied to production project wdkvrqekixczuhrfygen on 2026-09-26.
create table if not exists public.erp_requisicoes_compra (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,codigo text not null,ordem_producao_id uuid references public.erp_ordens_producao(id),data_limite date,comprador_nome text,status text not null default 'AGUARDANDO_COTACAO',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(empresa_id,codigo));
create table if not exists public.erp_requisicoes_compra_itens (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,requisicao_id uuid not null references public.erp_requisicoes_compra(id) on delete cascade,produto_id uuid not null references public.erp_produtos(id),quantidade numeric(14,3) not null default 0,fornecedor_id uuid references public.erp_fornecedores(id),status text not null default 'AGUARDANDO_COTACAO',created_at timestamptz not null default now());
create table if not exists public.erp_estoque_lotes (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,produto_id uuid not null references public.erp_produtos(id),fornecedor_id uuid references public.erp_fornecedores(id),nf_numero text,lote_interno text not null,lote_fornecedor text,quantidade_recebida numeric(14,3) not null default 0,quantidade_disponivel numeric(14,3) not null default 0,quantidade_reservada numeric(14,3) not null default 0,localizacao text,status_inspecao text not null default 'AGUARDANDO',data_entrada date not null default current_date,created_at timestamptz not null default now(),unique(empresa_id,lote_interno));
create table if not exists public.erp_producao_paradas (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,maquina_id uuid not null references public.erp_maquinas(id),ordem_producao_id uuid references public.erp_ordens_producao(id),motivo text not null,inicio timestamptz not null default now(),fim timestamptz,observacao text,status text not null default 'ABERTA',created_at timestamptz not null default now());
create table if not exists public.erp_acabamentos (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,ordem_producao_id uuid not null references public.erp_ordens_producao(id),lote_id uuid references public.erp_estoque_lotes(id),posto_trabalho text not null,quantidade_recebida numeric(14,3) not null default 0,quantidade_acabada numeric(14,3) not null default 0,quantidade_refugo numeric(14,3) not null default 0,status text not null default 'ABERTO',created_at timestamptz not null default now());
create table if not exists public.erp_estoque_separacoes (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,ordem_producao_id uuid not null references public.erp_ordens_producao(id),produto_id uuid not null references public.erp_produtos(id),lote_id uuid references public.erp_estoque_lotes(id),quantidade numeric(14,3) not null default 0,status text not null default 'PENDENTE',codigo_barras text,created_at timestamptz not null default now());
create table if not exists public.erp_rastreabilidade_cartoes (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,separacao_id uuid not null references public.erp_estoque_separacoes(id) on delete cascade,codigo text not null,impresso_em timestamptz,created_at timestamptz not null default now(),unique(empresa_id,codigo));
create table if not exists public.erp_qualidade_8d (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,codigo text not null,rpnc_id uuid references public.erp_rpnc(id),etapa_atual text not null default 'D1',d1_equipe text,d2_problema text,d3_contencao text,d4_causa_raiz text,d5_acoes text,d6_validacao text,d7_preventivas text,d8_encerramento text,status text not null default 'EM_ANALISE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(empresa_id,codigo));
create table if not exists public.erp_qualidade_5s_auditorias (id uuid primary key default gen_random_uuid(),empresa_id uuid not null,setor text not null,data_auditoria date not null default current_date,auditor text,acompanhante text,seiri smallint not null default 1 check(seiri between 1 and 5),seiton smallint not null default 1 check(seiton between 1 and 5),seiso smallint not null default 1 check(seiso between 1 and 5),seiketsu smallint not null default 1 check(seiketsu between 1 and 5),shitsuke smallint not null default 1 check(shitsuke between 1 and 5),observacoes jsonb not null default '{}'::jsonb,media numeric(4,2) generated always as ((seiri+seiton+seiso+seiketsu+shitsuke)/5.0) stored,status text not null default 'ABERTA',created_at timestamptz not null default now());
do $$ declare t text; begin foreach t in array array['erp_requisicoes_compra','erp_requisicoes_compra_itens','erp_estoque_lotes','erp_producao_paradas','erp_acabamentos','erp_estoque_separacoes','erp_rastreabilidade_cartoes','erp_qualidade_8d','erp_qualidade_5s_auditorias'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); execute format('drop policy if exists %I on public.%I',t||'_select',t); execute format('drop policy if exists %I on public.%I',t||'_insert',t); execute format('drop policy if exists %I on public.%I',t||'_update',t); execute format('drop policy if exists %I on public.%I',t||'_delete',t); execute format('create policy %I on public.%I for select to authenticated using (empresa_id=erp_current_empresa_id())',t||'_select',t); execute format('create policy %I on public.%I for insert to authenticated with check (empresa_id=erp_current_empresa_id())',t||'_insert',t); execute format('create policy %I on public.%I for update to authenticated using (empresa_id=erp_current_empresa_id()) with check (empresa_id=erp_current_empresa_id())',t||'_update',t); execute format('create policy %I on public.%I for delete to authenticated using (empresa_id=erp_current_empresa_id())',t||'_delete',t); end loop; end $$;
create index if not exists idx_erp_req_compra_op on public.erp_requisicoes_compra(empresa_id,ordem_producao_id);
create index if not exists idx_erp_lotes_produto on public.erp_estoque_lotes(empresa_id,produto_id);
create index if not exists idx_erp_paradas_abertas on public.erp_producao_paradas(empresa_id,status,maquina_id);
create index if not exists idx_erp_separacoes_op on public.erp_estoque_separacoes(empresa_id,ordem_producao_id);