-- Reconciliation artifact for the production migration 20260918142302_odonto_radiologia_metadata_v1.
-- Already recorded as applied in the shared production Supabase project.
-- Intentionally no-op: do not replay or destructively reconstruct production DDL.
