create policy erp_veiculos_select on public.erp_veiculos for select to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_veiculos_insert on public.erp_veiculos for insert to authenticated with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_veiculos_update on public.erp_veiculos for update to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master()) with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_veiculos_delete on public.erp_veiculos for delete to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_motoristas_select on public.erp_motoristas for select to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_motoristas_insert on public.erp_motoristas for insert to authenticated with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_motoristas_update on public.erp_motoristas for update to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master()) with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_motoristas_delete on public.erp_motoristas for delete to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicoes_select on public.erp_expedicoes for select to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicoes_insert on public.erp_expedicoes for insert to authenticated with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicoes_update on public.erp_expedicoes for update to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master()) with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicoes_delete on public.erp_expedicoes for delete to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicao_notas_select on public.erp_expedicao_notas for select to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicao_notas_insert on public.erp_expedicao_notas for insert to authenticated with check (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
create policy erp_expedicao_notas_delete on public.erp_expedicao_notas for delete to authenticated using (empresa_id = public.erp_current_empresa_id() or public.erp_is_master());
