create extension if not exists pg_trgm;

create table if not exists public.erp_ajuda_documentos (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  titulo text not null,
  resumo text not null,
  conteudo text not null,
  palavras_chave text[] not null default '{}',
  rota text,
  publico boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_erp_ajuda_documentos_keywords on public.erp_ajuda_documentos using gin (palavras_chave);
create index if not exists idx_erp_ajuda_documentos_titulo_trgm on public.erp_ajuda_documentos using gin (titulo gin_trgm_ops);

alter table public.erp_ajuda_documentos enable row level security;

drop policy if exists erp_ajuda_public_read on public.erp_ajuda_documentos;
create policy erp_ajuda_public_read on public.erp_ajuda_documentos for select to anon, authenticated using (publico = true);

insert into public.erp_ajuda_documentos (slug,titulo,resumo,conteudo,palavras_chave,rota,ordem) values
('login','Login e acesso','Como entrar no SGQ ERP e validar o acesso por empresa.','Campos: Nome da Empresa, Usuário ou e-mail e Senha. O login resolve o e-mail real do usuário e autentica no Supabase Auth. Depois da autenticação, o vínculo do usuário com a empresa e o status ativo são conferidos.',array['login','entrar','usuário','e-mail','senha','empresa','acesso','autenticação','Supabase Auth'],'/login',10),
('cadastro-empresa','Cadastro de nova empresa','Criação de um novo ambiente industrial isolado.','O cadastro solicita Razão Social, Nome Fantasia, responsável, e-mail e senha. O nome de acesso é gerado a partir do primeiro nome da empresa. A criação é feita pelo backend da Edge Function de provisionamento para manter isolamento por empresa.',array['cadastro empresa','nova empresa','razão social','nome fantasia','administrador','ambiente','provisionamento','setores'],'/cadastro-empresa',20),
('dashboard','Dashboard','Visão executiva da operação industrial.','O dashboard apresenta visão executiva da operação e atalhos para os módulos. Indicadores devem refletir dados reais do banco; números demonstrativos não devem ser tratados como dados de produção.',array['dashboard','indicadores','KPIs','visão executiva','operação'],'/',30),
('cadastros','Cadastros mestres','Base cadastral que alimenta os demais módulos.','Cadastros mestres mantêm setores, usuários, produtos, clientes, fornecedores, máquinas, moldes, serviços/processos e parâmetros necessários.',array['cadastros','mestre','setores','usuários','produtos','clientes','fornecedores','máquinas','moldes'],'/erp-industrial',40),
('produtos-engenharia','Produtos e engenharia','Produtos, BOM, ficha técnica e custos.','Produto possui código/SKU, descrição, unidade, grupo, estoque, custo e preço. A engenharia pode usar BOM/ficha técnica, componentes, quantidades e processo. O custo industrial considera materiais, mão de obra, máquinas, energia, indiretos, terceiros, embalagem e perdas.',array['produto','SKU','BOM','ficha técnica','componente','matéria-prima','custo','markup','margem'],'/erp-industrial',50),
('estoque','Estoque e rastreabilidade','Saldos, movimentos, lotes e inventário.','O estoque nasce dos movimentos de entrada, consumo, produção, transferência e saída. Lotes e matérias-primas devem permitir rastreabilidade. Estoque mínimo e alertas apoiam compras e PCP.',array['estoque','WMS','lote','saldo','movimentação','entrada','saída','consumo','inventário','rastreabilidade'],'/erp-industrial',60),
('compras','Compras','Solicitações, pedidos, fornecedores e recebimentos.','A necessidade pode nascer de estoque, MRP, produção ou solicitação manual. A solicitação contém descrição, prioridade, itens e aprovação. O pedido de compra acompanha fornecedor, prazo, recebimento e impacto no estoque.',array['compras','solicitação de compra','fornecedor','cotação','pedido','aprovação','recebimento','prazo'],'/compras-solicitacao',70),
('vendas','Vendas e pedidos','Pedidos comerciais conectados ao fluxo industrial.','Pedidos comerciais alimentam planejamento, estoque, produção, expedição, fiscal e financeiro. Dados de cliente, produto, quantidade, preço e prazo devem ser conferidos antes de liberar a produção.',array['vendas','cliente','pedido','pedido de venda','preço','quantidade','prazo','faturamento'],'/erp-industrial',80),
('pcp-mrp','PCP e MRP','Planejamento de materiais, capacidade e produção.','PCP transforma pedidos e necessidades em planejamento de materiais e capacidade. MRP identifica componentes necessários, estoque disponível e necessidade de compra. Fluxo: pedido → necessidade → compra/estoque → OP → apontamento → qualidade → estoque final → expedição.',array['PCP','MRP','planejamento','capacidade','necessidade','OP','ordem de produção','programação'],'/pcp',90),
('producao-apontamento','Produção e apontamento','Ordens, produção boa, refugo, paradas e ocorrências.','A ordem de produção identifica produto, quantidade, processo, máquina, setor e programação. O apontamento registra produção boa, refugo, paradas e ocorrências. A referência PLASTIBOR FRP-PROD-010 usa apontamento horário de 08:00 a 17:00, operador, cliente, pedido, molde, máquina, início/fim e motivo de parada.',array['produção','OP','ordem de produção','apontamento','refugo','parada','operador','máquina','molde','FRP-PROD-010'],'/pcp',100),
('qualidade','Qualidade / QMS','Documentos, inspeções, RPNC, auditorias e indicadores.','Qualidade controla documentos, inspeções, RPNC, ações corretivas, auditorias, metrologia, manutenção relacionada e indicadores. Referências PLASTIBOR: FRTB-GQ-004 Cadastro de Registro da Qualidade; FRP-GQ-001 Lista Mestre de Documentos enviados a fornecedores; FRP-GQ-002 Lista Mestre de Especificações enviadas a terceiros.',array['qualidade','QMS','RPNC','inspeção','auditoria','documento','revisão','retenção','registro','especificação','fornecedor'],'/qualidade',110),
('rpnc','RPNC e não conformidades','Tratamento de desvios, causas, ações e eficácia.','Uma não conformidade registra problema, causa, ação, responsável, prazo, evidência e encerramento. O sistema deve permitir analisar reincidência, severidade, ocorrência e detecção quando aplicável.',array['RPNC','não conformidade','causa','ação corretiva','eficácia','severidade','ocorrência','detecção'],'/qualidade',120),
('manutencao','Manutenção / CMMS','Preventiva, corretiva, planos e histórico de máquinas.','Máquinas possuem identificação, plano e histórico. A manutenção preventiva segue periodicidade e status. A referência PLASTIBOR 2026 usa R = Realizado, A = Agendado e AT = Atrasado; dashboard fornecido: 16 realizados, 20 agendados e 2 atrasados.',array['manutenção','CMMS','preventiva','corretiva','máquina','plano','OS','cronograma','PR-01','INJ-01','CP-01','TR-01','CH-01'],'/erp-industrial',130),
('fiscal','Fiscal','NF-e, NFC-e, XML, DANFE e integração oficial.','O módulo fiscal prepara NF-e modelo 55, NFC-e modelo 65, itens, tributos, XML, DANFE e chave de acesso. A autorização oficial depende de integrador fiscal e certificado digital no backend. O ERP não deve fingir emissão/autorização sem credencial real.',array['fiscal','NF-e','NFC-e','modelo 55','modelo 65','XML','DANFE','SEFAZ','certificado','integrador'],'/fiscal',140),
('financeiro','Financeiro','Caixa, contas, bancos, conciliação e resultado.','Financeiro acompanha contas a pagar, receber, caixa, bancos, conciliação, custos, pagamentos, recebimentos e resultado. Movimentos originados de vendas, compras e operações devem ser rastreáveis.',array['financeiro','caixa','contas a pagar','contas a receber','banco','conciliação','custo','resultado'],'/erp-industrial',150),
('relatorios','Relatórios e indicadores','Indicadores operacionais e visão executiva.','Relatórios devem ser baseados nos registros reais. Indicadores de produção, OEE, refugo, estoque, qualidade, manutenção, vendas e financeiro devem possuir período, empresa e origem dos dados.',array['relatórios','BI','KPI','OEE','refugo','estoque','qualidade','manutenção','vendas','financeiro'],'/erp-industrial',160),
('outlook-ia','Outlook, IA e OCR','Automação de pedidos recebidos por e-mail.','Fluxo: e-mail → leitura de remetente/assunto/anexo → OCR/IA → extração de cliente, SKU, quantidade, preço e entrega → conferência → aprovação → pedido → produção/faturamento.',array['Outlook','Microsoft Graph','IA','OCR','PDF','imagem','e-mail','pedido automático','aprovação'],'/erp-industrial',170),
('documentos-anexos','Documentos e anexos','Controle documental e evidências em armazenamento privado.','Documentos de qualidade podem receber anexos em armazenamento privado por empresa e documento. Downloads devem usar URLs assinadas, sem expor arquivos privados publicamente.',array['documento','anexo','Storage','arquivo','evidência','URL assinada','privado','empresa'],'/qualidade',180),
('usuarios-permissoes','Usuários e permissões','Perfis, setores, administração e isolamento por empresa.','Usuários são vinculados a uma empresa e podem possuir nível administrativo e setor. Master possui visão administrativa global. Usuários comuns devem enxergar apenas dados autorizados de sua empresa e módulos.',array['usuário','permissão','perfil','setor','Master','administrador','RLS','empresa'],'/master',190),
('seguranca','Segurança','Autenticação, RLS e menor privilégio.','O sistema usa autenticação real, RLS multiempresa e funções protegidas. Nenhuma senha deve ser armazenada em tabelas públicas como mecanismo paralelo ao Supabase Auth. Não usar service_role no navegador. Funções SECURITY DEFINER devem ter search_path seguro e privilégios mínimos.',array['segurança','RLS','multiempresa','SECURITY DEFINER','search_path','service_role','Supabase Auth'],'/master',200),
('integracoes','Integrações','Fiscal, e-mail, Outlook e pagamentos quando configurados.','Integrações externas incluem fiscal, e-mail, Outlook/Microsoft Graph e pagamentos quando configuradas. Sem credenciais reais, a interface deve informar que a integração está pendente e nunca simular sucesso.',array['integração','API','fiscal','e-mail','Outlook','Graph','pagamento','credencial'],'/erp-industrial',210),
('plastibor','Base PLASTIBOR','Base operacional de testes industriais.','A base de testes operacional contém empresa PLASTIBOR, setores, produtos, matérias-primas, máquinas, moldes, lotes, BOM/custos, pedidos, ordens de produção, estoque, RPNC, inspeções, manutenção, documentos e solicitações de compra. Os dados permanecem isolados por empresa.',array['PLASTIBOR','Plastibor','indústria','testes','pedidos','OPs','qualidade','manutenção','compras'],'/erp-industrial',220),
('regras-ia','Regras para a IA','Como o assistente deve pesquisar e responder.','Quando o usuário perguntar sobre uma tela, procure primeiro o tópico correspondente, depois palavras-chave e termos equivalentes. Nunca invente dados de produção. Diferencie funcionalidade disponível, funcionalidade preparada e integração pendente. Para problemas de login, verificar empresa, usuário/e-mail, Supabase Auth, vínculo auth_user_id, usuário ativo e empresa ativa.',array['IA','busca semântica','conhecimento','tópico','palavra-chave','suporte','diagnóstico'],null,230)
on conflict (slug) do update set titulo=excluded.titulo,resumo=excluded.resumo,conteudo=excluded.conteudo,palavras_chave=excluded.palavras_chave,rota=excluded.rota,ordem=excluded.ordem,publico=true,updated_at=now();
