create table if not exists public.erp_planos_catalogo (id uuid primary key default gen_random_uuid(),codigo text not null unique,nome text not null,ordem integer not null default 0,preco_mensal numeric(14,2) not null default 0,descricao text,ativo boolean not null default true,criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now());
create table if not exists public.erp_plano_modulos (id uuid primary key default gen_random_uuid(),plano_codigo text not null references public.erp_planos_catalogo(codigo) on update cascade on delete cascade,modulo_codigo text not null,modulo_nome text not null,acesso boolean not null default true,limite_usuarios integer,limite_empresas integer,recursos jsonb not null default '{}'::jsonb,criado_em timestamptz not null default now(),unique(plano_codigo,modulo_codigo));
alter table public.erp_planos_catalogo enable row level security;
alter table public.erp_plano_modulos enable row level security;
drop policy if exists erp_planos_catalogo_select on public.erp_planos_catalogo;
create policy erp_planos_catalogo_select on public.erp_planos_catalogo for select to authenticated using (ativo=true or public.erp_is_master());
drop policy if exists erp_plano_modulos_select on public.erp_plano_modulos;
create policy erp_plano_modulos_select on public.erp_plano_modulos for select to authenticated using (exists(select 1 from public.erp_planos_catalogo p where p.codigo=plano_codigo and (p.ativo=true or public.erp_is_master())));
insert into public.erp_planos_catalogo(codigo,nome,ordem,preco_mensal,descricao) values ('essencial','Essencial',1,199,'Base operacional industrial'),('profissional','Profissional',2,349,'Operação industrial integrada'),('diamante','Diamante',3,549,'Gestão industrial avançada e completa') on conflict(codigo) do update set nome=excluded.nome,ordem=excluded.ordem,preco_mensal=excluded.preco_mensal,descricao=excluded.descricao,atualizado_em=now();
insert into public.erp_plano_modulos(plano_codigo,modulo_codigo,modulo_nome,recursos) values
('essencial','cadastros','Cadastros e usuários','{"crud":true,"rbac":true}'),('essencial','estoque','Estoque e WMS','{"lotes":true,"enderecamento":true,"inventario":true}'),('essencial','vendas','Vendas e CRM','{"orcamento":true,"pedido":true}'),('essencial','compras','Compras e suprimentos','{"cotacao":true,"recebimento":true}'),('essencial','producao','Produção e OP','{"op":true,"apontamento":true}'),('essencial','expedicao','Expedição','{"separacao":true,"conferencia":true}'),
('profissional','cadastros','Cadastros e usuários','{"crud":true,"rbac":true}'),('profissional','estoque','Estoque e WMS','{"lotes":true,"enderecamento":true,"inventario":true,"projecao":true}'),('profissional','vendas','Vendas e CRM','{"orcamento":true,"pedido":true,"margem":true}'),('profissional','compras','Compras e suprimentos','{"cotacao":true,"aprovacao":true,"recebimento":true}'),('profissional','pcp','PCP e APS','{"mps":true,"mrp":true,"capacidade_finita":true,"gantt":true}'),('profissional','producao','Produção e MES','{"op":true,"apontamento":true,"oee":true}'),('profissional','engenharia','Engenharia/BOM/Roteiros','{"bom_multinivel":true,"revisao":true}'),('profissional','injecao','Injeção plástica','{"molde":true,"cavidades":true,"ciclo":true,"setup":true}'),('profissional','prensados','Prensados','{"prensa":true,"ferramental":true,"cura":true}'),('profissional','estamparia','Estamparia','{"prensa":true,"estampo":true,"forca":true,"setup":true}'),('profissional','ferramentaria','Ferramentaria','{"moldes":true,"estampos":true,"ciclos":true}'),('profissional','qualidade','Qualidade/SGQ','{"inspecao":true,"spc":true,"aql":true}'),('profissional','manutencao','Manutenção','{"preventiva":true,"corretiva":true,"preditiva":true}'),('profissional','custos','Custos industriais','{"custo_padrao":true,"custo_real":true,"margem":true}'),('profissional','expedicao','Expedição/WMS','{"separacao":true,"romaneio":true,"etiqueta":true}'),('profissional','rh','RH e competências','{"funcionarios":true,"treinamento":true}'),('profissional','bi','BI e inteligência','{"cockpit":true,"projecoes":true,"alertas":true}'),
('diamante','cadastros','Cadastros e usuários','{"crud":true,"rbac":true}'),('diamante','estoque','Estoque e WMS','{"lotes":true,"enderecamento":true,"inventario":true,"projecao":true}'),('diamante','vendas','Vendas e CRM','{"orcamento":true,"pedido":true,"margem":true}'),('diamante','compras','Compras e suprimentos','{"cotacao":true,"aprovacao":true,"recebimento":true}'),('diamante','pcp','PCP e APS','{"mps":true,"mrp":true,"capacidade_finita":true,"gantt":true}'),('diamante','producao','Produção e MES','{"op":true,"apontamento":true,"oee":true,"rastreabilidade":true}'),('diamante','engenharia','Engenharia/BOM/Roteiros','{"bom_multinivel":true,"revisao":true}'),('diamante','injecao','Injeção plástica','{"molde":true,"cavidades":true,"ciclo":true,"setup":true,"parametros":true}'),('diamante','prensados','Prensados','{"prensa":true,"ferramental":true,"cura":true,"parametros":true}'),('diamante','estamparia','Estamparia','{"prensa":true,"estampo":true,"forca":true,"avanço":true,"setup":true}'),('diamante','ferramentaria','Ferramentaria','{"moldes":true,"estampos":true,"manutencao":true,"ciclos":true}'),('diamante','qualidade','Qualidade/SGQ','{"inspecao":true,"spc":true,"aql":true,"cpk":true,"nc":true}'),('diamante','fmea','FMEA/RPNC/CAPA','{"fmea":true,"rpn":true,"capa":true,"auditoria":true}'),('diamante','manutencao','Manutenção','{"preventiva":true,"corretiva":true,"preditiva":true,"oee":true}'),('diamante','custos','Custos industriais','{"custo_padrao":true,"custo_real":true,"margem":true,"simulacao":true}'),('diamante','financeiro','Financeiro','{"pagar":true,"receber":true,"caixa":true,"cenarios":true}'),('diamante','fiscal','Fiscal Brasil','{"nfe":true,"sped":true,"bloco_k":true,"reforma_tributaria":true}'),('diamante','expedicao','Expedição/WMS','{"separacao":true,"romaneio":true,"etiqueta":true,"conferencia":true}'),('diamante','documentos','Documentos/Databook','{"revisao":true,"assinatura":true,"databook":true}'),('diamante','rh','RH e competências','{"funcionarios":true,"treinamento":true,"competencias":true}'),('diamante','bi','BI e inteligência','{"cockpit":true,"projecoes":true,"alertas":true}'),('diamante','ia','IA industrial','{"copilot":true,"previsao":true,"recomendacoes":true}')
on conflict(plano_codigo,modulo_codigo) do update set modulo_nome=excluded.modulo_nome,recursos=excluded.recursos,acesso=true;