create table if not exists public.erp_pedidos_compra (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null,
  numero bigint generated by default as identity,
  fornecedor_id uuid not null,
  requisicao_id uuid null,
  comprador_id uuid null,
  comprador_nome text null,
  condicao_pagamento text null,
  prazo_entrega date null,
  observacoes text null,
  status text not null default 'RASCUNHO',
  data_pedido timestamptz not null default now(),
  total numeric(18,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint erp_pedidos_compra_status_chk check (status in ('RASCUNHO','PENDENTE_APROVACAO','APROVADO','REJEITADO','CANCELADO','RECEBIMENTO_PARCIAL','RECEBIDO')),
  constraint erp_pedidos_compra_empresa_numero_uk unique (empresa_id, numero),
  constraint erp_pedidos_compra_fornecedor_fk foreign key (fornecedor_id) references public.erp_fornecedores(id),
  constraint erp_pedidos_compra_requisicao_fk foreign key (requisicao_id) references public.erp_requisicoes_compra(id),
  constraint erp_pedidos_compra_comprador_fk foreign key (comprador_id) references public.erp_usuarios(id)
);

create table if not exists public.erp_pedidos_compra_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null,
  pedido_id uuid not null references public.erp_pedidos_compra(id) on delete cascade,
  produto_id uuid not null references public.erp_produtos(id),
  codigo_produto text not null,
  descricao_produto text not null,
  quantidade numeric(18,3) not null,
  unidade text not null default 'UN',
  preco_unitario numeric(18,4) not null default 0,
  total numeric(18,2) generated always as (round(quantidade * preco_unitario, 2)) stored,
  created_at timestamptz not null default now(),
  constraint erp_pedidos_compra_itens_quantidade_chk check (quantidade > 0),
  constraint erp_pedidos_compra_itens_preco_chk check (preco_unitario >= 0)
);

create index if not exists idx_erp_pedidos_compra_empresa_status on public.erp_pedidos_compra(empresa_id,status);
create index if not exists idx_erp_pedidos_compra_empresa_data on public.erp_pedidos_compra(empresa_id,data_pedido desc);
create index if not exists idx_erp_pedidos_compra_itens_pedido on public.erp_pedidos_compra_itens(empresa_id,pedido_id);

alter table public.erp_pedidos_compra enable row level security;
alter table public.erp_pedidos_compra_itens enable row level security;

drop policy if exists erp_pedidos_compra_select on public.erp_pedidos_compra;
drop policy if exists erp_pedidos_compra_insert on public.erp_pedidos_compra;
drop policy if exists erp_pedidos_compra_update on public.erp_pedidos_compra;
drop policy if exists erp_pedidos_compra_delete on public.erp_pedidos_compra;
create policy erp_pedidos_compra_select on public.erp_pedidos_compra for select using (empresa_id = erp_current_empresa_id());
create policy erp_pedidos_compra_insert on public.erp_pedidos_compra for insert with check (empresa_id = erp_current_empresa_id());
create policy erp_pedidos_compra_update on public.erp_pedidos_compra for update using (empresa_id = erp_current_empresa_id()) with check (empresa_id = erp_current_empresa_id());
create policy erp_pedidos_compra_delete on public.erp_pedidos_compra for delete using (empresa_id = erp_current_empresa_id());

drop policy if exists erp_pedidos_compra_itens_select on public.erp_pedidos_compra_itens;
drop policy if exists erp_pedidos_compra_itens_insert on public.erp_pedidos_compra_itens;
drop policy if exists erp_pedidos_compra_itens_update on public.erp_pedidos_compra_itens;
drop policy if exists erp_pedidos_compra_itens_delete on public.erp_pedidos_compra_itens;
create policy erp_pedidos_compra_itens_select on public.erp_pedidos_compra_itens for select using (empresa_id = erp_current_empresa_id());
create policy erp_pedidos_compra_itens_insert on public.erp_pedidos_compra_itens for insert with check (empresa_id = erp_current_empresa_id());
create policy erp_pedidos_compra_itens_update on public.erp_pedidos_compra_itens for update using (empresa_id = erp_current_empresa_id()) with check (empresa_id = erp_current_empresa_id());
create policy erp_pedidos_compra_itens_delete on public.erp_pedidos_compra_itens for delete using (empresa_id = erp_current_empresa_id());

create or replace function public.erp_atualizar_total_pedido_compra()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.erp_pedidos_compra p
     set total = coalesce((select sum(i.total) from public.erp_pedidos_compra_itens i where i.pedido_id = p.id),0),
         updated_at = now()
   where p.id = coalesce(new.pedido_id, old.pedido_id)
     and p.empresa_id = coalesce(new.empresa_id, old.empresa_id);
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_erp_pedidos_compra_total on public.erp_pedidos_compra_itens;
create trigger trg_erp_pedidos_compra_total
after insert or update or delete on public.erp_pedidos_compra_itens
for each row execute function public.erp_atualizar_total_pedido_compra();

create or replace function public.erp_numero_pedido_compra_formatado(p_numero bigint)
returns text
language sql
immutable
as $$ select 'PC-' || lpad(p_numero::text, 4, '0') $$;

grant select, insert, update, delete on public.erp_pedidos_compra to authenticated;
grant select, insert, update, delete on public.erp_pedidos_compra_itens to authenticated;
