import { useCallback,useEffect,useMemo,useState,type FormEvent } from 'react'
import { Calculator, RefreshCw, Search } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import VendasLayout from '../VendasLayout'

type Product={id:string;codigo:string;nome:string;custo_medio:number|null}
type Stock={produto_id:string;saldo_fisico:number|null}
type CostRow={id:string;produto_id:string;documento_tipo:string;documento_referencia:string;quantidade_entrada:number;custo_unitario_liquido:number;saldo_anterior:number;custo_medio_anterior:number;custo_medio_novo:number;valor_total_liquido:number;observacao:string|null;calculado_em:string}
const input='h-[30px] w-full rounded-[2px] border border-slate-300 bg-white px-2 text-[11px] outline-none focus:border-[#2D8DB8]'
const label='mb-[2px] block text-[9px] font-medium uppercase tracking-[.04em] text-slate-600'
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function CustoMedioIndustrial(){
 const [empresa,setEmpresa]=useState('');const [products,setProducts]=useState<Product[]>([]);const [stocks,setStocks]=useState<Stock[]>([]);const [history,setHistory]=useState<CostRow[]>([])
 const [productId,setProductId]=useState('');const [quantity,setQuantity]=useState('');const [cost,setCost]=useState('');const [docType,setDocType]=useState('NFE_ENTRADA');const [docRef,setDocRef]=useState('');const [note,setNote]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const t=await supabase.rpc('erp_current_empresa_id');if(t.error)throw t.error;if(typeof t.data!=='string'||!t.data)throw new Error('Empresa da sessão não identificada.');setEmpresa(t.data)
 const [p,s,h]=await Promise.all([
  supabase.from('erp_produtos').select('id,codigo,nome,custo_medio').eq('empresa_id',t.data).eq('ativo',true).order('codigo').limit(5000),
  supabase.from('erp_produto_estoque').select('produto_id,saldo_fisico').eq('empresa_id',t.data).limit(5000),
  supabase.from('erp_custos_historico').select('id,produto_id,documento_tipo,documento_referencia,quantidade_entrada,custo_unitario_liquido,saldo_anterior,custo_medio_anterior,custo_medio_novo,valor_total_liquido,observacao,calculado_em').eq('empresa_id',t.data).order('calculado_em',{ascending:false}).limit(500)
 ]);if(p.error)throw p.error;if(s.error)throw s.error;if(h.error)throw h.error;setProducts((p.data??[]) as Product[]);setStocks((s.data??[]) as Stock[]);setHistory((h.data??[]) as CostRow[])
 }catch(e){setError(e instanceof Error?e.message:'Falha ao consultar custo industrial.')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const stockMap=useMemo(()=>new Map(stocks.map(x=>[x.produto_id,Number(x.saldo_fisico||0)])),[stocks])
 const selected=products.find(x=>x.id===productId);const qty=Number(quantity);const unit=Number(cost);const balance=stockMap.get(productId)??0;const nextCost=qty>0&&unit>=0?((balance*Number(selected?.custo_medio||0))+(qty*unit))/(balance+qty):null
 const visible=history.filter(x=>{const p=products.find(y=>y.id===x.produto_id);const q=query.trim().toLocaleLowerCase('pt-BR');return !q||[p?.codigo,p?.nome,x.documento_referencia,x.documento_tipo].some(v=>String(v??'').toLocaleLowerCase('pt-BR').includes(q))})
 async function save(e:FormEvent){e.preventDefault();setError('');setNotice('');if(!productId||!Number.isFinite(qty)||qty<=0||!Number.isFinite(unit)||unit<0||!docRef.trim()){setError('Informe produto, quantidade positiva, custo líquido não negativo e referência documental.');return}setSaving(true);try{const r=await supabase.rpc('erp_fiscal_recalcular_custo_medio',{p_produto_id:productId,p_quantidade_entrada:qty,p_custo_unitario_liquido:unit,p_documento_tipo:docType,p_documento_referencia:docRef.trim(),p_observacao:note.trim()||null});if(r.error)throw r.error;setNotice('Custo médio recalculado e histórico gravado na transação.');setQuantity('');setCost('');setDocRef('');setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao recalcular custo médio.')}finally{setSaving(false)}}
 return <VendasLayout title="Custo médio industrial" subtitle="Custo médio ponderado com trilha de auditoria por empresa" onRefresh={()=>void load()} showStatusCards={false}>
 <section className="erp-global-surface erp-compact mt-3 space-y-3">
  {(error||notice)&&<div role={error?'alert':'status'} className={'rounded border p-2 text-[11px] '+(error?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-800')}>{error||notice}</div>}
  <form onSubmit={save} className="grid grid-cols-1 gap-2 rounded border border-slate-200 bg-white p-3 md:grid-cols-4">
   <div className="md:col-span-2"><label className={label}>Produto</label><select className={input} required value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecione item ativo</option>{products.map(x=><option key={x.id} value={x.id}>{x.codigo} • {x.nome}</option>)}</select></div>
   <div><label className={label}>Tipo do documento</label><select className={input} value={docType} onChange={e=>setDocType(e.target.value)}>{[['NFE_ENTRADA','NF-e de entrada'],['RETORNO_PRODUCAO','Retorno de produção'],['AJUSTE_APROVADO','Ajuste aprovado'],['FECHAMENTO_OP','Fechamento de OP']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div>
   <div><label className={label}>NF / OP / documento</label><input className={input} required value={docRef} onChange={e=>setDocRef(e.target.value)} maxLength={120}/></div>
   <div><label className={label}>Quantidade recebida</label><input className={input} type="number" min="0.0001" step="0.0001" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></div>
   <div><label className={label}>Custo unitário líquido (R$)</label><input className={input} type="number" min="0" step="0.000001" required value={cost} onChange={e=>setCost(e.target.value)}/></div>
   <div><label className={label}>Saldo físico atual</label><input className={input+' bg-slate-50'} readOnly value={String(balance)}/></div>
   <div><label className={label}>Custo médio atual</label><input className={input+' bg-slate-50'} readOnly value={money(Number(selected?.custo_medio||0))}/></div>
   <div className="md:col-span-3"><label className={label}>Observação de auditoria</label><input className={input} value={note} onChange={e=>setNote(e.target.value)} maxLength={500}/></div>
   <div className="flex items-end"><button className="inline-flex h-[30px] w-full items-center justify-center gap-1 rounded-[2px] border border-[#2D8DB8] bg-[#2D8DB8] px-3 text-[10px] text-white disabled:opacity-50" disabled={saving||!empresa}><Calculator size={13}/>{saving?'Calculando...':'Recalcular e auditar'}</button></div>
   <div className="md:col-span-4 grid grid-cols-1 gap-2 border-t border-slate-100 pt-2 sm:grid-cols-3"><div><span className={label}>Valor líquido de entrada</span><strong className="text-[12px] tabular-nums">{money(Math.max(0,qty)*Math.max(0,unit))}</strong></div><div><span className={label}>Novo custo médio estimado</span><strong className="text-[12px] tabular-nums">{nextCost===null?'—':money(nextCost)}</strong></div><div><span className={label}>Fórmula</span><p className="text-[10px] text-slate-600">((saldo × custo atual) + (entrada × custo líquido)) ÷ (saldo + entrada)</p></div></div>
  </form>
  <div className="flex items-end gap-2"><div className="flex-1"><label className={label}>Pesquisar histórico</label><div className="relative"><Search size={12} className="absolute left-2 top-[9px] text-slate-400"/><input className={input+' pl-7'} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Produto, NF, OP ou tipo documental"/></div></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex h-[30px] items-center gap-1 rounded-[2px] border border-slate-300 px-3 text-[10px]"><RefreshCw size={12} className={loading?'animate-spin':''}/>Atualizar</button></div>
  <div className="overflow-x-auto rounded border border-slate-200 bg-white"><table className="industrial-table w-full min-w-[1000px] text-[10px]"><thead className="bg-slate-100 text-left"><tr>{['Data','Produto','Documento','Qtd. entrada','Custo unitário','Custo anterior','Custo novo','Valor líquido'].map(x=><th key={x} className="h-[32px] px-2 text-[9px] uppercase">{x}</th>)}</tr></thead><tbody>{visible.map(x=>{const p=products.find(y=>y.id===x.produto_id);return <tr key={x.id} className="border-t border-slate-100 hover:bg-neutral-50/80"><td className="h-[32px] px-2">{new Date(x.calculado_em).toLocaleString('pt-BR')}</td><td className="h-[32px] px-2">{p?.codigo??'—'} • {p?.nome??'Produto'}</td><td className="h-[32px] px-2">{x.documento_tipo} • {x.documento_referencia}</td><td className="h-[32px] px-2 text-right tabular-nums">{Number(x.quantidade_entrada).toLocaleString('pt-BR')}</td><td className="h-[32px] px-2 text-right tabular-nums">{money(x.custo_unitario_liquido)}</td><td className="h-[32px] px-2 text-right tabular-nums">{money(x.custo_medio_anterior)}</td><td className="h-[32px] px-2 text-right tabular-nums font-medium">{money(x.custo_medio_novo)}</td><td className="h-[32px] px-2 text-right tabular-nums">{money(x.valor_total_liquido)}</td></tr>})}{visible.length===0&&<tr><td colSpan={8} className="h-[32px] text-center text-slate-500">Nenhum cálculo encontrado.</td></tr>}</tbody></table></div>
  <p className="text-[9px] text-slate-500">Empresa da sessão: {empresa||'não identificada'}. O cálculo exige permissão Fiscal/Criar ou Estoque/Movimentar e não substitui a escrituração/autorização fiscal da NF-e.</p>
 </section></VendasLayout>
}
