import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Cpu,
  FileCheck2,
  FileText,
  Factory,
  Gauge,
  Handshake,
  Headphones,
  Home,
  Landmark,
  Leaf,
  PackageSearch,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Truck,
  UserCircle,
  Users,
  Wrench,
} from 'lucide-react'

export type SynqraModule = {
  key: string
  label: string
  route?: string
  permission?: string
  Icon: LucideIcon
}

export const SYNQRA_MODULES: readonly SynqraModule[] = [
  { key: 'inicio', label: 'Início', route: '/comercial', Icon: Home },
  { key: 'dashboard', label: 'Dashboard', route: '/erp-industrial', Icon: BarChart3 },
  { key: 'vendas', label: 'Vendas', route: '/vendas/tablet', permission: 'sales.read', Icon: Handshake },
  { key: 'compras', label: 'Compras', route: '/compras/rfq', permission: 'purchases.read', Icon: ShoppingCart },
  { key: 'estoque', label: 'Estoque', route: '/estoque', permission: 'inventory.read', Icon: Boxes },
  { key: 'fiscal', label: 'Fiscal', route: '/fiscal', permission: 'fiscal.ver', Icon: FileText },
  { key: 'financeiro', label: 'Financeiro', route: '/financeiro/caixa', permission: 'finance.read', Icon: Landmark },
  { key: 'pcp', label: 'PCP', route: '/pcp', Icon: Factory },
  { key: 'qualidade', label: 'Qualidade', route: '/qualidade', permission: 'audit.read', Icon: Award },
  { key: 'sgq', label: 'SGQ', route: '/vendas/sgq', permission: 'audit.read', Icon: ClipboardCheck },
  { key: 'engenharia', label: 'Engenharia', route: '/engenharia', Icon: Activity },
  { key: 'produtos', label: 'Produtos', route: '/produtos', permission: 'products.read', Icon: Boxes },
  { key: 'clientes', label: 'Clientes', route: '/clientes', permission: 'sales.read', Icon: Users },
  { key: 'fornecedores', label: 'Fornecedores', route: '/fornecedores', permission: 'purchases.read', Icon: Truck },
  { key: 'rh', label: 'RH', route: '/rh', Icon: Users },
  { key: 'administracao', label: 'Administração / Usuários', route: '/usuarios-admin', permission: 'users.read', Icon: ClipboardList },
  { key: 'logistica', label: 'Logística', route: '/expedicao/roteirizacao', permission: 'inventory.read', Icon: Truck },
  { key: 'manutencao', label: 'Manutenção', route: '/manutencao/ordens', permission: 'production.read', Icon: Wrench },
  { key: 'materiais', label: 'Controle de Materiais', route: '/pcp/materiais', Icon: PackageSearch },
  { key: 'documentos', label: 'Documentos', route: '/documentos-qualidade', permission: 'audit.read', Icon: FileText },
  { key: 'relatorios', label: 'Relatórios', route: '/vendas/relatorios', permission: 'reports.read', Icon: BarChart3 },
  { key: 'auditorias', label: 'Auditorias', route: '/qualidade/auditoria-5s', permission: 'audit.read', Icon: ClipboardCheck },
  { key: 'planejamento', label: 'Planejamento', route: '/pcp/planejamento', Icon: CalendarDays },
  { key: 'indicadores', label: 'Indicadores', route: '/pcp/dashboard-oee', Icon: Gauge },
  { key: 'configuracoes', label: 'Configurações', route: '/configuracoes-adm', permission: 'users.read', Icon: Settings },
  { key: 'suporte', label: 'Suporte', route: '/ajuda', Icon: Headphones },
  { key: 'perfil', label: 'Perfil', route: '/usuarios', permission: 'users.read', Icon: UserCircle },
  { key: 'agenda', label: 'Agenda', Icon: CalendarDays },
  { key: 'eng-produtos', label: 'Engenharia · Itens', route: '/engenharia/produtos', Icon: PackageSearch },
  { key: 'eng-bom', label: 'Engenharia · BOM', route: '/engenharia/bom', Icon: Boxes },
  { key: 'eng-roteiros', label: 'Engenharia · Roteiros', route: '/engenharia/roteiros', Icon: Factory },
  { key: 'wms-enderecos', label: 'Estoque · Endereços', route: '/estoque/enderecos', Icon: Boxes },
  { key: 'wms-movimentacoes', label: 'Estoque · Movimentações', route: '/estoque/movimentacoes', permission: 'inventory.read', Icon: Truck },
  { key: 'sgq-especificacoes', label: 'Qualidade · Especificações', route: '/qualidade/especificacoes', permission: 'audit.read', Icon: FileText },
  { key: 'sgq-inspecoes', label: 'Qualidade · Inspeções', route: '/qualidade/inspecoes', permission: 'audit.read', Icon: ClipboardList },
  { key: 'sgq-fmea', label: 'Qualidade · FMEA', route: '/qualidade/fmea', permission: 'audit.read', Icon: ShieldCheck },
  { key: 'sgq-rnc-capa', label: 'Qualidade · RNC/CAPA', route: '/qualidade/rnc-capa', permission: 'audit.read', Icon: ClipboardCheck },
  { key: 'sgq-cep', label: 'Qualidade · CEP', route: '/qualidade/cep', permission: 'audit.read', Icon: Activity },
  { key: 'pcp-ordens-industriais', label: 'PCP · Ordens industriais', route: '/pcp/ordens-industriais', Icon: Factory },
  { key: 'pcp-apontamentos-industriais', label: 'PCP · Apontamentos', route: '/pcp/apontamentos', Icon: ClipboardList },
  { key: 'fiscal-parametros-industriais', label: 'Fiscal · Parâmetros', route: '/fiscal/parametros', permission: 'fiscal.ver', Icon: FileText },
  { key: 'rh-funcionarios-industriais', label: 'RH · Funcionários', route: '/rh/funcionarios', Icon: Users },
  { key: 'rh-turnos-industriais', label: 'RH · Turnos', route: '/rh/turnos', Icon: CalendarDays },
  { key: 'rh-epis-industriais', label: 'RH · EPIs / CA', route: '/rh/epis', Icon: ShieldCheck },
  { key: 'treinamentos', label: 'Treinamentos', Icon: BookOpen },
  { key: 'seguranca', label: 'Segurança do Trabalho', Icon: ShieldCheck },
  { key: 'meio-ambiente', label: 'Meio Ambiente', Icon: Leaf },
  { key: 'ti', label: 'TI', Icon: Cpu },
  { key: 'notificacoes', label: 'Notificações', Icon: Bell },
  { key: 'aprovacoes', label: 'Aprovações', Icon: FileCheck2 },
]

const _synqraIconIntegrity: LucideIcon[] = [
  Activity, Award, BarChart3, Bell, BookOpen, Boxes, CalendarDays, ClipboardCheck, ClipboardList,
  Cpu, FileCheck2, FileText, Factory, Gauge, Handshake, Headphones, Home, Landmark, Leaf,
  PackageSearch, Settings, ShieldCheck, ShoppingCart, Truck, UserCircle, Users, Wrench,
]
