import { useEffect, useRef, useState } from 'react'
import { Check, Loader2, Search, X } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
export type LookupColumn<T> = { key: keyof T & string; label: string }
export type LookupResult<T> = { id: string; code: string; description: string; row: T }
type Props<T extends Record<string, unknown>> = { label:string; value:string; onChange:(value:string)=>void; onSelect:(result:LookupResult<T>)=>void; table:string; codeColumn?:string; descriptionColumn?:string; extraColumns?:string; placeholder?:string; disabled?:boolean; searchColumns?:string[]; columns:LookupColumn<T>[]; title?:string }
export default function LookupField<T extends Record<string, unknown>>({label,value,onChange,onSelect,table,codeColumn='codigo',descriptionColumn='nome',extraColumns='',placeholder='Digite o código',disabled=false,searchColumns,columns,title}:Props<T>){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[rows,setRows]=useState<T[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[resolved,setResolved]=useState(false); const timer=useRef<number|null>(null)
 async function findByCode(code=value){const v=code.trim();if(!v){setResolved(false);return};setLoading(true);setMessage('');const select=['id',codeColumn,descriptionColumn,extraColumns].filter(Boolean).join(',');const {data,error}=await supabase.from(table).select(select).eq(codeColumn,v).eq('ativo',true).maybeSingle();if(error){setMessage(error.message);setResolved(false)}else if(data){const r=data as Record<string,unknown>;setResolved(true);onSelect({id:String(r.id??''),code:String(r[codeColumn]??v),description:String(r[descriptionColumn]??''),row:data as T})}else{setResolved(false);setMessage('Código não localizado. Use a lupa para consultar.')}setLoading(false)}
 useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current)},[])
 async function search(){setLoading(true);setMessage('');const select='id,'+codeColumn+','+descriptionColumn+(extraColumns?','+extraColumns:'');let q=supabase.from(table).select(select).eq('ativo',true).limit(100);const term=query.trim();if(term){const cols=searchColumns?.length?searchColumns:[codeColumn,descriptionColumn];q=q.or(cols.map(c=>c+'.ilike.%'+term+'%').join(','))}const {data,error}=await q;if(error)setMessage(error.message);else setRows((data??[]) as T[]);setLoading(false)}
 return <div className="lookup-field"><label>{label}</label><div className="lookup-control"><input value={value} disabled={disabled} placeholder={placeholder} onChange={e=>{onChange(e.target.value);setResolved(false);if(timer.current)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>void findByCode(e.target.value),450)}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void findByCode()}}}/><button type="button" disabled={disabled||loading} aria-label={'Consultar '+label} title="Consulta avançada" onClick={()=>{setOpen(true);void search()}}><Search size={17}/></button>{resolved&&<Check className="lookup-ok" size={17}/>}</div>{message&&<small className="lookup-message">{message}</small>}
 {open&&<div className="lookup-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="lookup-dialog" role="dialog" aria-modal="true"><header><div><span>CONSULTA</span><h2>{title||'Consultar '+label}</h2></div><button type="button" onClick={()=>setOpen(false)}><X size={19}/></button></header><div className="lookup-search"><Search size={17}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="Código, descrição ou outro filtro..."/><button type="button" onClick={()=>void search()} disabled={loading}>{loading?<Loader2 className="spin" size={17}/>:'Pesquisar'}</button></div>{message&&<div className="lookup-error">{message}</div>}<div className="lookup-table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th/></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)}>{columns.map(c=><td key={c.key}>{String(row[c.key]??'—')}</td>)}<td><button type="button" className="lookup-select" onClick={()=>{const r=row as Record<string,unknown>;onSelect({id:String(r.id??''),code:String(r[codeColumn]??''),description:String(r[descriptionColumn]??''),row});setOpen(false);setResolved(true)}}>Selecionar</button></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={columns.length+1} className="lookup-empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div></section></div>}</div>
