import { useEffect, useRef, useState } from 'react'
import { Check, Loader2, Search, X } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
export type LookupColumn<T> = { key: keyof T & string; label: string }
export type LookupResult<T> = { id: string; code: string; description: string; row: T }
type Props<T extends Record<string, unknown>> = { label:string; value:string; onChange:(value:string)=>void; onSelect:(result:LookupResult<T>)=>void; table:string; codeColumn?:string; descriptionColumn?:string; extraColumns?:string; placeholder?:string; disabled?:boolean; searchColumns?:string[]; columns:LookupColumn<T>[]; title?:string }
export default function LookupField<T extends Record<string, unknown>>({label,value,onChange,onSelect,table,codeColumn='codigo',descriptionColumn='nome',extraColumns='',placeholder='Digite o código',disabled=false,searchColumns,columns,title}:Props<T>){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[rows,setRows]=useState<T[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[resolved,setResolved]=useState(false); const timer=useRef<number|null>(null)
 async function findByCode(code=value){const v=code.trim();if(!v){setResolved(false);return};setLoading(true);setMessage('');const select=['id',codeColumn,descriptionColumn,extraColumns].filter(Boolean).join(',');const {data,error}=await supabase.from(table).select(select).eq(codeColumn,v).eq('ativo',true).maybeSingle();if(error){setMessage(error.message);setResolved(false)}else if(data){const r=data as Record<string,unknown>;setResolved(true);onSelect({id:String(r.id??''),code:String(r[codeColumn]??v),description:String(r[descriptionColumn]??''),row:data as T})}else{setResolved(false);setMessage('Código não localizado. Use a lupa para consultar.')}setLoading(false)}
 useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current)},[])
 async function search(){setLoading(true);setMessage('');const select='id,'+codeColumn+','+descriptionColumn+(extraColumns?','+extraColumns:'');let q=supabase.from(table).select(select).eq('ativo',true).limit(100);const term=query.trim();if(term){const cols=searchColumns?.length?searchColumns:[codeColumn,descriptionColumn];q=q.or(cols.map(c=>c+'.ilike.%'+term+'%').join(','))}const {data,error}=await q;if(error)setMessage(error.message);else setRows((data??[]) as T[]);setLoading(false)}
 return <div className="lookup-field"><label>{label}</label><div className="lookup-control"><input value={value} disabled={disabled} placeholder={placeholder} onChange={e=>{onChange(e.target.value);setResolved(false);if(timer.current)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>void findByCode(e.target.value),450)}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void findByCode()}}}/><button type="button" disabled={disabled||loading} aria-label={'Consultar '+label} title="Consulta avançada" onClick={()=>{setOpen(true);void search()}}><Search size={17}/></button>{resolved&&<Check className="lookup-ok" size={17}/>}</div>{message&&<small className="lookup-message">{message}</small>}
 {open&&<div className="lookup-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="lookup-dialog" role="dialog" aria-modal="true"><header><div><span>CONSULTA</span><h2>{title||'Consultar '+label}</h2></div><button type="button" onClick={()=>setOpen(false)}><X size={19}/></button></header><div className="lookup-search"><Search size={17}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="Código, descrição ou outro filtro..."/><button type="button" onClick={()=>void search()} disabled={loading}>{loading?<Loader2 className="spin" size={17}/>:'Pesquisar'}</button></div>{message&&<div className="lookup-error">{message}</div>}<div className="lookup-table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th/></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)}>{columns.map(c=><td key={c.key}>{String(row[c.key]??'—')}</td>)}<td><button type="button" className="lookup-select" onClick={()=>{const r=row as Record<string,unknown>;onSelect({id:String(r.id??''),code:String(r[codeColumn]??''),description:String(r[descriptionColumn]??''),row});setOpen(false);setResolved(true)}}>Selecionar</button></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={columns.length+1} className="lookup-empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div></section></div>}</div>
}
.lookup-field{display:grid;gap:5px}.lookup-field>label{font-size:11px;font-weight:850;color:#31505d;text-transform:uppercase}.lookup-control{display:grid;grid-template-columns:minmax(0,1fr) 38px 22px;align-items:center;gap:5px}.lookup-control input{height:38px;box-sizing:border-box;border:1px solid #b9cbd6;border-radius:7px;padding:0 10px;color:#17313f;background:#fff}.lookup-control button{height:38px;border:1px solid #b9cbd6;border-radius:7px;background:#eef5f8;color:#1677b7;display:grid;place-items:center;cursor:pointer}.lookup-ok{color:#1f9d62}.lookup-message{color:#b94d55;font-size:11px}.lookup-overlay{position:fixed;inset:0;z-index:10050;background:rgba(12,32,43,.48);display:grid;place-items:center;padding:20px}.lookup-dialog{width:min(1080px,100%);max-height:min(760px,92vh);background:#fff;border:1px solid #cbdde4;border-radius:12px;box-shadow:0 24px 70px rgba(18,59,80,.25);display:flex;flex-direction:column;overflow:hidden}.lookup-dialog header{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #dbe7eb}.lookup-dialog header span{font-size:10px;font-weight:900;color:#1677b7;letter-spacing:.08em}.lookup-dialog h2{margin:3px 0 0;font-size:20px;color:#17313f}.lookup-dialog header button{border:0;background:transparent;cursor:pointer}.lookup-search{display:grid;grid-template-columns:20px minmax(0,1fr) auto;align-items:center;gap:8px;padding:14px 20px;background:#f4f7fa;border-bottom:1px solid #dbe7eb}.lookup-search input{height:38px;border:1px solid #b9cbd6;border-radius:7px;padding:0 10px}.lookup-search button{height:38px;border:0;border-radius:7px;background:#1677b7;color:#fff;padding:0 16px;font-weight:800}.lookup-table-wrap{overflow:auto}.lookup-table-wrap table{width:100%;border-collapse:collapse}.lookup-table-wrap th{position:sticky;top:0;background:#123b50;color:#fff;text-align:left;font-size:11px;padding:10px}.lookup-table-wrap td{border-bottom:1px solid #e1eaee;padding:9px;font-size:12px;color:#294754}.lookup-select{border:1px solid #9fc6d7;background:#edf7fb;color:#0e5f94;border-radius:6px;padding:7px 10px;font-weight:800}.lookup-empty,.lookup-error{padding:20px;text-align:center;color:#6c818a}.lookup-error{color:#b94d55;background:#fff5f5}.spin{animation:lookupspin 1s linear infinite}@keyframes lookupspin{to{transform:rotate(360deg)}}